app/src/main/java/org/wikipedia/suggestededits/ImageRecsFragment.kt

**Phab:** https://phabricator.wikimedia.org/T280273

Image Recs: Lock screen orientation

---

app/src/main/res/values/styles.xml

**Phab:** https://phabricator.wikimedia.org/T280714

Add styling to checkbox text for dark mode

---

app/src/main/java/org/wikipedia/main/MainFragment.kt

**Phab:** https://phabricator.wikimedia.org/T269448

Remove pre-beta flag on watchlist tooltip

---

app/src/main/res/values/styles.xml

https://phabricator.wikimedia.org/T278550#7013624

ImgRecs: tooltip bottom margin tweaks

---

app/src/main/res/layout/view_file_page.xml

https://phabricator.wikimedia.org/T278556#7013658

ImgRecs: reduce file page top margin

---

app/src/main/java/org/wikipedia/feed/mostread/MostReadArticles.java
app/src/main/java/org/wikipedia/feed/mostread/MostReadItemCard.java

https://appcenter.ms/orgs/ci-apps-hockeyapp-f5mf/apps/Wikipedia-Beta/crashes/errors/1788068044u/overview

Fix: possible crash when setting graphView on ListCardItemView

---

app/src/main/java/org/wikipedia/suggestededits/ImageRecsFragment.kt

https://phabricator.wikimedia.org/T280151#7023507

ImgRecs: optimize touch event when zooming image

---

app/src/main/java/org/wikipedia/suggestededits/ImageRecsFragment.kt
app/src/main/res/values/attrs.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/styles_black.xml
app/src/main/res/values/styles_dark.xml
app/src/main/res/values/styles_light.xml
app/src/main/res/values/styles_sepia.xml

**Phab:** https://phabricator.wikimedia.org/T278549

Updated navigation bar colors and names

---

app/src/main/java/org/wikipedia/suggestededits/provider/EditingSuggestionsProvider.kt

**Phab:** https://phabricator.wikimedia.org/T279454

Update distribution constant

---

app/src/main/res/values-ar/strings.xml
app/src/main/res/values-ca/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-in/strings.xml
app/src/main/res/values-iw/strings.xml
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-ko/strings.xml
app/src/main/res/values-mk/strings.xml
app/src/main/res/values-nqo/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values-sv/strings.xml
app/src/main/res/values-tr/strings.xml
app/src/main/res/values-uk/strings.xml
app/src/main/res/values-uz/strings.xml
app/src/main/res/values-zh-rTW/strings.xml
app/src/main/res/values/strings.xml

Update string resources for image recommendation PR #2342

ImgRecs: reduce spaces of daily amount string resources

---

app/src/main/java/org/wikipedia/onboarding/OnboardingPageView.kt
app/src/main/java/org/wikipedia/suggestededits/ImageRecsOnboardingFragment.kt
app/src/main/res/layout/view_onboarding_page.xml

ImgRecs: follow up: detect onboarding view height for small screen device

---

app/src/main/java/org/wikipedia/suggestededits/ImageRecsDialog.kt

**Phab:** https://phabricator.wikimedia.org/T273057

Image recs: Instrumentation has a repeated value

---

app/src/main/java/org/wikipedia/suggestededits/ImageRecsFragment.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
app/src/main/res/values/strings.xml

https://phabricator.wikimedia.org/T278528#7033856

ImgRecs: check and update daily count in SE task screen

---

app/src/main/java/org/wikipedia/suggestededits/ImageRecsFragment.kt

Not sure if these codes are staying for specific reasons.

ImgRecs: remove commented out code

---

app/build.gradle

https://developer.android.com/jetpack/androidx/releases/fragment#1.3.3

Update fragment-ktx to 1.3.3.

---

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsFragment.kt

https://phabricator.wikimedia.org/T281383

Change icon and text color of ImgRecs faq link

---

app/src/main/res/layout/view_wiki_article_card.xml

https://phabricator.wikimedia.org/T281557#7064940

Tweak: WikiArticleCardView design changes

---

app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt

https://phabricator.wikimedia.org/T280308

Fix: add correct anchor if editing the top section of a page

---

app/src/main/java/org/wikipedia/page/PageViewModel.java

The "project" namespace refers to pages in the form of `en.wikipedia.org/wiki/Wikipedia:[...]`

Allow pages in the Project namespace to be edited.

---

app/src/main/java/org/wikipedia/commons/FilePageView.kt
app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

**Phab:** https://phabricator.wikimedia.org/T282296

 Suggested image label update

---

app/src/main/java/org/wikipedia/Constants.kt

Make the `const val` and `enum entry` in alphabetical order.

Follow up: Constants Kotlin conversion

---

app/build.gradle

https://developer.android.com/jetpack/androidx/releases/core#1.5.0

Update androidx.core:core-ktx version to 1.5.0

---

app/src/main/java/org/wikipedia/Constants.kt

https://github.com/wikimedia/apps-android-wikipedia/pull/2490#pullrequestreview-674231050

Follow up #2: remove unnecessary comment

---

app/build.gradle

https://developer.android.com/jetpack/androidx/releases/fragment#1.3.4

Update androidx.fragment:fragment-ktx version to 1.3.4

---

app/src/main/java/org/wikipedia/login/LoginClient.kt

Minor update of using constant value in LoginClient.kt

---

app/src/main/java/org/wikipedia/feed/random/RandomClient.kt

This PR puts `RandomCard()` into a list before actually posting the list to `FeedCoordinator`. 
https://phabricator.wikimedia.org/T277922

Fix: post Random article cards to the feed correctly.

---

app/build.gradle

https://github.com/junit-team/junit4/blob/HEAD/doc/ReleaseNotes4.13.2.md

Update junit version to 4.13.2

---

app/build.gradle

https://developer.android.com/jetpack/androidx/releases/recyclerview#recyclerview-1.2.1

Update androidx.recyclerview version to 1.2.1

---

app/src/main/java/org/wikipedia/notifications/NotificationPresenter.kt

This bit of code was converted incorrectly (by me!).
It's not supposed to be an else-if condition.

Fix secondary actions in notifications.

---

app/src/main/java/org/wikipedia/page/PageViewModel.kt

The previous change was made by accident.
https://github.com/wikimedia/apps-android-wikipedia/pull/2534/files#r667944007

Fix: get cache control status correctly in PageViewModel

---

app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
app/src/main/java/org/wikipedia/page/PageFragment.kt
app/src/main/java/org/wikipedia/page/PageFragmentLoadState.kt

This implements the proper "retry" mechanism after submitting an edit (via the general editing activity, or from description editing).

Retry for updated revision after submitting edits.

---

app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt
app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt

https://phabricator.wikimedia.org/T284532#7207932

Tweak: make reply/new topic buttons disabled and adjust the opacity.

---

app/src/main/java/org/wikipedia/page/PageTitle.java
app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt

https://phabricator.wikimedia.org/T286424

Automatically navigate to Talk topic from notification intent.

---

app/build.gradle

https://developer.android.com/jetpack/androidx/releases/core#core_and_core-ktx_version_160_2

Update android core-ktx version to 1.6.0

---

app/build.gradle

https://developer.android.com/jetpack/androidx/releases/fragment#1.3.5

Update fragment-ktx version to 1.3.5

---

app/build.gradle
app/src/main/java/org/wikipedia/navtab/NavTabLayout.kt

https://github.com/material-components/material-components-android/releases/tag/1.4.0

Update android.material version to 1.4.0

---

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt

https://phabricator.wikimedia.org/T286098

Fix: Incorrect contributions number in SE task screen after the changing app langauges

---

app/src/main/java/org/wikipedia/analytics/NotificationFunnel.kt
app/src/main/java/org/wikipedia/notifications/NotificationItemActionsDialog.kt

https://meta.wikimedia.org/wiki/Schema_talk:MobileWikiAppNotificationInteraction

Make action_rank values more readable and match the schema description

---

app/build.gradle

https://developer.android.com/jetpack/androidx/releases/test#1.4.0

Update espresso related libraries version

---

app/src/main/res/values/strings.xml

https://phabricator.wikimedia.org/T287597

Tweak verbiage when posting Talk topics and replies.

---

app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt

https://phabricator.wikimedia.org/T287721

Fix link preview loading indicator when images are disabled.

---

app/src/main/java/org/wikipedia/history/db/HistoryEntryWithImageDao.kt

This takes care of warnings shown in the console from the Room annotation processor.

Fix a couple of Room build warnings.

---

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
app/src/main/java/org/wikipedia/userprofile/ContributionsActivity.kt
app/src/main/java/org/wikipedia/userprofile/ContributionsFragment.kt
app/src/main/java/org/wikipedia/userprofile/ContributionsHeaderView.kt

https://phabricator.wikimedia.org/T287031

Show all contribution numbers in Edits task and Contributions screens

---

app/src/main/java/org/wikipedia/analytics/eventplatform/NotificationInteractionEvent.kt

* Suppress warnings about unused parameters.
* Arrange constructor parameters in a readable way.

Follow-up to MEP NotificationInteraction events.

---

app/src/main/java/org/wikipedia/search/SearchResultsFragment.kt
app/src/main/java/org/wikipedia/views/TabCountsView.kt

[`ViewCompat.setBackgroundTintList()`](https://developer.android.com/reference/androidx/core/view/ViewCompat#setBackgroundTintList(android.view.View,%20android.content.res.ColorStateList)) contains a workaround for a bug that occurs on API level 21.

Use ViewCompat.setBackgroundTintList().

---

app/src/main/java/org/wikipedia/navtab/MenuNavTabDialog.kt
app/src/main/res/layout/view_main_drawer.xml

* Make the entire width of the top item clickable.

Follow-up to More list updates.

---

app/src/main/java/org/wikipedia/createaccount/CreateAccountActivity.kt
app/src/main/java/org/wikipedia/login/ResetPasswordActivity.kt
app/src/main/res/values/strings.xml
app/src/test/java/org/wikipedia/createaccount/CreateAccountActivityTest.java

https://phabricator.wikimedia.org/T288295

Verify 8-character password length requirement locally.

---

app/src/main/java/org/wikipedia/database/AppDatabase.kt

Now that we've seen that no further significant crashes have arisen in production due to the Room migration, we can fix the remaining _insignificant_ crashes due to edge cases that are too obscure for us to reproduce.

Plug up remaining minor issues in database conversion.

---

app/src/main/res/layout/activity_talk_topics.xml

https://phabricator.wikimedia.org/T274836#7269921

Set minimum height on last modified view in talk page

---

app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt

**Phab:** https://phabricator.wikimedia.org/T287594

Design tweak: Show the soft keyboard on talk responses

---

app/src/main/java/org/wikipedia/settings/LogoutPreference.kt

* The entire preference that contains the LOG OUT button was clickable, but didn't do anything, so let's not make it clickable.

Follow-up to "More" list tweak.

---

app/src/main/java/org/wikipedia/navtab/MenuNavTabDialog.kt
app/src/main/res/layout/view_main_drawer.xml

https://phabricator.wikimedia.org/T287958#7287961

Tweak: add "open in external" icon to the right of username view

---

build.gradle

https://kotlinlang.org/docs/whatsnew1530.html#apple-silicon-support

Update kotlin-gradle-plugin version to 1.5.30

---

app/src/main/java/org/wikipedia/dataclient/mwapi/EditorTaskCounts.kt

Removed the `EditStreak` related functions (but keep the `editStreak: JsonElement` for reference) since we are not actually using the them.

Follow up: EditorTaskCounts Kotlin conversion

---

app/src/main/java/org/wikipedia/page/PageFragment.kt

This Callable was relying on an exception being thrown for half of its logic, which is discouraged in RxJava.  This _may_ also fix the issue seen in https://phabricator.wikimedia.org/T290366 although I still haven't reproduced it.

Clean up Callable that updates reading list bookmark icon.

---

app/src/main/java/org/wikipedia/notifications/NotificationActivity.kt
app/src/main/res/menu/menu_notifications.xml

https://phabricator.wikimedia.org/T291575

Fix: put read/archived notifications menu options back

---

app/src/main/java/org/wikipedia/notifications/NotificationActivity.kt
app/src/main/res/menu/menu_notifications.xml

It is a revert PR of #2831. Will self merge it.

Remove temporary fix for notification

---

app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt

https://phabricator.wikimedia.org/T291781

Insert newline after adding short description template.

---

app/src/main/java/org/wikipedia/page/PageActivity.kt
app/src/main/java/org/wikipedia/page/tabs/TabActivity.kt
app/src/main/res/layout/activity_page.xml
app/src/main/res/layout/activity_tabs.xml
app/src/main/res/values/styles.xml

This PR also updates the icons' color in `PageActivity` to keep consistency. 
https://phabricator.wikimedia.org/T291682

Add notification bell icon to TabActivity

---

app/build.gradle
app/src/main/java/org/wikipedia/util/CustomTabsUtil.kt

This even uses our Theme colors (light, dark, etc) to customize the toolbar of the Custom Tab.
https://phabricator.wikimedia.org/T291969

Add basic ability to open any URL in a Custom Tab.

---

app/src/main/java/org/wikipedia/analytics/NotificationPreferencesFunnel.kt
app/src/main/java/org/wikipedia/notifications/NotificationActivity.kt
app/src/main/java/org/wikipedia/notifications/NotificationsFilterActivity.kt
app/src/main/java/org/wikipedia/views/SearchAndFilterActionProvider.kt

**Phab**: https://phabricator.wikimedia.org/T288068#7385976

Wire-up analytics for notifications search and filter

---

app/src/main/java/org/wikipedia/page/PageTitle.kt
app/src/main/java/org/wikipedia/views/NotificationActionsOverflowView.kt
app/src/main/res/layout/view_notification_actions_overflow.xml
app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

https://phabricator.wikimedia.org/T288065#7389764

Add a user talk page menu item to the notification list item overflow

---

app/src/main/java/org/wikipedia/edit/preview/EditPreviewFragment.kt
app/src/main/java/org/wikipedia/notifications/NotificationLinkHandler.kt
app/src/main/java/org/wikipedia/page/LinkHandler.kt
app/src/main/java/org/wikipedia/page/LinkMovementMethodExt.kt
app/src/main/java/org/wikipedia/page/PageFragment.kt
app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt

https://phabricator.wikimedia.org/T288064#7386546

Open native diff page when clicking on an diff page url

---

app/src/main/java/org/wikipedia/notifications/NotificationActivity.kt
app/src/main/res/layout/item_notification.xml

https://phabricator.wikimedia.org/T288066#7398859

Tweak: update notification list item font family

---

app/src/main/java/org/wikipedia/talk/TalkPageSurvey.kt
app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

* Remove the dialog title, since we don't have translations for it.

Final tweaks for Talk Page survey.

---

app/src/main/java/org/wikipedia/readinglist/ReadingListBehaviorsUtil.kt

https://phabricator.wikimedia.org/T293573
It is showing the dialog of warning mobile data usage when toggling off the offline reading.

Showing the mobile data downloading dialog correctly when toggle offline

---

app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt

1. Turn on "Don't keep activities"
2. Go to any article and go to the `SectionActivity` screen
3. Try to edit something and go back to the device home screen
4. Go back to the app and you will notice the edit field is not editable.

Preserve the status of editing allowed in the SectionActivity

---

app/src/main/java/org/wikipedia/notifications/NotificationActivity.kt
app/src/main/java/org/wikipedia/search/SearchFragment.kt
app/src/main/res/drawable/lang_button_shape_border.xml
app/src/main/res/layout/item_notification.xml

https://phabricator.wikimedia.org/T294369#7497340

Final design tweaks for notification list items.

---

app/src/main/java/org/wikipedia/notifications/NotificationActivity.kt
app/src/main/java/org/wikipedia/notifications/NotificationFilterItemView.kt
app/src/main/java/org/wikipedia/views/SearchAndFilterActionProvider.kt

`ImageViewCompat,setImageTintList()` contains a workaround for a bug on API level 21 for the `ImageView#setImageTintList()` method.

Use ImageViewCompat.setImageTintList().

---

app/src/main/java/org/wikipedia/notifications/NotificationActivity.kt

https://phabricator.wikimedia.org/T295785

Fix and simplify counting of unread notifications in tab headers.

---

app/build.gradle

https://developer.android.com/jetpack/androidx/releases/core#core_and_core-ktx_version_170_2
https://developer.android.com/jetpack/androidx/releases/browser#version_140_3

Update androidx core and browser library version

---

app/build.gradle

https://firebase.google.com/support/release-notes/android#messaging-ktx_v23-0-0

Update firebase-messaging-ktx library version to 23.0.0

---

app/src/main/res/values/styles.xml

https://phabricator.wikimedia.org/T295927

Make FlatButton style overflowable to multiple lines.

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/wikipedia/analytics/NotificationPreferencesFunnel.kt
app/src/main/java/org/wikipedia/notifications/NotificationActivity.kt
app/src/main/java/org/wikipedia/notifications/NotificationFilterActivity.kt
app/src/main/java/org/wikipedia/notifications/NotificationFilterItemView.kt
app/src/main/java/org/wikipedia/notifications/NotificationViewModel.kt
app/src/main/java/org/wikipedia/views/SearchAndFilterActionProvider.kt
app/src/main/res/layout/activity_notifications_filters.xml

This is for naming consistency.

Rename NotificationsFilterActivity to NotificationFilterActivity

---

app/src/main/java/org/wikipedia/notifications/NotificationActivity.kt
app/src/main/java/org/wikipedia/notifications/NotificationViewModel.kt

The current search function in NotificationActivity is broken because the search query is not applied correctly.

Fix: search function does not work in NotificationActivity

---

app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt

https://phabricator.wikimedia.org/T295696

Add "top" anchor in edit summary only for English edits.

---

app/build.gradle
app/src/main/java/org/wikipedia/analytics/eventplatform/CustomizeToolbarEvent.kt
app/src/main/java/org/wikipedia/analytics/eventplatform/TimedEvent.kt
app/src/main/java/org/wikipedia/page/customize/CustomizeQuickActionsFragment.kt

**Phab:** https://phabricator.wikimedia.org/T296753

Wired-up analytics for customizing toolbar

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

https://developer.android.com/studio/releases/gradle-plugin

Update gradle version to 7.2 and AGP dependency to 7.1.0

---

app/src/main/java/org/wikipedia/page/LinkMovementMethodExt.kt
app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt
app/src/main/java/org/wikipedia/talk/UserTalkPopupHelper.kt
app/src/main/res/menu/menu_user_talk_popup.xml
app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

This is independent of @-mentions. This should work in the general case of tapping on any username link while browsing talk topics.
https://phabricator.wikimedia.org/T299644

Add drop-down menu when tapping on usernames in Talk topics.

---

app/src/main/java/org/wikipedia/page/customize/CustomizeToolbarFragment.kt
app/src/main/java/org/wikipedia/page/customize/CustomizeToolbarViewModel.kt
app/src/main/java/org/wikipedia/settings/Prefs.kt
app/src/main/res/layout/dialog_theme_chooser.xml
app/src/main/res/layout/item_customize_toolbar.xml
app/src/main/res/layout/item_customize_toolbar_menu.xml
app/src/main/res/layout/item_customize_toolbar_tab.xml

(to be reviewed by @cooltey)
* Correctly make items swipeable with long-press action, same as Feed configuration.
* De-duplicate default list of menu items.
* Don't use fully qualified component names in XML.

Follow-up to Customize Toolbar.

---

app/src/main/java/org/wikipedia/page/PageFragment.kt
app/src/main/java/org/wikipedia/page/action/PageActionItem.kt
app/src/main/java/org/wikipedia/views/PageActionOverflowView.kt
app/src/main/res/layout/item_customize_toolbar.xml
app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

https://phabricator.wikimedia.org/T296753#7664098
https://phabricator.wikimedia.org/T296753#7664447

Tweak: customize toolbar strings and icon tint update

---

app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt
app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

https://phabricator.wikimedia.org/T298974

Update machine learning warning for the short description

---

app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayFragment.kt
app/src/main/res/layout/view_events_layout.xml

https://phabricator.wikimedia.org/T300941

Fix: use correct view binding on the OnThisDayFragment

---

build.gradle

The update message came out when upgrading the IDE to version Bumblebee

Update android gradle plugin version to 7.1.1

---

app/build.gradle
app/src/main/java/org/wikipedia/settings/EditTextAutoSummarizePreference.kt

https://github.com/material-components/material-components-android/releases/tag/1.5.0
https://developer.android.com/jetpack/androidx/releases/appcompat#1.4.1
https://github.com/androidx/constraintlayout/wiki/What's-New-in-2.1
https://developer.android.com/jetpack/androidx/releases/preference#1.2.0
https://jsoup.org/news/release-1.13.1

Update library versions

---

app/build.gradle

https://firebase.google.com/support/release-notes/android#ml_kit_for_firebase_model_interpreter_version_1703

Update google MLKit version to 17.0.3

---

app/src/main/java/org/wikipedia/page/PageActivity.kt

* Simplify some logic.
* Guard against activity being destroyed.

Follow-up to Tooltip for customizing toolbar.

---

app/src/main/java/org/wikipedia/page/ToCHandler.kt

https://phabricator.wikimedia.org/T301074

Fix highlighting of Table-of-contents section when opening ToC drawer.

---

app/src/main/java/org/wikipedia/language/AppLanguageLookUpTable.kt

Remove comments since the variable names are pretty clear.

Follow up: convert AppLanguageLookUpTable to Kotlin

---

app/src/main/java/org/wikipedia/search/SearchFragment.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt

See these warnings while doing another task.

Hygiene: update imports in SearchFragment and code style update

---

build.gradle

https://androidstudio.googleblog.com/2022/02/android-studio-bumblebee-202111-patch-2.html

Update gradle plugin version to 7.1.2

---

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt

Just some cleanup; independent of EditAttemptStep release.

Follow-up to EditAttempt changes.

---

app/src/main/java/org/wikipedia/page/PageActivity.kt
app/src/main/java/org/wikipedia/page/PageFragment.kt
app/src/main/java/org/wikipedia/page/SidePanelHandler.kt
app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt
app/src/main/java/org/wikipedia/talk/TalkTopicsProvider.kt

* Slightly clarify naming of a few things.
* Slightly simplify passing of parameters into the side panel.
* Put the Talk topics into a feature flag (pre-beta), so that the API call(s) are not made unnecessarily until we build out the proper pathways to activate them.

Follow-up to Talk topics in side panel.

---

app/src/main/java/org/wikipedia/notifications/NotificationActivity.kt

We hardcoded a certain length of the string and make them a `SpannableString` object, but it only works for English. 
For different languages, the blue color will be applied in an incorrect place.

Fix: show clickable blue link in search empty message in Notification correctly

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
app/src/main/res/layout/fragment_article_edit_details.xml
app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

https://phabricator.wikimedia.org/T299180

Final design tweaks for edit diffs.

---

app/src/main/java/org/wikipedia/page/PageActivity.kt
app/src/main/java/org/wikipedia/settings/Prefs.kt
app/src/main/res/values-qq/strings.xml
app/src/main/res/values/preference_keys.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/developer_preferences.xml

**Phab:**https://phabricator.wikimedia.org/T303975

Remove notification tooltip

---

app/build.gradle

https://developer.android.com/jetpack/androidx/releases/paging#version_31_2

Update androidx.paging version to 3.1.1

---

app/build.gradle

https://firebase.google.com/support/release-notes/android#messaging_v23-0-2

Update firebase-messaging version to 23.0.2

---

app/build.gradle

https://developer.android.com/jetpack/androidx/releases/room#version_242_3

Update androidx.room version to 2.4.2

---

app/src/main/java/org/wikipedia/commons/ImageTagsProvider.kt
app/src/main/java/org/wikipedia/dataclient/Service.kt
app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryPage.kt
app/src/main/java/org/wikipedia/gallery/GalleryActivity.kt
app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.kt
app/src/main/java/org/wikipedia/userprofile/ContributionsFragment.kt

https://phabricator.wikimedia.org/T304797

No longer use wbgetentities to get terms.

---

app/src/main/java/org/wikipedia/analytics/eventplatform/TimedEvent.kt

**Conversation :**  https://github.com/wikimedia/apps-android-wikipedia/pull/3040#discussion_r838866886

Get the updated value of duration in timed events.

---

app/src/main/java/org/wikipedia/views/UserMentionInputView.kt

https://phabricator.wikimedia.org/T305348

Fix improper scrolling/jumping when composing long Talk message.

---

build.gradle

https://kotlinlang.org/docs/whatsnew1620.html

Update kotlin-gradle-plugin version to 1.6.20

---

app/src/main/java/org/wikipedia/page/PageFragment.kt

All tasks related to Edit History have passed design review, so this whole feature is ready to go.

Lift feature flag from Edit History.

---

app/src/main/java/org/wikipedia/page/PageActivity.kt
app/src/main/java/org/wikipedia/page/tabs/TabActivity.kt

https://phabricator.wikimedia.org/T305912

Fix possible misassociation of tab bitmap with tab title.

---

app/src/main/java/org/wikipedia/analytics/eventplatform/EditHistoryInteractionEvent.kt
app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
app/src/main/java/org/wikipedia/diff/ArticleEditDetailsViewModel.kt
app/src/main/java/org/wikipedia/page/PageFragment.kt
app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListActivity.kt
app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListViewModel.kt

Analytics wiring for showing edit history screen, showing revision screen and the related actions like compare and thank.

Analytics wiring for edit history

---

app/src/main/java/org/wikipedia/categories/CategoryActivityViewModel.kt
app/src/main/java/org/wikipedia/categories/CategoryDialogViewModel.kt
app/src/main/java/org/wikipedia/diff/ArticleEditDetailsViewModel.kt
app/src/main/java/org/wikipedia/language/LangLinksViewModel.kt
app/src/main/java/org/wikipedia/page/PageFragment.kt
app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListViewModel.kt
app/src/main/java/org/wikipedia/page/shareafact/ShareHandler.kt
app/src/main/java/org/wikipedia/random/RandomFragment.kt
app/src/main/java/org/wikipedia/readinglist/LongPressMenu.kt
app/src/main/java/org/wikipedia/settings/languages/WikipediaLanguagesFragment.kt
app/src/main/java/org/wikipedia/theme/ThemeChooserDialog.kt
app/src/main/java/org/wikipedia/theme/ThemeFittingRoomFragment.kt

* Fix a few warnings related to nullability overrides.
* Remove usage of `JSONObject` in ShareHandler, and replace with modern Serializable.

Clean up a few warnings and style.

---

app/src/main/java/org/wikipedia/util/StringUtil.kt

https://play.google.com/console/u/1/developers/6169333749249604352/app/4972092403490495074/vitals/crashes/b871e34e/details?installedFrom=PLAY_STORE&days=7&versionCode=50401

Fix: possible ArrayIndexOutOfBoundsException in StringUtil.utf8Indices()

---

app/src/main/java/org/wikipedia/categories/CategoryActivity.kt
app/src/main/java/org/wikipedia/categories/CategoryDialog.kt
app/src/main/java/org/wikipedia/categories/CategoryDialogViewModel.kt
app/src/main/java/org/wikipedia/settings/RemoteConfigRefreshTask.kt
app/src/main/res/menu/menu_category.xml

https://phabricator.wikimedia.org/T307785

Add option to show categories of categories.

---

app/src/main/java/org/wikipedia/notifications/NotificationActivity.kt
app/src/main/java/org/wikipedia/page/customize/CustomizeToolbarItemView.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsSurvey.kt
app/src/main/java/org/wikipedia/views/NotificationActionsOverflowView.kt
app/src/main/java/org/wikipedia/views/PageActionOverflowView.kt

Use the relative compound drawable methods in `TextView` to support RTL layouts.
**Screenshots**
Before change:
After change:

Use setCompoundDrawablesRelative() methods.

---

app/src/main/java/org/wikipedia/activity/BaseActivity.kt

The issue (https://issuetracker.google.com/issues/141132133, https://issuetracker.google.com/issues/141351441) has been marked as fixed.

Remove WebView fix.

---

app/build.gradle

https://github.com/material-components/material-components-android/releases

Update android-material version to 1.6.0

---

app/src/main/java/org/wikipedia/feed/news/NewsCardView.kt
app/src/main/java/org/wikipedia/feed/news/NewsFragment.kt
app/src/main/res/layout/fragment_news.xml
app/src/main/res/layout/view_card_news.xml

Generic recyclerview names have been changed to be more specific to help event logging for breadcrumbs

News: Better naming for breadcrumbs

---

app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsFragment.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestionsActivity.kt
app/src/main/res/layout/view_description_edit.xml

https://phabricator.wikimedia.org/T308758

Move info icons from DescriptionEditFragment to SuggestedEditsCardsFragment

---

app/src/main/java/org/wikipedia/dataclient/Service.kt
app/src/main/java/org/wikipedia/dataclient/mwapi/UserInfo.kt
app/src/main/java/org/wikipedia/dataclient/rollback/Rollback.kt
app/src/main/java/org/wikipedia/dataclient/rollback/RollbackPostResponse.kt

https://phabricator.wikimedia.org/T303547

Add rollback API for rollback function in the Diff view

---

app/src/main/java/org/wikipedia/page/PageActivity.kt

Use the existing `enqueueTooltip` function to show the tooltip properly.

Properly enqueue the customize tooltip in PageActivity

---

app/src/main/res/layout/fragment_suggested_edits_tasks.xml

https://phabricator.wikimedia.org/T309865

Fix placement of Contribution History circle button.

---

app/src/main/java/org/wikipedia/language/LangLinksActivity.kt
app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.kt
app/src/main/java/org/wikipedia/util/FeedbackUtil.kt

https://phabricator.wikimedia.org/T309970

Add a couple of missing usages of fromHtml().

---

app/src/main/java/org/wikipedia/analytics/TalkFunnel.kt
app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt
app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt
app/src/main/java/org/wikipedia/views/TalkTopicsSortOverflowView.kt

https://phabricator.wikimedia.org/T303519

Wire-up analytics for talk page redesign

---

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
app/src/main/java/org/wikipedia/userprofile/ContributionDetailsFragment.kt
app/src/main/java/org/wikipedia/userprofile/ContributionsFragment.kt
app/src/main/java/org/wikipedia/userprofile/ContributionsHeaderView.kt
app/src/main/java/org/wikipedia/userprofile/ContributionsItemView.kt

https://phabricator.wikimedia.org/T308755

Update Edits contributions icons

---

app/src/main/java/org/wikipedia/analytics/EditFunnel.kt
app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt

https://phabricator.wikimedia.org/T303547#7984518

Wire-up analytics to rollback actions

---

app/src/main/java/org/wikipedia/dataclient/discussiontools/ThreadItem.kt
app/src/main/java/org/wikipedia/talk/TalkThreadItemView.kt
app/src/main/java/org/wikipedia/talk/TalkTopicViewModel.kt

https://phabricator.wikimedia.org/T297617#7991442

Blue reply button only on the first top-level talk topic.

---

app/src/main/java/org/wikipedia/page/SidePanelHandler.kt
app/src/main/java/org/wikipedia/talk/TalkTopicHolder.kt
app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt

- Simplify by using Binding classes.
- Remove unused `position` parameter.

Follow-up to ConcatAdapter.

---

build.gradle

https://developer.android.com/studio/releases/gradle-plugin#7-2-0

Update android gralde plugin version to 7.2.1

---

app/build.gradle

https://github.com/material-components/material-components-android/releases/tag/1.6.1
https://developer.android.com/jetpack/androidx/releases/appcompat#1.4.2
https://github.com/androidx/constraintlayout/wiki/What's-New-in-2.1#new-in-214

Update view component libraries version

---

app/src/main/java/org/wikipedia/search/SearchFragment.kt

https://phabricator.wikimedia.org/T311320

Fix: load recent search content correctly when only one app langauge

---

build.gradle

https://firebase.google.com/support/release-notes/android#google-services_plugin_v4-3-12

Update com.google.gms:google-services version to 4.3.12

---

app/src/main/res/layout/dialog_undo_edit.xml

The contents of the Undo dialog must be scrollable to account for small screens or large font selection.
https://phabricator.wikimedia.org/T311706

Put Undo dialog contents in a ScrollView.

---

build.gradle

https://firebase.google.com/support/release-notes/android#2022-06-28

Update google.gms:google-services version to 4.3.13

---

app/build.gradle

https://firebase.google.com/support/release-notes/android#messaging_v23-0-6

Update firebase-messaging version to 23.0.6

---

app/build.gradle
app/src/main/java/org/wikipedia/categories/CategoryActivity.kt
app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt
app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt

https://developer.android.com/jetpack/androidx/releases/fragment#version_15_2

Update androidx.fragment:fragment-ktx version to 1.5.0

---

app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt

https://phabricator.wikimedia.org/T313308

Edit notices: Only show keys starting with "editnotice"

---

.github/workflows/android.yml
.github/workflows/android_branch.yml
.github/workflows/android_pr.yml
.github/workflows/android_smoke_test.yml

Use [gradle-build-action](https://github.com/gradle/gradle-build-action) to speed up.

Optimize CI a bit

---

app/src/main/java/org/wikipedia/views/TalkTopicsSortOverflowView.kt

https://phabricator.wikimedia.org/T299033#8104360

Fix: talk page sorting function does not work properly

---

app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditUtil.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt

https://phabricator.wikimedia.org/T313267

Detect whether page is protected before allowing editing description.

---

build.gradle

https://developer.android.com/studio/releases/gradle-plugin#7-2-0

Update android gradle plugin to 7.2.2

---

app/src/main/res/menu/menu_user_talk_popup.xml
app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

https://phabricator.wikimedia.org/T315242
This PR also removes one of the unused "profile" related menu option.

Remove "Profile" from the user page menu option

---

app/build.gradle

https://developer.android.com/jetpack/androidx/releases/fragment#1.5.2

Update androidx.fragment:fragment-ktx to version 1.5.2

---

app/build.gradle

https://firebase.google.com/support/release-notes/android#messaging_v23-0-7

Update firebase-messaging version to 23.0.7

---

app/src/main/java/org/wikipedia/dataclient/Service.kt
app/src/main/java/org/wikipedia/dataclient/mwapi/ShortenUrlResponse.kt

This can be merged into master, since it's just the model + API call that is not yet used by the final feature.
https://phabricator.wikimedia.org/T316836

API underpinnings for URL shortening service.

---

app/src/main/java/org/wikipedia/views/UserMentionEditText.kt

https://phabricator.wikimedia.org/T317132

Fix handling of newline chars in user @mentions.

---

app/build.gradle

https://firebase.google.com/support/release-notes/android#messaging_v23-0-8

Update firebase messaging library version to 23.0.8

---

app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt

https://phabricator.wikimedia.org/T318829
It will still have a scrolling animation from the top to the highlighted position, but faster.

Replace smoothScrollToPosition with basic scrollToPostion in talk topic

---

app/src/main/java/org/wikipedia/gallery/GalleryActivity.kt
app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.kt
app/src/main/java/org/wikipedia/page/PageFragment.kt

* Upgrade GalleryItemFragment to use MenuProvider, and centralize its logic for inflating its own menu.
* Removed unnecessary `setHasOptionsMenu()` call from PageFragment.

Update one more instance of MenuProvider.

---

app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
app/src/main/res/menu/menu_action_mode_reading_lists.xml

**Phab:** https://phabricator.wikimedia.org/T320999

Add option to delete multiple lists

---

app/build.gradle

https://firebase.google.com/support/release-notes/android#messaging-directboot_v23-1-0

Update firebase cloud messaging library version to 23.1.0

---

app/src/main/java/org/wikipedia/page/PageFragmentLoadState.kt
build.gradle

https://kotlinlang.org/docs/whatsnew1720.html

Update kotlin to 1.7.20.

---

app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt

This is a better solution for math formula images.
https://phabricator.wikimedia.org/T322171
https://phabricator.wikimedia.org/T129054#2095664

Use a invert() function to properly show the math formula images

---

app/src/main/java/org/wikipedia/activity/BaseActivity.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListsReceiveSurveyHelper.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListsShareHelper.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListsShareSurveyHelper.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListsSurveyHelper.kt
app/src/main/java/org/wikipedia/settings/Prefs.kt
app/src/main/res/values/preference_keys.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/developer_preferences.xml

There is a little duplication of logic, but I believe this will make it simpler to remove when we're done.
https://phabricator.wikimedia.org/T322088

Split off Reading Lists surveys into two independent surveys.

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

Only add new strings and will do updates on the tweak PR.

Update strings for shareable reading list

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

For the upcoming tweak PR for shareable reading list

Update shareable reading list strings for translation

---

app/src/main/java/org/wikipedia/search/SearchResults.kt
app/src/main/java/org/wikipedia/search/SearchResultsFragment.kt
app/src/main/res/layout/fragment_search_results.xml
app/src/test/java/org/wikipedia/search/FullTextSearchClientTest.kt
app/src/test/java/org/wikipedia/search/PrefixSearchClientTest.kt

Per discussion: https://phabricator.wikimedia.org/T303933#8414353

Remove search suggestion related code from the app

---

app/build.gradle

https://developer.android.com/jetpack/androidx/releases/test#espresso_350_3
https://developer.android.com/jetpack/androidx/releases/test#junit_extensions_114_2
https://developer.android.com/jetpack/androidx/releases/test#orchestrator_142_2

Update test releated libraries version

---

app/src/main/java/org/wikipedia/main/MainActivity.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt

https://phabricator.wikimedia.org/T316834#8438620

Tweak: shareable reading list design feedback

---

app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt

https://phabricator.wikimedia.org/T324521

Fix flashing of onboarding tip when importing reading list.

---

app/src/main/java/org/wikipedia/analytics/eventplatform/BreadCrumbLogEvent.kt
app/src/main/java/org/wikipedia/analytics/eventplatform/BreadCrumbViewUtil.kt

Excluding the login screens from any event collection other than "shown"

Exclude some screens from click events

---

app/src/main/java/org/wikipedia/notifications/NotificationFilterItemView.kt

To prevent import confusion in the `WatchlistFilterItemView`

Use proper import in the NotificationFilterItemView

---

build.gradle

https://developer.android.com/studio/releases/gradle-plugin#android-gradle-plugin-7.4.1-february-2023

Update Android gradle plugin version to 7.4.1

---

app/src/main/java/org/wikipedia/readinglist/ReadingListsImportHelper.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListsShareHelper.kt

Instead of a single API call, make as many as necessary, windowed by 50 items.

Fix ability to share/receive a list with over 50 pages.

---

app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryResult.kt
app/src/main/java/org/wikipedia/watchlist/WatchlistItemView.kt

https://phabricator.wikimedia.org/T328453

Correctly show watchlist entries of "log" type.

---

app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt
app/src/main/java/org/wikipedia/history/HistoryFragment.kt

https://phabricator.wikimedia.org/T329237

Correctly hide voice icon when voice input unavailable.

---

build.gradle

https://developers.google.com/android/guides/releases#january_19_2023

Update gms google service version to 4.3.15

---

app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListsReceiveHelper.kt

Update the class name since we have another import and export helper.

Change ReadingListsImportHelper to ReadingListsReceiveHelper

---

app/src/main/java/org/wikipedia/readinglist/ReadingListItemView.kt
app/src/main/java/org/wikipedia/views/ReadingListsOverflowView.kt

**Phab:** https://phabricator.wikimedia.org/T319345

Remove feature flag for Export/Imp lists

---

app/build.gradle

https://github.com/ReactiveX/RxJava/releases/tag/v3.1.6
https://github.com/ReactiveX/RxAndroid/releases/tag/3.0.2

Update RxJava to 3.1.6 and RxAndroid to 3.0.2.

---

app/src/main/java/org/wikipedia/main/MainFragment.kt

https://phabricator.wikimedia.org/T329675

Fix: explicitly invalidate main menu when switching tabs.

---

app/src/main/java/org/wikipedia/page/PageActivity.kt
app/src/main/java/org/wikipedia/readinglist/MoveToReadingListDialog.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
app/src/main/java/org/wikipedia/readinglist/db/ReadingListDao.kt
build.gradle

The next follow up PR could be using coroutine in reading list behaviors.

Update Kotlin gradle plugin version to 1.8.0

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

Per request from this comment: [3829#pullrequestreview-1299632904](https://github.com/wikimedia/apps-android-wikipedia/pull/3829#pullrequestreview-1299632904)

Required strings for the shareable reading list preview screen

---

app/src/main/java/org/wikipedia/readinglist/ReadingListsExportImportHelper.kt

**Phab:** https://phabricator.wikimedia.org/T329805
- Fixed the json structure
- Added namespace into the mix

Fix: Overwriting of pages during RL export

---

app/src/main/res/menu/menu_reading_list_item.xml

Minor adjustment to reading list item pop-up options as suggested here during PM review.

Re-arranged reading list item pop-up menu

---

app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt

https://phabricator.wikimedia.org/T329868

Encode the talk topic title for sharing the topic link

---

app/build.gradle

Changelog: https://github.com/jhy/jsoup/releases

Update Jsoup to 1.15.4.

---

app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryPage.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListViewModel.kt
app/src/test/java/org/wikipedia/edit/wikitext/WikitextClientTest.kt

@cooltey  I saw your comment about using a `content` getter after merging, and I agree with it.

Follow-up to revision API slots.

---

app/build.gradle

https://firebase.google.com/support/release-notes/android#messaging_v23-1-2

Update firebase library version to 23.1.2

---

app/src/main/res/drawable/edit_improve_tag_selected_dark.xml
app/src/main/res/drawable/edit_improve_tag_selected_light.xml
app/src/main/res/drawable/edit_improve_tag_unselected_dark.xml
app/src/main/res/drawable/edit_improve_tag_unselected_light.xml
app/src/main/res/layout/fragment_article_edit_details.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/styles.xml
app/src/main/res/values/styles_black.xml
app/src/main/res/values/styles_dark.xml
app/src/main/res/values/styles_sepia.xml

This is for the upcoming component tickets.

Remove unused attritubes from attrs.xml

---

app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt
app/src/main/res/layout/view_description_edit.xml

Follow up task for #1 ~ #3 
https://phabricator.wikimedia.org/T327188#8673872

Follow-up tweaks of machine generate article description

---

app/src/main/java/org/wikipedia/settings/AboutActivity.kt

Use proper imports for functions and update naming.

Update imports and minor code clean up in AboutActivity

---

app/src/main/java/org/wikipedia/util/CenterCropWithFaceTransformation.kt
app/src/main/java/org/wikipedia/util/WhiteBackgroundTransformation.kt

If we look at the feed in dark mode with "image dimming" on, we can notice some images with faces will not be dimmed correctly.

Make sure dimming images on every images in dark mode

---

app/src/main/java/org/wikipedia/dataclient/Service.kt
app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryResult.kt
app/src/main/java/org/wikipedia/diff/ArticleEditDetailsActivity.kt
app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
app/src/main/java/org/wikipedia/diff/ArticleEditDetailsViewModel.kt
app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListActivity.kt
app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListViewModel.kt
app/src/main/java/org/wikipedia/usercontrib/UserContribListActivity.kt
app/src/main/java/org/wikipedia/watchlist/WatchlistFragment.kt

https://phabricator.wikimedia.org/T332173

When processing diffs, use pageId instead of page title.

---

app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.kt

https://phabricator.wikimedia.org/T333055

Remove HTML from Subject when sharing images.

---

app/src/main/java/org/wikipedia/diff/ArticleEditDetailsViewModel.kt
app/src/main/java/org/wikipedia/notifications/NotificationPresenter.kt
app/src/main/java/org/wikipedia/util/UriUtil.kt
app/src/test/java/org/wikipedia/util/UriUtilTest.kt

https://phabricator.wikimedia.org/T333369

Allow diff links from Notifications to go to native diff activity.

---

app/src/main/java/org/wikipedia/analytics/eventplatform/MachineGeneratedArticleDescriptionABCTest.kt
app/src/main/java/org/wikipedia/analytics/eventplatform/MachineGeneratedArticleDescriptionsAnalyticsHelper.kt
app/src/main/java/org/wikipedia/dataclient/wikidata/Entities.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditActivity.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditTutorialFragment.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt
app/src/main/java/org/wikipedia/views/SuggestedArticleDescriptionsDialog.kt
app/src/main/java/org/wikipedia/views/SuggestedArticleDescriptionsReportDialog.kt

Greatly simplify analytics functions.

Follow-up to machine suggestion analytics.

---

app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt

Hiding suggestions button in case of any api response errors

Hide suggestedEditButton on api response error

---

app/src/main/java/org/wikipedia/analytics/eventplatform/MachineGeneratedArticleDescriptionsAnalyticsHelper.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt

Data wiring updates:
- ApiSuggestions order added
- Suggestions display order added
- Time spent on edit added
- Api failed log added

Data wiring updates:

---

app/src/main/java/org/wikipedia/analytics/eventplatform/ABTest.kt
app/src/main/java/org/wikipedia/analytics/eventplatform/MachineGeneratedArticleDescriptionABCTest.kt
app/src/main/java/org/wikipedia/analytics/eventplatform/MachineGeneratedArticleDescriptionsAnalyticsHelper.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditActivity.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditTutorialFragment.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt
app/src/main/java/org/wikipedia/settings/Prefs.kt
app/src/main/java/org/wikipedia/views/SuggestedArticleDescriptionsDialog.kt
app/src/main/java/org/wikipedia/views/SuggestedArticleDescriptionsReportDialog.kt
app/src/main/res/values/preference_keys.xml

A bit further cleanup, object-orientation, and consistency.

Followup (final?) to machine suggestion analytics.

---

app/src/main/java/org/wikipedia/analytics/eventplatform/MachineGeneratedArticleDescriptionsAnalyticsHelper.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt

- Update timer logic and encapsulate it.

Follow up: Update timer logic

---

app/src/main/java/org/wikipedia/analytics/eventplatform/MachineGeneratedArticleDescriptionsAnalyticsHelper.kt

Shay wanted all key value pairs to be separated by `:`

Keeping a consistent delimiter between key : value pairs

---

app/src/main/java/org/wikipedia/descriptions/DescriptionEditTutorialFragment.kt
app/src/main/java/org/wikipedia/onboarding/OnboardingPageView.kt
app/src/main/res/layout/inflate_description_edit_tutorial_page_three.xml

**Phab:** https://phabricator.wikimedia.org/T331272#8751536

Fix: Show promise text at the correct place

---

app/src/main/res/layout/dialog_article_descriptions.xml
app/src/main/res/layout/dialog_description_suggestion_report.xml

Make suggested descriptions dialogs scrollable

---

app/src/main/res/values-ar/strings.xml
app/src/main/res/values-cs/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fi/strings.xml
app/src/main/res/values-hi/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-ko/strings.xml
app/src/main/res/values-ro/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-tr/strings.xml
app/src/main/res/values-vi/strings.xml
app/src/main/res/values-zh/strings.xml

This is still `wip` as we are waiting for some translations. However, please feel free to start review on the ones updated. Use the translation doc for verification.

Adding feature specific translations

---

app/src/main/res/values-nl/strings.xml

Dutch translations: Machine gen article descs

---

app/src/main/java/org/wikipedia/edit/preview/EditPreviewFragment.kt

https://phabricator.wikimedia.org/T335035

Fix/mitigate background color when previewing edits in Dark mode.

---

app/src/main/java/org/wikipedia/page/PageContainerLongPressHandler.kt
app/src/main/java/org/wikipedia/page/PageFragment.kt

https://phabricator.wikimedia.org/T334787

Fix opening page from external link, when already exists in another tab.

---

app/src/main/java/org/wikipedia/analytics/eventplatform/EditAttemptStepEvent.kt

https://wikimedia.slack.com/archives/CSV483812/p1681928691268299
Version of the schema needs to be updated to get geo data included.

Update editAttemptStepSchema version - > 1.4.0

---

app/src/main/res/values/strings.xml

**Phab:** https://phabricator.wikimedia.org/T333984

Copy change to edit warning

---

app/src/main/java/org/wikipedia/analytics/eventplatform/WatchlistAnalyticsHelper.kt
app/src/main/java/org/wikipedia/diff/ArticleEditDetailsViewModel.kt
app/src/main/java/org/wikipedia/page/PageFragment.kt
app/src/main/java/org/wikipedia/talk/TalkTopicsViewModel.kt

Here's what I meant by an optional `context` parameter.

Follow-up to Watchlist events.

---

app/src/main/java/org/wikipedia/dataclient/Service.kt
app/src/main/java/org/wikipedia/dataclient/growthtasks/GrowthImageSuggestion.kt
app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryPage.kt

https://phabricator.wikimedia.org/T335911
(does not interfere or impact any current functionality)

API underpinnings for Image Recommendations.

---

app/src/main/java/org/wikipedia/dataclient/Service.kt
app/src/main/java/org/wikipedia/dataclient/mwapi/ParamInfoResponse.kt

This will be useful for determining _whether_ the Image Recommendations growth feature is enabled on a given wiki.
https://phabricator.wikimedia.org/T335911

API underpinnings for Image Recommendations, part 2.

---

app/src/main/java/org/wikipedia/dataclient/Service.kt
app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryPage.kt

There may be a few more minor things when we're ready to start it, but this will be the crux.

API underpinnings for Nearby.

---

app/src/main/java/org/wikipedia/descriptions/DescriptionEditActivity.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt

**Phab: ** https://phabricator.wikimedia.org/T336278

Turn off Machine generated article descriptions in production and beta

---

app/build.gradle

https://github.com/material-components/material-components-android/releases/tag/1.9.0
https://developer.android.com/jetpack/androidx/releases/core#1.10.1
https://developer.android.com/jetpack/androidx/releases/fragment#1.5.7

Update Material/Androidx dependencies.

---

app/src/main/java/org/wikipedia/analytics/metricsplatform/ArticleEvent.kt

Verifying the new MP in beta only.

Put the MetricsPlatform wiring behind Beta flag

---

app/build.gradle

To incorporate @dbrant's recent change:
https://gerrit.wikimedia.org/r/c/mediawiki/libs/metrics-platform/+/927225
update MP lib to 1.8

Update Metrics Platform version

---

app/build.gradle

- Fix api endpoints with needed path and query params:
https://gerrit.wikimedia.org/r/c/mediawiki/libs/metrics-platform/+/927322
- Fix events serialization:
https://gerrit.wikimedia.org/r/c/mediawiki/libs/metrics-platform/+/927663

Bump Metrics Platform version to 1.9

---

app/src/main/res/layout/fragment_insert_media_settings.xml
app/src/main/res/layout/fragment_preview_summary.xml

- Fix background color of Insert Image settings fragment.
- Remove explicit tint from checkboxes in Edit Summary fragment.
https://phabricator.wikimedia.org/T336702#8906322

Additional tiny tweaks in Editing flow.

---

app/src/main/res/color/color_state_nav_tab.xml
app/src/main/res/color/color_state_nav_tab_dark.xml
app/src/main/res/color/color_state_nav_tab_light.xml
app/src/main/res/layout/fragment_main.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/styles.xml
app/src/main/res/values/styles_dark.xml

https://phabricator.wikimedia.org/T336702#8905766

Design tweak and simplification of Nav Bar colors.

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

Added a generic string for as a placeholder translated message for beta and production releases.

Add release notes string to code base

---

app/src/main/java/org/wikipedia/util/FeedbackUtil.kt
app/src/main/res/layout/view_plain_text_tooltip.xml

- Simplify the layout a bit, and add a comment to warn about Balloon bug.

Follow-up to tooltip button width.

---

app/src/main/java/org/wikipedia/captcha/CaptchaHandler.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt
app/src/main/res/layout/view_description_edit.xml

Follow-up to captcha in description editing.

---

app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
app/src/main/java/org/wikipedia/edit/preview/EditPreviewFragment.kt
app/src/main/res/layout/fragment_preview_edit.xml

This makes the edit preview more efficient and more in line with updated designs.

Design tweaks/fixes in edit preview.

---

app/build.gradle
app/src/main/java/org/wikipedia/main/MainFragment.kt
app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt

https://firebase.google.com/support/release-notes/android#messaging_v23-2-0
https://developer.android.com/jetpack/androidx/releases/room#2.5.2
https://developer.android.com/jetpack/androidx/releases/fragment#1.6.1
https://developer.android.com/jetpack/androidx/releases/paging#3.2.0
https://developer.android.com/jetpack/androidx/releases/recyclerview#recyclerview-1.3.1

Update a few dependencies.

---

app/src/main/java/org/wikipedia/connectivity/ConnectionStateMonitor.kt

(extremely obscure, but easily remedied)
https://issuetracker.google.com/issues/175055271

Fix obscure potential crash when updating network online state.

---

app/src/main/java/org/wikipedia/Constants.kt
app/src/main/java/org/wikipedia/wiktionary/WiktionaryDialog.kt

Clean up unused constant values and reduce not-null type in WikitionaryDialog

Clean up unused constant values and reduce not-null type in WikitionaryDialog

---

app/src/main/res/layout/fragment_main.xml

https://phabricator.wikimedia.org/T343177

Make sure to show color on the main navigation correctly

---

app/src/main/res/layout/view_edit_history_filter_overflow.xml

https://phabricator.wikimedia.org/T343391

Fix layout of edit history filter popup.

---

app/src/main/java/org/wikipedia/language/LangLinksViewModel.kt

Follow up: minor update of type definition in LangLinksViewModel

---

app/build.gradle

https://firebase.google.com/support/release-notes/android#messaging_v23-2-1

Update firebase-messaging library version to 23.2.1

---

app/src/main/java/org/wikipedia/readinglist/AddToReadingListDialog.kt
app/src/main/java/org/wikipedia/readinglist/MoveToReadingListDialog.kt

Convert from RxJava to Coroutine in `AddToReadingListDialog.kt` and `MoveToReadingListDialog.kt`

Use coroutine in reading list dialog related classes

---

app/src/main/res/layout/view_onboarding_page.xml

Design tweaks:
- All onboarding screens will have left-aligned text from now on.
- Text color and styles have been fixed.
**Phab:** https://phabricator.wikimedia.org/T340668#9005986

Design tweaks: Image recs  fullscreen onboarding

---

app/src/main/java/org/wikipedia/dataclient/Service.kt
app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryResult.kt

A few API bits and model objects, which can be merged now since they don't interfere with anything else.

API underpinnings for Patroller tasks.

---

app/src/androidTest/java/org/wikipedia/database/AppDatabaseTests.kt

Minor fix to build, following the notifications change.

Minor fix for notification lists in tests

---

app/src/main/res/layout/activity_user_contrib.xml

We use multiple adapters for different conditions.

Remove unused views in the user contribution layout

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

The string will be used in the patroller tasks list of edits.

Add additional required string for patroller tasks

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

The string will be used in the patroller tasks filter page.

Add required string for patroller tasks

---

app/src/main/java/org/wikipedia/analytics/BreadcrumbsContextHelper.kt
app/src/main/java/org/wikipedia/analytics/eventplatform/BreadCrumbViewUtil.kt
app/src/main/java/org/wikipedia/main/MainFragment.kt
app/src/main/java/org/wikipedia/navtab/NavTabLayout.kt
app/src/main/java/org/wikipedia/settings/AboutActivity.kt
app/src/main/java/org/wikipedia/views/ViewUtil.kt

Simplify some code using the view tree traversal extensions: [`allViews`](https://developer.android.com/reference/kotlin/androidx/core/view/package-summary#(android.view.View).allViews()), [`ancestors`](https://developer.android.com/reference/kotlin/androidx/core/view/package-summary#(android.view.View).ancestors()) and [`descendants`](https://developer.android.com/reference/kotlin/androidx/core/view/package-summary#(android.view.ViewGroup).descendants()).

Use view tree extensions

---

app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt

https://phabricator.wikimedia.org/T346633

Correctly set content directionality in Link Previews.

---

app/src/main/java/org/wikipedia/edit/WikiTextKeyboardView.kt

This fixes the issue addressed here: https://github.com/wikimedia/apps-android-wikipedia/pull/4131#issuecomment-1730291098

Fix the issue of inserting invalid article link in wikitext keyboard

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

Thanks @amire80 for noticing it. #4206

Fix incorrect string name and values for Patroller Tasks

---

app/src/main/java/org/wikipedia/dataclient/donate/Campaign.kt
app/src/main/java/org/wikipedia/dataclient/donate/CampaignCollection.kt
app/src/main/java/org/wikipedia/page/PageFragment.kt

https://phabricator.wikimedia.org/T346902

Model underpinnings for new campaign announcements.

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

https://phabricator.wikimedia.org/T344026

Add required strings for donor experience dialog

---

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt

For the upcoming release to production.

Remove feature flag for Image Recommendation

---

app/src/main/res/values-b+tt+Cyrl/strings.xml
app/src/main/res/values-ba/strings.xml
app/src/main/res/values-bew/strings.xml
app/src/main/res/values-ca/strings.xml
app/src/main/res/values-da/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-ia/strings.xml
app/src/main/res/values-iw/strings.xml
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-ko/strings.xml
app/src/main/res/values-lb/strings.xml
app/src/main/res/values-mk/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-qq/strings.xml
app/src/main/res/values-sl/strings.xml
app/src/main/res/values-sv/strings.xml
app/src/main/res/values-tr/strings.xml
app/src/main/res/values-uk/strings.xml
app/src/main/res/values-uz/strings.xml
app/src/main/res/values-zh-rTW/strings.xml
app/src/main/res/values-zh/strings.xml
app/src/main/res/values/strings.xml

Add quote for the target title.

Update string for Patroller Tasks

---

app/src/main/res/values-ba/strings.xml
app/src/main/res/values-ia/strings.xml
app/src/main/res/values-iw/strings.xml
app/src/main/res/values-mk/strings.xml
app/src/main/res/values-nb/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-qq/strings.xml
app/src/main/res/values-sl/strings.xml
app/src/main/res/values-sv/strings.xml
app/src/main/res/values-uk/strings.xml
app/src/main/res/values/strings.xml

Update required strings for Patroller Tasks

---

app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt

We have decided to change the "Quality" back to "Damage".

Patroller Tasks: Replace Quality with Damage and remove the inverted percentage

---

app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
app/src/main/java/org/wikipedia/diff/ArticleEditDetailsViewModel.kt

https://phabricator.wikimedia.org/T347431

Add Patroller Tasks related Rollback and Undo edit tags

---

app/src/main/java/org/wikipedia/analytics/eventplatform/AppInteractionEvent.kt
app/src/main/java/org/wikipedia/analytics/eventplatform/DonorExperienceEvent.kt
app/src/main/java/org/wikipedia/analytics/eventplatform/PatrollerExperienceEvent.kt

We have started experimenting with a generic schema with specific streams. Re-arranging out internal architecture to support it.

Fix: Multiple streams usage

---

app/src/main/java/org/wikipedia/analytics/eventplatform/PatrollerExperienceEvent.kt
app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
app/src/main/java/org/wikipedia/diff/ArticleEditDetailsViewModel.kt
app/src/main/java/org/wikipedia/diff/UndoEditDialog.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsFragment.kt
app/src/main/java/org/wikipedia/talk/TalkReplyActivity.kt

Found some issues and fixed some indentation

Follow-up: Patroller Tasks data wiring

---

app/src/main/java/org/wikipedia/dataclient/Service.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsRecentEditsFilterActivity.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsRecentEditsViewModel.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragmentViewModel.kt

https://phabricator.wikimedia.org/T350312

Fix: make Patroller Tasks available only on Indonesian and Test wiki

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

Removing some unused string resources

Hygiene: Unused strings

---

app/build.gradle
app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
app/src/main/java/org/wikipedia/onboarding/InitialOnboardingActivity.kt
build.gradle

Updated the following libraries:
- Firebase
- Room
- Desugar
- Google Material
- Recyclerview
- Fragment
- Gms

Library version updates

---

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsRecentEditsOnboardingFragment.kt

**Phab:** https://phabricator.wikimedia.org/T350744#9314893

Fix: PT data string

---

app/src/main/java/org/wikipedia/analytics/eventplatform/PatrollerExperienceEvent.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsRecentEditsOnboardingFragment.kt
app/src/main/java/org/wikipedia/usercontrib/UserInformationDialog.kt

**Phab:** https://phabricator.wikimedia.org/T350744#9318145

Fix: Minor changes PT Data 

---

app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
app/src/main/java/org/wikipedia/diff/ArticleEditDetailsViewModel.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsRecentEditsFragment.kt

Fix: Final touches to PT data

---

.github/workflows/android.yml
.github/workflows/android_branch.yml
.github/workflows/android_pr.yml
.github/workflows/android_smoke_test.yml

Update actions/checkout to v4

---

app/build.gradle

It supports SDK 34. See https://github.com/robolectric/robolectric/releases/tag/robolectric-4.11.1.

Bump Robolectric to 4.11.1

---

app/src/main/java/org/wikipedia/talk/template/AddTemplateActivity.kt
app/src/main/java/org/wikipedia/talk/template/TalkTemplatesFragment.kt

**Schema doc:** https://docs.google.com/presentation/d/1GZz_5py5El56roPu0bmFoiTTdPX1oNKbezkM7HZTa-E/edit#slide=id.g27da6c4b4e9_0_336

Updated Template Design: Data wiring

---

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragmentViewModel.kt

https://phabricator.wikimedia.org/T351275

Adding logic to lock the Image Recommendation on dewiki

---

app/src/main/java/org/wikipedia/navtab/MenuNavTabDialog.kt
app/src/main/java/org/wikipedia/settings/DeveloperSettingsPreferenceLoader.kt
app/src/main/res/drawable/baseline_location_on_24.xml
app/src/main/res/drawable/watchlist.xml
app/src/main/res/layout/view_main_drawer.xml
app/src/main/res/values/dev_settings_strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/developer_preferences.xml

In this Pr:
- Added Nearby entry point to Main Nav more menu
- Removed Nearby entry point on developer pref
- Updated the `watchlist` icon on main nav more menu
**Phab:** https://phabricator.wikimedia.org/T351393

Nearby: Move nearby to main nav more menu

---

app/build.gradle

Update to 'org.maplibre.gl:android-sdk:10.2.0'
Update to 'org.maplibre.gl:android-plugin-annotation-v9:2.0.2'

Update maplibre libraries version

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/wikipedia/navtab/MenuNavTabDialog.kt
app/src/main/java/org/wikipedia/places/PlacesActivity.kt
app/src/main/java/org/wikipedia/places/PlacesFragment.kt
app/src/main/java/org/wikipedia/places/PlacesFragmentViewModel.kt
app/src/main/res/layout/fragment_places.xml
app/src/main/res/layout/view_main_drawer.xml
app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

Android feature has now been names `Places`. This changes all code references from `nearby -> places`

Change label to `Places`

---

app/build.gradle
app/src/main/java/org/wikipedia/random/BottomViewBehavior.kt
app/src/main/java/org/wikipedia/util/GeoUtil.kt
build.gradle

...and fix (ignore) a couple of lint issues that have popped up as a result.
This also bumps the version of the Room dependency to 2.6.1:
https://developer.android.com/jetpack/androidx/releases/room#2.6.1

Update gradle plugin to 8.2.0.

---

app/src/main/java/org/wikipedia/navtab/MenuNavTabDialog.kt
app/src/main/res/values/strings_no_translate.xml

https://phabricator.wikimedia.org/T350919

Update donation URL to standardize utm_source parameter.

---

app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt

Tiny tweak: hide back/forward arrows while loading.

---

app/build.gradle

https://firebase.google.com/support/release-notes/android#messaging_v23-4-0

Update firebase messaging library version to 23.4.0

---

app/build.gradle

https://github.com/material-components/material-components-android/releases/tag/1.11.0

Update material-components-android library version to 1.11.0

---

app/src/main/java/org/wikipedia/navtab/MenuNavTabDialog.kt

https://phabricator.wikimedia.org/T354309

Launch donation flow from Donate button in Chrome Custom Tab.

---

build.gradle

Latest ksp plugin version:
https://github.com/google/ksp/releases/tag/1.9.22-1.0.16

Update Gradle and ksp to latest versions.

---

app/schemas/org.wikipedia.database.AppDatabase/26.json
app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
app/src/main/java/org/wikipedia/diff/ArticleEditDetailsViewModel.kt
app/src/main/java/org/wikipedia/page/PageActivity.kt
app/src/main/java/org/wikipedia/page/PageFragment.kt
app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt
app/src/main/java/org/wikipedia/talk/TalkTopicsViewModel.kt
app/src/main/java/org/wikipedia/watchlist/WatchlistExpiryDialog.kt
app/src/main/java/org/wikipedia/watchlist/WatchlistExpiryDialogViewModel.kt

Now the `WatchlistExpiryDialog` has its logic for updating the expiry, which can reduce some hassle when implementing watchlist functions

Move the logic of changing Watchlist expiry to its ViewModel

---

app/src/main/java/org/wikipedia/talk/UserTalkPopupHelper.kt

https://phabricator.wikimedia.org/T354466

Don't allow thanking when logged out.

---

app/src/main/java/org/wikipedia/search/SearchResultsViewModel.kt

It looks like full-text search has been broken for a while (ever since switching to `SearchResultsViewModel`).
More specifically, the full-text search only happens when the prefix search returns zero items. But in fact the full-text search should happen anytime the prefix search returns fewer than the _PagingSource_ asks for.
https://phabricator.wikimedia.org/T354592

Fix full-text search.

---

app/src/main/java/org/wikipedia/places/PlacesFragment.kt

@cooltey  This is what I was talking about -- observe how this code no longer creates any bitmaps (or even pulls any dirty bitmaps from the pool), except the initial `markerBitmapBase`.
(to be merged into your ui-update PR)

Don't create unnecessary bitmaps.

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

...so that translations can begin.

String resources for Places feature.

---

app/src/main/java/org/wikipedia/LongPressHandler.kt
app/src/main/java/org/wikipedia/feed/featured/FeaturedArticleCardView.kt
app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayCardView.kt
app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayPagesViewHolder.kt
app/src/main/java/org/wikipedia/feed/view/ListCardItemView.kt
app/src/main/java/org/wikipedia/page/PageFragment.kt
app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt
app/src/main/java/org/wikipedia/random/RandomFragment.kt
app/src/main/java/org/wikipedia/readinglist/LongPressMenu.kt

This PR is for the upcoming Places update.

Update constructor of the LongPressMenu

---

app/src/main/java/org/wikipedia/places/PlacesFragment.kt

**Phab:** https://phabricator.wikimedia.org/T351158#9441277

Design tweak: Places search

---

app/src/main/java/org/wikipedia/places/PlacesFragment.kt

This enables us to handle insets correctly for applying the proper margins to the Search bar, location button, etc.
Even works upon screen rotation and other configuration changes!

(Places) Correctly handle insets.

---

app/src/main/java/org/wikipedia/places/PlacesFragment.kt

This PR also moves the `updateSearchText()` to the `showLinkPreview()` method since they are related.

Show link preview dialog if access from an article

---

app/src/main/java/org/wikipedia/places/PlacesFragment.kt

This removes all delays when navigating to a new location. We were delaying movement by 1 second... does anyone recall why?

(Places) remove postDelayed calls.

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

**Phab:** https://phabricator.wikimedia.org/T355302

Places: tooltip strings for translation

---

app/src/main/java/org/wikipedia/places/PlacesFragment.kt
app/src/main/java/org/wikipedia/settings/Prefs.kt
app/src/main/res/values/preference_keys.xml

This PR also set `10` milliseconds for the camera animation in the `goToLocation` will reduce the time of moving to the save or current location.

Save last location information to the preference

---

app/src/main/java/org/wikipedia/places/PlacesFragment.kt
app/src/main/java/org/wikipedia/search/SearchFragment.kt
app/src/main/java/org/wikipedia/search/SearchResult.kt
app/src/main/java/org/wikipedia/search/SearchResultsFragment.kt

This uses existing functionality that we already had in SearchFragment to return a selected link.
This also fixes a tiny issue where we weren't remembering the last search term, to put in Recent Searches.

(Places) Clean up searching, and correctly remember last search term.

---

app/src/main/java/org/wikipedia/dataclient/Service.kt
app/src/main/java/org/wikipedia/places/PlacesFragmentViewModel.kt

As the request from Robin, https://phabricator.wikimedia.org/T347336#9480097
The list view item will need to show the first sentence if there is no article description.

Add prop=extracts for list view items in Places

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

**Phab:** https://phabricator.wikimedia.org/T355140
Survey text to send for translation

Survey text strings for translation

---

app/build.gradle
app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.kt
app/src/main/java/org/wikipedia/views/FaceAndColorDetectImageView.kt
build.gradle

https://square.github.io/okhttp/changelogs/changelog_4x/#version-4120
https://github.com/bumptech/glide/releases/tag/v4.16.0
(^ required a couple of interface updates)
https://square.github.io/leakcanary/changelog/#version-213-2024-01-03
https://github.com/Kotlin/kotlinx.serialization/releases/tag/v1.6.2
https://jsoup.org/news/release-1.17.2
https://github.com/skydoves/Balloon/releases/tag/1.6.4

Update gradle and dependencies.

---

app/src/main/java/org/wikipedia/places/PlacesFragment.kt
app/src/main/java/org/wikipedia/places/PlacesFragmentViewModel.kt

@cooltey This is to merge into your List PR, and this probably fixes any issues with list items disappearing upon moving the map, since now the list items will be literally what's shown on the map.

(Places) Don't use extra list along with LiveData.

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

**Phab:** https://phabricator.wikimedia.org/T355140#9487543

Places: New string

---

app/src/main/java/org/wikipedia/places/PlacesFilterActivity.kt
app/src/main/java/org/wikipedia/places/PlacesFragment.kt
app/src/main/res/layout/fragment_places.xml
app/src/main/res/layout/view_places_filter_item.xml

https://github.com/wikimedia/apps-android-wikipedia/pull/4415

Places: apply new language and tab counts view to Places

---

app/src/main/java/org/wikipedia/page/ExtendedBottomSheetDialogFragment.kt
app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt

**Phab:** https://phabricator.wikimedia.org/T351158#9494906

Places: Bring back bottomSheet dim

---

app/src/main/java/org/wikipedia/places/PlacesFilterActivity.kt

- Do not use `get()` to update the list in the adapter.
- Use `inner` class to access `this@PlacesFilterActivity`
... and some minor updates.

Simplify and optimize code in PlacesFilterActivity

---

app/src/main/res/layout/fragment_article_edit_details.xml

The progress bar is not showing in the Diff view correctly, this PR adds a `FrameLayout` to contain the `CollapsingToolbarLayout` and move the progressbar to so it will not make the view jumps after gone.

Fix: show the progressbar correctly in the diff view

---

app/src/main/java/org/wikipedia/places/PlacesFragment.kt

Remove the usage of `removeUnderscore()` and use `prefixText` for the if statement.

Minor code update for Places

---

app/src/main/java/org/wikipedia/places/PlacesFragment.kt
app/src/main/java/org/wikipedia/places/PlacesFragmentViewModel.kt

1. Go to Places.
2. Change to the List view.
3. Change the device's orientation to see the distance.

Fix: save lastKnowLocation in ViewModel to keep showing distance in list in Places

---

app/src/main/java/org/wikipedia/places/PlacesFragmentViewModel.kt

It would be better if the list items were sorted by distance, which makes more sense for users.

Sort the map list items by the distance from the current location

---

app/src/main/java/org/wikipedia/search/SearchFragment.kt

https://phabricator.wikimedia.org/T357814

Use proper hint for Search when entering from Places.

---

app/src/main/java/org/wikipedia/readinglist/sync/ReadingListSyncAdapter.kt

https://phabricator.wikimedia.org/T358232

Perform full reading list sync if previous sync is too old.

---

app/src/main/java/org/wikipedia/analytics/eventplatform/EventPlatformClient.kt

There is a very small chance of a race condition on line 155, when the stream configs are updated at the same time as they are queried, which will make the map return `null`, and cause a NullPointerException.

Prevent obscure race condition when querying Stream Configs.

---

app/src/main/java/org/wikipedia/places/PlacesFragment.kt

Another issue from insufficient testing of denying location permissions 😆 
We're requiring the checking of permissions in a couple of places where it's not necessary at all.
https://phabricator.wikimedia.org/T358426

Places: Fix requiring permissions to go to article map marker.

---

app/build.gradle

Fixes random generator for session id -- ensures length of 20 chars.
Bug: [T357181](https://phabricator.wikimedia.org/T357181)

Bump Metrics Platform version

---

app/build.gradle
build.gradle

Newer versions are available for a ew libraries. They have been updated here.

Updated library versions

---

app/src/main/java/org/wikipedia/analytics/eventplatform/EditAttemptStepEvent.kt

https://phabricator.wikimedia.org/T358734

Update EditAttemptStepEvent for the schema update

---

app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
app/src/main/java/org/wikipedia/diff/ArticleEditDetailsViewModel.kt
app/src/main/java/org/wikipedia/watchlist/WatchlistFragment.kt

https://phabricator.wikimedia.org/T360161

Remove edit hashtags coming from Watchlist.

---

app/src/main/java/org/wikipedia/settings/LogoutPreference.kt

Reverts wikimedia/apps-android-wikipedia#4536

Put back pre-prod flag from account vanishing.

---

app/src/main/res/values/strings.xml

Test the Github autolinks with the Phab ticket action
Bug:T360680
BUG:T360680
Bug: T360680

Update string order for talk warn learnMore label

---

app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt

Similar to #4556, the `TalkTipicActivity` should also support the diff link.

Add onDiffLinkClicked support to TalkTopic

---

app/src/main/java/org/wikipedia/search/RecentSearchesFragment.kt
app/src/main/java/org/wikipedia/search/SearchFragment.kt
app/src/main/res/layout/fragment_search_recent.xml

It does not make sense to offer Namespace selection when searching for articles with locations.

When searching from Places, hide namespace selection.

---

app/src/main/java/org/wikipedia/talk/TalkReplyActivity.kt
app/src/main/java/org/wikipedia/talk/template/TalkTemplatesTextInputDialog.kt

https://phabricator.wikimedia.org/T356774#9670298

Don't show option to "Update existing message" when not applicable.

---

app/src/main/java/org/wikipedia/settings/LogoutPreference.kt

This is now ready to go, and will be rereleased to Beta.

Remove (for real) feature flag for account vanishing.

---

app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
app/src/main/java/org/wikipedia/talk/template/TalkTemplatesFragment.kt
app/src/main/res/layout/fragment_talk_templates.xml

https://phabricator.wikimedia.org/T361646

Improve positioning of Snackbars in Diff screen.

---

app/src/main/java/org/wikipedia/talk/TalkReplyActivity.kt

This should finally, once and for all, fix the remaining Back-navigation issues when publishing Talk replies.
https://phabricator.wikimedia.org/T361655

Improve Back navigation when previewing New talk message.

---

app/src/main/java/org/wikipedia/dataclient/Service.kt
app/src/main/java/org/wikipedia/dataclient/wikidata/Entities.kt
app/src/main/java/org/wikipedia/feed/aggregated/AggregatedFeedContent.kt
app/src/main/java/org/wikipedia/feed/aggregated/AggregatedFeedContentClient.kt
app/src/main/java/org/wikipedia/language/LanguageUtil.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageRecsFragmentViewModel.kt

This is a temporary fix for T355192

Fix: load correct article and description for the featured article

---

.mailmap

Fixes my name and email address on old commits in this repo.

Add .mailmap file with name updates for bvibber

---

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsRecentEditsActivity.kt

Chinese language code: `zh`
Igbo language code: `ig`
No design review is needed.
Phabricator: T350512

Add Chinese and Igbo for thrid roll-out for Patroller Tasks

---

app/build.gradle
build.gradle

https://github.com/square/retrofit/releases/tag/2.11.0
https://github.com/Kotlin/kotlinx.serialization/releases/tag/v1.6.3

Update gradle and a few libraries.

---

app/src/main/java/org/wikipedia/feed/aggregated/AggregatedFeedContentClient.kt
app/src/main/java/org/wikipedia/feed/becauseyouread/BecauseYouReadClient.kt

Updates the proper `Dispatchers` for `CororutineScope` and `withContext`
https://play.google.com/console/u/1/developers/6169333749249604352/app/4972092403490495074/vitals/crashes/af0633ff24caa27fd1dd23c36433361a/details?days=28&versionCode=50482&isUserPerceived=true

Fix: crashes on Explore Feed when airplane mode is activated

---

app/src/main/java/org/wikipedia/talk/TalkReplyActivity.kt

https://phabricator.wikimedia.org/T362994

Fix enabling Next button in TalkReply from saved messages.

---

app/src/main/java/org/wikipedia/talk/template/TalkTemplatesFragment.kt

https://phabricator.wikimedia.org/T362996

Don't reset to Your Messages tab unless message was updated.

---

app/src/main/res/values/strings.xml

https://phabricator.wikimedia.org/T362935

Update verbiage for image recommendation rejection dialog.

---

app/build.gradle

https://developer.android.com/jetpack/androidx/releases/core#1.13.0

Update core-ktx dependency.

---

app/build.gradle
build.gradle
gradle/wrapper/gradle-wrapper.properties

Gradle wrapper -> 8.6
Gradle plugin -> 8.4.0
https://github.com/JetBrains/kotlin/releases/tag/v1.9.24
https://github.com/Kotlin/kotlinx.coroutines/releases/tag/1.8.1
https://firebase.google.com/support/release-notes/android#messaging_v24-0-0
https://github.com/material-components/material-components-android/releases/tag/1.12.0
https://developer.android.com/jetpack/androidx/releases/core#1.13.1
https://developer.android.com/jetpack/androidx/releases/fragment#1.7.0

Update Gradle and a few dependencies.

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

Strings for zhwiki language variants prompt

---

app/src/extra/java/org/wikipedia/donate/GooglePayActivity.kt
app/src/extra/java/org/wikipedia/donate/GooglePayViewModel.kt
app/src/extra/res/layout/activity_donate.xml
app/src/main/java/org/wikipedia/dataclient/Service.kt
app/src/main/java/org/wikipedia/dataclient/donate/DonationConfigHelper.kt
app/src/main/res/values/strings_no_translate.xml

..for parity with the Web donation form
https://phabricator.wikimedia.org/T364923

GPay: add standard data policy disclaimer.

---

app/src/main/java/org/wikipedia/donate/DonateViewModel.kt

Remove feature flag for Google Pay.

---

app/src/main/java/org/wikipedia/edit/richtext/SyntaxHighlighter.kt

- The use of `flow` is not necessary, since the flow only emits a single thing. The suspend function itself can just do the thing.
- The new code was not keeping track of the current coroutine `Job`, so it was no longer canceling the current job before launching a new one.

Follow-up to coroutines in SyntaxHighlighter.

---

app/src/main/java/org/wikipedia/captcha/Captcha.kt

Added kotlinx serialization for fancycaptchareload variable

Added kotlinx serialization for fancycaptchareload variable

---

app/build.gradle

https://developer.android.com/jetpack/androidx/releases/fragment#1.7.1
https://developer.android.com/jetpack/androidx/releases/viewpager2#1.1.0
https://developer.android.com/jetpack/androidx/releases/paging#3.3.0

Update libraries version

---

app/src/main/java/org/wikipedia/settings/AboutActivity.kt

Now it will show extra information:
```
Version: 2.7.50490-dev-2024-05-29
Device: samsung SM-G960U1 (SDK: 29)
```
Bug: T365120

Include additional device information in the Email body

---

app/src/main/java/org/wikipedia/suggestededits/provider/EditingSuggestionsProvider.kt

We can use `ArrayDeque` instead of a Java `Stack` in this provider.

Use ArrayDeque over Stack in EditingSuggestionsProvider

---

app/src/main/res/drawable/ic_share_material_secondary_themed.xml
app/src/main/res/menu/menu_talk_thread_item.xml

Remove the duplicated `share` icon.

Hygiene: Remove duplicated themed resource

---

app/src/main/java/org/wikipedia/dataclient/RestService.kt
app/src/main/java/org/wikipedia/feed/onthisday/OnThisDay.kt
app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayFragment.kt
app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayViewModel.kt
app/src/main/java/org/wikipedia/views/CustomDatePicker.kt
app/src/main/res/layout/fragment_on_this_day.xml

- Use `ViewModel` and `Coroutine`.
- Optimize a few logic of displaying items.

Refactoring OnThisDayFragment to use coroutine and ViewModel

---

app/src/extra/java/org/wikipedia/donate/GooglePayActivity.kt
app/src/extra/java/org/wikipedia/donate/GooglePayComponent.kt

https://phabricator.wikimedia.org/T365307

GPay: make transaction fee properly scale based on selected amount.

---

app/src/main/java/org/wikipedia/dataclient/Service.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagDialog.kt

This is the one missing from PR of refactoring suggested edits related classes.

Use coroutine in SuggestedEditsImageTagDialog

---

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagDialog.kt

This updates the code to achieve debouncing using a proper coroutine `delay()` instead of the old logic of `Runnable` / `postDelayed`.

Follow-up: improve/simplify debouncing in ImageTagDialog.

---

app/src/main/java/org/wikipedia/settings/Prefs.kt
app/src/main/res/values/preference_keys.xml

We already have `editingTextSizeMultiplier` in `Prefs`

Remove unused editing text size preference

---

app/src/main/java/org/wikipedia/dataclient/Service.kt
app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
app/src/main/java/org/wikipedia/edit/EditTags.kt
app/src/main/java/org/wikipedia/talk/TalkReplyViewModel.kt

https://phabricator.wikimedia.org/T366731

Batch 2 of edit tags.

---

app/build.gradle
app/src/extra/java/org/wikipedia/installreferrer/InstallReferrerListener.kt
app/src/fdroid/java/org/wikipedia/installreferrer/InstallReferrerListener.kt
app/src/main/java/org/wikipedia/WikipediaApp.kt

Created a new package `installreferrer` for `extra` and `fdroid` package.
Bug: T369814

Exclude InstallReferrer library from F-Droid build

---

.github/dependabot.yml

Introduce dependabot for dependency updates.

---

app/src/main/java/org/wikipedia/page/PageActivity.kt

Bug: [T370020](https://phabricator.wikimedia.org/T370020)

Support URL sharing on recent screen

---

app/src/main/java/org/wikipedia/dataclient/page/NearbyPage.kt
app/src/main/java/org/wikipedia/places/PlacesFragment.kt
app/src/main/java/org/wikipedia/places/PlacesFragmentViewModel.kt

Move `NearbyPage` to `dataclient` package for the upcoming change #4824

Move NearbyPage to dataclient package

---

app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
app/src/main/res/layout/fragment_article_edit_details.xml

https://phabricator.wikimedia.org/T370697

Show "Talk" button in Diff view for all cases.

---

app/src/main/java/org/wikipedia/feed/places/PlacesCardView.kt

Add entry point event tracking for Explore Card entry in Places

---

app/src/main/java/org/wikipedia/dataclient/Service.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragmentViewModel.kt

https://phabricator.wikimedia.org/T371442

Expand patrolling edits for Igbo Wikipedia.

---

app/src/main/java/org/wikipedia/feed/aggregated/AggregatedFeedContentClient.kt
app/src/main/java/org/wikipedia/util/L10nUtil.kt

Combine two methods into one method, and it will be used in #4859

Move language variant method to L10nUtil

---

app/src/main/java/org/wikipedia/analytics/metricsplatform/ArticleEvent.kt
app/src/main/java/org/wikipedia/analytics/metricsplatform/RecommendedContentABCTest.kt
app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
app/src/main/java/org/wikipedia/page/PageFragment.kt
app/src/main/java/org/wikipedia/recommendedcontent/RecommendedContentFragment.kt
app/src/main/java/org/wikipedia/recommendedcontent/RecommendedContentSectionView.kt
app/src/main/java/org/wikipedia/recommendedcontent/RecommendedContentViewModel.kt
app/src/main/java/org/wikipedia/search/RecentSearchesFragment.kt
app/src/main/java/org/wikipedia/search/SearchFragment.kt
app/src/main/java/org/wikipedia/views/SurveyDialog.kt

https://phabricator.wikimedia.org/T372761

Analytics for recommended content.

---

app/src/main/java/org/wikipedia/recommendedcontent/RecommendedContentViewModel.kt

* Combine `loadTopRead()` and `loadInTheNews()` into a single function, so that `loadFeed()` is called only once, for efficiency.
* Rename `explore` to `moreLike`, for a bit more conciseness.

Tiny follow-up to recommended content.

---

app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewViewModel.kt
app/src/main/java/org/wikipedia/watchlist/WatchlistExpiryDialogViewModel.kt

Fix: typo in ViewModel class

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

Adds strings for translateWiki to start translating the strings. 
https://phabricator.wikimedia.org/T376425

Navigation Strings for contribution dashboard

---

app/src/main/java/org/wikipedia/readinglist/sync/ReadingListSyncAdapter.kt

There was actually one benefit of the previous functionality of using a map of `wiki -> token`, which is to serve as a cache of the CSRF token(s). By removing the map, we're no longer caching the token, so we could be making multiple calls to get the same token, which is unnecessary.
This updates the logic to fetch the token once, at the beginning of the whole sync process, and use it anywhere it's needed.

Follow-up to Csrf worker updates.

---

app/src/main/res/xml/developer_preferences.xml

It provides an example format for the designer and QA to insert donation information to see the different types of donor badges.
@Williamrai Please review and merge this PR, and then update your QA steps for Sarah by including this example, thanks!

Add dialog message for donationResult preference

---

app/src/main/res/layout/fragment_suggested_edits_tasks.xml

Use a ConstraintLayout to accomplish everything we can hope for.

Update/streamline layout of "last donated" row.

---

app/src/main/res/values/strings.xml

This is based on the [copy](https://docs.google.com/spreadsheets/d/1z6EhbqeSrIfwykVVsA3QUaYWEOTmAiMEOfkMePdFeyU/edit?gid=0#gid=0).

Update strings for Contributions Dashboard

---

app/src/main/res/layout/view_donor_badge.xml
app/src/main/res/values/styles.xml

adds and changes the vertical padding for overflow menu and **Update donor status** button. 
https://phabricator.wikimedia.org/T376422

Fix: Overflow menu design changes

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

https://phabricator.wikimedia.org/T376435#10303514

Add string for the Contributions Dashboard

---

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
app/src/main/res/layout/fragment_suggested_edits_tasks.xml
app/src/main/res/xml/developer_preferences.xml

https://phabricator.wikimedia.org/T376435#10303514

Fix: Update Contribute tab for design signoff comments

---

app/src/main/java/org/wikipedia/usercontrib/ContributionsDashboardHelper.kt

Fixes the incorrect `interface` and `action` for the cancel button.
https://phabricator.wikimedia.org/T380233#10333831

Fix: instrumentation for Contributions Dashboard

---

app/src/main/java/org/wikipedia/usercontrib/ContributionsDashboardHelper.kt

fixes the link of the survey dialog form
https://phabricator.wikimedia.org/T376436

Fix updates survey form

---

app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

https://phabricator.wikimedia.org/T379381

Use slightly different verbiage for Reading List survey dialog.

---

app/build.gradle

Bump versionCode.

---

app/src/androidTest/java/org/wikipedia/robots/feature/ExploreFeedRobot.kt
app/src/androidTest/java/org/wikipedia/robots/feature/LoginRobot.kt
app/src/androidTest/java/org/wikipedia/robots/feature/ReadingListRobot.kt
app/src/androidTest/java/org/wikipedia/robots/screen/SavedScreenRobot.kt
app/src/androidTest/java/org/wikipedia/tests/explorefeed/FeedScreenSuggestedEditTest.kt
app/src/androidTest/java/org/wikipedia/tests/settings/AppThemeTest.kt
app/src/androidTest/java/org/wikipedia/tests/settings/ShowImageTest.kt
app/src/androidTest/java/org/wikipedia/testsuites/TestSuite.kt

Fix Espresso Test

---

app/src/main/java/org/wikipedia/language/AppLanguageState.kt

Follow up: show localized name in the Contributions filter screen

---

app/src/androidTest/java/org/wikipedia/robots/SystemRobot.kt
app/src/androidTest/java/org/wikipedia/robots/feature/ReadingListRobot.kt
app/src/androidTest/java/org/wikipedia/robots/feature/SearchRobot.kt
app/src/androidTest/java/org/wikipedia/robots/screen/SuggestedEditsScreenRobot.kt
app/src/androidTest/java/org/wikipedia/tests/DeepLinkingTest.kt
app/src/androidTest/java/org/wikipedia/tests/SuggestedEditScreenTest.kt
app/src/androidTest/java/org/wikipedia/tests/settings/ChangingLanguageTest.kt
app/src/androidTest/java/org/wikipedia/tests/settings/CollapseTablesTest.kt
app/src/androidTest/java/org/wikipedia/tests/settings/DownloadReadingListTest.kt
app/src/androidTest/java/org/wikipedia/tests/settings/LinkPreviewTest.kt
app/src/androidTest/java/org/wikipedia/tests/settings/ReadingFocusModeTest.kt

Updates espresso test for supporting new changes and code fixes which were causing test failure

Expresso code fixes

---

app/src/main/java/org/wikipedia/connectivity/ConnectionStateMonitor.kt

This solidifies the workaround from #5221 a bit further, by allowing the `online` state to be set explicitly from the `onLost()` and `onAvailable()` callbacks, and resetting the 1-minute interval for subsequent queries for `isOnline`.

Follow-up to offline state tracking.

---

app/src/androidTest/java/org/wikipedia/testsuites/ArticlesTestSuite.kt

Espresso article test fix

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

Adds strings for entry dialog
https://phabricator.wikimedia.org/T383693

[WikiGames] Strings for entry dialog

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

These are the strings used in the main workflow of the game, prior to the final screen.

WikiGames: strings for main gameplay.

---

app/src/main/java/org/wikipedia/settings/DeveloperSettingsFragment.kt
app/src/main/java/org/wikipedia/settings/DeveloperSettingsPreferenceLoader.kt
app/src/main/res/menu/menu_developer_settings.xml
app/src/main/res/values/dev_settings_strings.xml
app/src/main/res/values/preference_keys.xml
app/src/main/res/xml/developer_preferences.xml

Follow-up: move developer settings search into toolbar.

---

app/src/main/res/values/strings.xml

From `Played` to `Games played`.
(Will self merge this PR)

Minor update for the wiki game final screen string

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

For the bottom sheet in the final screen of the wikigame.

Add strings for wikigame final screen bottom sheet

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

Strings update for correct and incorrect answers.
https://www.figma.com/design/JljLgMaebLZ5ugbZ9qnXB2/Android-%E2%86%92-Games-%E2%86%92-T...?node-id=1909-10183&m=dev 
and for the menu items:
https://www.figma.com/design/JljLgMaebLZ5ugbZ9qnXB2/Android-%E2%86%92-Games-%E2%86%92-T...?node-id=2110-11348&m=dev

Update strings for the wikigame final screen

---

app/src/main/res/values/strings_no_translate.xml

The Contributions Dashboard has been removed from the app.

Remove unused Contributions Dashboard url

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

[Wikigames] string for share-link

---

app/src/main/res/values/credits.xml

puts credits.xml back

---

app/src/main/res/layout/activity_on_this_day_game.xml
app/src/main/res/layout/fragment_on_this_day_game_final.xml

Updates the color for the "Next question" button and the text on the score card.

Update texts color for Wikigame

---

app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameFinalFragment.kt

Some minor tweaks for the final screen.

Wikigame: remove visibility set for bookmark icon and change image loading function

---

app/src/main/res/layout/view_wiki_games_card.xml

updates wiki games entry card view from P.Article to P
https://phabricator.wikimedia.org/T383692

Minor Wikigame design change

---

app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameViewModel.kt

A minor follow-up PR for the code format and removes unused methods.

Follow up: code format update and remove unused methods

---

app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt

This cleans up the logic of enabling/disabling the ActionMode icons based on which reading lists are selected.
* If no lists are selected, the Delete and Export buttons are disabled (and half-opacity).
* If only the default Saved list is selected, the Delete button is disabled, and the Export button is enabled.
* If more than one list is selected (which may include the default Saved list), the Delete and Export buttons are enabled.
https://phabricator.wikimedia.org/T387931

Disable Delete button when only Default reading list selected.

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

adds accessibility text for clear icon

accessibility text for clear icon

---

app/src/main/java/org/wikipedia/compose/components/SearchTopAppBar.kt
app/src/main/java/org/wikipedia/compose/components/WikiTopAppBar.kt
app/src/main/java/org/wikipedia/compose/components/WikiTopAppBarWithSearch.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-bn/strings.xml
app/src/main/res/values-ckb/strings.xml
app/src/main/res/values-et/strings.xml
app/src/main/res/values-fa/strings.xml
app/src/main/res/values-fi/strings.xml
app/src/main/res/values-hi/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-iw/strings.xml
app/src/main/res/values-ko/strings.xml
app/src/main/res/values-lb/strings.xml
app/src/main/res/values-mk/strings.xml
app/src/main/res/values-pa/strings.xml
app/src/main/res/values-qq/strings.xml
app/src/main/res/values-sl/strings.xml
app/src/main/res/values-sr/strings.xml
app/src/main/res/values-sv/strings.xml
app/src/main/res/values-tcy/strings.xml
app/src/main/res/values-uk/strings.xml
app/src/main/res/values/strings.xml

1. Changed the font size to `16.sp`
2. Rename the strings for `contentDescription`.

Follow-up: Compose topbar with search

---

app/src/main/java/org/wikipedia/wiktionary/WiktionaryDialogScreen.kt
app/src/main/java/org/wikipedia/wiktionary/WiktionaryViewModel.kt

- fixes the scrollable issue with BottomSheetDialogFragment and composeView 
- Adds a data class to simplify the management of Compose UI state.
https://phabricator.wikimedia.org/T386527

follow up compose wiktionary dialog 

---

app/src/main/java/org/wikipedia/readinglist/ReadingListFragmentViewModel.kt

Instead of showing a hardcoded text, we can use a generic error message instead.

Follow-up of ReadingListFramgent to use viewModel

---

app/src/main/java/org/wikipedia/yearinreview/YearInReviewActivity.kt
app/src/main/java/org/wikipedia/yearinreview/YearInReviewScaffold.kt

This PR shows the code formatting adjustments for project consistency.
@voyagerfan Please review and merge if it looks good to you.

Follow up: Year-in-review code format optimization

---

app/src/main/java/org/wikipedia/language/addlanguages/AddLanguagesListActivity.kt
app/src/main/java/org/wikipedia/language/addlanguages/AddLanguagesListScreen.kt
app/src/main/java/org/wikipedia/language/addlanguages/AddLanguagesViewModel.kt

- adds a sealed interface approach to handle state 
- adds a debounce for search
- code/ui fixes

Compose Language List experimentation 

---

app/src/main/java/org/wikipedia/dataclient/page/PageSummary.kt
app/src/main/java/org/wikipedia/page/PageFragmentLoadState.kt
app/src/main/java/org/wikipedia/page/PageProperties.kt

Mostly updated the `PageSummary` class by removing unused variables and simplifying code formats.

Hygiene: remove unused variables and update code format

---

app/src/main/java/org/wikipedia/compose/components/SearchEmptyView.kt

Converts SearchEmptyView to compose
https://phabricator.wikimedia.org/T389151

compose SearchEmptyView

---

app/build.gradle
app/src/main/java/org/wikipedia/yearinreview/YearInReviewActivity.kt
app/src/main/java/org/wikipedia/yearinreview/YearInReviewScaffold.kt
gradle/libs.versions.toml

This adds a pagination indicator with a size gradient. It also removes the default "flash" transition in the navhost
Pagination indicators are part of the YiR screen design
https://phabricator.wikimedia.org/T387941

Create and add pagination indicator to the BottomAppBar - T387941

---

app/src/main/java/org/wikipedia/yearinreview/YearInReviewScaffold.kt

Simplified some code and tried to make the coding style match the project. 
@voyagerfan Please review and merge if it looks good to you.

Follow-up: YiR pagination and code formats update

---

app/src/main/java/org/wikipedia/feed/image/FeaturedImageCard.kt

Show the file name if there's no image description.
https://phabricator.wikimedia.org/T392744

Show file name if no image description on the featured image

---

app/src/main/java/org/wikipedia/settings/dev/playground/CategoryDeveloperPlayGroundActivity.kt
app/src/main/java/org/wikipedia/settings/dev/playground/CategoryDeveloperPlayGroundViewModel.kt

1. Changed the file name to `CategoryDeveloperPlayGroundActivity`.
2. Created a function for validating input fields.
3. Used the app `L.e` instead of `Log.e`.

Follow up: Category dev playground

---

app/src/main/java/org/wikipedia/readinglist/AddToReadingListDialog.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListActivity.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListItemView.kt

Simplify callback functions, clean up imports, and prepare for the upcoming Discover tasks.

Simplify and code clean up for ReadingList screen

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

Adds strings for archive games

strings for archive game

---

app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameNotificationManager.kt
app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameOnboardingFragment.kt
app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameViewModel.kt

https://phabricator.wikimedia.org/T393055

Update languages for Game availability and release dates.

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

Updates sound string for wikigames

updates strings for wikigames

---

app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameActivity.kt
app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameFinalFragment.kt
app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameOnboardingFragment.kt
app/src/main/java/org/wikipedia/settings/Prefs.kt
app/src/main/res/drawable/volume_off_24dp.xml
app/src/main/res/drawable/volume_up_24dp.xml
app/src/main/res/layout/activity_on_this_day_game.xml
app/src/main/res/menu/menu_on_this_day_game.xml
app/src/main/res/values-qq/strings.xml
app/src/main/res/values/preference_keys.xml
app/src/main/res/values/strings.xml

- adds sound to the game menu 
- adds menu on the main game screen
https://phabricator.wikimedia.org/T393048

Wikigames sound menu option

---

app/src/main/java/org/wikipedia/readinglist/AddToReadingListDialog.kt
app/src/main/java/org/wikipedia/readinglist/LongPressMenu.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListBehaviorsUtil.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListHeaderView.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListItemView.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListPreviewSaveDialogView.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListTitleDialog.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt

Some code clean-up and updates for the upcoming recommended reading list task.

Hygiene: reading list code clean up and updates

---

app/src/main/java/org/wikipedia/auth/AccountUtil.kt
app/src/test/java/org/wikipedia/util/AccountUtilTest.kt

Some more solid logic for correctly detecting a temp account name.
Now with tests!

Further solidify detection of temp account name.

---

app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameViewModel.kt

Add a `ReleaseUtil.isPreBetaRelease` tag for an earlier release date so that we can test the archive function easily.

Add a `isPreBetaRelease` condition for the release date for WikiGames

---

app/src/main/java/org/wikipedia/yearinreview/YearInReviewActivity.kt
app/src/main/java/org/wikipedia/yearinreview/YearInReviewScaffold.kt

This PR integrates the `DonateDialog` class with the donate button in the year in review `MainBottomBar`
This adds the ability for a user to donate.
https://phabricator.wikimedia.org/T393815

Integrate DonateDialog class into YiR donate button - T393815

---

app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameBaseFragment.kt
app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameFinalFragment.kt
app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameOnboardingFragment.kt

The previous PR created an architecturally-correct "BaseFragment", but can go even further to consolidate code.
This PR de-duplicates a bunch more code, and centralizes _all_ of the calendar-related logic in the base fragment.

Follow-up to final game Archive updates.

---

app/src/main/res/values/strings.xml

minor string update

---

app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListOptions.kt
app/src/main/java/org/wikipedia/settings/Prefs.kt
app/src/main/res/values/preference_keys.xml

Create preferences and enum classes for the recommended reading list feature.

Add preferences and enum classes for Recommended Reading list

---

app/src/main/java/org/wikipedia/categories/db/CategoryDao.kt
app/src/main/java/org/wikipedia/recurring/CategoriesTableCleanupTask.kt
app/src/main/java/org/wikipedia/settings/dev/playground/CategoryDeveloperPlayGroundViewModel.kt

Deletes categories in batches and adds this function to the category dev playground

Delete categories in batches

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/wikipedia/compose/components/WikipediaAlertDialog.kt
app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListOnboardingActivity.kt
app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListOptions.kt
app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSettingsActivity.kt
app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSettingsScreen.kt
app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSettingsViewModel.kt
app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSourceFragment.kt
app/src/main/java/org/wikipedia/settings/SettingsPreferenceLoader.kt
app/src/main/res/values/preference_keys.xml
app/src/main/res/xml/preferences.xml

- Move around the classes and rename classes a bit.
- Update parameters naming style.
- Simplify the way of accessing the source fragment / and the upcoming interests fragment by using the `RecommendedReadingListOnboardingActivity`
- Add ripple animation for dialog radio items and update the frequency item.

Follow-up: Discover settings for Recommended reading list

---

app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListInterestsFragment.kt

- Add logic for the case when the user comes from the settings screen.
- Connect with the `ReadingListFragment`.

Follow-up: the interests screen for Recommended reading list

---

app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSourceScreen.kt

- adds a back handler for source screen

Source Screen backHandler

---

app/src/main/java/org/wikipedia/analytics/eventplatform/RecommendedReadingListEvent.kt
app/src/main/java/org/wikipedia/history/HistoryEntry.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListItemView.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListSyncBehaviorDialogs.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListInterestsFragment.kt
app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListInterestsViewModel.kt
app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListOptions.kt
app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSettingsActivity.kt
app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSettingsScreen.kt
app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSourceFragment.kt
app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSourceScreen.kt
app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSourceViewModel.kt
app/src/main/java/org/wikipedia/settings/SettingsPreferenceLoader.kt

https://phabricator.wikimedia.org/T393488

Instrumentation for the Recommended reading list

---

app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListInterestsFragment.kt
app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListInterestsViewModel.kt

(to be merged, then design-reviewed from the Feature branch)

Design tweaks for Interests selection screen.

---

app/src/main/java/org/wikipedia/readinglist/RecommendedReadingListDiscoverCardView.kt
app/src/main/res/layout/fragment_reading_lists.xml

- adds nested scroll to the whole screen

Reading List whole screen scrollable

---

app/src/main/java/org/wikipedia/readinglist/ReadingListFragmentViewModel.kt
app/src/main/java/org/wikipedia/readinglist/db/RecommendedPageDao.kt
app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListHelper.kt

Optimize the logic of generating new recommendations, and fill up the list with the same titles if the source articles are not enough. 
This also reduce the error by showing the expire pages if the API cannot get more recommendations.

Optimize the algorithm of generating recommendations

---

app/src/main/java/org/wikipedia/notifications/NotificationPollBroadcastReceiver.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListActivity.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListHelper.kt
app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListNotificationManager.kt
app/src/main/java/org/wikipedia/settings/dev/DeveloperSettingsPreferenceLoader.kt

- Always cancel the existing notification before scheduling a new one.
- Return an empty list if no titles were found.
- Handle back click listener correctly for the `ErrorView`.

Fix: notifications and error logic handling

---

app/src/main/java/org/wikipedia/navtab/MenuNavTabDialog.kt
app/src/main/res/xml/developer_preferences.xml

Simplified code and cleaned up spaces.

Follow-up: dev settings for YiR

---

app/src/main/java/org/wikipedia/yearinreview/YearInReviewActivity.kt
app/src/main/java/org/wikipedia/yearinreview/YearInReviewScaffold.kt
app/src/main/java/org/wikipedia/yearinreview/YearInReviewViewModel.kt

- refactors the code to simplify survey dialog presentation

Yir survey dialog follow up

---

app/src/main/java/org/wikipedia/WikipediaApp.kt
app/src/main/java/org/wikipedia/csrf/CsrfTokenClient.kt
app/src/main/java/org/wikipedia/login/LoginClient.kt

This makes a few improvements in the logic of re-logging-in the user in the background, which could reduce the instances of users seeing messages of "You've been logged out", or at least behaving more consistently when such cases happen.

Streamline and improve background re-login workflow.

---

app/src/main/java/org/wikipedia/views/SurveyDialog.kt

- adds missing click listener to **Cancel** and **Submit** button

Edit Patrol Feedback dialog bug fix

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

- adds strings for donation reminders 
https://docs.google.com/spreadsheets/d/1K4WobHNc7iLk6tasTxiiSN-ULRzcifn8xcTo3mH12fs/edit?gid=0#gid=0

Strings for donation reminders

---

app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGamePlayFragment.kt

Fixes two crashes occurred in On this day game 
1. [IllegalStateException](https://play.google.com/console/u/0/developers/6169333749249604352/app/4976363884102945010/vitals/crashes/c7a3ff25669c975462166541879c36d9/details?days=28&versionCode=50543&isUserPerceived=true) thrown because  **OnThisDayGamePlayFragment** was detached from the **OnThisDayGameActivity** while a postDelayed call was still pending. 
2. [mediaPlayer](https://play.google.com/console/u/0/developers/6169333749249604352/app/4976363884102945010/vitals/crashes/2401d5378a63a132ec449051368e4c73/details?days=28&versionCode=50543&isUserPerceived=true) was not initialized and managed properly.

On This day game crash fixes

---

app/src/main/java/org/wikipedia/analytics/eventplatform/DonorExperienceEvent.kt
app/src/main/java/org/wikipedia/donate/donationreminder/DonationReminderHelper.kt

- adds user groups as action data for sending  survey events

Survey Instrumentation Donation Reminders

---

app/src/main/java/org/wikipedia/donate/donationreminder/DonationReminderHelper.kt
app/src/main/java/org/wikipedia/donate/donationreminder/DonationReminderScreen.kt
app/src/main/java/org/wikipedia/donate/donationreminder/DonationReminderViewModel.kt
app/src/main/java/org/wikipedia/settings/SettingsFragment.kt
app/src/main/java/org/wikipedia/util/FeedbackUtil.kt
app/src/main/res/values/strings.xml

- ui fixes
- adds snackbar on confirmation, saves confirmation only when donation reminders value changes
- fixes min amount validation check
- makes "About this experiment" always available

Donation reminder UI fixes

---

app/src/main/java/org/wikipedia/activitytab/ActivityTabFragment.kt
app/src/main/java/org/wikipedia/activitytab/WikiGamesModule.kt
app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

Remove the blue wikigames card and replace it with a small button, and adjust the logic a bit based on the design updates.
[Figma](https://www.figma.com/design/MXUBnIJvHfMBHhPZta7yRm/Android---%3E-Activity-Tab?node-id=46-3573&m=dev)
https://phabricator.wikimedia.org/T399751#11145358

Update WikiGames entry button for the Game module

---

app/src/main/java/org/wikipedia/activitytab/ActivityTabFragment.kt
app/src/main/java/org/wikipedia/activitytab/ActivityTabViewModel.kt
app/src/main/java/org/wikipedia/activitytab/DonationModule.kt
app/src/main/java/org/wikipedia/activitytab/EditingInsightsModule.kt
app/src/main/java/org/wikipedia/activitytab/ImpactModule.kt
app/src/main/java/org/wikipedia/activitytab/ReadingHistoryModule.kt
app/src/main/java/org/wikipedia/activitytab/WikiGamesModule.kt
app/src/main/java/org/wikipedia/activitytab/timeline/TimelineRepository.kt
app/src/main/java/org/wikipedia/compose/extensions/Modifier.kt
app/src/main/java/org/wikipedia/compose/theme/WikipediaColor.kt

- adds loading shimmer effect for loading

Activity tab shimmer loading

---

app/src/main/java/org/wikipedia/dataclient/Service.kt
app/src/main/java/org/wikipedia/login/LoginActivity.kt
app/src/main/java/org/wikipedia/login/LoginClient.kt
app/src/main/java/org/wikipedia/login/LoginModuleSelectResult.kt
app/src/main/java/org/wikipedia/login/LoginOATHResult.kt
app/src/main/java/org/wikipedia/login/LoginResponse.kt
app/src/main/java/org/wikipedia/login/ResetPasswordActivity.kt

https://phabricator.wikimedia.org/T403819

Add support for selectable TOTP auth module.

---

app/src/main/java/org/wikipedia/analytics/eventplatform/EventPlatformClient.kt

We get some occasional ANRs that point to the serialization of StreamConfigs. This makes sense, because the list of StreamConfigs is a **very** heavy object, and even though `kotlinx.serialization` is quite efficient, serializing an object of this size can still be very CPU-intensive, and shouldn't be done on the main thread.
Let's make sure that serialization of StreamConfigs is done in a separate thread. This should fix those ANRs, and perhaps even improve general startup performance for other devices.

Prevent possible ANRs from serializing stream configs.

---

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
app/src/main/res/layout/suggested_edits_tasks_container.xml
app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/strings_no_translate.xml

https://phabricator.wikimedia.org/T404766

Activity Tab: tweak verbiage in Edits screen.

---

app/src/main/java/org/wikipedia/activitytab/ActivityTabCustomizationActivity.kt
app/src/main/java/org/wikipedia/activitytab/ActivityTabFragment.kt
app/src/main/java/org/wikipedia/activitytab/ActivityTabModules.kt
app/src/main/java/org/wikipedia/language/AppLanguageState.kt

(Uses very similar logic as showing/hiding the Donation module. The logic is getting a bit complex; I wonder if we could simplify it in a future PR.)
https://phabricator.wikimedia.org/T404764

Activity Tab: don't show Game module if unavailable in current language.

---

app/src/main/java/org/wikipedia/yearinreview/YearInReviewSlides.kt
app/src/main/java/org/wikipedia/yearinreview/YearInReviewViewModel.kt
app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

https://phabricator.wikimedia.org/T405496

YiR: Update # of articles edited slide
