app/src/main/res/values/styles.xml
- This will help us use Material Design components with ease.
Phab: https://phabricator.wikimedia.org/T216277
Change-Id: I40fd2e47026c97916388943121294e6393cf9363
=> Make BaseAppTheme inherit from MaterialComponents

app/src/main/java/org/wikipedia/LongPressHandler.java
If an article contains links with different domain names, the app will show an error page when long pressing to open the link.
https://phabricator.wikimedia.org/T214950
=> Get correct WikiSite() when long pressing on links

app/src/main/res/layout/fragment_search.xml, app/src/main/res/layout/view_language_scroll.xml, app/src/main/res/values/styles.xml, app/src/main/res/values/styles_dark.xml, app/src/main/res/values/styles_light.xml
This moves our Dialog styles to use the MaterialComponents theme instead of the older AppCompat. No visual differences are expected. This also sets an explicit background color on the search language selection bar, since this is now required.
=> Migrate dialog styles to MaterialComponents theme.

app/src/main/res/layout/activity_page.xml
The background of the ToC dotted line is showing incorrectly on API 19 devices.
=> Fix: incorrect dotted line background on API 19

app/src/main/java/org/wikipedia/edit/EditSectionActivity.java
The `undo` and `redo` buttons in the `EditSectionActivity.java` do not work properly if the device's OS version is below API 21.
=> Disable the undo and redo buttons if API<21

app/src/main/java/org/wikipedia/edit/EditSectionActivity.java, app/src/main/java/org/wikipedia/edit/richtext/SyntaxHighlighter.java, app/src/main/java/org/wikipedia/edit/richtext/SyntaxRuleStyle.java, app/src/main/java/org/wikipedia/views/PlainPasteEditText.java, app/src/main/res/layout/activity_edit_section.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/styles.xml, app/src/main/res/values/styles_dark.xml, app/src/main/res/values/styles_light.xml, app/src/main/res/values/styles_sepia.xml
Tweak of "find text" function 
- Using the SyntaxRuleStyle to apply the selected text style.
- Remove the back arrow if is in the find in page action mode.
- The selected text color will be changed after DateUtils.SECOND_IN_MILLIS / 2, which is the default behavior in our SyntaxHighlighter class
https://phabricator.wikimedia.org/T89202
=> Tweak: "find text" function when editing

app/src/main/java/org/wikipedia/bridge/CommunicationBridge.java, app/src/main/java/org/wikipedia/theme/Theme.java
This places the theme's CSS class as an actual member field, rather than needing to look it up using its own funnel name.
=> Follow-up to theme change flicker.

app/src/main/java/org/wikipedia/edit/FindInEditorActionProvider.java, app/src/main/java/org/wikipedia/edit/richtext/SyntaxHighlighter.java, app/src/main/java/org/wikipedia/views/FindInPageActionProvider.java
- Reduce the 0.5s delay when only on the **Find in text** mode since the texts are not actually changed.
- Save the search query into the `PlainPasteEditText` view to reduce a `static` or` perferences` value.
=> Tweak of "find text" feature in the editor screen

app/src/main/java/org/wikipedia/history/HistoryFragment.java
The recent updates to SwipeableItemTouchHelper have broken the ability to swipe History items. This adds the necessary function to enable swiping again.
=> Fix swiping-to-delete of history items.

app/src/main/res/values/styles.xml
When scrolling quickly through the Feed in dark mode, you'll notice that the images briefly start with a bright white background before loading the actual image. This corrects the temporary background to use the current theme.
=> Fix drawee base placeholder background color.

app/src/main/assets/bundle.js, app/src/main/java/org/wikipedia/page/PageFragment.java, app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java, app/src/main/res/values/dimens.xml, www/js/sections.js
**Root cause and fix**
When we load the page, we set a custom horizontal margin on the page, customized on screen size.
Removed all margin setting code, since this is handled by the css upstream.
Before: https://drive.google.com/open?id=1snAS2L0LkknD2LJsTRgF36M1__RsRbuB
Fixed: https://drive.google.com/open?id=1bmvnwfeBD-jxbZb93NvRAXsTqoBDo0KY
Phab: https://phabricator.wikimedia.org/T216856
=> Fix: set proper margin on tablets in landscape mode

app/src/main/res/layout/item_reading_list.xml, app/src/main/res/layout/view_list_card_item.xml
Margin values on list item views do not set properly for tablets.
=> Use proper margin values on list item views

app/src/main/java/org/wikipedia/editactionfeed/EditTasksFragment.java, app/src/main/res/drawable/ic_info_outline_themed_24dp.xml, app/src/main/res/menu/menu_edit_tasks.xml
Looks like the 
`
android:iconTint="?attr/main_toolbar_icon_color"
`
Only works on `API 26` and above, and maybe we can just use a themed icon and skip the manual setup the tint in code.
=> Follow up of update Info/help screen concept

app/src/main/java/org/wikipedia/Constants.java, app/src/main/java/org/wikipedia/analytics/SuggestedEditsFunnel.java, app/src/main/java/org/wikipedia/dataclient/Service.java, app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.java, app/src/main/java/org/wikipedia/editactionfeed/AddTitleDescriptionsActivity.kt, app/src/main/java/org/wikipedia/editactionfeed/EditTasksFragment.java, app/src/test/java/org/wikipedia/descriptions/DescriptionEditClientTest.java
This adds a stub Funnel that will be used for the Suggested Edits feature. This also adds the `summary` parameter to our API functions so that the edits submitted from the app will be made with a comment that contains the version number of the feature.
=> Beginnings of analytics for Suggested Edits

app/src/main/java/org/wikipedia/dataclient/okhttp/OkHttpWebViewClient.java
It looks like the newest version of the Android WebView is trying to be a little too smart, and is adding conditional caching headers which are interfering with OkHttp's internal caching logic. Stripping away these headers (and allowing OkHttp to do all the caching work) fixes the issue.
https://phabricator.wikimedia.org/T218623
=> Fix WebView/OkHttp caching clash.

app/src/main/java/org/wikipedia/page/ToCHandler.java, app/src/main/res/drawable/shape_circle_black.xml, app/src/main/res/drawable/shape_circle_dark.xml, app/src/main/res/drawable/shape_circle_light.xml, app/src/main/res/drawable/shape_circle_sepia.xml, app/src/main/res/layout/activity_page.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/styles_black.xml, app/src/main/res/values/styles_dark.xml, app/src/main/res/values/styles_light.xml, app/src/main/res/values/styles_sepia.xml
The ToC scroller can be barely seen if it does not have a shadow.
It might be good to add a custom "shadow" to the ToC scroller before we officially move up to 21.
=> Add custom shadow to ToC scroller for API 19 devices.

app/src/main/java/org/wikipedia/bridge/CommunicationBridge.java, app/src/main/java/org/wikipedia/edit/preview/EditPreviewFragment.java, app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java
Recently the app has been unable to play audio elements. (This has been reported in OTRS, and verified locally.)  It's possible that some additional updates to the System Webview have changed the default behavior with regard to audio tags.
It looks like the WebView has a setting called `setMediaPlaybackRequiresUserGesture`, and if we set this to `false`, the audio seems to work again.
=> Fix audio playback.

app/src/main/assets/bundle.js, www/js/sections.js
Currently, the preference to "collapse tables" is not working properly: if you turn it off, the lead infobox still gets collapsed (while other tables in the article are not collapsed).
This seems to be because we're calling the `hideTables` function twice: once for the lead section, and once for the remaining sections. This fixes the issue by calling `hideTables` only in the remaining-sections logic, which will automatically pick up the tables in the lead section as well. This also changes the lazyLoader to be called only once (in the remaining sections) for the same reason, which will be a slight improvement in efficiency.
=> Fix collapsing of tables preference.

app/src/main/java/org/wikipedia/language/LangLinksActivity.java
Currently the list of other-language links is preserved in the activity's `savedInstanceState`, which is not really necessary, since it can actually be a rather large object, and can cause issues with inter-activity data parcel transactions. Re-fetching the list of links when the activity is re-created is perfectly fine.
=> Don't preserve LangLinks state unnecessarily.

app/src/main/java/org/wikipedia/page/PageActivity.java
We still get a small number of crashes when the system WebView gets updated. This is because we're not catching all the possible ways in which this exception can manifest itself.
=> Fix permissiveness in catching WebView update exception.

app/src/main/java/org/wikipedia/edit/EditSectionActivity.java
For some reason we were overriding the default ActionMode in the editing activity. This is incorrect, since the overridden actions ("edit here", "define", etc) don't make sense in the editing context.
https://phabricator.wikimedia.org/T219393
=> Fix standard ActionMode when editing.

app/src/main/res/layout/view_list_card.xml
Not sure why the "More like this" item in a list of a card only is not a full-width clickable view. It might be good if expands it to full-width.
=> Expand the width of "More like this" view

app/src/main/res/menu/menu_edit_action_feed.xml, app/src/main/res/menu/menu_edit_tasks.xml, app/src/main/res/values-qq/strings.xml, app/src/main/res/values/strings.xml
Renamed “Help“ to “Info“ in the overflow menu so the label text is aligned with the icon 
Phab: https://phabricator.wikimedia.org/T217562
=> Change help label verbiage

app/src/main/java/org/wikipedia/main/MainActivity.java, app/src/main/res/values-qq/strings.xml, app/src/main/res/values/strings.xml
The "log out" button in our Navigation menu is pretty easy to tap, and is rather abrupt in logging out the user. It would be nice to have a confirmation message that asks if you actually want to log out.
=> Add confirmation dialog when logging out.

app/src/main/res/layout/view_wikitext_keyboard.xml, app/src/main/res/menu/menu_edit_section.xml, app/src/main/res/values-qq/strings.xml, app/src/main/res/values/strings.xml
The new WikiText keyboard overlay buttons actually had some hard-coded text in them, and didn't actually use string resources!
This also fixes an incorrect hint provided for the "find-in-page" menu icon when editing.
=> Whoops: make WikiText button strings translateable.

app/src/main/java/org/wikipedia/editactionfeed/AddTitleDescriptionsFragment.kt, app/src/main/java/org/wikipedia/editactionfeed/AddTitleDescriptionsItemFragment.kt
- Because we do not check for empty sourceDescription on card click, sometimes we end-up with empty text field for it . This fixes the issue by adding the check.
Bug: https://drive.google.com/open?id=13GP_tCvoeb65lJDL892e1q60VpZfwEDD
=> Fix: Empty sourceDescription

app/src/main/java/org/wikipedia/editactionfeed/AddTitleDescriptionsItemFragment.kt
Change to summary so Title Descriptions click doesn't get locked.
=> Fix incorrect null check when clicking on description card view

app/src/main/java/org/wikipedia/editactionfeed/AddTitleDescriptionsFragment.kt, app/src/main/java/org/wikipedia/settings/Prefs.java, app/src/main/res/values-qq/strings.xml, app/src/main/res/values/preference_keys.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/developer_preferences.xml
Regarding the comment from Robin: 
https://phabricator.wikimedia.org/T215630#5077695
The onboarding dialogs are no longer needed, and related strings/preferences should be removed from the project.
=> Remove onboarding dialogs and unused strings.

app/src/main/java/org/wikipedia/editactionfeed/AddTitleDescriptionsActivity.kt, app/src/main/java/org/wikipedia/editactionfeed/EditTasksFragment.java, app/src/main/java/org/wikipedia/login/LoginActivity.java, app/src/main/java/org/wikipedia/main/MainActivity.java, app/src/main/java/org/wikipedia/main/MainDrawerView.java, app/src/main/java/org/wikipedia/notifications/NotificationEditorTasksHandler.java, app/src/main/java/org/wikipedia/settings/DeveloperSettingsPreferenceLoader.java, app/src/main/java/org/wikipedia/settings/Prefs.java, app/src/main/res/values/preference_keys.xml, app/src/main/res/xml/developer_preferences.xml
If a current user has an account that has unlocked the `SuggestedEdits`, and then the user logs out to another account that has not unlocked the `SuggestedEdits`, the preferences and the item in drawer menu should be changed right after the user logged in.
Also, I've renamed some preferences and methods to `SuggestedEdits`
=> Tweak the logic of login/logout for SuggestedEdits

app/src/main/java/org/wikipedia/descriptions/DescriptionEditLicenseView.kt, app/src/main/java/org/wikipedia/descriptions/DescriptionEditReviewView.kt, app/src/main/java/org/wikipedia/editactionfeed/EditTasksFragment.java, app/src/main/java/org/wikipedia/editactionfeed/provider/MissingDescriptionProvider.kt, app/src/main/res/values-qq/strings.xml, app/src/main/res/values/strings.xml
The general license notice is **_By changing the title description ..._** and in the `SuggestedEdits` we should use **_By adding the title description_**
Reference: https://app.zeplin.io/project/57a120b91998d8977642a238/screen/5c77d809981c3b6256b4521e
Move the related string into `` block.
When doing the clean-up in `values-qq/strings.xml`, I found there's a **translated** string in the file, which is not correct.
=> Update strings for suggested edits and remove unused strings

app/src/main/assets/bundle.js, app/src/main/java/org/wikipedia/dataclient/okhttp/OkHttpWebViewClient.java, app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.java, www/js/sections.js
There's a callback from the WebView that is only made in API 19, and also some Javascript-level items that can now go away.
=> Follow-up to API 21 (Clean up WebView details)

app/src/main/res/layout/view_description_edit.xml
If using the landscape mode in Tablet, or using large font size, the `EditText` view will be covered by the bottom view.
=> Use ScrollView for the EditText in add description screen

app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.java
Keeping the DescriptionEditView invisible in the Fragment until we get response from the api to get rid of flicker in ui update
=> Loading DescriptionEditView smoothly

app/src/main/res/layout/fragment_add_title_descriptions.xml
Changing dropdown arrow caret tint to **colorAccent.**
Zeplin : https://app.zeplin.io/project/57a120b91998d8977642a238/screen/5c77d20a86d8b86292fd9750
**Phab:** https://phabricator.wikimedia.org/T217170
=> Changing dropdown caret tint - Suggested Edits Translation 

app/src/main/assets/bundle.js, app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java, www/js/sections.js
The changes made in #31 seems to have removed too much functionality, and broke image dimming. This restores the explicit call into the page-library to dim the images when necessary.
=> Fix image dimming in dark mode(s).

app/src/main/res/layout-land/fragment_add_title_descriptions_item.xml, app/src/main/res/layout/fragment_add_title_descriptions_item.xml
'viewAddDescriptionButton' has a bottom marging of 5dp and in portrait mode we have 19dp for top margin on the divider, which makes it 24dp [expected 19dp], and in landscape mode, 14dp on top margin for divider, which makes it correctly 19dp. In this PR they have been synced both layouts to just have a top margin on divider to 19dp.
=> Update margin above the divider - Suggested Edits 

app/src/main/res/values/strings.xml
Elegant quotes are actually good, but the current file uses
them inconsistently, so it's better to use plain quotes
until there's an agreement about standard usage of elegant quotes.
=> Use plain double quotes in all the English strings

app/src/main/java/org/wikipedia/analytics/Funnel.java, app/src/main/java/org/wikipedia/feed/announcement/Announcement.java, app/src/main/java/org/wikipedia/notifications/Notification.java, app/src/main/java/org/wikipedia/page/PageProperties.java, app/src/main/java/org/wikipedia/readinglist/sync/ReadingListSyncAdapter.java, app/src/main/java/org/wikipedia/util/DateUtil.java, app/src/test/java/org/wikipedia/util/DateUtilTest.java
Instantiating a new `SimpleDateFormat` object is actually a pretty expensive operation. Let's cache and reuse these objects.
However, note that `SimpleDateFormat` objects are not thread safe, so the methods that access them must be `synchronized`.
=>  Optimization: cache SimpleDateFormat objects.

app/src/main/java/org/wikipedia/main/floatingqueue/FloatingQueueBottomViewBehavior.java, app/src/main/java/org/wikipedia/main/floatingqueue/FloatingQueueView.kt, app/src/main/res/layout/fragment_main.xml, app/src/main/res/layout/fragment_reading_list.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/styles_dark.xml, app/src/main/res/values/styles_light.xml
Uses CardView so that we can show the elevation properly.
Also, fixes the issue that floating queue view stick when the Snackbar showing.
=> Use CardView for floating queue view and fix bottom view behavior.

app/src/main/java/org/wikipedia/page/PageActivity.java, app/src/main/java/org/wikipedia/page/PageFragment.java
A minor clean up of removing the unused methods since we are calling the SearchActivity when searching article.
=> Remove unused methods of showing tool bar in PageActivity/PageFragment

app/src/test/java/org/wikipedia/gallery/GalleryClientTest.java
The previous test cases in `GalleryClientTest` were testing in an incorrect way.
=> Use correct way of testing observable calls in GalleryClientTest

app/src/main/java/org/wikipedia/page/ToCHandler.java
A minor changes to the class since some methods can be in the `package-private` level.
Also, add `@SuppressLint("RtlHardcoded")` to the methods have set up `rtl ? Gravity.LEFT : Gravity.RIGHT;`, to avoid the unwanted suggestion from Android Studio.
=> Update metrhods access level and add SupressLint for RTL settings in ToC

app/src/main/java/org/wikipedia/search/SearchResultsFragment.java
Since we've fixed the `ContextMenu` issue, I found that the long press action in `SearchResultsFragment` will show a `PopupMenu` and then also go to the article page, which is incorrect.
The way of doing this correctly is to implement the `OnClickListener` to each list item, like how `BottomContentView` does.
=> Use view click listener to solve the conflict of actions in SearchResultsFragment

app/src/main/java/org/wikipedia/feed/FeedContentType.java, app/src/main/java/org/wikipedia/settings/Prefs.java, app/src/main/res/values/preference_keys.xml, app/src/main/res/xml/developer_preferences.xml
-Turning on the developer setting for descriptions/translations dialog will not help load cards as it gets unset with the next poll, so created an exclusive switch for suggested edits feed cards.
User still needs to be logged in, the cards should be enabled and still under the preBeta flag.
**Phab**: https://phabricator.wikimedia.org/T217373
=> Developer setting for testing suggested edits cards

app/src/main/java/org/wikipedia/page/bottomcontent/BottomContentView.java
The issue can be reproduced by the following steps:
1. Open the article [Hackathon] in English
2. Scroll down to the "Read more" section
3. Change article language to Traditional Chinese
4. Scroll down to the "Read more" section, and you will see the issue.
=> Fix: bottom content view list item does not have correct height

app/src/main/java/org/wikipedia/descriptions/DescriptionEditActivity.java, app/src/main/java/org/wikipedia/edit/preview/EditPreviewFragment.java, app/src/main/java/org/wikipedia/feed/mostread/MostReadFragment.java, app/src/main/java/org/wikipedia/feed/news/NewsFragment.java, app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayPagesViewHolder.java, app/src/main/java/org/wikipedia/main/MainFragment.java, app/src/main/java/org/wikipedia/notifications/NotificationActivity.java, app/src/main/java/org/wikipedia/page/PageActivity.java, app/src/main/java/org/wikipedia/page/tabs/TabActivity.java, app/src/main/java/org/wikipedia/random/RandomFragment.java, app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.java, app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.java, app/src/main/res/menu/menu_tabs.xml
We want to change the general default behavior for opening articles (e.g. from the Feed, Reading Lists, History, etc) in the "current" tab, instead of opening a new tab every time.
https://phabricator.wikimedia.org/T222056
=> Open articles from other sources in current tab, not new tab.

app/src/main/java/org/wikipedia/views/DiscreteSeekBar.java
When the system language is set to RTL, and you invoke the theme chooser, the text size SeekBar was looking weird, with incorrect placement of tick marks.
=> Fix appearance of text size SeekBar in RTL.

app/src/main/java/org/wikipedia/descriptions/DescriptionEditReadArticleBarView.kt, app/src/main/java/org/wikipedia/descriptions/DescriptionEditReviewView.kt, app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardView.kt, app/src/main/java/org/wikipedia/readinglist/ReadingListBehaviorsUtil.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsAddDescriptionsFragment.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsAddDescriptionsItemFragment.kt, app/src/main/java/org/wikipedia/suggestededits/provider/MissingDescriptionProvider.kt
`String?#isNullOrEmpty()` uses contracts such that the string is implicitly non-nullable if the check passes. For example, [here](https://github.com/wikimedia/apps-android-wikipedia/compare/master...veyndan:kt-TextUtils?expand=1#diff-eb25cdd07ccca1c70f96371dd907b1b6R112) the not-null assertion operator is no longer required as the [surrounding conditional](https://github.com/wikimedia/apps-android-wikipedia/compare/master...veyndan:kt-TextUtils?expand=1#diff-eb25cdd07ccca1c70f96371dd907b1b6R102) states the use of the string in that instance is not-null.
As an additional bonus, the linter tells us that `String?#isNullOrEmpty()` can be replaced with `String#isEmpty()` when the string is non-null, removing a redundant non-null check, and more importantly, making the code more concise.
=> Replace Kotlin occurrences of TextUtils.isEmpty(String) with String#isNullOrEmpty()

app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardView.kt
`disposable` is never added to, so only every clearing an empty `CompositeDisposable` is rather pointless.
=> Remove unused CompositeDisposable

app/src/main/java/org/wikipedia/page/PageToolbarHideHandler.java
Instead of continuously updating the opacity of toolbar and its icons, we can use the height of the header view and update opacity when `ScrollY` reaches/over the height.
Also, update methods and constructor to the `package-private` level.
https://phabricator.wikimedia.org/T223121
=> Fix: Invisible app bar on article page with image

app/build.gradle, build.gradle, project.properties
If your workstation is offline, it is currently not possible to build and install the app onto a device or emulator, making it difficult to work while traveling.
The issue was because the `chrome-like-tab-switcher` library was depending on an old version of the `jetbrains:annotations` library that we don't provide.
This fixes the issue of building offline, and also cleans up some additional items in our Gradle file.
=> Fix ability to build app while offline.

app/build.gradle
This should fix the weird-seeming issues with using standalone `OnClick` annotations.
=> Remove unnecessary (and destructive) ButterKnife parameters.

app/src/main/res/layout/group_captcha.xml
The view should set a `ScaleType` for __CAPTCHA__ image since it is wider than the parent view's width. 
The following screenshot shows the difference between with and without setting up `scaleType="fitCenter"`
=> Set scale type for CAPTCHA image to avoid image being cut off

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsAddDescriptionsFragment.kt, app/src/main/res/drawable/ic_add_gray_white_24dp.xml, app/src/main/res/layout-land/fragment_suggested_edits_add_descriptions.xml, app/src/main/res/layout/dialog_add_to_reading_list.xml, app/src/main/res/layout/fragment_suggested_edits_add_descriptions.xml, app/src/main/res/layout/view_onboarding_language_list.xml, app/src/main/res/layout/view_wikipedia_language_footer.xml
The "add" icon in `TabActivity` was replaced to a non-themed icon, which should be fixed.
=> Use correct themed "add icon" in TabActivity

app/src/main/java/org/wikipedia/page/PageToolbarHideHandler.java
The issue can be reproduced by the following steps:
1. Go to article __Perfect season__
2. Click on the second paragraph link: __Exhibition game__
This PR also brings the `tabsButton.setTabCount` back to constructor because we don't need to update the value every time after scrolled.
=> Fix: incorrect toolbar opacity in PageActivity

app/src/main/java/org/wikipedia/feed/view/FeedView.java
This was a workaround for an internal AOSP issue that has been fixed a while ago.
https://rink.hockeyapp.net/manage/apps/226649/app_versions/670/crash_reasons/272043113
=> Fix possible crash when destroying FeedView.

app/src/main/java/org/wikipedia/main/MainActivity.java, app/src/main/java/org/wikipedia/page/PageActivity.java, app/src/main/java/org/wikipedia/page/PageToolbarHideHandler.java, app/src/main/java/org/wikipedia/page/tabs/TabActivity.java, app/src/main/java/org/wikipedia/views/TabCountsView.java
The tab count button was actually being updated incorrectly if you open a Search Result in a new tab. This improves the setting of the tab count by putting it in the `onPrepareOptionsMenu` function, where it logically belongs (even though we're not using a proper options menu).
=> Improve updating tab count button in PageActivity.

app/src/main/java/org/wikipedia/feed/news/NewsItem.java
Caused indirectly by the same crash as #288, but this will catch even more possible issues.
https://rink.hockeyapp.net/manage/apps/226649/app_versions/669/crash_reasons/272569905
=> Fix possible crash when rendering News cards.

app/build.gradle
Now that we have switched to using Bundles, the versionCode of the bundle needs to be greater than any previous versionCode of any individual APK (where we had "split" version codes such as 10280, 20280, 30280, and 40280).
We will hereby start the Bundle versionCodes in the 50000 series!
=> Update versionCode beyond all previous limits.

app/src/main/res/layout/fragment_page.xml
After we removed the circular thumb-scroller, we forgot to re-enable the default scroll bar on the WebView.
=> Whoops: bring back the WebView's scroll bar!

app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.java, app/src/main/java/org/wikipedia/util/DeviceUtil.java, app/src/main/java/org/wikipedia/util/DimenUtil.java
It is reproducible on my Pixel 3 XL running Android 9.0.
The full-screen mode in the `GalleryActivity` will also hide the navigation bar.
https://phabricator.wikimedia.org/T223948
=> Fix the issue of media playback overlaps the navigation bar.

app/src/main/res/layout/date_picker_dialog.xml
@dbrant 
I found a bug at `OnThisDayActivity` when I opened the date picker dialog. The bottom of the month's text was clipped. 
I was able to reproduce it on Samsung S8 and on emulators as well.
Solution:
As the `TextView` was in a `LinearLayout` with fix height, I removed the bottom padding as it clipped the bottom of the `TextView` and has no purpose.
See attached image about the issue:
=> Fix date text clipping at On this day dialog

app/src/main/java/org/wikipedia/notifications/NotificationEditorTasksHandler.java
To reproduce:
1. Have an account that has 50+ verified description edits.
2. Keep only "English" app language and log out.
3. Log in the same account and go to the Suggested edits
4. You will see the "Multilingual task" card with incorrect messages. It should be the one with "add languages" button
=> Fix: update unlock suggested edits preferences correctly.

app/src/main/java/org/wikipedia/page/tabs/TabActivity.java
https://rink.hockeyapp.net/manage/apps/226649/app_versions/678/crash_reasons/275174097
Sometime it will crash when getting a `null` PageTitle object.
This PR also add an additional logic of the Main page since the `getThumbUrl()` from the Main page is not empty.
=> Fix possible crash on Tab screen

app/src/main/java/org/wikipedia/views/WikiErrorView.java
https://phabricator.wikimedia.org/T163230
A [great article](https://medium.com/androiddevelopers/using-vector-assets-in-android-apps-4318fd662eb9) detailing why `ContextCompat` cannot be used for vector assets.
=> Fix error icon incorrect rendering on API 21 and 23

app/src/main/res/layout-land/fragment_suggested_edits_add_descriptions.xml, app/src/main/res/layout/fragment_suggested_edits_add_descriptions.xml
- The "add" icon does not need to tint since it contains the correct color itself.
- The color of the button text should be `@color/base100` instead of themed colors.
=> Use correct text color for Suggested edits "ADD" button

app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.java
1. Go to suggested edit and tap on "Add description"
2. Add a description and go to review screen
3. Change device orientation and you'll lose the added description.
=> Retain the added description when changing the orientation

app/src/main/res/layout-land/fragment_suggested_edits_add_descriptions.xml, app/src/main/res/layout/fragment_suggested_edits_add_descriptions.xml
The "ADD" button actually needs the `android:tint="@color/base100"` since the "edit" icon is not in white.
=> Fix the "edit" icon in Suggested edits has incorrect color

app/src/main/java/org/wikipedia/main/MainDrawerView.java
The "Suggested edits" menu item wasn't being properly unlocked if the user makes only caption edits, and no description edits.
=> Fix unlocking of Left Nav menu upon adding captions.

app/src/main/java/org/wikipedia/gallery/GalleryActivity.java
The translation button should not show if the user only has one language set.
=> Fix: the translation button visibility in GalleryActiviy

app/src/main/java/org/wikipedia/views/ImagePreviewDialog.kt, app/src/main/res/layout/dialog_image_preview.xml
1. Go to any article page
2. Tap on the lead image and click the `Translate caption` button
3. Tap on the bottom bar to open the `ImagePreviewDialog`.
This PR also fixes the issue that the `errorView` does not work properly if an error happens.
=> Fix: crash happens when tapping on ImagePreviewDialog if no metadata in SuggestedEditsSummary

app/src/main/java/org/wikipedia/gallery/GalleryActivity.java
https://phabricator.wikimedia.org/T225635#5262288
=> Fix: translate caption in Gallery should be editable if it hosts in Commons

app/src/main/res/layout/activity_gallery.xml
`#4` in https://phabricator.wikimedia.org/T225635
This PR also shorten the width of the translate button to `wrap_content`
=> Widen the edit icon clickable area in Gallery

app/src/main/java/org/wikipedia/descriptions/DescriptionEditBottomBarView.kt, app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.java, app/src/main/java/org/wikipedia/views/ImagePreviewDialog.kt, app/src/main/res/layout/dialog_image_preview.xml, app/src/main/res/layout/view_description_edit_read_article_bar.xml
`#10` in https://phabricator.wikimedia.org/T225635
The `ViewGroup`s are not necessary anymore, and we can make it simpler.
And also update the title in `ImagePreviewDialog` to make it consistent with the title in bottom bar view.
`#25` in https://phabricator.wikimedia.org/T225635
Make the image has correct `wrap_content` to the height.
=> Make bottom bar in Suggested edits consistent and update image view ratio in ImagePreviewDialog

app/src/main/java/org/wikipedia/descriptions/DescriptionEditActivity.java, app/src/main/java/org/wikipedia/views/ImagePreviewDialog.kt
`#8` in https://phabricator.wikimedia.org/T225635
The source and target `SuggestedEditsSummary` for image caption are basically the same, and only the source contains the description (or caption).
=> Use correct SuggestedEditsSummary for ImagePreviewDialog

app/src/main/java/org/wikipedia/dataclient/mwapi/EditorTaskCounts.java
Due to a quirk of the server-side logic, the "actual" milestones reported by the API might not exactly match the "theoretical" milestones. This PR updates the counting logic to properly determine the number of milestones passed by the user, in all cases.
=> Fix tallying of suggested edit milestones.

app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.java
Language names need to be according to the system language. so changing it to Localized names.
**Phab**: https://phabricator.wikimedia.org/T225874
=> Fix: Use localized language names in DescriptionEditView

app/src/main/java/org/wikipedia/util/UriUtil.java
We've changed the deep link logic in #331 but forgot to update the method of removing the link prefix. This will cause the `/zh/` link always shows an error page.
https://phabricator.wikimedia.org/T224788
=> Fix the /zh/ deep link always shows error page

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsFragment.kt
The `source` field gets deserialized in `onCreateView()`, whereas the funnel for the initial impression gets called in `onCreate()` which happens earlier, and uses the default value for `source`.
https://phabricator.wikimedia.org/T225439
=> Fix analytics of the first impression of suggested edit card.

app/src/main/res/layout/fragment_suggested_edits_cards.xml, app/src/main/res/layout/fragment_suggested_edits_cards_item.xml
If you look closely, the top border of the suggested edit card is cut off (overlapped by the toolbar).
=> Fix padding around suggested edit card.

app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCard.kt, app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardView.kt
Remove date completely from all Suggested edit cards, since it’s not really relevant for it.
Phab: https://phabricator.wikimedia.org/T224600
=> Suggested edits: Removed date from feed card

app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.java, app/src/main/res/values/strings.xml
The toolbar should show the correct title based on the current action
=> Show the correct title when editing and reviewing article description and image caption

app/src/main/java/org/wikipedia/descriptions/DescriptionEditBottomBarView.kt, app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardView.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsItemFragment.kt
For "Add article descriptions" or "Translate article descriptions" in Suggested edits, the article title will contain HTML tag such as `<i></i>`, and we should show it properly.
=> Fix: show HTML style for article title in Suggested edits

app/src/main/res/values/strings.xml
`#7` in https://phabricator.wikimedia.org/T225635#5299612
https://phabricator.wikimedia.org/T225635#5304437
Update the string base on the `copy master` document: https://docs.google.com/spreadsheets/d/1t0IWXoSz7EYBS6LrQM5fV_qZ6paK_sFRjnCp9H7rEPo/edit#gid=0
=> Tweak: update suggested edits lock message

app/src/main/java/org/wikipedia/util/StringUtil.java, app/src/main/java/org/wikipedia/views/ImagePreviewDialog.kt, app/src/main/res/layout/view_image_detail.xml
Also fixed the issue that the `detailsContainer` is not clickable with the external icon if the `detailTextView` applies `movementMethod`
=> Follow up: simplify the logic of handling clickable links in ImagePreviewDialog

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsItemFragment.kt
This fixes the issue of not being able to click the Suggested Edit card when returning from editing the caption. (with "don't keep activities" enabled)
=> Correctly preserve instanceState of Suggested Edit cards.

app/src/main/java/org/wikipedia/readinglist/database/ReadingListPageTable.java
The `TODO` says: _TODO: Remove in Dec 2018_
It's time to remove it.
=> Remove the method of importing old reading lists

app/src/main/res/layout/view_image_detail.xml, app/src/main/res/values/strings.xml
- "infos" is not a word.
- the external link arrow icon should be 16x16, according to Zeplin.
=> Minor tweaks to ImagePreviewDialog.

app/src/main/java/org/wikipedia/page/ExtendedBottomSheetDialogFragment.java, app/src/main/java/org/wikipedia/views/ImagePreviewDialog.kt, app/src/main/res/values-sw600dp-port/dimens.xml, app/src/main/res/values-sw720dp-port/dimens.xml, app/src/main/res/values/dimens.xml
On tablets, the default peekheight of bottomsheets is very small. so, we need to set it dynamically to a fraction of the screen height.
**Phab**: https://phabricator.wikimedia.org/T223130
=> Adjusting bottom sheet peekHeight

app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.java
1. The `getPage().getPageProperties().getLeadImageName()` should add underscores when matching the file page name.
2. The "add caption" button should refer to the current article's language.
3. If the current article has assigned value to `callToActionTargetSummary`, and it should be cleared when setting up the CTA on the next article.
=> Fix the issue that the add caption button in PageActivity does not work properly

app/src/main/java/org/wikipedia/page/PageFragment.java
The issue can be found here: https://github.com/wikimedia/wikimedia-page-library/pull/217
To fix that, we can also use the `setTextZoom()` to update the percentage of the text size, which is more sense to me.
=> Use setTextZoom() to change the WebView font size

app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.java
According to discussion on the ticket, removed the requisite for article image cta to be open only to users with suggested edits features unlocked. It is now open to all logged in users
**Phab**: https://phabricator.wikimedia.org/T224728
=> Article lead image cta - remove suggested edits unlock requirement

app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsFeedClient.kt, app/src/main/java/org/wikipedia/gallery/GalleryActivity.java, app/src/main/java/org/wikipedia/page/PageFragment.java, app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.java, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsItemFragment.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsSummary.kt
Since we are using `ImageUrlUtil.getUrlForPreferredSize()` for higher resolution images from `thumbnailUrl`, it would be better if we remove the unused `originalUrl` parameter.
=> Remove unused parameter from SuggestedEditsSummary

app/src/main/java/org/wikipedia/util/FeedbackUtil.java
When logging with globally locked username, for example, "test", the message from the API response will contain `<strong>` HTML tag.
We should handle the HTML tags.
=> Handle HTML tags in SnackBar

app/src/main/java/org/wikipedia/page/PageFragment.java
1. Read any article
2. Turn on airplane mode
3. Back to explore feed
=> Fix: prevent possible crash after left PageFragment

app/src/main/java/org/wikipedia/dataclient/RestService.java, app/src/main/java/org/wikipedia/gallery/GalleryActivity.java
Changes the assumption that the source language will be the 0th language of the app languages and the target language is the 1st. This PR keeps track of the source language in which the galleryActivity is launched and the target language as the one that doesn't have structured caption.
=> Gallery activity editing fix

.travis.yml, app/build.gradle
Somehow the Travis CI changed their `install-jdk.sh` recently, and also something wrong with the license when installing `oraclejdk8`. 
```
Installing oraclejdk8
$ export JAVA_HOME=~/oraclejdk8
$ export PATH="$JAVA_HOME/bin:$PATH"
$ ~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"
Ignoring license option: BCL -- using GPLv2+CE by default
install-jdk.sh 2019-07-17
Expected feature release number in range of 9 to 14, but got: 8
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .
Your build has been stopped.
```
To solve that, we can simply change the virtual environment to `Trusty`. …
=> Update travis config to avoid a license error

app/src/main/java/org/wikipedia/page/PageActivity.java, app/src/main/java/org/wikipedia/page/PageFragment.java, app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.java
In every other case, GalleryActivity takes into account the pageTitle lanuguage that launches it, but only for launch from the feedbackUtil, we need to update it to the targetLanguage.
=> Consider article CTA language during GalleryActivity launch from FeedbackUtil

app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.java, app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.java
This also fixes the issue that we should no longer send "no description" text to the Suggested edits flows.
=> Tweak: hide description view after added the caption

app/src/main/java/org/wikipedia/gallery/GalleryActivity.java, app/src/main/java/org/wikipedia/page/PageActivity.java
https://phabricator.wikimedia.org/T224728#5374101
The first issue is a crash. We should use the first app language if "target" language is `null`, otherwise it will lead a crash.
=> Fix crash and refresh page if an image caption has been added in Gallery

app/src/main/java/org/wikipedia/gallery/GalleryActivity.java
https://phabricator.wikimedia.org/T224728#5374588
The core of this issue is:
https://en.wikipedia.org/api/rest_v1/page/media/Badminton_at_the_1992_Summer_Olympics
If looks closely, you will notice that the `Titles` is `File:Olympic_rings.svg`, but the `file_page` is `https://commons.wikimedia.org/wiki/File:Olympic_rings_without_rims.svg`.
`File:Olympic_rings.svg` will be redirected to the `File:Olympic_rings_without_rims.svg`, and we should make a double check the `filename` from both `Titles` and `file_page` url.
=> Fix: check "redirected" filename correctly in GalleryActivity

app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.java
The logic for showing the CTA was using the `media` endpoint, which will be deprecated soon, and is not really necessary for this purpose anyway.
=> Simplify and speed up the call-to-action on top of lead image.

app/src/main/java/org/wikipedia/dataclient/WikiSite.java, app/src/main/java/org/wikipedia/language/AppLanguageLookUpTable.java
There is still some confusion and inconsistency within MediaWiki itself regarding the deprecation of the old `be-x-old` domain and the newer `be-tarask`: https://phabricator.wikimedia.org/T111853
This provides some logic to work around the issue.
=> Fix support for switching to be-tarask language.

app/src/main/java/org/wikipedia/login/LoginClient.java
https://phabricator.wikimedia.org/T227925
We were checking whether the response is exactly equal to `TOTPAuthenticationRequest`, when in fact the latest update to MediaWiki makes it `MediaWiki\Extension\OATHAuth\Auth\TOTPAuthenticationRequest`.
This PR loosens the check to whether the response _ends with_ this expected value.
=> Fix handling of TOTP login response.

app/src/main/java/org/wikipedia/page/PageFragment.java
If the article is not available for offline reading, it will cause a crash because of the `null` object.
=> Fix the issue of a crash when loading article offline

app/src/main/java/org/wikipedia/gallery/GalleryActivity.java, app/src/main/java/org/wikipedia/language/LangLinksActivity.java, app/src/main/java/org/wikipedia/page/PageActivity.java
When opening pages from the Gallery or LangLinks, let's push them onto the current backstack instead of squashing the backstack, kthx.
https://phabricator.wikimedia.org/T230203
=> Don't squash current tab backstack when opening Gallery file page or LangLinks

app/src/main/java/org/wikipedia/dataclient/okhttp/OkHttpWebViewClient.java
We can remove the logic of loading local assets of CSS styles since we removed the page-library from the app,
=> Remove unused logic of loading local CSS assets

app/src/main/java/org/wikipedia/page/PageFragment.java
Shouldn't put the `setupToC()` and `editHandler.setPage()` into the logic of checking reading list.
The ToC will not display if the article has not being saved into the reading list.
=> Mobile-html: fix the logic of showing ToC

app/src/main/java/org/wikipedia/bridge/CommunicationBridge.java
**Steps to reproduce**
1. Open article [South Korea]
2. Go to [Climate] 
3. Open the "Quick facts" and click on the "explanation" for the climate chart
4. Open the article
The title is `Template:Climate_char/How_to_read_a_climate_chart`, and the `/` should be encoded to `%2F`, which will be `Template:Climate_chart%2FHow_to_read_a_climate_chart`
=> Encode the page title to prevent showing page with error codes

app/src/main/java/org/wikipedia/language/LangLinksActivity.java, app/src/main/java/org/wikipedia/notifications/NotificationActivity.java, app/src/main/java/org/wikipedia/search/SearchResultsFragment.java
**Steps to reproduce:**
- Go to "NotificationActivity"
- Log out the account somewhere else (e.g. Desktop Wikipedia)
- Try to refresh the page
=> Fix: make sure the "go back" button work properly on WikiErrorView

app/src/main/java/org/wikipedia/analytics/SuggestedEditsFunnel.java, app/src/main/java/org/wikipedia/feed/FeedFragment.java, app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCard.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksActivity.kt
The `SuggestedEditsFunnel` wasn't really designed to work with how the user enters the workflow directly from the feed. This patch attempts to make it work as well as it can.
=> Make SuggestedEditsFunnel work when entering from Feed.

scripts/make-release.py
The updated Gradle plugin puts the built Bundle in a slightly different folder than before.
=> Fix copying of AAB bundle when building releases.

app/src/main/java/org/wikipedia/search/SearchFragment.java, app/src/main/java/org/wikipedia/views/LanguageScrollView.java, app/src/main/res/layout/fragment_search.xml, app/src/main/res/layout/view_language_scroll.xml
Since the `TabLayout` extends the `HorizontalScrollView`, which supports the `requiresFadingEdge` and `fadingEdgeLength`, we can use it instead of creating a custom gradient view. And, it supports RTL languages correctly.
=> Tweak: use fadingEdge on LanguageScrollView and minor code clean up

app/src/main/java/org/wikipedia/login/LoginActivity.java, app/src/main/java/org/wikipedia/login/LoginClient.java, app/src/main/res/layout/activity_login.xml
If we add up all the evidence that we have gathered so far, there is only one code path that could lead to the `logintoken` being null in the login API call:
The issue is not related to 2FA _per se_, but rather has to do with how we display and bind to the entry field for the 2FA token.  For some reason, the text field for entering the 2FA code was being bound as an `EditText`, instead of a `TextInputLayout` as it's supposed to be.  This may be producing unexpected behavior (on some devices / platforms) when we try to read the string value from the field.
NOTE: We still need to test whether actual 2FA is still working after this patch.
=> Fix obscure login issue.

app/src/main/java/org/wikipedia/notifications/NotificationActivity.java, app/src/main/java/org/wikipedia/notifications/NotificationPollBroadcastReceiver.java
Since we cannot get "read" Commons notifications from `en.wikipedia.org`, we can make the API calls from `https://commons.wikimedia.org/` to get notifications from Commons.
=> Use Commons URL sas WikiSite to get all notifications

app/build.gradle
The app bundle splitting process splits apk according different screen densities, cpu architectures and languages. While this has not been a problem in the past,Playstore threw an error while trying to split the apk according to languages as it doesn't recognize th 'qq' flavor. This patch requests languages to be excluded during splitting, hence avoiding the problem.
=> Exclude languages while creating app bundles

app/src/main/java/org/wikipedia/util/ShareUtil.java, app/src/main/java/org/wikipedia/util/UriUtil.java
This is an attempt to mitigate the issue described in https://phabricator.wikimedia.org/T231581, whereby if our current mechanism fails, it will fall back to the very standard and default way of launching a `VIEW` intent.
=> Add fallback mechanism for bouncing to external intent chooser.

app/src/main/java/org/wikipedia/Constants.java, app/src/main/java/org/wikipedia/WikipediaApp.java, app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.java, app/src/main/java/org/wikipedia/main/MainFragment.java, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsSurvey.java
Instead of having logic that is highly specific to a single survey spread throughout the app (including in the `WikipediaApp` class itself), this consolidates the logic into a self-contained helper class, which will be much easier to remove later.
This also extends the date of the survey until Sep 30, as requested in https://phabricator.wikimedia.org/T233745
=> Consolidate Survey logic into its own utility class, and extend date.

app/build.gradle
Since Facebook is quite slow at releasing a new version of Fresco with the newest version of SoLoader (which fixes a significant crash), we might as well do it ourselves for now.
=> Force dependency on latest version of SoLoader.

app/src/main/res/values/styles.xml
Here's what the buttons were looking like:
=> Fix incorrect button backgrounds in Lollipop.

app/src/main/java/org/wikipedia/page/PageActivity.java, app/src/main/java/org/wikipedia/views/ObservableWebView.java
The previous fix worked, but it introduced a few undesirable side effects (e.g. crashing when long-pressing the WebView).  This updated fix is more robust.
=> Improve fix of WebView loading on Lollipop.

app/src/main/java/org/wikipedia/activity/BaseActivity.java, app/src/main/java/org/wikipedia/page/PageActivity.java
The previous fix should have been placed in BaseActivity instead of PageActivity, so that all child activities can benefit from it.
=> Fix Lollipop WebView crash when launching edit preview.

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
Since we move the Suggested edits to the navigation tab, the `SuggestedEditsTasksFragment.kt` will be loaded if we visit `History`, and we will see an error message about "You must be logged in ..."
=> Prevent to fetch user contributions if user is not logged in

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsFragment.kt
The current one is deprecated and keeps showing a warning message in the CI build log.
https://developer.android.com/reference/androidx/fragment/app/FragmentStatePagerAdapter
=> Update the deprecated FragmentStatePagerAdapter()

app/src/main/java/org/wikipedia/language/LangLinksActivity.java, app/src/main/java/org/wikipedia/staticdata/FileAliasData.java, app/src/main/java/org/wikipedia/staticdata/MainPageNameData.java, app/src/main/java/org/wikipedia/staticdata/SpecialAliasData.java, app/src/main/res/values/languages_list.xml, scripts/generate_wiki_languages.py, scripts/make-templates.py
Very old versions of Android (e.g. API 15 or lower) used to have problems displaying Gothic characters because they are outside the Unicode BMP.  More recent versions of Android are handling this properly, so we no longer need to explicitly remove the Gothic language from our selections.
=> Stop suppressing Gothic language selection.

app/build.gradle, app/src/main/java/org/wikipedia/WikipediaApp.java
This should catch a wider range of native .so linking errors, until Fresco finally fixes things internally, or we switch to another library.
=> Fix further native linking errors in Fresco.

app/src/main/java/org/wikipedia/dataclient/mwapi/EditorTaskCounts.java, app/src/main/java/org/wikipedia/settings/Prefs.java, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt, app/src/main/java/org/wikipedia/util/DateUtil.java, app/src/main/res/layout/fragment_suggested_edits_tasks.xml, app/src/main/res/values/preference_keys.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/developer_preferences.xml
This does the heavy lifting of hooking up our logic to the new Revert counters coming from the API, and taking care of all the workflows of pausing and/or disabling the Suggested Edits feature. This also introduces a new and updated method of testing the whole feature (via developer preferences).
=> Wire up the app with new Revert counters, and update pause/disable logic.

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
If a newly created account enters the Suggested edit page, it should not show the error page to the user when the `entities.entities()` is `null`.
=> Prevent showing the error page when the user has no edits

app/src/main/java/org/wikipedia/dataclient/mwapi/EditorTaskCounts.java, app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsFeedClient.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsUserStats.kt
This will make the Suggested Edit feed cards no longer appear if the feature is paused or disabled. Note: it may be necessary to refresh the feed for the updating to take effect.
=> Make Suggested Edit feed cards dependent on paused/disabled state.

app/src/main/java/org/wikipedia/settings/DeveloperSettingsPreferenceLoader.java
Since we removed `preference_key_remote_log`, we should also remove the preference setting in preference loader to prevent crash.
=> Remove unused preference settings in preference loader

app/src/main/java/org/wikipedia/page/LinkHandler.java
Sometimes the `title` on the link does not match the `title` from the `JSONObject`, and we should check that.
https://zh.wikipedia.org/api/rest_v1/page/mobile-html/晚報
The link of `新民晚報` is `./新民晚报`, which the `報` is different with `报`
=> Fix language variants issue on LinkHandler

app/src/main/java/org/wikipedia/page/bottomcontent/BottomContentView.java
Some `displayTitle`s have `<i></i>` and the app should support that.
https://en.wikipedia.org/wiki/Jon_Favreau
=> Fix: adding HTML support on the "read more" item title

app/src/main/java/org/wikipedia/history/HistoryFragment.java, app/src/main/java/org/wikipedia/history/SearchActionModeCallback.java, app/src/main/java/org/wikipedia/language/LangLinksActivity.java, app/src/main/java/org/wikipedia/language/LanguagesListActivity.java, app/src/main/java/org/wikipedia/notifications/NotificationActivity.java, app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.java, app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.java
https://phabricator.wikimedia.org/T238349
The removed overriding method was made because of this ticket: 
https://phabricator.wikimedia.org/T188569
It would be better if we follow the default behavior.
=> Use default action mode backpress behavior on searching

app/src/main/java/org/wikipedia/main/MainFragment.java, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt, app/src/main/java/org/wikipedia/util/FeedbackUtil.java, app/src/main/res/values/strings.xml
* 8 seconds for longer-length tooltips.
* updated verbiage.
=> Final minor verbiage tweaks.

app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.java
This fixes the Chinese variant issue that the link text does not match the title on `LinkPreviewDialog`.
=> Show link preview dialog title correctly

app/src/main/java/org/wikipedia/page/PageFragment.java
The page loading is now performant enough (and doesn't have a lot of jitter) that we don't really need to hide the WebView while it loads.
=> Don't hide the WebView while loading the article.

app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java
Before we ripping out the `getConvertedText()`, we should use it when requesting endpoints.
=> User proper article title to request reset html

app/src/main/java/org/wikipedia/gallery/MediaListItem.java
The `page/media-list` has the `srcset`, which provides the image URLs and their scales. It will be used in the #546 when downloading images for offline use.
=> Add srcset data class for media-list endpoint

app/src/main/java/org/wikipedia/Constants.java, app/src/main/java/org/wikipedia/analytics/DescriptionEditFunnel.java, app/src/main/java/org/wikipedia/analytics/EditFunnel.java, app/src/main/java/org/wikipedia/analytics/SuggestedEditsFunnel.java, app/src/main/java/org/wikipedia/descriptions/DescriptionEditActivity.java, app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.java, app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.java, app/src/main/java/org/wikipedia/feed/FeedContentType.java, app/src/main/java/org/wikipedia/feed/FeedFragment.java, app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCard.kt, app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardView.kt, app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsFeedClient.kt, app/src/main/java/org/wikipedia/gallery/GalleryActivity.java, app/src/main/java/org/wikipedia/onboarding/SuggestedEditsOnboardingActivity.kt, app/src/main/java/org/wikipedia/onboarding/SuggestedEditsOnboardingFragment.kt, app/src/main/java/org/wikipedia/page/PageActivity.java, app/src/main/java/org/wikipedia/page/PageFragment.java, app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.java, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsActivity.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsFragment.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsItemFragment.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt, app/src/main/java/org/wikipedia/views/ImagePreviewDialog.kt
This does a couple of things:
- Splits off the `SUGGESTED_EDITS_...` invoke source constants into a separate `Action` enum, since these constants are not really "sources", and were conflating different types of functionality and intention.  `InvokeSource` should be generally used for analytics/funnels, and should not be used for logic and behavior.  Observe how the logic everywhere is simplified a bit.
- Endowed the `InvokeSource` constants with a string representation which can be passed directly into a funnel that accepts a string "source" parameter.
- Updated the `MobileWikiAppEdit` funnel to accept an (optional) source parameter.
=> Radically refactor InvokeSource.

app/src/main/java/org/wikipedia/main/MainFragment.java
Currently the Feed auto-scrolls back to the top every time the user returns to the feed, which is not desirable.
=> Fix: don't scroll Feed to the top every time the fragment resumes.

app/src/main/java/org/wikipedia/gallery/GalleryActivity.java
The `getItem()` is not actually `NonNull`, and maybe we should rewrite it later. 
The current solution was copied from the previous logic, and the following steps is the way of reproducing it:
1. Click on any random images to open the gallery.
2. If the image is still loading, press the back button.
3. You will see the crash log on the Logcat by searching `Gallery`.
=> Fix: press back causes a crash on GalleryActivity while the image is loading

app/src/main/res/layout/activity_gallery.xml
The icons for CC-BY-SA were not being displayed properly.
For example, go to [[Jellyfish]] and click on the lead image.
=> Fix: properly display license icons in Gallery.

app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.java
If you look closely when entering the gallery, the image fades in from a flash of white color, which looks a little jarring. This patch makes the fade look perfectly smooth from the background black color.
=> Fix: fade-in gallery images from Black instead of default (white).

app/src/main/java/org/wikipedia/feed/featured/FeaturedArticleCardView.java
The article title of the feature article on Dec 19, 2019, has a `<i></i>` tag, and we should support that.
=> Show article title HTML tag properly on the feature article card

app/src/main/java/org/wikipedia/bridge/CommunicationBridge.java
Open Barack Obama article, and click on the pronunciation link after his name, and you will see "Help:IPA/English" article. It contains a slash and it should be encoded.
=> Use encodeURL to encode special strings

app/src/main/java/org/wikipedia/database/contract/PageHistoryContract.java, app/src/main/java/org/wikipedia/database/contract/PageImageHistoryContract.java, app/src/main/java/org/wikipedia/database/contract/ReadingListPageContract.java, app/src/main/java/org/wikipedia/history/HistoryEntryDatabaseTable.java, app/src/main/java/org/wikipedia/history/UpdateHistoryTask.java, app/src/main/java/org/wikipedia/pageimages/PageImageDatabaseTable.java
At the database level, the `SELECTION` keys for retrieving History rows should still use the old `apiTitle` parameter, instead of the new `displayTitle` parameter.  This results in upgrade-related bugs, such as History items being duplicated when being visited after upgrading.
=> Follow-up / corrections to History table updates.

app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.java
Since the `PageTitle` has already contained the `namespace` when creating the `PageTitle`, we should remove the `namespace` when setting the new text to it.
=> Remove namespace when setting new API text to PageTitle in LinkPreviewDialog

app/src/main/java/org/wikipedia/theme/ThemeChooserDialog.java
The `ThemeChooserDialog` has disabled the dim background, which will make the navigation bar and status bar icons show incorrectly when in the `PageActivity`. To fix the issue, we can choose to show the default dim background only when in the `PageActivity`.
=> Prevent showing incorrect navigation bar  and status bar icons color in PageActivity

app/src/main/java/org/wikipedia/page/references/ReferenceDialog.java, app/src/main/java/org/wikipedia/util/StringUtil.java
The first reference in the article [Line_Corporation]( https://en.wikipedia.org/wiki/Line_Corporation) contains a `<style>*</style>` tag, which does not show properly.
Reference endpoint:
https://en.wikipedia.org/api/rest_v1/page/references/Line_Corporation
=> Remove style tags from HTML text

app/src/main/java/org/wikipedia/page/PageFragment.java, app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java
These are pretty old logic and should be fine to be removed.
I've tested it with some edits and it does not affect the app.
=> Remove unused variables and class from PageFragmentLoadState

app/src/main/java/org/wikipedia/analytics/FindInPageFunnel.java
https://phabricator.wikimedia.org/T147196
Just by using the new schema version, it should fix the errors that are being seen by Analytics.
(I updated the [schema](https://meta.wikimedia.org/wiki/Schema:MobileWikiAppFindInPage) to no longer require the `findText` parameter.)
=> Analytics fix: use updated FindInPage schema.

app/src/main/java/org/wikipedia/page/PageProperties.java
The current way of showing the lead image on `mobile-html` is directly showing the thumbnail size, and we should change it a proper size.
=> Show higher resolution for the lead image

app/src/main/java/org/wikipedia/page/PageFragment.java, app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java
Sometimes the `model.getPage()` will be a `null` object, and it will cause crashes.
It is often reproducible on the Chinese articles on trending.
=> Prevent crashes when loading page

app/src/main/java/org/wikipedia/page/PageProperties.java
The new way of extracting the URL from the Summary response doesn't take into account URL-encoded characters, which need to be decoded.  This breaks the functionality of being able to add image captions for the lead image.
=> Fix: correctly extract lead image URL.

app/build.gradle
This can cause Robolectric to fail if there's a newer version of okhttp cached on the testing machine.
=> Explicitly specify okhttp version to use for test builds.

app/src/main/java/org/wikipedia/settings/Prefs.java, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt, app/src/main/res/values/preference_keys.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/developer_preferences.xml
https://phabricator.wikimedia.org/T241840
=> Make the "new" text disappear after the first successful image tag edit.

app/src/main/java/org/wikipedia/dataclient/Service.java, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt
This improves the caching performance of these APIs, since we don't need the absolute freshest data from these calls every time.
=> Add explicit maxage parameter to siteInfo and siteMatrix API calls.

app/build.gradle, app/src/main/java/org/wikipedia/WikipediaApp.java, app/src/main/java/org/wikipedia/feed/FeedFragment.java, app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.java, app/src/main/java/org/wikipedia/history/HistoryFragment.java, app/src/main/java/org/wikipedia/page/ExtendedBottomSheetDialogFragment.java, app/src/main/java/org/wikipedia/page/NoDimBottomSheetDialog.java, app/src/main/java/org/wikipedia/page/PageFragment.java, app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.java
This is actually a very nice upgrade that greatly simplifies the code necessary to watch for leaks. We no longer need to manually manage our own `RefWatcher`.
=> Upgrade to LeakCanary 2.2.

app/src/main/java/org/wikipedia/dataclient/Service.java, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt
The existing Machine Vision API no longer applies the image tags to the Commons item automatically for us.  Therefore we must use the `wbsetclaim` API ourselves.  This is actually good because we will eventually need to do this anyway when we allow the user to set a "custom" tag.
=> Fix/update the API calls used for applying tags to images.

app/src/main/java/org/wikipedia/analytics/DescriptionEditFunnel.java, app/src/main/java/org/wikipedia/dataclient/Service.java, app/src/main/java/org/wikipedia/dataclient/wikidata/Entities.java, app/src/main/java/org/wikipedia/dataclient/wikidata/EntityPostResponse.java, app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.java, app/src/main/java/org/wikipedia/page/PageFragment.java, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt, app/src/main/java/org/wikipedia/suggestededits/provider/SuggestedEditItem.kt
This correctly parses the response given by Wikibase when adding descriptions or captions, so that we can get the resulting revision ID to pass to analytics, among other things.
=> Improve handling of wikibase POST responses.

app/build.gradle
This should fix certain crashes from within AppCenter, namely https://github.com/microsoft/appcenter-sdk-android/issues/1348
=> Update AppCenter sdk version.

app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.java, app/src/main/java/org/wikipedia/main/MainFragment.java, app/src/main/java/org/wikipedia/search/SearchFragment.java
This also adds a required parameter (according to the [documentation](https://developer.android.com/reference/android/speech/RecognizerIntent#ACTION_RECOGNIZE_SPEECH)) for launching the Voice input dialog, which may fix some obscure errors:
https://phabricator.wikimedia.org/T246515
=> Fix potential crash upon starting Search fragment.

app/src/main/java/org/wikipedia/page/PageCacher.java
The `PageCacher` is a weird class that is only used when the user loads a title in a new tab. It automatically fetches the PageSummary for that title, and injects the thumbnail for the title into the Tab structure.  However, it was also loading the full `mobile-html` contents for the title, apparently for no reason.
=> Don't request full page contents in PageCacher.

app/src/main/java/org/wikipedia/bridge/CommunicationBridge.java, app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt, app/src/main/java/org/wikipedia/dataclient/RestService.java, app/src/main/java/org/wikipedia/dataclient/ServiceFactory.java, app/src/main/java/org/wikipedia/edit/preview/EditPreviewFragment.java, app/src/main/java/org/wikipedia/page/PageCacher.java, app/src/main/java/org/wikipedia/page/PageFragment.java, app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java, app/src/main/java/org/wikipedia/savedpages/SavedPageSyncService.java, app/src/main/java/org/wikipedia/util/SavedPagesConversionUtil.java
Currently if we override the base REST url in developer settings, it won't actually take effect for `mobile-html` calls.
=> Make mobile-html calls work correctly with developer base URL.

app/src/main/java/org/wikipedia/page/shareafact/ShareHandler.java, app/src/main/java/org/wikipedia/page/shareafact/SnippetImage.java
Some display titles include HTML tags. This patch ensures that
(1) the visible title does not show HTML tags anymore and
(2) the file name used for sharing an image does not include HTML tags.
Bug: https://phabricator.wikimedia.org/T246847
=> Hide HTML tags from title in Share-a-fact

app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCard.kt, app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardView.kt
Not seeing the date string subtitle and correct language indicator on the translate cards. This should update them correctly.
=> Add subtitle to suggested edits explore feed cards

app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
Fixes missing "Read More" items in the footer
=> Remove trailing slashes from baseURL

app/src/main/java/org/wikipedia/util/L10nUtil.java
Looks like we don't have to show the language count on the footer anymore.
=> Remove unused language count method

app/src/main/res/layout/view_suggested_edit_card.xml
**Phab:** https://phabricator.wikimedia.org/T244866
The margin needs to be on the title view, because, we need to hide the margin when the view is hidden, otherwise we will have an unnecessary top margin.
=> Minor margin fix for ImageTag feed card

app/src/main/java/org/wikipedia/bridge/CommunicationBridge.java
The messages passed to us by mobile-html are bound to change in the future in unexpected ways, which can cause our bridge handlers to crash.  Instead of crashing in production, let's just log the exceptions remotely.
=> Harden bridge handlers against deserialization errors.

app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.java
Since we are fetching the summary endpoint for correct `displayTitle`, we should use it on the preview dialog.
=> Show preview dialog title in the correct language variant

app/src/main/java/org/wikipedia/activity/BaseActivity.java, app/src/main/java/org/wikipedia/navtab/NavTabLayout.kt
You see, when we create the bottom navigation items, the "index" that we pass into the `add()` function will actually become the `id` of the resulting View.  So, if we pass an index of 1, the view will have an id of `id/0x1`, which can conflict with the id that `ViewPager2` automatically assigns to its `RecyclerView`.
This change will start using the `View.generateViewId()` function instead, so that it's guaranteed to no longer conflict with any other View id.
Even though I haven't been able to reproduce the actual crash reliably, I'm hopeful that this is the correct fix.
=> Possibly fix elusive saveInstanceState bug!

app/build.gradle, app/src/main/java/org/wikipedia/settings/Prefs.java
This allows for `labsPCS` and `localPCS` build variants. I added it as a separate loop to avoid having to declare it for each variant. I initially implemented `labsPCS` and `localPCS` as `buildTypes` with `initWith buildTypes.debug` and an override for `DEFAULT_RESTBASE_URI_FORMAT`, but a warning was thrown on every build about overriding the value for `DEFAULT_RESTBASE_URI_FORMAT`. Open to suggestions on different ways to implement this.
=> Add DEFAULT_RESTBASE_URI_FORMAT as a buildConfigField 

app/src/main/res/values/strings.xml
This word is usually unnecessary. See
https://www.mediawiki.org/wiki/Localisation#Avoid_jargon_and_slang
=> Removed "successfully" from several messages

app/src/main/java/org/wikipedia/edit/EditHandler.java, app/src/main/java/org/wikipedia/page/PageFragment.java, app/src/main/java/org/wikipedia/page/ToCHandler.java
If you exiting an article while loading and then enter another article so quickly, you will get a chance to see a crash. 
```
2020-03-31 14:08:13.840 31057-31057/org.wikipedia.dev W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List org.wikipedia.page.Page.getSections()' on a null object reference
2020-03-31 14:08:13.840 31057-31057/org.wikipedia.dev W/System.err:     at org.wikipedia.page.ToCHandler$ToCAdapter.setPage(ToCHandler.java:233)
2020-03-31 14:08:13.840 31057-31057/org.wikipedia.dev W/System.err:     at org.wikipedia.page.ToCHandler.setupToC(ToCHandler.java:134)
2020-03-31 14:08:13.840 31057-31057/org.wikipedia.dev W/System.err:     at org.wikipedia.page.PageFragment.lambda$null$10$PageFragment(PageFragment.java:991)
2020-03-31 …
```
=> Fix potential crashes when getting the section list from Page

app/src/main/java/org/wikipedia/feed/FeedCoordinatorBase.java
If you keep scrolling to the bottom of the feed, you will see certain feed cards like `SuggestedEditsFeedCard` or `BecauseYouReadCard`  require a longer time on loading.
=> Show progressCard when requesting APIs on the Feed

app/src/main/java/org/wikipedia/page/PageActivity.java
Since the doesn't show `SearchView` on the `PageActivity`, it should be safe to remove the `onSearchRequested()`. This PR also updates the `openSearchActivity()` because it is always sending `TOOLBAR` for `InvokeSource` and `null` for the query.
=> Remove onSearchRequested() from PageActivity

app/src/main/java/org/wikipedia/feed/featured/FeaturedArticleCardView.java, app/src/main/res/layout/view_card_featured_article.xml
Today's (2020/04/08) featured article card shows an empty `ImageView`, which is also reproducible on the production app, and we should fix it.
=> Prevent showing empty ImageView on featured article card

app/src/main/java/org/wikipedia/page/PageActivity.java, app/src/main/java/org/wikipedia/page/shareafact/ShareHandler.java
Notice that we only show the Wiktionary dialog for English articles, because we don't yet have the capability of parsing non-English Wiktionary pages. Therefore, we should only remove the system-provided Define option for non-English articles.
=> Quick follow-up: remove Define item only for non-English articles.

app/build.gradle, app/src/main/java/org/wikipedia/gallery/GalleryActivity.java, app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.java, app/src/main/res/layout/fragment_gallery_item.xml, build.gradle
After the switchover to Glide, the zooming functionality in the Gallery was relying on our custom pinch-to-zoom function, which snaps the image back when the pinch is released. This is not desirable, since we want the image to remain zoomed after pinching.
This PR adds the `PhotoView` component, which is a very popular component precisely for zooming ImageViews..  We were actually going to use this component a long time ago, but it's not compatible with Fresco, which is why we couldn't use it.
P.S. After including this library, our method count is still about 42000, so we're still good for a while.
=> Use PhotoView in the Gallery for zooming images.

app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
Sometimes articles have section titles with quotes in them. Currently when clicking on such a section in the Table of Contents does not correctly cause the WebView to scroll to the section.
For example, in the [[Howard Dean]] article, try clicking the section `Iowa Caucus setback and the "Dean Scream" media gaffe`.
=> Fix encoding of quotes in ToC section titles.

app/src/main/java/org/wikipedia/views/LinearLayoutOverWebView.java
Currently, if you touch to scroll the lead image, it scrolls without any account for touchSlop. (in other words, it scrolls too readily, which makes it inconsistent with the rest of the WebView.)
=> Correctly use touchSlop when scrolling over WebView.

app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
If you disable loading images (in Settings) and then go to an article, we make space for the lead image at the top, which will never get loaded and remain blank unnecessarily.
=> When image loading is disabled, don't reserve top-margin space.

app/src/main/res/layout/date_picker_dialog.xml
The right-most day items in the date picker dialog touch to the edge and the blue circles are cut off.
=> Adjust date picker dialog width to prevent being cut off

app/src/main/java/org/wikipedia/edit/EditSectionActivity.java, app/src/main/java/org/wikipedia/page/PageActivity.java, app/src/main/java/org/wikipedia/settings/Prefs.java, app/src/main/res/values/preference_keys.xml
This may fix the issue here: https://phabricator.wikimedia.org/T242449#6073882
For a really long wikitext section, the app will crash when using the app switcher and going back to the app. If we want to keep the edit states, saving them into the `SharedPreferences` might be a way to solve the `TransactionTooLargeException` error.
=> Store wikitext section into SharedPreferences temporarily to prevent a crash

app/src/main/java/org/wikipedia/createaccount/CreateAccountActivity.java, app/src/main/java/org/wikipedia/dataclient/mwapi/ListUserResponse.java
When the user types their username to create an account, we automatically check if that username is available or taken, and we show the message as the user is typing.  However, if the user's IP address is blocked, then we still show a message of "this username is not available," instead of properly saying "your IP address is blocked".  This can surely cause confusion while the user keeps trying to type their new username.
=> Fix possible confusion in account creation errors.

app/src/main/java/org/wikipedia/bridge/CommunicationBridge.java, app/src/main/java/org/wikipedia/edit/preview/EditPreviewFragment.java, app/src/main/java/org/wikipedia/page/PageFragment.java, app/src/main/java/org/wikipedia/views/ObservableWebView.java
Currently, it's not at all obvious that the `clearAllListeners()` function will _also_ load a blank page into the WebView. This PR makes this behavior more explicit, and moves more cleanup code into the Bridge.
=> Be slightly more explicit about loading blank page into WebView.

app/src/main/java/org/wikipedia/readinglist/ReadingListBehaviorsUtil.kt
Use Kotlin's `filter` and `any` functions to simplify the filtering operation in getListsContainPage().
This makes the code more idiomatic and allows the function to be declared as a single expression function.
=> Rewrite ReadingListBehaviorsUtil.getListsContainPage() using standard Kotlin functions.

app/src/main/java/org/wikipedia/edit/preview/EditPreviewFragment.java
Edit article -> preview the changes -> go back to edit screen -> cancel edit
=> Fix: set webview to null to prevent crash when EditPreviewFragment got destroyed

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt, app/src/main/res/values/strings.xml
https://phabricator.wikimedia.org/T251911
Note: this still uses the Machine Vision suggestions for the actual images that are served as image tagging candidates.  An additional PR may be coming to switch over to a purely random search from Commons.
=> Remove CAT suggestions from Image Tags.

app/src/main/res/layout/dialog_image_preview.xml
This is a temporary fix and a better optimization is in #1157.
=> Temporary fix of not showing images in the image preview dialog

app/src/main/java/org/wikipedia/edit/EditSectionActivity.java, app/src/main/java/org/wikipedia/util/FeedbackUtil.java
Related ticket: https://phabricator.wikimedia.org/T235028
Since the message and status are the same, we should share the logic. The `boolean` value of the method will be used when getting the response from #1216 and update the edit pencil in `GalleryActivity` and suggested edits CTA in the lead image.
=> Move the logic of showing protection status message to FeedbackUtil

app/src/main/java/org/wikipedia/readinglist/AddToReadingListDialog.java, app/src/main/java/org/wikipedia/readinglist/database/ReadingListDbHelper.java, app/src/test/java/org/wikipedia/readinglist/database/ReadingListDbHelperTest.java
**Phab:** https://phabricator.wikimedia.org/T166462
Only one of the cases has a wrong plural message : 
Adding many articles from one list to another, where only one article did not exist in the new list. 
Previous message :  
"Added 1 articles to 'list'" 
To match with existing messages, new message : 
"Added %articleName to 'list'
Details on phab ticket.
=> Handling plurals in ReadingList messages

app/src/main/res/layout/fragment_suggested_edits_tasks.xml
The current `progressbar` should show on the top of the `NestedScrollView`, otherwise, it will be a little bit weird if the view scrolls to the top after content updated.
This PR just creates a `FrameLayout` and arranges the `NestedScrollView` and `ProgressBar`.
=> Show progressbar correctly in the Suggested edits task screen

app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.java
When adding a caption in a different language from the "Add caption" prompt in the lead image, the captions are sometimes going to the incorrect language.
=> Priority: fix incorrect target language when translating descriptions/captions.

app/src/main/java/org/wikipedia/bridge/CommunicationBridge.java, app/src/main/java/org/wikipedia/edit/preview/EditPreviewFragment.java, app/src/main/java/org/wikipedia/savedpages/SavedPageSyncService.java
When making requests to the `mobile-html` endpoint, we need to explicitly encode the title before it goes into the interceptor chain.  The new TitleEncodeInterceptor is supposed to encode the title transparently, but it operates on path segments -- but when a title contains slashes, it gets treated as multiple path segments.
This should have no additional impact on loading other articles, with any other special characters.
=> Priority: fix loading of articles with slash in title.

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagDialog.kt
https://appcenter.ms/orgs/ci-apps-hockeyapp-f5mf/apps/Wikipedia/crashes/errors/3007784083u/overview
=> Prevent possible crash when searching for image tag labels.

app/src/main/java/org/wikipedia/views/FaceAndColorDetectImageView.java, app/src/main/java/org/wikipedia/views/ViewUtil.java
Images loaded in the Gallery must be properly downsampled. Otherwise, certain images (especially ones with a highly eccentric aspect ratio) will be upscaled beyond the memory limits of the VM.
https://appcenter.ms/orgs/ci-apps-hockeyapp-f5mf/apps/Wikipedia/crashes/errors/3506720188u/overview
=> Fix possible out-of-memory conditions when loading large images.

app/src/main/java/org/wikipedia/search/SearchFragment.java, app/src/main/java/org/wikipedia/views/FindInPageActionProvider.java, app/src/main/java/org/wikipedia/views/SearchActionProvider.java
Open search screen -> search something -> tap first article -> tap system "back" button -> tap system "back" button again to hide the keyboard -> see a translucent cover.
=> Fix: prevent showing a translucent cover when losing focus on searchView

app/src/main/java/org/wikipedia/commons/FilePageFragment.kt, app/src/main/java/org/wikipedia/views/ImagePreviewDialog.kt
If the file is protected, then we should not show the edit pencil in the file page. This PR also makes the global `private` variables to local variables.
=> Use local variables and hide edit pencil if protected in FilePage and ImagePreviewDialog

app/src/main/res/layout/view_card_header.xml
In Chromebook, the feed cards are smaller and the views may overlap with each other. For example, the feed card that shows Suggested edits add image caption with `zh-hant` language code.
=> Constraint views correctly to prevent views overlap

app/src/main/java/org/wikipedia/bridge/CommunicationBridge.java, app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt, app/src/main/java/org/wikipedia/dataclient/okhttp/OkHttpWebViewClient.java, app/src/main/java/org/wikipedia/edit/preview/EditPreviewFragment.java, app/src/main/java/org/wikipedia/page/PageFragment.java, app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java, app/src/main/java/org/wikipedia/page/PageTitle.java, app/src/main/java/org/wikipedia/page/PageViewModel.java
Thanks to some ideas from @joewalsh, we shall now load the Main Page (of any language wiki) by literally loading the mobile web URL into the WebView. (this is in fact what the iOS app does.)
This has a couple of drawbacks:
* It will only appear in the Light theme (i.e. will ignore the user's theme selection).
* The Main Page of many wikis often has links to various Special and Portal pages that may also render weirdly in the app.
* The Main Page won't have the other affordances that other pages have, such as the table of contents, collapsible tables, etc.
...But at least this will allow us to present the Main Page to users who need it, making sure it's formatted correctly because we're leveraging mobile web, instead of the still-evolving parsoid `page/html` API.
=> Load Main Page(s) via Mobile Web instead of via API.

app/src/main/res/values-ar/strings.xml, app/src/main/res/values-ckb/strings.xml, app/src/main/res/values-fa/strings.xml, app/src/main/res/values-iw/strings.xml, app/src/main/res/values-sd/strings.xml, app/src/main/res/values/strings.xml
https://phabricator.wikimedia.org/T253486#6244764
I manually added the translated "Hi" to the RTL languages that potentially have the issue. (with Google translate's help).
=> Fix: RTL language texts do not show properly in the SE tooltip

app/src/main/res/values/styles.xml
It shows a purple color as the status bar background and it looks really weird.
The emulator runs API 21:
=> Set default status bar color to black for < API 23 devices

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsContributionDetailsFragment.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsContributionsFragment.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsContributionsItemView.kt, app/src/main/res/values-qq/strings.xml, app/src/main/res/values/strings.xml
This fixes a few important details that were incorrect in the original PR:
* Old image tag contributions (made using the old single-contribution scheme) were being shown as "0 tags added".
* The incorrect number of added/removed characters was being shown for descriptions and captions.
* Improved the logic for formatting positive/negative numbers, without needing an explicit sign placeholder.
=> Follow-up to contributions detail screen.

app/src/main/java/org/wikipedia/dataclient/mwapi/UserInfo.java
It will show the error message below if it is a newly created account:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
at java.text.SimpleDateFormat.parseInternal(SimpleDateFormat.java:1739)
at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1726)
at java.text.DateFormat.parse(DateFormat.java:360)
at org.wikipedia.util.DateUtil.iso8601DateParse(DateUtil.java:34)
at org.wikipedia.dataclient.mwapi.UserInfo.getLatestContrib(UserInfo.java:45)
at org.wikipedia.suggestededits.SuggestedEditsTasksFragment$fetchUserContributions$1.apply(SuggestedEditsTasksFragment.kt:157)
at org.wikipedia.suggestededits.SuggestedEditsTasksFragment$fetchUserContributions$1.apply(SuggestedEditsTasksFragment.kt:43)
```
=> Prevent showing error page if latestcontrib is empty in SE task screen

app/src/main/java/org/wikipedia/main/MainFragment.java, app/src/main/res/layout/fragment_main.xml
If we search the history, you will see the "more" menu is still visible, which is incorrect.
=> Fix: should hide all nav menus when searching history

app/src/main/java/org/wikipedia/dataclient/okhttp/CommonHeaderRequestInterceptor.kt
We've just realized that the apps' accessing of the `mobile-html` endpoint isn't actually counting as a pageview by the Analytics backend. We need to explicitly send an `X-Analytics` header so that the pageview is counted.
=> Explicitly set X-Analytics header for correct accounting of pageviews.

app/src/main/java/org/wikipedia/feed/news/NewsListCardView.java, app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayCardView.java, app/src/main/java/org/wikipedia/feed/view/DefaultFeedCardView.java, app/src/main/res/layout/view_card_on_this_day.xml
If you watch closely, the "more on this day" bottom action layout has `paper_color` background and makes the rounded border has a rectangle background. This PR fixes it but still has a minor issue: the ripple animation is still in a square shape. 
Please advise if any suggestions.
=> Tweak: set up "more on this day" background correctly

app/src/main/java/org/wikipedia/feed/announcement/AnnouncementCardView.java
Announcement cards that don't have an explicit `border` should not override the `strokeWidth` of the card.
=> Don't override inactive border for Announcement cards.

app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.java, app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayFragment.java, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/date_picker_dialog.xml, app/src/main/res/layout/fragment_contribution_diff_detail.xml, app/src/main/res/layout/fragment_on_this_day.xml, app/src/main/res/layout/view_description_edit.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/styles.xml, app/src/main/res/values/styles_dark.xml, app/src/main/res/values/styles_light.xml
Just noticed that the `toolbar_title_color` has the same color set as `material_theme_primary_color`, and we can remove it.
=> Remove toolbar_title_color and replace it with material_theme_primary_color

app/src/main/java/org/wikipedia/notifications/NotificationPollBroadcastReceiver.java
This is contributing to a lot of noise in AppCenter, and doesn't really need to be logged anymore.
=> Don't log nuisance exception in Notification receiver.

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt
The crash happens because we're modifying a list while iterating it using a foreach structure. Reproducible by adding multiple tags, then unselecting all but one tag, then publishing.
=> Fix possible crash when adding multiple image tags.

app/src/main/java/org/wikipedia/main/MainFragment.java
This issue happens when rotating the device.
=>  Should re-select tab to prevent losing current activated tab.

app/src/main/java/org/wikipedia/feed/mostread/MostReadItemCard.java
https://phabricator.wikimedia.org/T194161
The API is fixed and now we can show the title correctly.
=> Fix: set PageTitle correctly to show the correct displayTitle in MOstReadItemCard

app/build.gradle
`com.android.installreferrer:installreferrer` from `1.1.2` to `2.1`
`androidx.drawerlayout:drawerlayout` is in the stable `1.1.0`
=> Update installreferrer to 2.1 and drawerlayout to 1.1.0

app/src/main/java/org/wikipedia/main/MainFragment.java
This code was removed accidentally in the #1297.
=> Fix: should not scroll the feed to top if not manually tap on the nav item

app/src/main/java/org/wikipedia/views/CustomDatePicker.java
The button color in the current production is purple, which does not align with our app theme guideline. The default theme should be better.
=> Use default dialog theme in CustomDatePicker

app/src/test/java/org/wikipedia/language/TranslationTests.java
Sometimes the build failed because we forgot to add newly created string items to the `qq/strings.xml`. This test case will show us a more specific error message in the Travis build log.
=> Add a test case of checking the resources in qq/strings.xml match en/strings.xml

app/src/main/java/org/wikipedia/readinglist/sync/ReadingListSyncAdapter.java
Otherwise, the snackbar will not appear.
=> Should disable the SE highest priority when manually refreshing the reading list

app/src/main/java/org/wikipedia/page/PageActivity.java, app/src/main/java/org/wikipedia/page/PageFragment.java, app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java, app/src/main/res/layout/activity_page.xml
- The `ProgressBar` is always `indeterminate=true`.
- When loading page that requires more time to load (e.g. Chinese article - [2019冠状病毒病疫情](https://zh.wikipedia.org/wiki/2019%E5%86%A0%E7%8A%B6%E7%97%85%E6%AF%92%E7%97%85%E7%96%AB%E6%83%85)), the progress bar should disappear after the metadata is loaded.
=> Hygiene: optimize progress bar method

app/src/main/java/org/wikipedia/activity/BaseActivity.java, app/src/main/java/org/wikipedia/readinglist/database/ReadingListDbHelper.java, app/src/main/java/org/wikipedia/readinglist/sync/ReadingListSyncAdapter.java, app/src/main/java/org/wikipedia/readinglist/sync/ReadingListSyncEvent.java, app/src/main/java/org/wikipedia/savedpages/SavedPageSyncService.java
The updates in #1397 totally changed the behavior of when the snackbar is shown -- it's now being shown for every page added to a list.  The snackbar should only be shown when the user explicitly refreshes the lists.
=> Fix logic of when to show Reading List sync snackbar.

app/src/main/java/org/wikipedia/commons/FilePageView.kt
It is reproducible in today's (07/14/2020) featured image. The content after "Artist" is empty.
=> Fix: use proper language code in FilePage to avoid empty content

app/src/main/java/org/wikipedia/feed/FeedFragment.java, app/src/main/java/org/wikipedia/feed/configure/ConfigureActivity.java, app/src/main/java/org/wikipedia/feed/configure/ConfigureFragment.java, app/src/main/java/org/wikipedia/main/MainFragment.java, app/src/main/java/org/wikipedia/settings/SettingsActivity.java, app/src/main/java/org/wikipedia/settings/languages/WikipediaLanguagesFragment.java
- Should refresh the feed after we tapped on the "Customize" button on the onboarding card in the explore feed
- Should refresh the feed after we went to the Settings -> "Wikipedia languages" or "Explore feed"
=> Refresh feed after updated app languages or updated feed config

app/src/main/res/drawable/ic_translate_white_24dp.xml
The "文" character should not be auto mirrored, otherwise, it would be super weird to people who recognize it.
=> Translate icon should not be autoMirrored

app/src/main/java/org/wikipedia/descriptions/DescriptionEditReviewView.kt, app/src/main/res/layout/view_description_edit_review.xml
If you try to review the image caption in the "review image caption" screen, the image will be cropped in the first time of visiting the review screen.
=> Fix: make sure image in the image caption review screen shows the entire image

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
If we switch between different tabs, the screen should remain in the previous position.
Please note this PR also removes unused/unnecessary import.
=> Don't always scroll to the top in the SE task screen

app/src/main/java/org/wikipedia/navtab/MenuNavTabDialog.java, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTypeItem.kt
Replace uses of `ContextCompat.getDrawable()` with `Context.getDrawable()`, as the minimum API level (Lollipop) supports the method.
=> Remove usages of ContextCompat.getDrawable().

app/src/main/java/org/wikipedia/commons/ImageTagsProvider.kt, app/src/main/java/org/wikipedia/dataclient/Service.java
If image has claims other than P180, ImageTagsProvider.kt doesn't count them. Filtering them at the api call level corrects this.
Ex: https://commons.wikimedia.org/w/api.php?format=json&formatversion=2&errorformat=plaintext&action=wbgetclaims&entity=M87877968
tags count is 0.
=> Filter claims by P180

app/src/main/java/org/wikipedia/feed/view/ListCardView.java, app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.java, app/src/main/java/org/wikipedia/views/DrawableItemDecoration.kt
Since we remove the elevation from the action bar, it would be better if we also remove the first divider on the first item and make it as a default setting in `DrawableItemDecoration `
=> Update DrawableItemDecoration default setting to make dividers having consistent rules

app/src/main/java/org/wikipedia/page/PageFragment.java
1. Tap on any Chinese article that has a lead image.
2. While the page is not completely loaded, click on the lead image
The reason why causes error is because the revision is still using the revision from the last page.
=> Fix: reset page revision to prevent loading media-list incorrectly

app/src/main/res/layout/activity_gallery.xml
If we see the `WikiErrorView` in the Gallery, we will not be able to click the "back" button.
=> Fix: make sure buttons in WikiErrorView are clickable in Gallery

app/src/main/res/layout/fragment_news.xml
If we don't apply a background color to the list explicitly, we will see the divider color after returning to the Explore feed from the news list screen.
=> Add news list background color to prevent incorrect transition animation

app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.java
Not sure why we are using the `getTitleOriginal()` here, but it causes a language variant issue.
1. Open https://en.wikipedia.org/wiki/Permanent_members_of_the_United_Nations_Security_Council in `Traditional Chinese`
2. Click on [聯合國安全理事會](https://zh.wikipedia.org/wiki/%E8%81%94%E5%90%88%E5%9B%BD%E5%AE%89%E5%85%A8%E7%90%86%E4%BA%8B%E4%BC%9A) in the first paragraph
3. Click on the lead image and will see the error message
=> Fix: prevent using incorrect page title to fetch media-list

app/src/main/java/org/wikipedia/page/PageFragment.java
The progress icon will be covered by the toolbar if the article has no lead image.
=> Update the additional offset for refresh spinner in PageFragment

app/src/main/java/org/wikipedia/page/PageFragment.java
A similar issue as #1490. Found that if we turn off the link preview, it will use the incorrect title to request endpoint when loading the Gallery sometimes. 
1. Turn off link preview in settings.
2. Go to https://en.wikipedia.org/wiki/List_of_countries_by_military_expenditures in Traditional Chinese
3. Click on [開發中國家] in-article link in the first paragraph. 
4. Click on the first image in article.
=> Fix: replace getTitleOriginal() with getTitle() to prevent failing on loading media-list

app/src/main/java/org/wikipedia/page/PageActivity.java, app/src/main/java/org/wikipedia/page/PageFragment.java
The change made in #1494 is not exactly right. It does not take into account the fact that the system window insets can be variable, and are not always exactly `24dp`. This correctly leverages the inset callback to set the refresh offset.
=> Correctly set offset for Refresh spinner.

app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.java
**Bug:** https://youtu.be/1zFVuMov5o8
When there are more than 100 search result items also, the "Can\'t create another list. You\'ve reached the limit of 100 reading lists per account" message is getting triggered. This fixes that issue.
=> Fix: Reading list limit message bug

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
Otherwise, the reverted edits count will always be `0`.
=> Follow up: set up UserStats tooltips with the updated user stats

app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.java, app/src/main/java/org/wikipedia/feed/searchbar/SearchCardView.java, app/src/main/java/org/wikipedia/main/MainActivity.java, app/src/main/java/org/wikipedia/main/MainFragment.java, app/src/main/java/org/wikipedia/page/PageActionTabLayout.kt, app/src/main/java/org/wikipedia/page/PageActivity.java, app/src/main/java/org/wikipedia/page/tabs/TabActivity.java, app/src/main/java/org/wikipedia/random/RandomFragment.java, app/src/main/java/org/wikipedia/search/RecentSearchesFragment.java, app/src/main/java/org/wikipedia/search/SearchFragment.java, app/src/main/java/org/wikipedia/theme/ThemeChooserDialog.java, app/src/main/java/org/wikipedia/util/FeedbackUtil.java, app/src/main/java/org/wikipedia/views/CabSearchView.java, app/src/main/java/org/wikipedia/views/PageActionOverflowView.java, app/src/main/java/org/wikipedia/views/PageItemView.java, app/src/main/java/org/wikipedia/views/WikitextKeyboardButtonView.java
Since the `setToolbarButtonLongPressToast()` is not only used on toolbar buttons, we may need to update it to a more generic name.
=> Rename the long press toast method with a proper name

app/src/main/java/org/wikipedia/random/BottomViewBehavior.java
The issue can be reproduced in the Randomizer when adding an article to the reading list.
=> Fix: view does not go back to its original position after snackbar dismissed

app/src/main/res/layout/fragment_onboarding_pager.xml, app/src/main/res/layout/fragment_references_pager.xml
https://phabricator.wikimedia.org/T259892
This also applies the correct ripple color to the `TabLayout`. If you re-tap on the selected indicator in `ReferenceDialog`, you'll see the purple ripple color, which is incorrect.
=> Change TabLayout background to prevent incorrect color in certain devices

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt, app/src/main/java/org/wikipedia/util/FeedbackUtil.java, app/src/main/java/org/wikipedia/views/ImageTitleDescriptionView.kt
Need this to be configurable for cases like https://phabricator.wikimedia.org/T259717 where the arrow needs to be show in a different orientation based on the balloon position
=> Making arrow orientation in tooltip configurable

app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
Mobile-html has been updated to no longer require the `title` parameter when building the Footer structure.
https://phabricator.wikimedia.org/T255579
=> Remove 'title' parameter from footer call.

app/src/main/java/org/wikipedia/commons/FilePageView.kt
It prevents showing incomplete content in the FilePage.
1. Find a non-English article with a lead image.
2. Go to the gallery and find images that require image tags.
3. Add image tags in English.
=> Fix: add image tags null check in FilePageView

app/src/main/java/org/wikipedia/history/HistoryFragment.java, app/src/main/java/org/wikipedia/notifications/NotificationActivity.java, app/src/main/java/org/wikipedia/readinglist/ReadingListBehaviorsUtil.kt, app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.java, app/src/main/java/org/wikipedia/readinglist/ReadingListItemView.java, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsFragment.kt, app/src/main/java/org/wikipedia/userprofile/ContributionsHeaderView.kt, app/src/main/res/values-qq/strings.xml, app/src/main/res/values/strings.xml
https://phabricator.wikimedia.org/T260575
Note that this leaves the old `strings` resources in place until the next TWN sync, so that there's no confusion on the TWN side with renaming and copying strings, which would break our code.
=> Transform several strings to plurals.

app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.java
The latest Material library (1.2.0) broke the automatic handling of the error-color of the `TextInputLayout`, so now we have to set the color of the bottom line manually.
=> Fix TextInputLayout error color to comply with latest Material library.

app/src/main/java/org/wikipedia/util/UriUtil.java
https://phabricator.wikimedia.org/T260684
=> Update isValidPageLink() to avoid showing long-press dialog on "add article description" CTA

app/src/main/java/org/wikipedia/search/SearchResultsFragment.java
If the search results is less than 20 items and the last item is visible, the app will keep calling `doFullTextSearch()`.
=> Fix: prevent doing doFullTextSearch() infinitely in the SearchResultsFragment

app/src/main/java/org/wikipedia/commons/FilePageView.kt, app/src/main/java/org/wikipedia/dataclient/Service.java, app/src/main/java/org/wikipedia/dataclient/mwapi/MwPostResponse.java, app/src/main/java/org/wikipedia/feed/FeedFragment.java, app/src/main/java/org/wikipedia/gallery/GalleryActivity.java, app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.java, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagEditActivity.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt
Currently we're not tracking the `invokeSource` for the Image Tags activity.  This will help us do analytics on the sources from which the user reaches the Image Tags screen.
We were also incorrectly trying to get the last revision-id from the response structure.
=> Correctly wire up tracking of invokeSource for Image Tags.

app/src/main/java/org/wikipedia/commons/FilePageFragment.kt, app/src/main/java/org/wikipedia/commons/FilePageView.kt, app/src/main/java/org/wikipedia/navtab/NavTabLayout.kt, app/src/main/java/org/wikipedia/onboarding/OnboardingPageView.kt, app/src/main/java/org/wikipedia/page/PageActionTabLayout.kt, app/src/main/java/org/wikipedia/readinglist/ReadingListBehaviorsUtil.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsFragment.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagDialog.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTypeItemView.kt, app/src/main/java/org/wikipedia/userprofile/ContributionsFragment.kt, app/src/main/java/org/wikipedia/userprofile/ContributionsItemView.kt, app/src/main/java/org/wikipedia/views/AppTextViewWithImages.kt, app/src/main/java/org/wikipedia/views/ImageTitleDescriptionView.kt, app/src/main/java/org/wikipedia/views/MessageCardView.kt
Since we don't have implemented `checkstyle` plugin for Kotlin files yet, it is easy to forget to remove unused imports from Kotlin files.
=> Hygiene: remove unused imports, redundant code and use getDrawable() properly in Kotlin files

app/src/main/java/org/wikipedia/search/SearchResultsFragment.java
This performs the time delay using pure Rx functions, and no more `post`ing.
This also bumps the delay to 500ms. This will be imperceptible to the user, but will save a lot of unnecessary network traffic.
=> Follow-up: Further simplify logic of performing search.

app/src/main/java/org/wikipedia/page/PageToolbarHideHandler.java
> 01) To be consistent with other areas of the app, please remove the app bar shadow on article pages with no header image.
https://phabricator.wikimedia.org/T260871
=> Don't show the toolbar elevation if the content reaches to the top

app/src/main/java/org/wikipedia/dataclient/Service.java, app/src/main/java/org/wikipedia/userprofile/ContributionsFragment.kt
It is because of some article only contains the `zh` article title in the API responses, and we should show it instead of showing the QNumber.
**Actual**
**Expected**
=> Fix: the article description contribution list does not show the article title correctly

app/src/main/AndroidManifest.xml
Reverts wikimedia/apps-android-wikipedia#1586
There are very specific and extremely important reasons why `PageActivity` is set to be `singleTask`.
This would introduce much more confusion than the issue that it attempts to fix.
=> Revert "Launch PageActivity in default mode to maintain back-stack as expected"

app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.java
In the current master, we set the RTL support for the summary view only. Since the user will mostly input RTL text for the RTL articles, it would be a good idea to give the input field the RTL support.
=> Set RTL support for the input field in the edit description view

app/src/main/java/org/wikipedia/commons/FilePageFragment.kt, app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsFeedClient.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt, app/src/main/java/org/wikipedia/suggestededits/provider/EditingSuggestionsProvider.kt, app/src/main/java/org/wikipedia/userprofile/ContributionsFragment.kt
Looks like the previous building failure issue has been fixed, now we can remove the redundant code from this file.
=> Hygiene: remove redundant code and optimize warning in Kotlin files

app/src/main/java/org/wikipedia/page/PageFragment.java
From the previous PR #1581, the revision is actually a string "null", and we should add it to the if statement. Otherwise, we will still see the error message in the log.
=> Follow up: add revision "null" string check

app/src/main/java/org/wikipedia/userprofile/Contribution.kt, app/src/main/java/org/wikipedia/userprofile/ContributionDetailsFragment.kt, app/src/main/java/org/wikipedia/userprofile/ContributionsFragment.kt
The previous PR (#1588) does not fix the page title correctly for some articles.
For example, https://www.wikidata.org/wiki/Q24284283
The `label` is `花木兰`, but when we opening a page it will open an incorrect page because the page title matches the `label`.
The correct page title should be `花木兰 (2020年电影)`,  which is in the `sitelinks`.
Also, since we already have called the `getSummary()`, we can update the page title with the correct one.
This PR also updates the `Contribution` class to have both `apiTitle` and `displayTitle` to prevent possible language variant issues.
=> Fix: show proper page title in the contribution list

app/src/main/java/org/wikipedia/gallery/GalleryActivity.java
Not sure why we are using `getAppOrSystemLanguageCode()` for finding caption from the `getCaptions()` and also getting image tags.
There's an issue when translating caption in the Gallery, here are the steps of reproducing:
1. Have two app languages setup. e.g. `Traditional Chinese` and `English`.
2. Go to the gallery and find an image that does not have the image captions in both languages.
3. Add an image caption for `Traditional Chinese`.
4. Now you'll see "ADD IMAGE CAPTION (ENGLISH)`, and click on the button to add the translation.
5. In the  `Image caption(繁體中文)` summary field, it shows the original image description of the image.
**Expected:**
We should see the `Traditional Chinese` image caption we just added in `Image caption(繁體中文)` summary field
=> Fix: use correct language code for source caption/tags

app/src/main/java/org/wikipedia/main/MainActivity.java
This allows the user to interact with the rest of the UI while the tooltip is shown, instead of having to dismiss the tooltip first.
=> Make the Search tooltip not auto-dismissable.

app/src/main/java/org/wikipedia/history/HistoryDbHelper.kt
Searching through History should be ordered by Descending order (most recently read).
This also makes the search by Display title, not Api title.
And also this should fix a bug when searching for a single letter, as mentioned in https://phabricator.wikimedia.org/T259717#6462779
=> Fix search order when searching History.

app/src/main/java/org/wikipedia/util/L10nUtil.java
Somebody forgot a `return` statement.
=> Make getting strings for custom locale more efficient.

app/src/main/java/org/wikipedia/search/SearchFragment.java, app/src/main/java/org/wikipedia/search/SearchResultsFragment.java
https://phabricator.wikimedia.org/T260433#6469719
This also fixes an issue when "removing" languages from the Wikipedia Language screen. The search results should be refreshed.
=> Tweak: do both prefix and fulltext search for result counts

app/src/main/java/org/wikipedia/views/TabCountsView.kt
The `background.setColorFilter()` is deprecated.
=> Replace background.setColorFilter with backgroundTintList

app/src/main/java/org/wikipedia/gallery/MediaListItem.java
They were for testing purposes and forgot to remove them.
=> Remove unwanted log from MediaListItem.java 

app/src/main/java/org/wikipedia/navtab/MenuNavTabDialog.java, app/src/main/res/values/dimens.xml
The current peek height makes it pop up _almost_ all the way, obscuring the last item for no reason.
=> Increase peek height of main navigation overflow dialog.

app/src/main/res/values/strings.xml
Since the statistics in the Edits screen now refer to your total edits (not just through Suggested Edits), the tooltip messages should be updated to reflect it.
https://phabricator.wikimedia.org/T263363
=> Update tooltip verbiage to reference Edits instead of Suggested Edits.

upload-all.sh
The Releases server was recently moved from `releases1001` to `releases1002`.
=> Update hostname of Releases server.

app/src/main/java/org/wikipedia/page/PageFragment.java, app/src/main/java/org/wikipedia/page/PageTitle.java, app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.java, app/src/main/java/org/wikipedia/util/StringUtil.java, app/src/main/res/drawable/ic_user_talk.xml, app/src/main/res/values-qq/strings.xml, app/src/main/res/values/strings.xml
- Adjust the Talk icon to be slightly smaller, according to the OOUI shape.
- Update link preview button text for talk pages.
- Explicitly open the User Talk activity from internal links.
=> A few tweaks for User Talk pages.

app/src/main/java/org/wikipedia/gallery/GalleryActivity.java, app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.java
There's an annoying thing when flipping through images in the Gallery:  if you start zooming in on an image, and then pan around the zoomed-in image, it sometimes causes the ViewPager to flip to another image instead.
This will make the ViewPager disable its scrolling while an image is zoomed in, and only reenable the ViewPager when the image is fully zoomed out.
https://phabricator.wikimedia.org/T260625
=> Improve Gallery zoom+pager interaction.

app/src/main/java/org/wikipedia/search/SearchResultsFragment.java
Forgot to add the `size()` check to the code and it causes the crash.
https://appcenter.ms/orgs/ci-apps-hockeyapp-f5mf/apps/Wikipedia/crashes/errors/3242268481u/overview
https://github.com/wikimedia/apps-android-wikipedia/commit/994cd6757f0e10b53a525c46d68ebbcdec6ad594#diff-85741b59e95afd1258918b505cc3c844L442-L443
=> Fix: prevent crash when clicking on search results

app/src/main/java/org/wikipedia/random/RandomItemFragment.java
**Background**
https://phabricator.wikimedia.org/T261746
@AICT2020 reported this issue where `disposables` may request and hold several callbacks for `getRandomSummary()` when device rotates.
**Change**
=> Fix: properly clear disposables in RandomItemFragment

app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayFragment.java, app/src/main/res/layout/fragment_on_this_day.xml
**Background**
https://phabricator.wikimedia.org/T182195
**Change**
**Result**
Before:
After:
=> Fix scroll transition for "On This Day" fragment

app/src/main/java/org/wikipedia/feed/FeedFragment.java
https://appcenter.ms/orgs/ci-apps-hockeyapp-f5mf/apps/Wikipedia/crashes/errors/44565870u/overview
=> Fix: crash when showing SE snackbars on the Explore feed

app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
When we pass the page margins into the Page Library, they get formatted as `%d`, which actually follows the current Locale of the device. And if the locale is Persian, then it will output Persian numbers, e.g. `۱۲۳px`.
Therefore we must use the `ROOT` locale when formatting strings to be passed to the WebView.
This will finally fix the issue reported by numerous Persian users about the lead image overlapping the article.
=> Fix page margins for Persian and other locales.

app/src/main/java/org/wikipedia/page/PageActivity.java
Related to #1695 
When adding an article that the `getDisplayText()` is not the same as the `getPrefixedText()`, the bookmark icon will not change its status correctly.
e.g. 
https://zh.wikipedia.org/wiki/核武器 in `zh-hant`
`apiTitle` => 核武器 
`displayTitle` => 核子武器
=> Fix: should use apiTitle and language code when updating bookmark status

app/src/main/java/org/wikipedia/dataclient/WikiSite.java, app/src/main/java/org/wikipedia/page/LinkHandler.java, app/src/main/java/org/wikipedia/util/UriUtil.java, app/src/test/java/org/wikipedia/util/UriUtilTest.java
When testing the PR #1695, I have noticed that some in-article links will not get the page title correctly.
Please test this PR with this `testwiki` article: https://test.wikipedia.org/wiki/Language_Variants
=> Fix: correct the regular expression of getting page title from a link

app/src/main/java/org/wikipedia/page/PageFragment.java, app/src/main/res/layout/fragment_page.xml
https://appcenter.ms/orgs/ci-apps-hockeyapp-f5mf/apps/Wikipedia/crashes/errors/3504266540u/overview
https://appcenter.ms/orgs/ci-apps-hockeyapp-f5mf/apps/Wikipedia/crashes/errors/367965300u/overview
Note: I believe the crash was happening because the "source" ImageView from which the transition starts gets destroyed when the user goes back to the previous activity. This change will make the source ImageView always present in the activity.
=> Fix possible crash due to transitions on Lollipop devices.

app/src/main/java/org/wikipedia/theme/ThemeChooserDialog.java, app/src/main/res/drawable/button_shape_border_light.xml, app/src/main/res/layout/dialog_theme_chooser.xml, app/src/main/res/values/styles.xml, app/src/main/res/values/styles_dark.xml, app/src/main/res/values/styles_light.xml
We have to resize (re-style) the theme color buttons in order to add font-family buttons to the theme dialog.
https://phabricator.wikimedia.org/T264445
=> Replace the theme color button with plain circular buttons

app/src/main/java/org/wikipedia/views/FaceAndColorDetectImageView.java, app/src/main/java/org/wikipedia/views/ViewUtil.java
In today's "in the news" (Oct 22, 2020), the first article [OSIRIS-REx] shows a blue background in the `NewsFragment`, which is incorrect.
We can also apply a background color to the `FaceAndColorDetectImageView` in `fragment_news.xml`, but I believe this PR solves the root of this issue.
=> Make sure to apply white background on transparent images

app/src/main/java/org/wikipedia/analytics/AppearanceChangeFunnel.java
The funnel should not have a session token; this is why the `preprocessSessionToken()` function was overridden earlier.
=> Follow-up to serif font.

app/src/main/java/org/wikipedia/richtext/URLSpanBoldNoUnderline.java
**Phab:** https://phabricator.wikimedia.org/T261672#6567557
When we bold parts of rich text, it should be bold, and not faux bolded by converting to sans-serif-medium
=> Design tweak: News

app/src/main/res/layout/fragment_news.xml
Although we applied a white background to the image, we still can see blue background during the transition animation. This PR applies `paper_color` to the image container to solve the issue.
=> Set paper_color for the ImageView container in NewsFragment

app/build.gradle, app/src/extra/java/org/wikipedia/mlkit/MlKitLanguageDetector.kt, app/src/fdroid/java/org/wikipedia/mlkit/MlKitLanguageDetector.kt, app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.java
A quick follow-up to the excellent new language detection feature:
* Keep a single instance of the identifier object for the lifetime of the `DescriptionEditView`.
* Show the language warning in order of priority, relative to the other warnings (too short, punctuation, etc).
* A bit of additional cleanup.
=> Follow-up to language detection.

app/src/main/java/org/wikipedia/page/PageActivity.java
We've recently moved the donation Thank You pages to
thankyou.wikiPedia.org so we can set cookies which are readable
across the encyclopedias.
Bug: T259312
=> Bounce "thankyou." domain to external browser too

app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsFeedClient.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsItemFragment.kt
This is a proper fix of #1719, since it also fixes the broken views in the SE feed of translate description in `enwiki`.
=> Fix: properly retry the request when getting empty source description

app/src/main/java/org/wikipedia/feed/mostread/MostReadFragment.java, app/src/main/java/org/wikipedia/feed/news/NewsFragment.java, app/src/main/java/org/wikipedia/main/MainFragment.java
Since we implement the transition animation as default in `ListCardItemView`, we should not ignore the `onSelectPage` method.
This PR also optimizes the animation which if there is nothing to be transited between screens, it should be disabled.
=> Fix: make sure list items are clickable in NewsFragment and MostReadFragment

app/src/main/java/org/wikipedia/settings/SettingsActivity.java
**Background**
https://phabricator.wikimedia.org/T198385
The feed automatically refreshes every time user enters language selection or feed configuration from settings even if nothing is changed.
**Change**
**Testing**
\ | Before | After |
--- | --- | --- |
Languages | ![languages_before](https://user-images.githubusercontent.com/22717320/97793523-65213f00-1baa-11eb-974e-b61b5a30df55.gif) | ![languages_after](https://user-images.githubusercontent.com/22717320/97793524-694d5c80-1baa-11eb-90f1-700304e0dc14.gif) |
Feed configuration | ![feed_before](https://user-images.githubusercontent.com/22717320/97793526-736f5b00-1baa-11eb-90e9-dcd097e023f7.gif) | ![feed_after](https://user-images.githubusercontent.com/22717320/97793529-7f5b1d00-1baa-11eb-81d6-8164465b357c.gif) |
=> Only refresh feed if languages or feed configurations are changed in settings

app/src/main/java/org/wikipedia/dataclient/page/PageSummary.java, app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsFeedClient.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsItemFragment.kt, app/src/main/java/org/wikipedia/suggestededits/provider/EditingSuggestionsProvider.kt
As discussed, this PR set the description from `recommendation` API in the `PageSummary`.
This PR also rename the variables to reduce confusion, because the `articlesWithTranslatableDescriptionCache` is `<TargetPageTitle, SourcePageTitle>`
=> Fix: set description from recommendation api for enwiki

app/src/main/java/org/wikipedia/edit/preview/EditPreviewFragment.java, app/src/main/java/org/wikipedia/page/PageActivity.java, app/src/main/java/org/wikipedia/page/PageContainerLongPressHandler.java, app/src/main/java/org/wikipedia/page/PageFragment.java, app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java, app/src/main/java/org/wikipedia/page/PageViewModel.java
Sometimes the `getTitleOriginal().getPrefixedText()` is not the same as `getTitle().getPrefixedText()`, which will affect the process of updating bookmark status.
This PR removes `getTitleOriginal()` related variables and objects and use `getTitle()` instead.
**Steps to reproduce:**
1. Go to [Henry_Clifford,_10th_Baron_Clifford](https://en.wikipedia.org/wiki/Henry_Clifford,_10th_Baron_Clifford).
2. Click on [English nobleman](https://en.wikipedia.org/wiki/English_peerage) in the first sentence.
3. Click on "Save" to save the article.
**Expected:**
Should see the bookmark icon turns into a filled icon.
=> Fix: update bookmark status correctly

app/src/main/java/org/wikipedia/feed/featured/FeaturedArticleCardView.java, app/src/main/java/org/wikipedia/page/PageActivity.java, app/src/main/res/layout/activity_page.xml
The new design changes in #1743 resized the lead image height, and the animation should adapt that.
=> Update WikiArticleCard image height to adapt new design changes

app/src/main/java/org/wikipedia/page/PageActivity.java, app/src/main/java/org/wikipedia/util/TransitionUtil.kt
By hiding the image container in `WikiArticleCardView` and not sending the shareElement.
=> Handle transition animation properly when the image download is disabled

app/src/test/java/org/wikipedia/json/RequiredFieldsCheckOnReadTypeAdapterFactoryTest.java, app/src/test/java/org/wikipedia/language/AppLanguageStateTests.java, app/src/test/java/org/wikipedia/media/StateTest.java, app/src/test/java/org/wikipedia/util/BatchUtilTest.java
This should not require any testing, as the old methods call the new ones internally.
=> Fix JUnit-related deprecations

app/src/main/res/xml/developer_preferences.xml, app/src/main/res/xml/preferences.xml, app/src/main/res/xml/preferences_about.xml, app/src/main/res/xml/preferences_experimental.xml, app/src/main/res/xml/preferences_notifications.xml
This simply corrects the XML preference tags (the androidx.preference prefix is not supposed to be used in XML; it is used [automatically](https://developer.android.com/guide/topics/ui/settings)).
=> Fix XML preference tags

app/build.gradle
https://square.github.io/leakcanary/changelog/#version-25-2020-10-01
=> Update leakCanary library version to 2.5

app/src/main/java/org/wikipedia/feed/announcement/AnnouncementCardView.java
The recently change in #1771 added a bottom margin to the view, and we should reset it to zero in the dialog on the article screen.
=> Fix: reset margins to zero in the Announcement dialog on the article screen

app/src/main/java/org/wikipedia/feed/view/FeedAdapter.java, app/src/main/java/org/wikipedia/history/HistoryFragment.java, app/src/main/res/layout/view_search_bar.xml
If we look closely, we'll notice that the search bar's top and bottom are being cut. It is more obvious when using the app on a tablet.
This PR also updates the logic of adjusting the view width only if the device is in landscape mode.
=> Tweak: don't let the seach bar top and bottom be cut

app/src/main/res/values/styles.xml
The default `colorPrimary` in material design is `#6200EE`, which is a purple color that we have seen in the past (e.g. view pager indicators, buttons...)
This is a temporary fix that replaces the default `colorPrimary` with our custom `?attr/colorPrimary` in the `BaseAppTheme`, and the result shows below:
Other default colors might have the same issue, but we can hold until they really affect the app.
=> Fix: make sure to override the colorPrimary to prevent showing default color

app/src/main/java/org/wikipedia/page/PageFragment.java
This fixes a necessary precondition that I believe could lead to this weird crash.
https://appcenter.ms/orgs/ci-apps-hockeyapp-f5mf/apps/Wikipedia-Beta/crashes/errors/466475843u/overview
=> Fix possible crash from tab removal conditions.

app/src/main/java/org/wikipedia/dataclient/page/PageSummary.java, app/src/main/java/org/wikipedia/page/PageProperties.java, app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.java
For the current implementation, we will see the center cropped image in the Gallery before the actual image is loaded. If the cropped image contains a human, it will look not that good while loading.
=> Use actual image width and height for the lead image transition animation

app/src/main/java/org/wikipedia/Constants.java, app/src/main/java/org/wikipedia/main/MainFragment.java, app/src/main/java/org/wikipedia/page/PageActivity.java, app/src/main/java/org/wikipedia/page/PageFragment.java, app/src/main/java/org/wikipedia/views/WikiArticleCardView.kt, app/src/main/res/layout/activity_page.xml
The new "wikiArticleCardView" in the PageActivity is being shown at inappropriate times, and is causing unnecessary jankiness and flashing when loading articles.
=> Simplify and reduce jankiness of feed-to-page transition animation.

app/src/main/java/org/wikipedia/page/tabs/TabActivity.java, app/src/main/res/menu/menu_tabs.xml, app/src/main/res/values-qq/strings.xml, app/src/main/res/values/strings.xml
https://phabricator.wikimedia.org/T268289
This PR also fixes the incorrect `qq-string` format for `suggested_edits_tags_diff_count_text` and `suggested_edits_removed_contribution_label`
=> Tweak: changes to overflow menu in tabs overview screen

app/src/main/res/menu/menu_tabs.xml, app/src/main/res/values-qq/strings.xml, app/src/main/res/values/strings.xml
shorter name instead of using 'v2'
=> Follow-up to overflow menu changes: Minor renaming

app/src/main/java/org/wikipedia/page/PageFragment.java
**Phab:** https://phabricator.wikimedia.org/T268525
The root cause for this bug is that we are removing 'Saved' from the list of existing lists because we are moving it from the saved list. However, it is having an unwanted side-effect of not throwing an exception when they try to create a second saved list. 
We can either resolve this by not removing "Saved" from the list just to not show it [preferred], or if that is crucial we can remove it at a different more suitable stage.
Will round this up after a short discussion with the rest of the team.
=> Block user from creating a second "Saved" list

app/src/main/java/org/wikipedia/page/PageFragment.java, app/src/main/java/org/wikipedia/readinglist/AddToReadingListDialog.java
This blocks the creation of a second "Saved" list more properly, by maintaining separate lists for the logic vs. presentation layer, as we do in other places.
=> Follow-up to creating "Saved" list.

app/src/main/java/org/wikipedia/page/PageActivity.java, app/src/main/java/org/wikipedia/views/TabCountsView.kt, app/src/main/res/drawable/tab_counts_shape_border.xml, app/src/main/res/layout/view_tabs_count.xml
The previous PR incorrectly updates the icon and text color, which leads the inconsistency with other icons in the toolbar in most places that have the `TabCountsView`.
=> Fix: should use correct color on TabCountsView

app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
The current top margin on the main pages is too large and it should be updated.
This PR also removes the unnecessary `{}` from variables.
=> Adjust top margin correctly for main page

app/src/main/java/org/wikipedia/analytics/eventplatform/DestinationEventService.java, app/src/main/java/org/wikipedia/analytics/eventplatform/EventPlatformClient.java, app/src/main/java/org/wikipedia/analytics/eventplatform/EventPlatformClientIntegration.java, app/src/main/java/org/wikipedia/analytics/eventplatform/EventService.java, app/src/main/java/org/wikipedia/dataclient/ServiceFactory.java, app/src/test/java/org/wikipedia/analytics/eventplatform/EventPlatformClientIntegrationTest.java
Buffering while online creates unnecessary flurry of 128 network calls. We can limit this batching to 10 when online and 128 while offline
=> Use buffering only whilst Offline

app/src/main/res/layout/view_search_bar.xml
When the system language is RTL (e.g. Farsi) the text in the Search field is misaligned.
=> Fix RTL alignment of Search card in Feed.

app/src/main/java/org/wikipedia/dataclient/Service.java, app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryPage.java
Per @sharvaniharan's finding, this is an API call of the watched state of an article.
=> API call of getting watched info.

app/src/main/java/org/wikipedia/watchlist/WatchlistFragment.kt
The list is currently listing by the language code, and we have to scroll down to see the watched articles in other languages.
=> Sort watchlist items by date descending

app/src/main/java/org/wikipedia/analytics/eventplatform/EventPlatformClient.java
This removes the usage of `SecureRandom` and generates the 80-bit random ID in a much faster way.
=> Optimize MEP random id generation.

app/src/main/java/org/wikipedia/page/PageFragment.java, app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java, app/src/main/java/org/wikipedia/page/PageViewModel.java
This PR also fixes an issue that `watchlistExpirySession` should be cleared when entering another article on the page.
=> Use getWatchedInfo() to get the proper watched state of an article

app/src/main/res/values-sw360dp/preference.xml
Perhaps #1871 accidentally removed it, which makes the preference screens has the extra start-padding on the list items.
=> Fix: remove extra start-padding in preference screen

app/src/main/java/org/wikipedia/views/TextInputDialog.java, app/src/main/res/menu/menu_reading_lists.xml
This does a bit of cleanup, and fixes a potential issue:
On a very small display, the "My Lists" screen will have a toolbar that will hide the "filter" and "overflow" buttons, so that the option to create a new list will be inaccessible. Therefore we're changing the buttons in that menu to be `showAsAction=always`.
=> Quick follow-up to reading list name dialog.

app/src/main/java/org/wikipedia/page/PageFragment.java
When navigating to a nonexistent article (e.g. a User page that hasn't been created yet), the app will briefly flash a 404 error, but then will be overwritten by a very general "An error has occurred" message. This is because the WebView performs a `onReceivedError()` callback right after the `summary` response returns the 404 error.
This works around the issue by showing only the "first" error that was received, and ignoring any additional errors if the error view is already visible.
=> Fix display of 404 errors for nonexistent articles.

app/src/main/res/values-ca/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-fa/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-fy/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-in/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-iw/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-ko/strings.xml, app/src/main/res/values-mk/strings.xml, app/src/main/res/values-mnw/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-qq/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values-tl/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-uk/strings.xml, app/src/main/res/values-uz/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values-zh/strings.xml, app/src/main/res/values/strings.xml
This PR also corrects the `suggested_edits_tags_diff_count_text` and `suggested_edits_removed_contribution_label` in `qq/strings.xml` that should be `plurals` items.
=> Hygiene: clean up unused string resources

app/src/main/java/org/wikipedia/commons/FilePageView.kt
A follow-up PR of #1898. The only way of viewing the "Picture of the day" image is on the File page, and we should still show the image if images are disabled.
=> Follow up: display file page image when images are disabled

app/src/main/res/layout/view_reference_pager_item.xml
https://phabricator.wikimedia.org/T127406
=> Fix: use the same text direction in the ReferenceDialog as the article

app/src/main/java/org/wikipedia/page/PageFragment.java
If we visit a page that has already on the watchlist and then remove it, the menu item status will not be changed properly.
=> Fix: update Watchlist overflow menu item properly

app/src/main/java/org/wikipedia/widgets/WidgetProviderFeaturedPage.kt, app/src/main/java/org/wikipedia/wiktionary/WiktionaryDialog.kt
Things to keep in mind:
* The automatic Kotlin conversion doesn't seem to know that Rx consumers will always receive a nonnull value.
* Simple string splitting can be done with a character parameter.
=> Follow-up to Kotlin conversion.

app/src/main/java/org/wikipedia/util/log/L.kt
I noticed that inside the `log` function we acquire the stack trace of the current thread (to get the line number where the log was called) every time we call it. This is actually a kind of expensive operation.  Let's do it only for `dev` builds, and for all other builds it will only print the message, without the line number.  (This does not impact logging of exceptions, since exceptions already contain stack information in them.)
=> Follow-up to Kotlin L conversion.

app/src/main/java/org/wikipedia/activity/SingleFragmentActivity.kt
This one slipped past me:
When an Activity is rotated, it gets recreated (`onCreate` is called again) but its state is preserved, along with the fragment that's already in there, so we don't need to re-add the fragment a second time.
=> Whoops: fix rotation of SingleFragmentActivity.

app/src/main/java/org/wikipedia/page/PageFragment.java, app/src/main/java/org/wikipedia/readinglist/database/ReadingListDbHelper.java
A rather obscure issue, but worth fixing:
* Add an article to more than one reading list, and make sure the lists are synced to your account.
* Uninstall the app, then reinstall it and login to get your lists back, but cancel downloading of the articles as soon as it starts.
* Go to your reading lists and navigate to the article that you added (pick from one of the lists).
* Wait for the article to load, so that its description and lead image are loaded.
* Go back to your lists, and observe that the description and thumbnail for that page are not updated, or updated only for one instance, instead of all of them.
=> Fix updating of reading list metadata for articles in multiple lists.

app/src/main/java/org/wikipedia/bridge/CommunicationBridge.kt
@cooltey  sorry, this is the real reason for the crash:
When converting the Bridge code, there was a line that resets the WebViewClient to `null`, but I forgot to put it back because Kotlin was not allowing a null value to be passed there. We will now pass an empty WebViewClient, which is the more proper thing to do anyway.
=> Fix crash upon destroying WebView.

app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
We should not use `prefixedText` on UI.
=> Fix: should show PageTitle.displayText on watchlist snackbar

app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryPage.java, app/src/main/java/org/wikipedia/diff/ArticleEditDetailsActivity.kt, app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt, app/src/main/java/org/wikipedia/watchlist/WatchlistFragment.kt
* The character count was incorrect (off-by-one) for certain types of diffs.
* This fixes rotating the display and staying on the revision that you were looking at before rotating.
* We only need to check once if the article is Watched -- we don't need to re-check it every time we go backward and forward through the edit history.
* We no longer need to pass the diff size from the parent activity, since we're calculating the diff size ourselves.
* We can compose the actual diff (Spannable) in a background thread, and not block the UI thread while loading it.
=> Follow-up: simplify and fix a bunch of things in Diff view.

app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt
The `loadTopics` function, which makes the network call to load the talk page, gets called in `onResume()`, so it doesn't need to be called in `onCreate()`.
=> Tweak: don't load talk page an extra time unnecessarily.

app/src/main/java/org/wikipedia/page/PageTitle.java
1. Go to https://en.wikipedia.org/wiki/Joey_Santiago
2. Change article language to `zh-hant`
3. Click the first in-article link `菲律賓裔美國`
4. On the `菲律賓裔美國` page, click any in-article links and will see an error message.
=> Fix: URL fragment should be encoded before navigating to other articles in PageFragment

app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt, app/src/main/java/org/wikipedia/util/DateUtil.kt, app/src/main/java/org/wikipedia/watchlist/WatchlistItemView.kt, app/src/main/res/layout/item_watchlist.xml
* I recall discussing the `Locale.ROOT` issue that was causing incorrect "M01" dates to be shown, but it looks like this was never fixed?
* Apply correct sizing to the diff-count button.
* For zero-sized diffs, show "0" instead of "+0".
https://phabricator.wikimedia.org/T269447
=> Fix additional UI issues in Diff screens.

app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt, app/src/main/java/org/wikipedia/watchlist/WatchlistItemView.kt
**Phab: ** https://phabricator.wikimedia.org/T269447
Beginning of a page doesn't have a diff text, and the comparison results in 404. Any content associated with the initial commit is returned as a comment
=> Fix: Improper revId results in 404

app/src/main/java/org/wikipedia/util/L10nUtil.kt
The way of setting locale in the configuration is deprecated.
https://developer.android.com/reference/android/content/res/Resources#Resources(android.content.res.AssetManager,%20android.util.DisplayMetrics,%20android.content.res.Configuration)
=> Follow up: replace deprecated method in L10nUtil

app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.java
We were stripping away the namespace when applying the proper title from the Summary response, but this is incorrect when the response is a redirect to a page in a different namespace.
It's better to reconstruct the PageTitle altogether, with the information received from the Summary response.
=> Fix loss of namespace when showing redirected title in Link Preview.

app/src/main/java/org/wikipedia/util/ShareUtil.kt, app/src/main/java/org/wikipedia/util/UriUtil.kt
https://phabricator.wikimedia.org/T120315
This finally solves the long-standing issue of removing the Wikipedia app from the list of apps when sharing content, or when navigating to external links (if the external link is also on Wiki).
=> Correctly remove Wikipedia from any Sharing intents.

app/src/main/java/org/wikipedia/commons/FilePageFragment.kt, app/src/main/java/org/wikipedia/commons/FilePageView.kt, app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt, app/src/main/java/org/wikipedia/feed/view/CardFooterView.kt, app/src/main/java/org/wikipedia/feed/view/GradientCircleNumberView.kt, app/src/main/java/org/wikipedia/views/ImageDetailView.kt
This removes all of the remaining usages of synthetics, and switches everything to View Bindings.  After this, we will be ready to remove the `kotlin-extensions` dependency from Gradle.
=> Convert all remaining things to View Bindings.

app/src/main/java/org/wikipedia/readinglist/ReadingListTitleDialog.kt, app/src/main/java/org/wikipedia/views/WikiTextKeyboardView.kt, app/src/main/java/org/wikipedia/wiktionary/WiktionaryDialog.kt
As we discussed, it should be fine to use `trim()` instead of the addition `trim { it <= ' ' }` logic.
=> Simplify the way of trim() text in Kotlin

app/src/main/java/org/wikipedia/readinglist/LongPressMenu.kt
1. Save any page on the PageFragment
2. Click on the "save" button again
The necessary check was removed by accident in #2175
=> Fix: "save" on PageFragment does not work properly on PageFragment

app/src/main/java/org/wikipedia/page/PageFragment.java, app/src/main/java/org/wikipedia/page/references/ReferenceDialog.kt
https://appcenter.ms/orgs/ci-apps-hockeyapp-f5mf/apps/Wikipedia-Beta/crashes/errors/3207428379u/overview
Didn't notice that the `referenceGroup` can be null sometimes.
https://github.com/wikimedia/apps-android-wikipedia/pull/2246/files#diff-1bbfb3f068c1a476373b73366e53dec2cf716e99f7d31c0f01338808ddf75308L57-L59
=> Fix: crash when referenceGroup is null when opening ReferenceDialog

app/src/main/java/org/wikipedia/commons/FilePageView.kt, app/src/main/res/values-qq/strings.xml, app/src/main/res/values/strings.xml
https://phabricator.wikimedia.org/T278561
IMO this is low-risk enough that it can be merged before design review.
=> Indicate if a file originates from Wikimedia Commons.

app/src/main/java/org/wikipedia/feed/view/CardLargeHeaderView.kt, app/src/main/java/org/wikipedia/views/FaceAndColorDetectImageView.kt
`FIT_CENTER` is the default ScaleType, and therefore should not be used for this new special case. `FIT_START` shall be the new special case if we want a `FaceAndColorDetectImageView` that fits the image without actual face detection.
=> Whoops: don't use the default ImageView ScaleType for non-transform.

app/build.gradle
https://developer.android.com/jetpack/androidx/releases/recyclerview#recyclerview-1.2.0
I am not seeing the `getAdapterPosition` has the deprecated label on it and I think we can still continue using it for a while.
=> Update recyclerview version to 1.2.0

app/src/main/res/layout/view_onboarding_page.xml
Parts of the onboarding text are cut off on small screen devices.
How it looks on Nexus S emulator in `imageRecs_design`
Please note that the image is also cut off but I believe @sharvaniharan will have another PR(https://phabricator.wikimedia.org/T278526)  to fix it.
=> ImgRecs: prevent onboarding text being cut off on small screen devices

app/src/main/java/org/wikipedia/settings/LongPreference.kt
The developer preferences (`IntPreference` and `LongPreference`) have been broken, due to an erroneous string conversion that was missed during kotlin conversion.
=> Fix display of numeric Developer Preferences.

app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt, app/src/main/res/values-qq/strings.xml, app/src/main/res/values/strings.xml
We were actually only performing capitalization checking in the case of English anyway. This simply changes the capitalization requirement from lower to upper.
https://phabricator.wikimedia.org/T279702
=> Update short description capitalization guidance for English.

app/src/main/java/org/wikipedia/suggestededits/provider/EditingSuggestionsProvider.kt
For English, the suggestion algorithm might be suggesting articles that already have a description locally. This updated logic will filter those out.  (We are already filtering them out correctly in the "add descriptions" case, but not the "translate descriptions" case.)
https://phabricator.wikimedia.org/T279702
=> Perform additional existence check when translating short descriptions.

app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
The edit comment of `suggestededit-add_1.0` was being added incorrectly even when the edit came organically from the article, not just the Suggested Edits feature.
https://phabricator.wikimedia.org/T279702
=> Fix edit comment when submitting short descriptions.

app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt, app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt
As we discussed on Slack, sometimes the `id` is `-1` and we should not show the "new topic" page for it and should hide the reply button.
https://en.wikipedia.org/api/rest_v1/page/talk/Talk%3ADreamsnake
=> Don't show reply button when the topicId=-1 in TalkTopicActivity

app/src/main/java/org/wikipedia/suggestededits/ImageRecsFragment.kt
Sometimes the `langWikis` list will contains a `null` value, which will cause an error in `ImageRecsFragment`.
We should filter out `species`, or we can just use `mapNotNull`.
=> ImgRecs: prevent having null value in the langWikis list in ImageRecsFragment

app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.kt
**Phab:** https://phabricator.wikimedia.org/T279851
When there is an image caption available in the only language selected, the imageEditType is null. But we were not checking for null here and hence just adding the default "Add image caption" CTA by default. This would fail during the execution of click listener.
=> When imageEditType is null, do not add default CTA 

app/src/main/java/org/wikipedia/suggestededits/ImageRecsFragment.kt
Sometimes the `recommendation!!.pageTitle` is `null`, and it will make the `WikiErrorView` show only the `backButton`, and the user will not able to go to the next one since we removed the swipe function in the feed.
This is a temporary fix and will have another proper solution coming soon.
=> ImgRecs: don't block the feed if title is empty

app/src/main/java/org/wikipedia/onboarding/OnboardingPageView.kt, app/src/main/java/org/wikipedia/suggestededits/ImageRecsOnboardingFragment.kt, app/src/main/res/layout/view_onboarding_page.xml
Currently onboarding image is getting cut-off on the top on small screens. This is because of the gravity of the layout below it. However if we make a general change, the layout doesnt render correctly in other places. So put in a specific change.
=> Image recs : Small screen fix for onboarding image being cut-off

app/src/main/java/org/wikipedia/suggestededits/ImageRecsFragment.kt, app/src/main/java/org/wikipedia/util/ThrowableUtil.kt, app/src/main/java/org/wikipedia/views/WikiErrorView.kt, app/src/main/res/values-qq/strings.xml, app/src/main/res/values/strings.xml
In order to use unclear `Exception` for the empty title, it would be better if we show the "Next" button for `ExceptionEmpty`.
=> ImgRecs: throw proper exception and provide a proper button for going to next item

app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt, app/src/main/java/org/wikipedia/descriptions/DescriptionEditLicenseView.kt, app/src/main/java/org/wikipedia/descriptions/DescriptionEditReviewView.kt
Right now we're showing the CC0 license for all descriptions, but that's the license for Wikidata contributions. When contributing to Wikipedia, the license is CC-BY-SA 3.0.
=> Show correct license when editing descriptions in English.

app/src/main/java/org/wikipedia/analytics/eventplatform/EventPlatformClient.java, app/src/test/java/org/wikipedia/analytics/eventplatform/EventPlatformClientTest.java
Sends events immediately upon submission to the MEP client to match the legacy eventlogging behavior. We'll compare the resulting events with those sent via the legacy system in order to determine conclusively whether events are being leaked in the queueing process.
This PR also contains an incidental change to drop support for looking up stream names by regular expression matching. This feature is only used in practice by job-queue-related stream configurations, and the app need not support it.
Phab: https://phabricator.wikimedia.org/T281001
=> MEP: Send events immediately for testing

app/src/main/java/org/wikipedia/commons/FilePageView.kt
1. Go to the "IMDb" article.
2. Click on the lead image.
3. Go to the second image ("screenshot of IMDb's front page as of March 31, 2021") and go to its file page.
4. Click on the "Fair use" external link in the "Licensing" section.
=> Fix: apply UriUtil.resolveProtocolRelativeUrl() for externalLink in FilePage

app/src/main/java/org/wikipedia/analytics/eventplatform/EventPlatformClient.java, app/src/main/java/org/wikipedia/analytics/eventplatform/EventService.kt
In our network call to the MEP service, we expect a response in the form of a `EventServiceResponse` object.  However, since we're sending the events "hastily", the server doesn't actually give us any response (it's a zero-length body). This causes an exception to be thrown in RxJava, and we're simply not handling it now.
This is OK for the current release, since we're not doing anything with those responses one way or another. But this PR simply cleans up that logic and no longer expects a response body for hasty requests, and no exceptions are thrown anymore.
=> MEP: Stop incorrectly expecting response for hasty requests.

app/src/main/res/layout/view_image_detail.xml
For some reason `textIsSelectable` was removed.
https://phabricator.wikimedia.org/T281705
=> Make text selectable again in Image Detail view.

app/src/main/java/org/wikipedia/feed/announcement/AnnouncementCardView.kt
It was a bug from #2401, which in a fresh install, the "customize feed" card will show four action buttons.
=> Fix: announcement card action buttons container visibility

app/src/main/java/org/wikipedia/feed/news/NewsCardView.kt, app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardView.kt
Also a bug from #2401.
If we click on the second news card item and then press the back button to return to the feed, the `NewsCard` view will be created again and it will push down an empty space below the news card. 
If you try many times the issue will become more obvious.
=> Fix: don't set new card if it matches the old one

app/src/main/java/org/wikipedia/feed/announcement/AnnouncementCardView.kt, app/src/main/java/org/wikipedia/page/AnnouncementDialog.kt
Yet another bug introduced in #2401 -- when the Announcement card is shown as a dialog while browsing an article, the positive/negative buttons don't work, because the callback never gets called.
=> Fix buttons on Announcement dialog when shown over article.

app/src/main/java/org/wikipedia/util/CenterCropWithFaceTransformation.kt
If you set the app to Dark mode, and look very closely at large images (e.g. lead images in articles, card images in the feed, etc), you might notice a very thin white line at the left and top of the image.
For some reason the matrix transformation logic was adding an extra 0.5 dp to the translation.  I have no idea why this was being done, so I removed it, and now the images are aligned perfectly.
=> Fix face-transformed image alignment.

app/src/main/java/org/wikipedia/dataclient/Service.java
This is related to https://phabricator.wikimedia.org/T276139
The API requires another obscure parameter to return MediaWiki errors that are overridden on the local wiki. This should make our displaying of errors even more accurate for each language wiki.
=> Explicitly request locally overridden errors from the API.

app/src/main/java/org/wikipedia/util/StringUtil.kt
When we parse html messages with "images" in them, the images appear as green boxes. (This can be seen in link previews for certain articles, as well as in certain types of error messages.)
Instead of showing a green box, let's just remove images from html strings that we parse.
=> Remove images when parsing strings as Html.

app/src/main/java/org/wikipedia/page/PageActivity.java
https://phabricator.wikimedia.org/T282765
=> Fix: return to the original position after editing image caption/tags from Gallery

app/src/main/java/org/wikipedia/settings/NotificationSettingsActivity.kt, app/src/main/res/xml/preferences_notifications.xml
https://phabricator.wikimedia.org/T281414
Noticed that in `preferences_notifications.xml`, the default value of `preference_key_notification_poll_enable` is `false`.
but the `Prefs.notificationPollEnabled()`, the default value is `true`.
Not sure but it would be better if the default values are consistent. 
1. Fresh install app. (`preference_key_notification_poll_enable` = `true`)
2. Log in.
3. Go to `NotificatonSettings`, and  `preference_key_notification_poll_enable` will become `false` automatically.
=> Update enable poll notification value to true on XML

app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.kt
It would cause when trying to get the `scale` from `binding.image` from a destroyed `GalleryItemFragment`, which the `_binding` is set to `null`.
=> Fix: crash when destroying GalleryActivity

app/src/main/java/org/wikipedia/edit/Edit.kt
If we are going to use the values from the object itself when building it, we should apply `get()` for the variables.
Now the latest beta app has the issue that it will show `Received unrecognized edit response` after submitting edits.
=> Fix: prevent showing incorrect edit message after submitting edits

app/src/main/java/org/wikipedia/page/PageFragment.java
1. Click on any article.
2. Scroll to the bottom and click on "View edit history".
3. In the overflow menu, click on "Share link".
=> Fix: make "Share link" working properly on Special: pages

app/build.gradle
The newest version finally runs Robolectric tests successfully on my Windows machine.
=> Update Robolectric to 4.5.1.

app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt, app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt
Now they are showing the default color on the circle icons.
=> Apply correct loading circle icon color for talk topic activites

app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt, app/src/main/res/values/strings.xml
This states the last-edit time as a relative time, e.g. "5 minutes ago", "13 hours ago", "5 days ago", etc.
=> Follow-up to Talk Page last edited time.

app/src/main/java/org/wikipedia/captcha/CaptchaHandler.kt, app/src/main/java/org/wikipedia/createaccount/CreateAccountActivity.kt, app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
This applies to `CreateAccountActivity` and also `EditSectionActivity`
https://phabricator.wikimedia.org/T286095
=> Fix: request new CAPTCHA when backing from the error view

app/src/main/java/org/wikipedia/notifications/NotificationActivity.kt, app/src/main/res/layout/item_notification.xml
Since NotificationItemHolders are reused by the RecyclerView, some notifications incorrectly have secondary and tertiary action links, when they actually shouldn't.
=> Correctly show/hide secondary and tertiary actions in notifications.

app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt
Steps:
1. Go to talk page and click on any topic.
2. In topic page, click on reply.
3. Press "back" button, and it should close the compose response input view.
=> Tweak: should close the compose response input field before exiting the topic page

app/src/main/java/org/wikipedia/savedpages/SavedPageSyncNotification.kt
1. Clear app data.
2. Log in to an account that has multiple reading lists synced.
3. While downloading the articles, click on "Pause" to pause the procedure.
The "Pause" button should change to "Resume" when it is paused.
=> Fix: make sure the notification "Pause" and "Resume" button showing correctly

.github/FUNDING.yml
**Fixes Phabricator ticket:** N/A
* Add a support WMF link. From conversation w/ advancement.
* This will cause a link to show up on the right side of our main repo webpage.
1. N/A
=> Add fundraising link to GitHub

app/src/main/java/org/wikipedia/notifications/NotificationActivity.kt
In the notification screen, the RTL language notifications should be displayed in a proper layout direction.
=> Apply a proper layout direction in NotificationActivity

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt, app/src/main/java/org/wikipedia/userprofile/Contribution.kt, app/src/main/java/org/wikipedia/userprofile/ContributionsFragment.kt
This does a few things:
* Fixes the edit streak shown in the Edits screen by taking into account edits from the user's home wiki.
* In the Contributions activity, it will now show all contributions from the user's home wiki (which we weren't doing yet??)
=> Follow-up to showing all contributions

app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt
1. Go to your Talk page from the "More" menu
2. Change the language that does not have a talk page yet.
The list will remain the same items in the previous language and will need to wait 20 times of retrying, which will make the user a little bit confused.
=> Fix: remove unnecessary retry logic and unused parameter in TalkTopicsActivity

app/src/main/java/org/wikipedia/page/PageTitle.kt
Unfortunately you might need to clear the app's data if you've used it to browse articles after merging of #2657
=> Fix (de)serialization of PageTitle.

app/src/main/java/org/wikipedia/feed/news/NewsItemView.kt, app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayCardView.kt, app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayPagesViewHolder.kt, app/src/main/res/layout/item_on_this_day_pages.xml, app/src/main/res/layout/view_horizontal_scroll_list_item_card.xml
If there are no images showing on the card, the text should be aligned to the center.
=> Fix: card text should be aligned to center if no images on the card

app/src/main/java/org/wikipedia/feed/news/NewsCardView.kt, app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardView.kt
Not sure if it is the best practice. Please advise if you have any other solution.
https://phabricator.wikimedia.org/T288990
=> Fix: enable/disable downloading images on NewsCard and SECard correctly after changed it

app/src/extra/java/org/wikipedia/push/WikipediaFirebaseMessagingService.kt, app/src/main/java/org/wikipedia/WikipediaApp.java, app/src/main/java/org/wikipedia/activity/BaseActivity.kt, app/src/main/java/org/wikipedia/analytics/NotificationPreferencesFunnel.kt, app/src/main/java/org/wikipedia/main/MainActivity.kt, app/src/main/java/org/wikipedia/notifications/NotificationActivity.kt, app/src/main/java/org/wikipedia/notifications/NotificationPollBroadcastReceiver.kt, app/src/main/java/org/wikipedia/settings/NotificationSettingsActivity.kt, app/src/main/java/org/wikipedia/settings/Prefs.java, app/src/main/res/values/preference_keys.xml
This cleans up a couple of things:
* Move the creation of notification channels to `WikipediaApp.onCreate()` instead of `MainActivity.onCreate()`. (the channels don't need to be created every time the activity is launched)
* Removed unused preferences related to polling. The polling broadcast receiver runs in the background unconditionally, and should no longer be constrained by a preference. (the polling is already constrained by whether FCM is active)
=> Follow-up to notification settings.

app/src/main/java/org/wikipedia/analytics/eventplatform/EventPlatformClient.java
This doesn't really affect our handling of errors coming from MEP, since we're using the "hasty" endpoint, but this just makes it more correct, since a response with an HTTP error code (>=400) would never make it into the `subscribe` block in rxjava.
=> Move MEP error handling to the correct block.

app/src/main/AndroidManifest.xml, app/src/main/java/org/wikipedia/util/ShareUtil.kt, app/src/main/java/org/wikipedia/util/UriUtil.kt
https://phabricator.wikimedia.org/T291199
Here's what seems to be happening:
On Android 11 (and possibly 10?) if our app is set as the default app for our intent filter, we can no longer use `queryIntentActivities()` to get a list of other external apps that can handle links.  The guidance from the documentation is to use a `<queries>` element in our manifest to state that we need to query activities that match a certain intent.  But even with a proper `<queries>` tag, the system is still not returning other apps that can handle the intent, if the intent is "tightly bound" to our app (i.e. if our app is the explicit default).
This PR makes the following workaround:
If our current way of bouncing to an external browser fails (i.e. if the intent chooser is empty), we will query apps that …
=> Fix explicit bouncing of links to external browser app.

app/src/main/java/org/wikipedia/page/tabs/TabActivity.kt
It looks like the original PR didn't actually wire up the Notification button to be clickable. ;)
=> Follow-up to notification bell in TabActivity.

app/src/main/java/org/wikipedia/notifications/NotificationActivity.kt, app/src/main/java/org/wikipedia/views/SwipeableItemTouchHelperCallback.kt
Can be applied to other places where we'll use `SwipeRefreshLayout` plus swipeable `RecyclerView` items.
https://phabricator.wikimedia.org/T292124
=> Disable Refresh view when swiping list items.

app/src/main/java/org/wikipedia/notifications/NotificationPresenter.kt
Failing to set this flag can actually lead to loss and corruption of the `Bundle` that is included in the `PendingIntent`.
=> Apply correct flags to all PendingIntents in notifications.

app/src/main/java/org/wikipedia/page/PageTitle.kt
For certain specific user talk namespaces, the `displayText` could end up containing the namespace twice, e.g. `User talk:User talk:Dbrant`
=> Fix creation of PageTitle for certain User Talk pages.

.github/workflows/android.yml, .github/workflows/android_branch.yml, .github/workflows/android_pr.yml, .github/workflows/android_smoke_test.yml
Updating the [setup-java](https://github.com/actions/setup-java) action to v2. 
- V2 supports custom distributions and provides support for `Zulu OpenJDK`, `Eclipse` `Temurin` and `Adopt OpenJDK`. V1 supports only `Zulu OpenJDK`.
- V1 supported legacy Java syntax such as 1.8 (same as 8) and 1.8.0.212 (same as 8.0.212). V2 dropped support for legacy syntax.
=> Update setup-java action to v2 for workflows

app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt, app/src/main/java/org/wikipedia/util/UriUtil.kt, app/src/test/java/org/wikipedia/util/UriUtilTest.java
The Echo API was recently updated where they changed the formatting of the URL fragment that leads to the section heading on the user's Talk page. The fragment is now in this format:
`https://en.wikipedia.org/wiki/User_talk:Dbrant_testing?markasread=229188641&markasreadwiki=enwiki#c-Dmitry_Brant-2021-10-01T12:36:00.000Z-test`
Therefore we need a bit more complex logic to parse the name of the heading from that fragment.
https://phabricator.wikimedia.org/T286424
=> Fix parsing of Talk topic fragment due to API updates.

app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.kt
Under our current logic, the animated transition bitmap (coming from the lead image in an article) will incorrectly remain visible, if the selected media is a video.
https://phabricator.wikimedia.org/T294508
=> Fix loading sequence of video thumbnail in Gallery.

app/src/main/java/org/wikipedia/notifications/NotificationPresenter.kt
This removes the "direct reply" functionality from the redesigned Notifications, while we figure out whether it will be possible to do, given the current APIs that we can use.
=> Remove direct replies for now.

app/src/main/res/layout/item_notification.xml
This makes the wiki-code box properly wrap around the language code text, making it much more readable, especially with three-letter (or greater) language codes:
=> Make Notification wiki code box expand to text length.

app/src/main/java/org/wikipedia/notifications/NotificationActivity.kt
We should count the unread notifications after filtering the list instead of always counting the whole list.
=> Fix: count unread items correctly when filtering language codes in NotificationActivity

app/src/main/java/org/wikipedia/gallery/ExtMetadata.kt
**Phab:** https://phabricator.wikimedia.org/T294869
Removed all unused fields to simplify serialization of ExtMetadata.
=> Removed unnecessary fields to simplify serialization

app/src/main/java/org/wikipedia/descriptions/DescriptionEditActivity.kt, app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
1. Turn on "Don't keep activities"
2. Go to any article and click on "edit article description"
3. Press the "home" button and go back to the app again.
4. Click on the "back" button and the app crashes.
=> Fix: send proper action value to avoid crash in DescriptionEditActivity

app/src/main/java/org/wikipedia/page/PageFragment.kt
https://phabricator.wikimedia.org/T184828
The way of preventing saving an incorrect prefix title to the database is by calling the `/page/summary` endpoint to get the correct title. 
In this case, the user tended to store "B*-tree" article, but it is actually a section inside the "B-tree" article, and the API request will be redirected to "B-tree#Variants" and that's why the offline reading list does not work properly.
=> Fix: handle redirected title properly before saving into database.

app/src/main/java/org/wikipedia/notifications/NotificationActivity.kt
Tweak PR that based on the comment in [2872](https://github.com/wikimedia/apps-android-wikipedia/pull/2872#issuecomment-963740971), which will not show the toast message and skip the "markReadItems" action since maybe some pages will be available if the user visited them before.
=> Skip markReadItems action when clicking on offline notification items

app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardItemFragment.kt
When running the Android Studio Kotlin code inspection, here's the suggestion from the `SuggestedEditsCardItemFragment`:
Non exhaustive 'when' statements on enum will be prohibited in 1.7, add 'null' branch or 'else' branch instead
=> Add "else" to the "when" statements in SuggestedEditsCardItemFragment

app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
If you are an anonymous user, and you go into our Editing workflow, you will now always be greeted with an Edit Notice that contains a warning about editing as an IP user. The problem is that this warning contains links for logging in, which will be bounced out to an external browser and won't actually make the user log in within the app.
Let's just suppress these types of edit notices, because we already show a warning about anonymous IP editing in the Preview screen before submitting an edit.
=> Don't show implicit edit notice for anonymous users.

app/src/main/java/org/wikipedia/csrf/CsrfTokenClient.kt, app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt
https://phabricator.wikimedia.org/T295811
This should also indirectly improve error handling in other places that depend on `CsrfTokenClient`.
=> Improve handling of errors when submitting Talk messages.

app/src/main/java/org/wikipedia/dataclient/CoreRestService.kt
You will notice there's a double `//` in the API request in `ArticleEditDetailsFragment`
=> Remove unnecessary slash in CORE_REST_API_PREFIX

app/src/main/java/org/wikipedia/feed/announcement/Announcement.kt, app/src/main/java/org/wikipedia/feed/announcement/AnnouncementClient.kt, app/src/test/java/org/wikipedia/feed/announcement/AnnouncementClientTest.kt, app/src/test/res/raw/announce_2016_11_21.json
This should be fast-tracked to production, so that announcements are shown properly for fundraising.
=> Fix deserialization of Announcements with version numbers.

app/src/main/java/org/wikipedia/edit/EditHandler.kt, app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
The `var pageProps` is not being used in `EditSectionActivity` and it is safe to be removed.
=> Remove unused variable from EditHandler and EditSectionActivity

app/src/main/java/org/wikipedia/dataclient/Service.kt, app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryResult.kt, app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt, app/src/main/java/org/wikipedia/notifications/NotificationPresenter.kt, app/src/main/java/org/wikipedia/page/PageActivity.kt, app/src/main/java/org/wikipedia/page/PageFragment.kt, app/src/main/java/org/wikipedia/page/PageTitle.kt, app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt, app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt
This will now automatically "resolve" the Talk page that corresponds to a regular page, without needing to construct the Talk title ourselves.
The Talk activity will now accept any regular page title, and will automatically query the API to get the correct Talk page.
https://phabricator.wikimedia.org/T297124
=> Dynamically resolve Talk page names.

app/src/main/java/org/wikipedia/notifications/NotificationRepository.kt
Technically it doesn't matter which wiki we fetch notifications from, as long as it's part of the CentralAuth collection of wikis. But it doesn't seem right to hardcode Commons wiki for getting notifications every time. This is a remnant of some previous logic that might have "required" getting it from Commons, but is no longer relevant.
It makes more sense to fetch notifications from the user's home wiki. And in fact this is already how the polling notification background worker does it.
=> Don't fetch all notifications from Commons wiki only.

app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt
In order to be consistent with the general article editing interface, we should send an `editAttempt` event when submitting a Talk message. (Since the edit could fail for various reasons, it's useful to know when an attempt was made.)
=> Add saveAttempt funnel event when submitting Talk messages.

app/src/main/java/org/wikipedia/notifications/PollNotificationService.kt
On some devices, it is not allowed to schedule a `JobInfo` without any constraints. At least one constraint must be specified, so let's require a NetworkType to be available, since that's what we need anyway.
=> Fix crash due to JobInfo request without constraints.

app/src/main/java/org/wikipedia/language/LanguageUtil.kt, app/src/main/java/org/wikipedia/page/PageTitle.kt
We used to use `startsWith` to find the `zh` variant, but `zh-yue` is not a part of the Chinese language variant and it causes some issues. 
https://phabricator.wikimedia.org/T298448
=> Fix: handle Chinese language variant and Cantonese correctly

app/src/main/java/org/wikipedia/notifications/NotificationPresenter.kt
This will need to be cherry-picked onto the current `beta` and `r` tags before going to production.
=> Fix crash due to missing PendingIntent flag.

app/build.gradle
This resolves a crash in Android 12 that was fixed in a recent version of this dependency:
* https://developer.android.com/jetpack/androidx/releases/work#2.7.0-alpha02
=> Update androidx work-runtime-ktx library, fixing potential crash.

app/src/main/java/org/wikipedia/page/PageActivity.kt
When we load edit history from the footer of the article, we load the "Special: History/%title" directly into the webview, but when loading it from the menu we are opening the external browser. They should be consistent with each other.
=> Fix: Consistency while loading edit history

app/src/main/java/org/wikipedia/page/PageFragment.kt, app/src/main/java/org/wikipedia/views/ObservableWebView.kt
https://phabricator.wikimedia.org/T254771#7617426
This fixes some scrolling issues when turning Focus Mode on/off, due to the fact that enabling focus mode in the article itself would change the height of the article, which would generate scroll events that would shift the position of the hideable toolbars.
=> Minor tweak and fix for Focus Mode.

app/src/main/res/values-qq/strings.xml
Per the request from Amir, we should add a note to the `qq/strings.xml` about using a language-specific URL for the disclaimer.
=> Add proper description for talk_edit_disclaimer in qq/strings

app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
Certain edit notices don't get parsed correctly by the API, and are received by us as HTML tags with no textual content in them. This causes us to show an edit notice that appears "blank".
This will filter out edit notices that don't contain any text content.
=> Don't show edit-notices that are parsed as blank.

app/src/main/java/org/wikipedia/activity/BaseActivity.kt
I've observed a case where a tooltip is shown, but won't go away:
* The new Toolbar customization tooltip:  If you open an article and start scrolling it (i.e. touch the screen and don't let go), and then the tooltip appears, the tooltip will remain there permanently, and is no longer dismissable. This is because of a race condition between showing the tooltip and nulling it in BaseActivity.
This changes the logic so that the tooltip is dismissed only on a "down" event (`DOWN` or `POINTER_DOWN`).
=> Dismiss tooltips only upon "DOWN" events.

app/src/main/java/org/wikipedia/dataclient/CoreRestService.kt, app/src/main/java/org/wikipedia/dataclient/Service.kt, app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt, app/src/main/java/org/wikipedia/diff/ArticleEditDetailsViewModel.kt, app/src/main/java/org/wikipedia/language/LanguagesListActivity.kt, app/src/main/java/org/wikipedia/language/LanguagesListViewModel.kt, app/src/main/java/org/wikipedia/util/Resource.kt, app/src/main/java/org/wikipedia/util/SingleLiveData.kt
In preparation for: https://phabricator.wikimedia.org/T299180
Using the new ViewModel pattern in this fragment means:
* No more RxJava, only coroutines + LiveData
* I introduced a new `SingleLiveData` helper class, to allow LiveData objects that should be consumed _once_ only, for example the result of a network call that should trigger a Snackbar to be shown. (we don't want the snackbar to be shown again upon screen rotation, which would happen with the standard `MutableLiveData`)
=> Refactor ArticleEditDetailsFragment to use ViewModel

app/src/main/java/org/wikipedia/dataclient/RestService.kt, app/src/main/java/org/wikipedia/dataclient/restbase/Metrics.kt
Based on Toni's comment, this API call can help us draw the graph on the edit history page.
https://phabricator.wikimedia.org/T299181#7698567
=> Add metrics REST API for showing graph in Edit history page

app/src/main/java/org/wikipedia/commons/FilePageActivity.kt, app/src/main/java/org/wikipedia/createaccount/CreateAccountActivity.kt, app/src/main/java/org/wikipedia/descriptions/DescriptionEditActivity.kt, app/src/main/java/org/wikipedia/descriptions/DescriptionEditSuccessActivity.kt, app/src/main/java/org/wikipedia/feed/configure/ConfigureActivity.kt, app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardItemFragment.kt, app/src/main/java/org/wikipedia/feed/topread/TopReadArticlesActivity.kt, app/src/main/java/org/wikipedia/gallery/GalleryActivity.kt, app/src/main/java/org/wikipedia/main/MainActivity.kt, app/src/main/java/org/wikipedia/page/PageActivity.kt, app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt, app/src/main/java/org/wikipedia/page/tabs/TabActivity.kt, app/src/main/java/org/wikipedia/random/RandomActivity.kt, app/src/main/java/org/wikipedia/search/SearchActivity.kt, app/src/main/java/org/wikipedia/search/SearchFragment.kt, app/src/main/java/org/wikipedia/settings/DeveloperSettingsActivity.kt, app/src/main/java/org/wikipedia/settings/SettingsActivity.kt, app/src/main/java/org/wikipedia/settings/languages/WikipediaLanguagesActivity.kt, app/src/main/java/org/wikipedia/settings/languages/WikipediaLanguagesFragment.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagEditActivity.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestionsActivity.kt, app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt, app/src/main/java/org/wikipedia/theme/ThemeFittingRoomFragment.kt, app/src/main/java/org/wikipedia/watchlist/WatchlistExpiryDialog.kt
We used to add `@Jvm` annotations for the communication between Java code and Kotlin code, and now it is not necessary between Kotlin code and it's safe to delete the annotations.
=> Hygiene: remove unnecessary Jvm annotations

app/src/main/java/org/wikipedia/language/AppLanguageState.kt, app/src/main/java/org/wikipedia/settings/Prefs.kt
* Move the logic of converting csv to lists into the Prefs class, so that consumers of Prefs never worry about how the prefs are actually stored internally.
* Remove explicit capitalization of language names when stating them in a joined list, since many language names actually shouldn't be capitalized.
=> Follow-up to LanguageState conversion.

app/src/main/java/org/wikipedia/page/shareafact/ShareHandler.kt
The long-press menu in the WebView was no longer showing our custom items (`Define` and `Edit here`).
Apparently in Android 12 we are required to `invalidate()` the ActionMode if we update it ourselves.
https://phabricator.wikimedia.org/T302078
=> Fix showing long-press menu over WebView in Android 12.

app/src/main/AndroidManifest.xml, app/src/main/java/org/wikipedia/page/PageFragment.kt, app/src/main/java/org/wikipedia/page/edithistory/EditHistoryItemView.kt, app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListActivity.kt, app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListViewModel.kt, app/src/main/res/layout/item_edit_history_separator.xml, app/src/main/res/values/strings.xml
* Update the package name from `edit_history` to `edithistory`, since we don't use an underscore in any other package names.
* The ViewModel class was incorrectly in the base `page` package instead of the `edithistory` package.
* Change the activity title from "Page history" to "Revision history", as specified in the designs.
* Change the nomenclature of "header" to the more accurate "separator", for reasons that will become apparent in future updates.
=> Edit history follow-up 1.

app/src/main/java/org/wikipedia/csrf/CsrfTokenClient.kt, app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt, app/src/main/java/org/wikipedia/notifications/NotificationPollBroadcastReceiver.kt
There are cases when fetching a CSRF token will cause us to re-login the current user (due to expired cookies, etc).
In such cases, there is no reason to use any other WikiSite than the default site, i.e. the "first" language selected in the app.
=> Use default WikiSite when re-logging-in from CsrfClient.

app/build.gradle, app/src/debug/java/LeakCanaryStub.kt
The latest version of LeakCanary no longer requires AppWatcher to be configured explicitly.
=> Update LeakCanary and fix deprecations.

app/src/main/java/org/wikipedia/edit/richtext/SpanExtents.kt, app/src/main/java/org/wikipedia/edit/richtext/SyntaxHighlighter.kt, app/src/main/java/org/wikipedia/edit/richtext/SyntaxRule.kt, app/src/main/java/org/wikipedia/views/PlainPasteEditText.kt, app/src/main/res/layout/activity_edit_section.xml
The result of a quick and random rabbit-hole.
* This creates a simple diff algorithm to determine only which spans need to be set, instead of using brute force to remove and re-set all spans at once, every time. This basically brings that part of the routine from O(n^2) to O(n), and will make it more suitable for lower-end devices.
* Transform CharSequences to arrays of `char`, for optimized indexing.
* Remove usage of `post()` and `Handler`s.
* Remove incorrect padding from the EditText.
=> Highly optimize syntax highlighting.

app/src/main/java/org/wikipedia/dataclient/Service.kt, app/src/main/java/org/wikipedia/diff/ArticleEditDetailsViewModel.kt, app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListActivity.kt, app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListViewModel.kt, app/src/main/java/org/wikipedia/views/EditHistoryStatsView.kt, app/src/main/res/layout/activity_edit_history.xml, app/src/main/res/values-qq/strings.xml, app/src/main/res/values/strings.xml
* Consolidate a couple of API calls.
* When scrolling, increase the activity title text to 2 lines.
* Remove basically duplicate string resource.
=> Follow-up to Statistics in Edit History.

app/src/main/java/org/wikipedia/page/edithistory/EditHistoryItemView.kt, app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListActivity.kt, app/src/main/res/layout/activity_edit_history.xml
* When in Compare mode, make the entire item into a tap target.
* Proper letter spacing of Compare button.
* Proper Navigation bar color when comparing.
https://phabricator.wikimedia.org/T299180
=> Design tweaks for Edit History screen, part 1.

app/src/main/java/org/wikipedia/page/SidePanelHandler.kt, app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt, app/src/main/java/org/wikipedia/talk/TalkTopicsProvider.kt
* It's more logical to (re)create the funnel when our pageTitle is updated by the Provider.
* The Provider actually modifies the PageTitle object that it receives, which can be unexpected. It should always make an internal `copy()` of the PageTitle.
=> Follow-up to TalkFunnel.

app/src/main/java/org/wikipedia/page/PageFragment.kt, app/src/main/java/org/wikipedia/views/PageActionOverflowView.kt, app/src/main/res/values-qq/strings.xml, app/src/main/res/values/strings.xml
Per conversation with Design, the label for removing an article from the Watchlist should be "Unwatch", to be more clear and be consistent with Mobile Web.
=> Update verbiage for unwatching an article.

app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt, app/src/main/res/menu/menu_talk.xml
This adds a "View edit history" menu item when looking at Talk pages, as approved by Design. Previously there was no way to see the full edit history of a talk page. This will also appear in the updated design refresh of Talk pages, but we can have this particular item before beginning the design refresh.
=> Add Edit History menu item in Talk Page activity.

app/src/main/java/org/wikipedia/settings/Prefs.kt
We currently have 10 possible PageActionItems, and our Prefs are _hard-coded_ to know about just those 10 items. If we ever add more PageActionItems, we will need to manually update the Prefs logic to account for the new items.
This PR makes the Prefs automatically detect any new PageActionItems, and append them to the end of the current list.
=> Simplify adding of new PageActionItems in the future.

app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.kt
At the moment, when looking at an article with a Lead Image, and after rotating the display, all the API calls that determine which call-to-action to show over the image are repeated unnecessarily.
(This will all be solved in a better way when we switch to a ViewModel, but until then, this will have to do.)
=> Don't make unnecessary API calls for Lead Image CTA after orientation change

app/src/main/java/org/wikipedia/dataclient/Service.kt, app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryPage.kt, app/src/main/java/org/wikipedia/suggestededits/ImageTag.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagDialog.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt
When the "image tags" feature was first rolled out, the workflow involved "reviewing" image labels that were suggested by an algorithm. However, shortly afterwards the machine suggestions were phased out, and the tags just became human-added. Therefore, the entire layer of automatic image labels (which we're still requesting in the API) is _completely unused_, and can be removed.
=> Remove unused API layer for ImageLabels.

app/src/main/java/org/wikipedia/Constants.kt, app/src/main/java/org/wikipedia/commons/FilePageFragment.kt, app/src/main/java/org/wikipedia/commons/ImageTagsProvider.kt, app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt, app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardItemFragment.kt, app/src/main/java/org/wikipedia/gallery/GalleryActivity.kt, app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.kt, app/src/main/java/org/wikipedia/notifications/NotificationRepository.kt, app/src/main/java/org/wikipedia/notifications/NotificationViewModel.kt, app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsItemFragment.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagDialog.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt, app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt, app/src/main/java/org/wikipedia/suggestededits/provider/EditingSuggestionsProvider.kt, app/src/main/java/org/wikipedia/userprofile/ContributionsFragment.kt, app/src/main/java/org/wikipedia/userprofile/UserContributionsStats.kt, app/src/main/java/org/wikipedia/views/ImagePreviewDialog.kt
There are a ton of places where we create new instances of `WikiSite` objects for Commons and Wikidata, when in fact these objects only need to be created once. The instantiation of `WikiSite` is actually a bit heavy, with text parsing and additional logic, so this is an optimization that could add up performance-wise.
=> Create constant WikiSite for Commons and Wikidata.

app/src/main/java/org/wikipedia/dataclient/page/PageSummary.kt
@sharvaniharan When you converted the PageSummary class to Kotlin in #2627, the `pageId` field was not converted correctly.
It's gone undetected for so long because we haven't actually needed it until now.
=> Fix deserialization of pageId.

app/src/main/java/org/wikipedia/views/PageActionOverflowView.kt, app/src/main/res/layout/view_page_action_overflow.xml
* Automatically dismiss the menu if the screen configuration changes.
* Put the menu in a ScrollView, so that all options are accessible on a very narrow viewport.
https://phabricator.wikimedia.org/T305346
=> Fix behavior of article overflow menu in split-screen mode.

app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt, app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
Whenever a `postDelayed` is performed, the result must always check if the current context still exists.
=> Prevent possible crash when highlighting text for editing.

app/src/test/java/org/wikipedia/analytics/eventplatform/EventPlatformClientTest.kt
I'm tired of this test failing randomly during our CI runs.
The test itself is not particularly useful -- it's basically testing whether `kotlinx.serialization` is working properly, which we know it does, and it's tested implicitly everywhere else in the app.
=> Disable flaky test of EventPlatformClient.

app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt, app/src/main/java/org/wikipedia/readinglist/database/ReadingList.kt
The diffing callback wasn't taking into account changes to the lists' name or description.
https://phabricator.wikimedia.org/T305555
=> Fix updating of reading lists after renaming.

app/src/main/java/org/wikipedia/Constants.kt, app/src/main/java/org/wikipedia/analytics/TalkFunnel.kt, app/src/main/java/org/wikipedia/page/PageFragment.kt, app/src/main/java/org/wikipedia/page/SidePanelHandler.kt
**Phab:** https://phabricator.wikimedia.org/T303772
What to measure:
Measure clicks on the bubble in MobileWikiAppTalk as "action" = "bubble_click" and "source" will be "article_bubble"
Add another new source as "article_side_panel" and log it as source when Talk page is opened from bubble->side panel -> talk page and "action" as always will be "open_talk"
This will equip us to measure the number of users who clicked the bubble, and of them, how many actually opened the full view talk page.
=> Analytics wiring for talk bubble

app/src/main/AndroidManifest.xml, app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListActivity.kt, app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListViewModel.kt, app/src/main/java/org/wikipedia/views/SearchAndFilterActionProvider.kt
@cooltey A few notes:
* We should try to never resort to using `configChanges` flags in our activities. I assume you added it to preserve the ActionMode state, but this should now be done in the ViewModel.
* Ideally the `ViewHolder` of an adapter should not be accessed from a different adapter, because it might not have been created yet (due to Activity re-creation), and if we really need to access it, it should be guarded by a null check.
=> Follow-up to Edit History

app/src/main/java/org/wikipedia/util/DateUtil.kt, app/src/test/java/org/wikipedia/util/DateUtilTest.kt
The timestamps returned by the new Talk API are formatted as ISO 8601, with millisecond resolution, e.g. `2022-04-26T11:13:47.000Z`, which is not handled correctly by our date parsing.
This simplifies the parsing pattern to allow all variations of ISO 8601 time.
=> Improve parsing of ISO 8601 dates.

app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt, app/src/main/java/org/wikipedia/diff/ArticleEditDetailsViewModel.kt, app/src/main/java/org/wikipedia/page/PageFragment.kt, app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListActivity.kt, app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListViewModel.kt
@sharvaniharan 
* The EditHistory activity itself gets the `pageId` of the current page _for free_ from the API, so it doesn't need to be fed into the EditHistory activity by callers.
* Same for the EditDetails fragment.
* Since these activities get the `pageId` for free, why not include it in the Events that we send?
=> Follow-up to EditHistory analytics (properly get pageId)

app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListActivity.kt, app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListViewModel.kt
In the EditHistory activity, the `pageId` is being ascertained while gathering the stats, which produces a `Flow`. However, when the ViewModel is first initialized, the Flow emits an empty object which causes the analytics Event to be constructed before the `pageId` is initialized.
Let's turn the stats into a LiveData instead of Flow, which simplifies things a bit and ensures that the Event will get a valid `pageId`.
=> Fix usage of pageId in EditHistory analytics.

app/src/main/java/org/wikipedia/feed/FeedCoordinatorBase.kt
Use requestOfflineCard(),
instead of inserting the card unchecked with appendCard(),
to prevent duplication.
https://phabricator.wikimedia.org/T282388
=> Error handling in FeedCoordinatorBase.kt.

app/src/main/java/org/wikipedia/page/PageActionTabLayout.kt
Long-pressing the toolbar buttons should show a toast with the full text of the button, especially when the text of the button is ellipsized because it's too long.
=> And standard long-press toasts to article toolbar.

app/src/main/java/org/wikipedia/dataclient/okhttp/UnsuccessfulResponseInterceptor.kt, app/src/main/java/org/wikipedia/settings/RemoteConfigRefreshTask.kt
We have an Interceptor that checks the response code and _throws an exception_ if the code is a failure. This is OK to do, but it means that OkHttp internally might no longer have a chance to `close()` the response body.
We need to explicitly close the response ourselves, to make sure no resources are leaked.
=> Fix possible resource leaks from unsuccessful network responses.
