wikimedia/apps-android-wikipedia

app/src/main/java/org/wikipedia/settings/RemoteConfigRefreshTask.kt

The URL for fetching our RemoteConfig parameters has been updated recently (or a long time ago, and we hadn't noticed?) and is now returning 404.
This is the new URL.

Update RemoteConfig URL.

---

app/src/main/java/org/wikipedia/page/ExclusiveBottomSheetPresenter.kt
app/src/main/java/org/wikipedia/page/PageFragment.kt

Sometime in recent history, we started explicitly dismissing any bottom sheet upon loading/reloading an article. However this is not actually correct behavior in the case of the Theme chooser. This updates the logic to dismiss the bottom sheet only if it's _not_ the Theme chooser.
https://phabricator.wikimedia.org/T308349

Don't dismiss Theme chooser on page reload.

---

app/src/main/java/org/wikipedia/util/DateUtil.kt

This passes our common date format strings into the "skeleton pattern" parser, which correctly passes it into a `@Synchronized` block, and also automatically respects RTL differences (mostly).

Follow-up to DateTime updates.

---

app/src/main/java/org/wikipedia/dataclient/Service.kt

These API calls actually need to include the `info` property, in order to receive the essential `lastrevid` field that is used to determine whether it's possible to navigate forward or backward.

Fix API call for edit history forward/back navigation.

---

app/src/main/java/org/wikipedia/search/SearchResultsFragment.kt

Deduplication of search results (from different sources) is currently broken because it was relying on the equality `==` operator of the `PageTitle` object, which was changed after conversion to Kotlin.
This fixes deduplication, and also streamlines it with Kotlin sugar.

Fix deduplication of search results.

---

app/src/main/java/org/wikipedia/page/PageActionTabLayout.kt

...so that we avoid a situation where the labels clash against each other:
https://phabricator.wikimedia.org/T306282

Add a bit of horizontal padding to PageActionTab items.

---

app/src/main/res/layout/fragment_search_recent.xml

Per Design suggestion, the "Add Wikipedia Languages" button should have a slightly darker background, so that it looks more like a button:

Tweak style of "add languages" button in Recent Searches.

---

app/src/main/java/org/wikipedia/activity/BaseActivity.kt
app/src/main/java/org/wikipedia/analytics/eventplatform/BreadCrumbLogEvent.kt
app/src/main/java/org/wikipedia/analytics/eventplatform/BreadCrumbViewUtil.kt
app/src/main/java/org/wikipedia/navtab/MenuNavTabDialog.kt
app/src/main/java/org/wikipedia/onboarding/OnboardingFragment.kt
app/src/main/java/org/wikipedia/page/PageActivity.kt
app/src/main/java/org/wikipedia/settings/LogoutPreference.kt
app/src/main/java/org/wikipedia/settings/PreferenceMultiLine.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
app/src/main/java/org/wikipedia/util/FeedbackUtil.kt
app/src/main/java/org/wikipedia/views/ViewUtil.kt
app/src/main/res/values/strings_no_translate.xml

* Remove a lot of unnecessary null checks and `let { }` blocks.
* Greatly simplify click detection, with system-provided touch slop and timeout values.
* Revert changes to `getTooltip` function, where the new `anchor` parameter did not do what it says.

Follow-up to breadcrumbs.

---

app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt

It is impossible (and does not make sense) to undo the initial revision of an article.

Don't display Undo button on the initial revision.

---

app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
app/src/main/res/layout/fragment_article_edit_details.xml

Now the position of the `errorView` in the diff view is not quite correct, it will show above the detail view and will not disappear after going forward/back to another revision.
1. Add "Queen angelfish" to the watchlist
2. Scroll down to the revision that was published by user `Dylan620`, which is the revision before it got protected. 
3. Enter the revision and you will see the error.
4. Go forward/back and the error view is still there.

Fix: show the ErrorView in a correct position in the diff view

---

app/src/main/java/org/wikipedia/userprofile/Contribution.kt
app/src/main/java/org/wikipedia/userprofile/ContributionsFragment.kt
app/src/main/java/org/wikipedia/userprofile/ContributionsItemView.kt

I think it's pretty useful to store the namespace of a contribution in the `Contribution` object itself, so that we don't need to construct a `PageTitle` object just to ascertain the namespace from the text.

Follow-up to updated contribution icons.

---

app/src/main/java/org/wikipedia/talk/TalkReplyActivity.kt
app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt
app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt
app/src/main/res/layout/activity_talk_topics.xml
app/src/main/res/menu/menu_talk.xml
app/src/main/res/values/styles.xml

* Apply explicit RTL to specific subviews, not the root view.
* Update order of overflow menu items, and fix tinting.
https://phabricator.wikimedia.org/T297617#7991442

Fix RTL consistency in Talk activities, and menu order.

---

app/src/main/java/org/wikipedia/history/HistoryFragment.kt
app/src/main/java/org/wikipedia/notifications/NotificationActivity.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
app/src/main/java/org/wikipedia/search/RecentSearchesFragment.kt
app/src/main/java/org/wikipedia/talk/TalkTopicHolder.kt
app/src/main/java/org/wikipedia/views/SwipeableItemTouchHelperCallback.kt

This adds a new callback for swipeable RecyclerView items, to indicate which items are swipeable on an individual basis.
(to be merged into the cofee-roll feature branch.)

Make coffee-roll non swipeable, by adding a callback function.

---

app/src/main/java/org/wikipedia/WikipediaApp.kt

To fix the issue, users cannot change the font size on the article page.

Fix: make sure fontSize can be changed correctly

---

app/src/main/java/org/wikipedia/page/PageFragment.kt
app/src/main/java/org/wikipedia/search/SearchResultsFragment.kt

We cannot use the equality `==` operator to compare `PageTitle` objects. Instead we must use the `.matches()` convenience function.
https://phabricator.wikimedia.org/T310416

Fix one more broken case of PageTitle equality.

---

app/src/main/java/org/wikipedia/analytics/eventplatform/BreadCrumbLogEvent.kt

The `stream` name of this event was different (??) from the name that's defined in the schema. Therefore these events were not being sent.
https://gerrit.wikimedia.org/r/c/schemas/event/secondary/+/794023

Fix incorrect stream name of BreadcrumbEvent object.

---

app/src/main/res/layout/item_talk_thread_item.xml

The button size should be `48dp` x `48dp` for accessibility reasons.

Increase overflow button size to 48dp in talk page thread view

---

app/src/main/java/org/wikipedia/analytics/eventplatform/BreadCrumbLogEvent.kt

The `primary_language_code` field is named differently (???) from what the server-side schema expects.

Fix breadcrumbs schema, for real.

---

scripts/bump-version-code.py

We will no longer have a "permanent" branch called `bumpVersionCode`. Instead, this branch will be created whenever a new bump occurs, just like any other pull request, and will be deleted automatically by GitHub when merged.

Simplify flow of bumping versionCode.

---

app/src/main/java/org/wikipedia/analytics/eventplatform/EventPlatformClient.kt
app/src/main/java/org/wikipedia/analytics/eventplatform/EventService.kt
app/src/main/java/org/wikipedia/dataclient/okhttp/HttpStatusException.kt

When we send improperly-formatted MEP events, the server actually responds with some useful debugging information. However, we were simply ignoring this information, and not passing it through to our `HttpStatusException` object.
For the `dev` build, we will now send events using the non-hasty call, which will give us the server-side error(s) properly, and then catch any errors in our exception class.

Improve debuggability of MEP events.

---

app/src/main/java/org/wikipedia/page/SidePanelHandler.kt
app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt
app/src/main/java/org/wikipedia/talk/TalkTopicHolder.kt
app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt

In `TalkTopicsActivity` we allow the user to change the language to see their talk page on a different wiki. But after changing the language and navigating to a topic in the new language, the navigation fails, and may even result in a crash. This is because a reference to a `PageTitle` object is maintained by `TalkTopicHolder`, when it can just get the pageTitle from the ViewModel instead.

Fix navigating to talk topics after switching language.

---

app/src/main/java/org/wikipedia/talk/TalkTopicHolder.kt
app/src/main/java/org/wikipedia/talk/TalkTopicsViewModel.kt

Looks like fix #3427 will make every topic show "(No subject)" with an empty content in the `TalkTopicActivity`.

Fix: use resolved pageTitle in TalkTopicHolder

---

app/src/main/java/org/wikipedia/page/PageActivity.kt
app/src/main/java/org/wikipedia/page/PageFragment.kt
app/src/main/java/org/wikipedia/page/SidePanelHandler.kt
app/src/main/java/org/wikipedia/talk/TalkTopicHolder.kt
app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt
app/src/main/java/org/wikipedia/talk/TalkTopicsViewModel.kt

Pardon the size of this follow-up, but this nails down a few inconsistencies that have bothered me for a while:
* The `pageTitle` object in TalkTopicsViewModel should always be nonnull, which simplifies everything.
* The `pageTitle` object in TalkTopicsViewModel should never be modified by external sources.
* TalkTopicsActivity should not have its own copy of `pageTitle`, and should always reference it from the ViewModel.
* Offload nullability state to the `viewModel` object maintained by SidePanelHandler, so that the viewModel can always have a nonnull PageTitle.

Follow-up to PageTitle in TalkTopics.

---

app/src/main/java/org/wikipedia/page/PageFragment.kt
app/src/main/java/org/wikipedia/page/SidePanelHandler.kt
app/src/main/res/layout/activity_page.xml

* Load the Talk topics only when the bubble is clicked, instead of automatically on every page view.
* Remove Beta feature flag.
(This will re-load the talk topics every time the bubble is clicked, which I think is OK.)

Load Talk topics into Side panel only when bubble is clicked.

---

app/src/main/res/layout/view_talk_topics_footer.xml

The content will touch the edge of the footer if we have a really long article title or edited by an anonymous IP editor

Add marginEnd to the talk topics footer

---

app/src/main/java/org/wikipedia/dataclient/okhttp/OkHttpWebViewClient.kt

For embedded videos that begin with a nonzero timestamp, there seems to be a problem with the way we're intercepting Web requests from the WebView and passing them through OkHttp.
This will add a special case (which we're already doing for OGG files) to no longer intercept loading WebM videos.
https://phabricator.wikimedia.org/T309105

Fix playback of timestamped WebM videos.

---

app/src/main/java/org/wikipedia/analytics/eventplatform/BreadCrumbLogEvent.kt

[facepalm] In my refactoring of breadcrumbs, I joined the declaration and assignment of a field, which we cannot do because of how these events are serialized.
(If declaration and assignment are joined, that field will not be serialized for some reason.)

Whoops: fix breadcrumbs serialization.

---

app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt

We were detecting a "coffee-roll" section based on if the `headingLevel` is equal to 99. Apparently this was actually unintentional from the Editing team, and was changed to 0. This is a more consistent way to detect a coffee roll section.

Fix detection and display of coffee-roll talk topics.

---

app/src/main/java/org/wikipedia/language/AppLanguageLookUpTable.kt
app/src/main/java/org/wikipedia/language/LangLinksActivity.kt

We still have some annoying edge-case behavior coming from the change of the language code from `be-x-old` to `be-tarask`, which is still not consistent in API responses. We need additional special logic to handle it properly.
https://phabricator.wikimedia.org/T311877

Fix minor inconsistencies in handling be-tarask language.

---

app/src/main/java/org/wikipedia/dataclient/Service.kt
app/src/main/java/org/wikipedia/talk/ArchivedTalkPagesViewModel.kt

* Remove a bunch of unnecessary parameters from the API call (those are useful for a full-blown prefix search like we do in the Search box, but not necessary for this specific case).
* Explicitly add a slash `/` to the search query, because we want to search for subpages. Not including the slash can potentially return unwanted results.
* The continuation parameter (`gpsoffset`) should be `null` on the first call, and should be an integer on subsequent calls.

Follow-up to archived talk pages.

---

app/src/main/java/org/wikipedia/dataclient/discussiontools/DiscussionToolsEditResponse.kt

When an edit to a Talk page fails (e.g. if your IP address is blocked, and so on), we're currently showing "Unknown error occurred", because we're not correctly accounting for errors in our model class.
By making the `DiscussionToolsEditResponse` object inherit from `MwResponse`, we will automatically get the functionality of parsing errors and throwing the correct exception when an error is returned.

Improve/fix error handling when posting DiscussionTools edits.

---

app/build.gradle
app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt

Version `1.5.0` breaks the menu items behaviors in some fragments, we will need to wait until they fix the issue.

Downgrade the androidx.fragment library to 1.4.1

---

app/src/main/java/org/wikipedia/page/PageActivity.kt
app/src/main/java/org/wikipedia/page/PageFragment.kt
app/src/main/java/org/wikipedia/page/ViewHideHandler.kt
app/src/main/java/org/wikipedia/settings/Prefs.kt
app/src/main/res/values/preference_keys.xml

* Shift the tooltip arrow a little further, so that it aligns as close as possible with the overflow button. It's still not perfect on all devices, but better.
* Explicitly disable the tooltip once the user taps the overflow menu.
* No longer abuse Prefs to communicate state between the activity and `ViewHideHandler`, and instead use a lambda.
https://phabricator.wikimedia.org/T312523

Improve positioning and state of "customize toolbar" tooltip.

---

app/src/main/java/org/wikipedia/talk/ArchivedTalkPagesActivity.kt

We are not using the `LinkPreviewDialog` in the `ArchivedTalkPagesActivity` and the callback should be removed.

Remove unused callback from ArchivedTalkPagesActivity

---

app/build.gradle

Refactor by making `computeVersionName()` into a static function.

Fix lint warnings in gradle file.

---

app/src/main/java/org/wikipedia/dataclient/okhttp/CacheControlInterceptor.kt

Our current method of overriding the Cache-Control header (for better offline access) means that we could potentially cache responses that contain session tokens, which should not actually be cached.

Security fix: don't cache network replies with private CacheControl.

---

app/src/main/java/org/wikipedia/settings/PreferenceMultiLine.kt

(Issue caught by TSG during regression testing!)
Certain Settings items, specifically the ones at the bottom that lead to an external link, don't have a `key` associated with them. Since the breadcrumbs logger expects a nonnull key, it causes a crash.

Fix crash when tapping certain Settings items.

---

app/src/main/java/org/wikipedia/dataclient/mwapi/MwVisualEditorResponse.kt
app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt

When an article doesn't have any editnotices, the structure is received as an empty array `[]` instead of an empty object `{}`, which is a weird MediaWiki convention of sending empty elements. This was throwing off our deserializer, and was causing an error to be printed in the log.
(This did not impact the presentation of edit notices.)

Improve deserialization of editnotices.

---

app/src/main/java/org/wikipedia/util/FeedbackUtil.kt

This shall be the new size of the arrow for all tooltips. This creates a more understated arrow, and is a better choice for certain harder-to-reach spots, such as the overflow button.

Tweak size of tooltip arrow.

---

app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt

Not sure why we weren't doing this already. (It's not possible to "thank" an anonymous IP editor.)

Don't show Thanks button for anonymous edits.

---

app/src/main/java/org/wikipedia/talk/TalkReplyActivity.kt
app/src/main/java/org/wikipedia/views/UserMentionInputView.kt

When you reply to a comment on a user's talk page, which was written by that same user, we don't need to prepopulate the @-ping, since that user will get a notification anyway.

Don't prepopulate ping message when replying on same user's talk page.

---

app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt

As it is currently, there's actually no way to invoke the "Success" activity after adding/editing a description, because we now have different `invokeSource` constants from the Edit Pencil and the Add Description CTA.
The original intention was to show the Success screen only when editing a description from within the PageActivity (i.e. NOT from suggested edits), so let's just do it that way.

Follow-up to registerForActivityResult in description editing.

---

app/src/main/java/org/wikipedia/dataclient/discussiontools/ThreadItem.kt

When we parse Talk topics, we expect the timestamp to be in ISO 8601 format, but actually sometimes it's formatted in the db format, which is causing us to fail to parse the date.
For example in the `Talk:Darjeeling` page, the dates are not parsed, and are not appearing correctly in our Talk screen.
This patch will handle both types of timestamps automatically.

Fix/improve parsing of Dates in talk thread topics.

---

app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
app/src/main/java/org/wikipedia/edit/FindInEditorActionProvider.kt
app/src/main/java/org/wikipedia/edit/SyntaxHighlightableEditText.kt
app/src/main/java/org/wikipedia/edit/richtext/SyntaxHighlighter.kt
app/src/main/java/org/wikipedia/views/PlainPasteEditText.kt
app/src/main/java/org/wikipedia/views/WikiTextKeyboardView.kt
app/src/main/res/layout/activity_edit_section.xml

This makes our wikitext editing experience much more performant, and more usable on a wider range of devices.
There are a few key insights that led to this improvement:
1. The `androidx.appcompat` library adds a lot of extra baggage to the `AppCompatEditText` component, which actually cripples its performance with large amounts of text. Our new editing component will _no longer inherit_ from `AppCompatEditText`, and instead inherit from the base platform `EditText`. This accounts for ~**80%** of the performance issue.
2. Syntax highlighting (as well as find-in-page) uses Spans, and the longer the text, the more Spans there will be, which also impacts performance. Instead of applying syntax highlighting to the entire text every time it's updated, we will now apply syntax highlighting _only …

Radically improve performance of wikitext editor.

---

app/src/main/java/org/wikipedia/page/PageTitle.kt

When setting a new Namespace on a PageTitle, we also update the `displayText`, but we should only do this if `displayText` was already non-empty, and not if it's null.
https://phabricator.wikimedia.org/T315940

Fix possible mangling of displayName in PageTitle.

---

app/build.gradle
app/src/main/java/org/wikipedia/watchlist/WatchlistFragment.kt

The old ways of menu handling are deprecated and need to be replaced with `MenuProvider` interfaces, for some reason. This PR provides an example of upgrading a fragment from old-style menu handling to the new style.
https://developer.android.com/jetpack/androidx/releases/appcompat#1.5.0

Update to AppCompat 1.5.0, and add example of using MenuProvider.

---

app/build.gradle

https://github.com/bumptech/glide/releases/tag/v4.13.2

Update Glide to 4.13.2.

---

app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryResult.kt

It looks like there were some recent changes to the backend API that are breaking our account creation flow, in particular our Captcha handling.
We expect the `authmanagerinfo` structure to contain an object with an id of `CaptchaAuthenticationRequest`, but now the id has become `MediaWiki\Extension\ConfirmEdit\Auth\CaptchaAuthenticationRequest`, which we don't account for. This PR will account for both variations.
To be investigated more fully later.
https://phabricator.wikimedia.org/T316403

Fix CreateAccount captcha handling broken by recent API changes.

---

app/src/main/java/org/wikipedia/edit/SyntaxHighlightableEditText.kt

The crash can occur if you go into the wikitext editor and add empty line(s) at the end of the text box.

Fix possible crash due to off-by-one error in wikitext editor.

---

app/build.gradle

This is now the proper way to make sure that our `OkHttpGlideModule` is compiled and included properly.

Fix kapt compilation of Glide module.

---

app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
app/src/main/java/org/wikipedia/edit/insertmedia/InsertMediaActivity.kt
app/src/main/java/org/wikipedia/edit/insertmedia/MediaSearchResult.kt
app/src/main/java/org/wikipedia/views/WikiTextKeyboardView.kt
app/src/main/res/layout/item_insert_media.xml

* Remove `ActivityResultLauncher` logic from WikiTextKeyboardView. This is a component that shouldn't have too much knowledge of who is using it and what PageTitle it's operating on. This is now changed to a callback method.
* Add background ripple effect when tapping to select image items.
* The `MediaSearchResult` class doesn't need to be serializable, and doesn't need to be a `data class`.

Follow-up to insert images into wikitext.

---

app/src/main/res/mipmap-anydpi-v26/launcher.xml

Android 13 adds support for themed icons - which includes the ability to have monochrome icons based on the overal system theme/wallpaper.
This change adds `launcher_foreground` as the monochrome icon.
---
Example (Alpha icon):

Add a monochrome icon to `launcher.xml`.

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/wikipedia/WikipediaFileProvider.kt

According to the documentation it's bad practice to declare the base `androidx.core.content.FileProvider` in our manifest. Instead it should always be a subclass, even if the subclass doesn't do anything special.

Properly use custom FileProvider class.

---

app/build.gradle

While building the app, we will see the following message about use `ksp` vs `kapt`:
```
app: 'annotationProcessor' dependencies won't be recognized as kapt annotation processors. Please change the configuration name to 'kapt' for these artifacts: 'androidx.room:room-compiler:2.4.3'.
```

Use kapt for androidx.room:room-compiler

---

app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
app/src/main/java/org/wikipedia/edit/insertmedia/InsertMediaViewModel.kt

This will solve the language variant issue when entering the `InsertMediaActivity` for the first time.
1. Go to `Elizabeth II` in en.wiki
2. Change the language to `zh-hant`
3. Edit the article and click on the insert media icon
4. You will see `伊丽莎白二世` (`zh-hans`) instead of `伊莉莎白二世` (`zh-hant`)

Fix: use displayText to search images in InsertMedia screen

---

app/src/main/java/org/wikipedia/dataclient/Service.kt

This API call has another special parameter that enables the parser to actually parse the wikitext of the message, which will expand templates and magic words.
https://phabricator.wikimedia.org/T317504

Fix API call for retrieving parsed messages with arguments.

---

app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
app/src/main/java/org/wikipedia/util/StringUtil.kt

https://phabricator.wikimedia.org/T318039
The recent update that changes our `SyntaxHighlightableEditText` to inherit from the platform `EditText` seems to have altered its behavior when programmatically highlighting a selection.

Fix/improve "edit here" selection.

---

app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListActivity.kt
app/src/main/java/org/wikipedia/views/EditHistoryStatsView.kt

1. Go to [Elizabeth II](https://en.wikipedia.org/wiki/Elizabeth_II)
2. Click on Edit history
You'll see the blank in the edit stats and no article title, that's because the following API returns HTTP 500:
https://en.wikipedia.org/w/rest.php/v1/page/Elizabeth_II/history/counts/editors
This PR hides the graph data and also the filter button since there are no numbers will be displayed in the components.

Fix: make sure showing article title and search bar when receiving 500 error code in EditHistoryListActivity

---

app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt
app/src/main/java/org/wikipedia/util/ResourceUtil.kt

* Improve conversion of `ColorInt` resource to CSS color, preserving opacity.

Follow-up to WebView in link preview.

---

app/src/main/java/org/wikipedia/readinglist/sync/ReadingListSyncAdapter.kt

Once again we're bitten by incorrect usage of the equals operator `==` when comparing `PageTitle` objects. This should not be used, and instead we should use the `.matches()` function.
This is because the `displayTitle` field could change between different instances of `PageTitle`, but the actual page that it represents is the same.
https://phabricator.wikimedia.org/T318319

Fix duplication of reading list pages when syncing.

---

app/src/main/java/org/wikipedia/page/PageFragment.kt
app/src/main/java/org/wikipedia/page/PageTitle.kt
app/src/main/java/org/wikipedia/readinglist/db/ReadingListPageDao.kt
app/src/main/java/org/wikipedia/readinglist/sync/ReadingListSyncAdapter.kt
app/src/main/java/org/wikipedia/search/SearchResultsFragment.kt
app/src/main/res/values/preference_keys.xml
app/src/test/java/org/wikipedia/page/PageTitleTest.java

* Switch (back?) to using the equality `==` operator for comparing `PageTitle` objects, because I'm tired of being bitten by having to use the `matches()` function for some reason.
* Add some logic to de-duplicate reading list entries, in case they were duplicated because of some previous bugs. This should happen automatically and transparently to the user.

Add logic to de-duplicate and fix consistency of reading lists.

---

app/src/main/java/org/wikipedia/commons/FilePageFragment.kt
app/src/main/java/org/wikipedia/commons/ImageTagsProvider.kt
app/src/main/java/org/wikipedia/language/LanguageUtil.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt
app/src/main/java/org/wikipedia/userprofile/ContributionsFragment.kt

https://phabricator.wikimedia.org/T318738
It looks like the `entityterms` API in Commons does not properly support `test` wiki, which also affects the function in SE image tags.

Fix: use uselang for entityterms API in testwiki

---

app/src/main/java/org/wikipedia/analytics/LinkPreviewFunnel.kt

The change was reverted, but I just made this update to stay at the latest rev id.

 Updated to latest revision id for MobileWikiAppLinkPreview

---

app/src/main/java/org/wikipedia/main/MainFragment.kt

...and also assign the `currentFragment` to a `val` so we don't have to cast it twice.

Replace deprecated BottomNavigationView listener with a proper one

---

app/build.gradle

Aside from being the latest SDK, it's also starting to become necessary for the latest AndroidX dependencies.

Upgrade SDK to 33 (Tiramisu).

---

app/src/main/java/org/wikipedia/feed/configure/ConfigureFragment.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
app/src/main/java/org/wikipedia/settings/SettingsFragment.kt
app/src/main/java/org/wikipedia/settings/languages/WikipediaLanguagesFragment.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsFragment.kt

I believe there are no more deprecation warnings about MenuProvider. (Old-style optionsMenu functions in Activity classes are not yet deprecated, and probably shouldn't be changed yet.)

Convert remaining Fragments to use MenuProvider.

---

app/build.gradle

The Room annotation processor wants the schema directory to be specified explicitly. This simply gives it the current schema location where the schemas already exist.

Fix gradle warning about Room schema location.

---

app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryResult.kt
app/src/main/java/org/wikipedia/language/LangLinksActivity.kt
app/src/main/java/org/wikipedia/language/LanguagesListActivity.kt
app/src/main/java/org/wikipedia/settings/languages/WikipediaLanguagesItemView.kt
app/src/main/java/org/wikipedia/userprofile/ContributionsFragment.kt
app/src/main/java/org/wikipedia/util/StringUtil.kt

The Kotlin standard library no longer wants us to use the `capitalize()` function, and prefers us to use `replaceFirstChar{}` instead for some reason. So let's put it into a utility function.

Remove deprecated usages of capitalize().

---

app/build.gradle

This is a much more complete solution than the previous PR. This updates the `schemaLocation` to be provided via `kapt`, allowing us to remove the weird `ksp` dependency.

Further improve room.schemaLocation declaration.

---

app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
app/src/main/java/org/wikipedia/edit/SyntaxHighlightableEditText.kt

https://phabricator.wikimedia.org/T318039
This uses a much more proper and consistent way of scrolling highlighted text into view.
This unfortunately introduces a little code duplication, but it's unavoidable because it involves usage of internal `EditText` fields.

Further improve scrolling to "Edit here" highlighted text.

---

app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
app/src/main/res/layout/view_wikitext_keyboard.xml

* Rearrange the order of a couple of icons.
* Explicitly show the keyboard after dismissing a link preview.
https://phabricator.wikimedia.org/T313223#8313690
(no need for Design review, just merge and review via Alpha)

Minor design tweaks in editing screen.

---

app/src/main/java/org/wikipedia/dataclient/wikidata/Entities.kt
app/src/main/java/org/wikipedia/gallery/GalleryActivity.kt
app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.kt

https://phabricator.wikimedia.org/T320617
The empty `statements` will return an empty list `[]` instead of `{}`, which causes the parsing error.

Fix: add additional logic to check empty statements in Entities object

---

app/src/main/java/org/wikipedia/analytics/LoginFunnel.kt

This seems to have gotten missed when adding a new enum parameter to the schema.
https://phabricator.wikimedia.org/T318584

Update revision number of Login schema.

---

app/src/main/java/org/wikipedia/analytics/ReadingListsFunnel.kt

This makes the necessary additions to the `ReadingListsFunnel`, so that it could be used by both Sharing and Exporting feature branches independently.
https://phabricator.wikimedia.org/T321949

Update ReadingListsFunnel, prelude to share/export lists.

---

app/src/main/java/org/wikipedia/analytics/ReadingListsFunnel.kt

Shay had to update some descriptions which bumped the rev id. No other consequences.

Revision id update for Schema:MobileWikiAppReadingLists

---

app/src/main/java/org/wikipedia/analytics/SessionFunnel.kt
app/src/main/java/org/wikipedia/dataclient/okhttp/OkHttpWebViewClient.kt

* Bump the `apiMode` field to 2.
* I don't think we actually need to check for `cacheResponse == null`, since if we have a nonnull `networkResponse`, it definitely means that a network transaction was made, and we want to log the latency of it.

Follow-up to latency logging.

---

app/src/main/java/org/wikipedia/dataclient/Service.kt
app/src/main/java/org/wikipedia/util/StringUtil.kt

In API calls where we ask for `varianttitles`, we should also ask for `displaytitle` because this will automatically decorate the title with HTML tags if necessary, which is much better for our presentation.
Before / After:

Improve retrieving rich-text displayTitles from API calls.

---

app/src/main/java/org/wikipedia/history/db/HistoryEntryWithImageDao.kt
app/src/main/java/org/wikipedia/readinglist/db/ReadingListPageDao.kt
app/src/main/java/org/wikipedia/search/SearchResultsFragment.kt
app/src/main/java/org/wikipedia/util/StringUtil.kt

This fixes a few long-standing bugs in our logic of searching PageTitles based on the `displayTitle` field.
* We allow the `displayTitle` to contain HTML tags, which is good, because we want the title to be rich-text, with italics, bold, etc. The problem is that the displayTitle could also contain other tags that we need to ignore, such as `<style class=...>`.
* Another issue emerges when searching through displayTitles. If we search for the word "class", it will return titles with the tag `<style class=...>` in them, so we need to pre-process the title before searching.
* And one last issue is **boldening** keywords within titles, which we do by injecting a `<strong>` tag around the keyword. To do this correctly, we need to detect whether the keyword is already inside an HTML tag, and …

Fix searching for keywords within displayTitles.

---

app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.kt
app/src/main/java/org/wikipedia/main/MainFragment.kt

In API 33, it's no longer necessary to explicitly obtain external storage permissions to write to the Downloads folder, therefore the usual ActivityResultContracts logic no longer works as expected.
https://phabricator.wikimedia.org/T323359

Fix: don't check for explicit storage permission in API 33+.

---

app/src/main/res/values/strings.xml

The MediaWiki convention is to aovid "successfully" in messages, as documented here:
https://www.mediawiki.org/wiki/Help:System_message#Avoid_jargon_and_slang

Remove unnecessary word from a message

---

app/src/main/java/org/wikipedia/main/MainFragment.kt

This is a very easy fix: The order of Intent handing in MainActivity matters: if we have an import intent, we must check for it first, before checking for an intent to continue reading an article.

Fix importing lists when in the middle of browsing article.

---

app/src/main/java/org/wikipedia/edit/summaries/EditSummaryFragment.kt

https://phabricator.wikimedia.org/T324940
It looks like the logic for localizing them was there, but not fully hooked up yet.

Fix localization of edit summary chips.

---

app/src/main/java/org/wikipedia/analytics/eventplatform/EventPlatformClient.kt

The original intention was for the app to crash when the MEP service returned an error. However, because the exceptions happen within an RxJava subscription, they are consumed without crashing.
Instead of crashing, let's show a large toast with the error returned by MEP, to serve as a signal that one or more MEP issues need to be investigated.

Show loud warning messages upon MEP errors (dev build only).

---

app/src/main/java/org/wikipedia/usercontrib/UserContribListViewModel.kt

When selecting contributions from "all" namespaces to be shown, it should really be from _all_ namespaces, instead of the four namespaces we offer for filtering.
https://phabricator.wikimedia.org/T325130

Fix showing contributions from all namespaces.

---

app/src/main/java/org/wikipedia/watchlist/WatchlistFragment.kt
app/src/main/java/org/wikipedia/watchlist/WatchlistViewModel.kt

* Remove unnecessary `fetch` call inside `viewCreated()`.
* Introduce a `Loading` UI state, for complete consistency in the spirit of ViewModel usage.
* Hooked up the Retry button in the ErrorView.

Follow-up to Watchlist ViewModel.

---

app/src/main/java/org/wikipedia/notifications/NotificationViewModel.kt

Use `asStateFlow()` for the `uiState`

Correctly expose immutable state flow in NotificationViewModel

---

app/src/main/java/org/wikipedia/analytics/SessionData.kt
app/src/main/java/org/wikipedia/analytics/SessionFunnel.kt

We're currently using `System.currentTimeMillis()` for tracking the latency of page loads, which is actually not the appropriate thing to use in this case.
The `currentTimeMillis()` function gives us the "current time" of the device, which can actually change at any moment:
- The device's clock might have drifted a bit, and suddenly receives an updated date/time from GPS or the network.
- The user moves from one time zone into another.
- The user changes the date/time on the device manually.
A much more appropriate function for measuring an "elapsed" time is the `nanoTime()` function, which gives the total nanoseconds of uptime for the current VM.
(Note that we should not be changing all instances of `currentTimeMillis()` into `nanoTime()`, since there are cases where …

Fix/improve tracking of latency on page loads.

---

app/src/main/java/org/wikipedia/search/SearchFragment.kt

Fixes the SearchFragment's toolbar's "up"-button missing it's accessibility label.

Bind the SearchFragment toolbar as the parent SearchActivity toolbar.

---

app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryPage.kt
app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListViewModel.kt

Display the date in the user's current time zone instead of the UTC date in an article's edit history. Related to #3721.

Fix edit date display in page history.

---

app/src/main/java/org/wikipedia/dataclient/Service.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListsImportHelper.kt

We should request the `info` along with `inprop=varianttitles|displaytitle` in order to save a proper title from different language variants and also save the correct language code in the database.

Fix the issue of showing incorrect language variants in an article title

---

app/src/main/res/values/strings.xml

The space appears in the beginning of the message, which is unusual, because messages usually don't begin with whitespace. It may also cause issue when exporting from translatewiki.
If the space is intentional, then I guess this can be closed without merging, but the reason for the space's presence there should be documented.
Thanks :)

Remove an unnecessary space from a message

---

app/src/main/java/org/wikipedia/search/SearchFragment.kt
app/src/main/java/org/wikipedia/search/SearchResultsFragment.kt
app/src/main/java/org/wikipedia/search/SearchResultsViewModel.kt

* Achieve total concurrency for all local searching (tabs / reading lists / history
* Don't force reloading all results upon language change, since this causes searches to be reloaded upon screen rotation.
* Correctly deduplicate local vs. network results.

Follow-up to search results ViewModel

---

app/src/main/java/org/wikipedia/activity/BaseActivity.kt
app/src/main/java/org/wikipedia/analytics/eventplatform/BreadCrumbLogEvent.kt
app/src/main/java/org/wikipedia/analytics/eventplatform/BreadCrumbViewUtil.kt
app/src/main/java/org/wikipedia/page/ExtendedBottomSheetDialogFragment.kt
app/src/main/java/org/wikipedia/readinglist/AddToReadingListDialog.kt
app/src/main/java/org/wikipedia/readinglist/MoveToReadingListDialog.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListItemView.kt
app/src/main/java/org/wikipedia/views/ReadingListsOverflowView.kt

* Added a breadcrumb event in the `onCreate` event of all `BottomSheetDialogs`, so that they'll be automatically logged when they're shown.
* This eliminates the need for the `logClick` function that was in the `AddToReadingListDialog`. (The `invokeSource` from that old event is also not necessary, because we have breadcrumbs leading up to it.)
* Added a general breadcrumb function for logging `MenuItem` clicks, which we can use for any menu event, until we figure out a completely generic way to log menus and other popup windows.

Follow-up to reading lists MEP, and enhance Breadcrumbs overall.

---

app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionSuggestionResponse.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionSuggestionService.kt

@sharvaniharan This adds the API layer for getting suggested descriptions.
* Notice the `requestSuggestion()` function, which makes the API request and then provides a TODO for doing something with the received suggestion(s).
* Also notice the response contains a `blp` field, which specifies whether the given article is a BLP (biography of living person). The idea will be: showing machine-suggested descriptions for BLP articles will only be available to editors with 50+ edits.
(This is mergeable now, since it's feature-flagged for pre-beta)

API groundwork for machine-generated descriptions.

---

app/src/main/java/org/wikipedia/offline/db/OfflineObjectDao.kt
app/src/main/java/org/wikipedia/recurring/DailyEventTask.kt
app/src/main/java/org/wikipedia/recurring/RecurringTask.kt
app/src/main/java/org/wikipedia/recurring/RecurringTasksExecutor.kt
app/src/main/java/org/wikipedia/recurring/TalkOfflineCleanupTask.kt
app/src/main/java/org/wikipedia/settings/RemoteConfigRefreshTask.kt
app/src/main/res/values/preference_keys.xml

This creates a new periodic task (to run every 7 days) to clean up saved offline talk pages that are older than 7 days. It works very simply by querying the DB for offline Talk responses and cross-referencing them with the state of the filesystem.
Also includes some light refactoring of the base RecurringTask class.
https://phabricator.wikimedia.org/T328677

Introduce periodic task to clean up stale offline Talk pages.

---

app/src/main/java/org/wikipedia/dataclient/ServiceFactory.kt

For our upcoming work on IP masking, it will be very important to be able to communicate with Beta Wikipedia, because IP masking will be deployed there first.
Currently, setting a custom MediaWiki base URL (in Developer preferences) is a bit broken and inconsistent. This fixes the inconsistency.

Fix usage of non-default / beta base URL for MediaWiki.

---

app/src/main/java/org/wikipedia/readinglist/ReadingListsReceiveSurveyHelper.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListsShareSurveyHelper.kt

This extends the surveys by 30 days after our projected release date of Mar 15, plus a couple extra days to allow for some uptake of the new app version.

Extend survey dates for Reading Lists by 30 days.

---

app/src/main/java/org/wikipedia/dataclient/Service.kt
app/src/main/java/org/wikipedia/dataclient/mwapi/UserInfo.kt
app/src/main/java/org/wikipedia/edit/summaries/EditSummaryFragment.kt

There's a user preference (settable on Desktop) that allows you to "Add pages and files I edit to my watchlist".
This is exposed via the `userinfo` API, and we can automatically check the box to "Watch" a page that is being edited, if we see that this preference is set.
https://phabricator.wikimedia.org/T331503
Surprisingly, we don't do any checking of any user options at all, so this also lays the groundwork (serialization logic) for checking other user options.

Correctly respect user option to add edited pages to watchlist.

---

app/src/main/java/org/wikipedia/commons/FilePageView.kt
app/src/main/java/org/wikipedia/history/HistoryEntry.kt

Currently, in the `FilePageFragment`, we always open the links in the descriptions on an external browser, even if the links are valid page links.
1. Search "The Sting" in `en.wiki`
2. Click on the lead image and go to the image page.
3. Scroll down to the Author section and click on the "Universal Pictures" link.

Handle valid page link in the FilePage properly

---

app/src/main/java/org/wikipedia/page/tabs/TabActivity.kt

This is an extremely minor crash that is occasionally observed in Play Store logs.

Fix potential minor crash when drawing Tab bitmap.

---

app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
app/src/main/java/org/wikipedia/page/PageFragment.kt

Currently our ActionMode for reference backlinks is broken, because it's erroneously relying on `MenuItemCompat.setActionProvider()`, which is incorrect because we're not actually using the Compat version of ActionMode in our PageActivity. This is because we're overriding menu items in the long-press menu of the WebView, which invokes a platform-level ActionMode, and doesn't get captured by SupportActionMode.
The longer-term solution will need to be some way to switch over to SupportActionMode, while still overriding the WebView's context menu.
This also improves the behavior of the ActionMode by clearing the highlighted items when the mode is destroyed. (Previously the items remained highlighted permanently.)
https://phabricator.wikimedia.org/T332706

Fix ActionMode for reference backlinks.

---

.github/workflows/android.yml

It is showing "Error: Unable to resolve action `dev-drprasad/delete-tag-and-release@v0.1.2`, unable to find version `v0.1.2`" on the `main` branch.

Update "delete-tag-and-release' library to v0.2.1 for Github action

---

app/src/main/java/org/wikipedia/util/ImageUrlUtil.kt
app/src/test/java/org/wikipedia/util/ImageUriUtilTest.kt

Notice that in today's featured article ("Nelson's Pillar") the lead image is broken.
This is because our regex for getting the appropriate thumbnail width is failing for this particular image, because the image filename itself contains a "px"-size as part of the name, which trips up the regex and produces an invalid URL.
This fixes and hardens our regex to catch both regular images from Commons, as well as paged documents such as PDF and Tiff files.

Fix/improve thumbnail URL transforming for certain URLs.

---

app/src/main/java/org/wikipedia/analytics/eventplatform/MachineGeneratedArticleDescriptionsAnalyticsHelper.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
app/src/main/java/org/wikipedia/util/ActiveTimer.kt

* We have a perfectly good pre-made component for tracking elapsed time (`ActiveTimer`).
* This will properly `pause` and `resume` the timer precisely when we want to measure just the "editing" time of the user.
* This allows us to send the elapsed time as part of all events, and it will be uniform.
* As a bonus, this **fixes** the `ActiveTimer` class, which was actually working wrongly before.

Final follow-up (for real!) to analytics.

---

app/src/main/java/org/wikipedia/descriptions/DescriptionEditActivity.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt

For the below scenario:
1. User is not logged in
2. Stumbles upon an article without a description
3. Enters the edit description screen
User will get put into group 0 - no suggestions or 1 - non-blp - and never in 2, because without them being logged in, we cannot find their edit count.
Since this alters the experiment, @JTannerWMF wants the gate to be tightened to logged in users.

Only logged in users should be included in the experiment

---

app/src/main/java/org/wikipedia/analytics/eventplatform/MachineGeneratedArticleDescriptionsAnalyticsHelper.kt

This crash is because users being in group0 which doesn't receive api response, and hence attempting to access the list objects produces a crash.
**Crash:**
https://play.google.com/console/u/0/developers/6169333749249604352/app/4972092403490495074/vitals/crashes/a09ba6c2234facc96fd131a793b0ffb9/details?installedFrom=PLAY_STORE&days=28&versionCode=50435

Crash fix: Do not log api info for group 0 users

---

app/src/main/java/org/wikipedia/analytics/eventplatform/MachineGeneratedArticleDescriptionsAnalyticsHelper.kt

When users are not logged in, the .start event inadvertently triggered group assignment in all cases. This check is to fix the issue of accidental assignment.

Fix: Do not assign group to users not in experiment

---

app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt

In cases where group1 users see blp articles, the spinners shows endlessly.
This fix hides the spinner once blp check is done
**Phab:** https://phabricator.wikimedia.org/T333733#8765947

Fix: hide descriptions button conditionally for group1 users

---

app/src/main/res/values/styles.xml

This is to follow up on the big color consolidation, and it looks like Snackbars got a bit broken, showing slightly incorrect colors and typeface.
This brings our Snackbars back to their correct state before the consolidation.

Fix/update snackbar styles.

---

app/src/main/java/org/wikipedia/views/PageItemView.kt
app/src/main/res/layout/item_page_list_entry.xml

You might have noticed that when you go to the History (Search) tab, and try to "swipe" items to remove them, they have a weird transparency that shows the red background incorrectly.
This fixes that.

Fix swipe background of History items.

---

app/build.gradle
app/src/main/java/org/wikipedia/dataclient/okhttp/OfflineCacheInterceptor.kt

This reverts #3874 by @Isira-Seneviratne, since it's causing sporadic crashes on a subset of devices in our Beta track.
The `desugar_jdk_libs_nio` library is _not mature enough_ for us to use. We do not need it.

Revert "Use Files methods in OfflineCacheInterceptor. (#3874)"

---

app/src/main/java/org/wikipedia/search/SearchFragment.kt

I believe this broke because of us updating `SearchResultsFragment` to use a ViewModel, while the main `SearchFragment` itself doesn't yet use a ViewModel, and so there may be some clashes of lifecycle events.
https://phabricator.wikimedia.org/T335139

Fix search execution when entering from intent.

---

app/src/main/java/org/wikipedia/categories/CategoryDialogViewModel.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
app/src/main/java/org/wikipedia/diff/ArticleEditDetailsViewModel.kt
app/src/main/java/org/wikipedia/edit/summaries/EditSummaryFragment.kt
app/src/main/java/org/wikipedia/history/HistoryFragment.kt
app/src/main/java/org/wikipedia/language/LangLinksViewModel.kt
app/src/main/java/org/wikipedia/language/LanguagesListViewModel.kt
app/src/main/java/org/wikipedia/notifications/NotificationViewModel.kt
app/src/main/java/org/wikipedia/page/PageFragment.kt
app/src/main/java/org/wikipedia/page/PageFragmentLoadState.kt
app/src/main/java/org/wikipedia/page/SidePanelHandler.kt
app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListViewModel.kt
app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewViewModel.kt
app/src/main/java/org/wikipedia/readinglist/LongPressMenu.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
app/src/main/java/org/wikipedia/search/RecentSearchesFragment.kt
app/src/main/java/org/wikipedia/search/SearchFragment.kt
app/src/main/java/org/wikipedia/search/SearchResultsViewModel.kt
app/src/main/java/org/wikipedia/talk/TalkTopicHolder.kt
app/src/main/java/org/wikipedia/talk/TalkTopicViewModel.kt
app/src/main/java/org/wikipedia/talk/TalkTopicsViewModel.kt
app/src/main/java/org/wikipedia/usercontrib/UserContribListViewModel.kt
app/src/main/java/org/wikipedia/util/ShareUtil.kt
app/src/main/java/org/wikipedia/watchlist/WatchlistViewModel.kt

When making Retrofit or Room calls from within a coroutine, it is not necessary to wrap it in an explicit `withContext(Dispatchers.IO) { }` block, since Retrofit and Room automatically provide main-safe `suspend` functions.
Pardon the size of this PR, but it's literally just removing a bunch of outer `withContext(Dispatchers.IO) {` calls that are redundant. Note the reduction in code size.

Remove unnecessary explicit IO dispatching from coroutines.

---

app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditLicenseView.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditUtil.kt

This will make description editing on TestWiki articles behave more like English Wikipedia, where descriptions will be written to the article instead of Wikidata.
This will have the benefit of being able to test the Captcha workflow on TestWiki, by adding a description that is known to trigger captcha.
https://phabricator.wikimedia.org/T331027

Enable local description editing for Test Wiki.

---

app/build.gradle
gradle.properties

When Android Studio upgraded the project to Gradle 8.0, it automatically enabled "full mode" in R8, which minifies the project too aggressively, stripping away things that are required at runtime. (We'll need to revisit our ProGuard rules if we want to actually enable full mode.)
This disables full mode explicitly (which is the same behavior as before gradle 8) and reenables minifying in production.

Disable R8 full mode, and reenable minification.

---

app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryPage.kt

There will soon be a new API for getting edit notices directly, instead of relying indirectly on the existing visualeditor API.
This new API is not deployed to production yet, but we can start building the underpinnings regardless.
https://phabricator.wikimedia.org/T337101

Underpinnings for updated Edit Notices API.

---

app/src/main/java/org/wikipedia/dataclient/Service.kt
app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryResult.kt
app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsFeedClient.kt
app/src/main/java/org/wikipedia/language/LangLinksViewModel.kt
app/src/main/java/org/wikipedia/search/SearchResults.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragmentViewModel.kt
app/src/main/java/org/wikipedia/usercontrib/UserContribStats.kt

This refactors our `UserContribStats` functions to become `suspend` functions, and no longer rely on rxjava.
This will indirectly benefit transitioning to IP masking.

Coroutinize user contribution stats.

---

app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt

- Don't show "Watch" menu item if not logged in.
- Use correct color for disabled state of buttons.

Tiny design tweaks in Diff activity.

---

app/src/main/java/org/wikipedia/analytics/metricsplatform/MetricsPlatform.kt

This is just for us to have more explicit control of the timing and capacity of the Metrics Platform logic.
(In particular, the default Stream Config fetch delay in the library is 30 seconds, which is much too frequent.)

Configure Metrics Platform parameters more explicitly.

---

app/src/main/java/org/wikipedia/analytics/metricsplatform/MetricsPlatform.kt

The existing parameters were incorrect (didn't match required enum values), and were resulting in server errors.

Send correct parameters to Metrics Platform AgentData.

---

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagEditActivity.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsItemFragment.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestionsActivity.kt

This confines the responsibility of showing the popup dialog entirely to the specific `SuggestedEditsImageTagsFragment`, and abstracts away the `onBackPressed` handler to the superclass.

Follow-up to Image Tags exit warning.

---

app/src/main/res/layout/view_plain_text_tooltip.xml

Looks like the Material button needs to inherit its style from ` style="@style/Widget.Material3.Button"` or else it is not getting the correct width.
Before fix:
After:

Fix: Tooltip button style

---

app/build.gradle
app/src/androidTest/java/org/wikipedia/main/LoggedInTests.kt
app/src/androidTest/java/org/wikipedia/main/SmokeTests.kt

We will now be able to run Espresso tests where the workflow automatically logs itself in (through the LoginActivity), using credentials that are pulled from the system environment variables.
You (or an automated test system) must set the environment variables `TEST_LOGIN_USERNAME` and `TEST_LOGIN_PASSWORD` with the credentials, and they will become available as `BuildConfig` constants, ready to be used within a test that requires them.

Underpinnings for Logged-in Espresso tests using env variables.

---

app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsFeedClient.kt

This fixes a very obscure potential crash when scrolling down the Feed when logged in (towards the Suggested Edits card). We make a request that fetches your contribution stats, and if that request fails with an error, we don't actually handle the exception.

Fix potential crash when fetching suggested edit stats for Feed.

---

app/src/main/java/org/wikipedia/diff/ArticleEditDetailsViewModel.kt
app/src/main/java/org/wikipedia/page/LinkHandler.kt

* This fixes a very obscure potential crash stemming from certain diff links.
* This also expands the types of diff links that can be handled by our `LinkHandler` and our Diff activity.
Our code was previously assuming that diff links always have a `diff=` attribute that equals the revision ID to diff against, like this:
https://en.wikipedia.org/w/index.php?title=User%3ADmitry_Brant%2Fsandbox&diff=1139503514&oldid=1132602357
But in fact, the `diff=` attribute can contain certain keywords, like `cur`, `prev`, and `next`:
https://en.wikipedia.org/w/index.php?title=User:Dmitry_Brant/sandbox&diff=cur&oldid=1139503514
These can now be handled by our code.

Improve parsing and handling of diff links.

---

app/src/main/java/org/wikipedia/language/AppLanguageState.kt

This is extremely rare, but possible on devices that have a very nonstandard language configuration that might throw us off.

Fix obscure potential crash during language initialization.

---

app/src/main/res/layout/view_custom_language_tab.xml

A simple change to fix a UI of Lang Tab view in Search. Language codes with more than 2 characters won't fit into the Tab view.
--
Before:
After:

[UI] Use "wrap_content" width for the search lang tab view instead of the hardcoded value

---

app/src/main/java/org/wikipedia/util/FeedbackUtil.kt
app/src/main/res/values/styles.xml

A holdover from the Material3/Components update:
* Snackbars should have a background of `border-color` and text color of `primary-color`.
https://phabricator.wikimedia.org/T336702

Design tweak: snackbar styles.

---

app/src/main/java/org/wikipedia/dataclient/Service.kt
app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryPage.kt
app/src/main/java/org/wikipedia/language/LangLinksActivity.kt
app/src/main/java/org/wikipedia/language/LangLinksViewModel.kt

There's a perfectly good MediaWiki API that we can use in place of (and more efficiently!) than the `page/summary` endpoint.

Stop using Summary endpoint for getting LangLinks variants.

---

app/src/main/java/org/wikipedia/analytics/metricsplatform/MetricsEvent.kt

Moving Article interaction logging to Metrics Platform to beta, in order to collect more data.

Move MP logging to Pre-prod

---

.editorconfig
app/src/androidTest/java/org/wikipedia/TestUtil.kt
app/src/androidTest/java/org/wikipedia/main/LoggedInTests.kt
app/src/androidTest/java/org/wikipedia/main/SmokeTests.kt
app/src/main/java/org/wikipedia/analytics/eventplatform/DestinationEventService.kt
app/src/main/java/org/wikipedia/dataclient/okhttp/OkHttpWebViewClient.kt
app/src/main/java/org/wikipedia/history/HistoryEntry.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListsShareHelper.kt
gradle/src/ktlint.gradle

This upgrades to the latest version of ktlint (we've been behind for a few versions):
https://github.com/pinterest/ktlint/releases/tag/0.50.0
The latest version has totally changed and expanded their collection of standard rules, so we need to update our `.editorconfig` file to match the rules that we were disabling before.
This also makes a few tweaks that play with the newest ktlint rules.

Update ktlint to 0.5.0.

---

app/src/main/java/org/wikipedia/page/AnnouncementDialog.kt

When using the MaterialDialog style with announcement dialogs, it makes them unnecessarily tiny, and also gives incorrect rounded corners.
For now, let's no longer use MaterialDialogBuilder for announcements, and use the standard AlertDialog.

Don't use MaterialDialogBuilder for announcement dialogs.

---

app/src/main/java/org/wikipedia/page/PageActivity.kt
app/src/main/java/org/wikipedia/page/PageFragment.kt
app/src/main/java/org/wikipedia/page/PageFragmentLoadState.kt

When reading an article, then tapping on the Tabs icon, and then tapping on the topmost tab which returns you to the current article, there is no need to reload it.
https://phabricator.wikimedia.org/T344247

Don't reload article unnecessarily when returning from Tabs.

---

app/src/main/java/org/wikipedia/main/MainFragment.kt

This seems to have mysteriously disappeared during our transition to Material 3 about ~two months ago, and should be put back.

Fix sending of ReadingLists receive_start event.

---

app/src/main/java/org/wikipedia/views/TextInputDialog.kt

Before: no label (title) on the input field
After:

Set input field hint properly in TextInputDialog

---

app/src/main/java/org/wikipedia/settings/AboutActivity.kt
app/src/main/java/org/wikipedia/util/FeedbackUtil.kt
app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/strings_no_translate.xml

This factors out a special function for composing an email (i.e. sending an Intent that contains email information), currently used only from AboutActivity for sending feedback, but will be used in the upcoming Image Recommendation and Patroller Tasks features.
This also includes a few new strings for use in Image Recommendations, which should be merged now, so that they'll be synced to TWN and get translated sooner.

Generalize composing feedback email.

---

app/src/main/java/org/wikipedia/views/PlainPasteEditText.kt

The way our `PlainPasteEditText` functions is actually not exactly right, and doesn't work on certain devices.
This should now make it work across all API versions and devices.

Correctly strip rich-text pasting on all API levels.

---

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageRecsFragment.kt

There is a request in the instrumentation doc to change the naming order to keep consistent with the rest: https://docs.google.com/presentation/d/10Twu9rnHy4XFzBjxRKDQPMKDVPDJDd9hBQXYwN7nilU/edit#slide=id.g1e4cd7273df_0_29

Change in edit comment tag naming order for IR

---

app/src/main/java/org/wikipedia/gallery/GalleryActivity.kt
app/src/main/java/org/wikipedia/gallery/MediaDownloadReceiver.kt
app/src/main/java/org/wikipedia/main/MainFragment.kt

Android 34 (beta) will now crash if we try to register a Receiver without specifying a `RECEIVER_NOT_EXPORTED` or `RECEIVER_EXPORTED` flag.

Fix possible crash due to Receiver on API 34.

---

app/build.gradle
app/src/main/java/org/wikipedia/feed/announcement/AnnouncementCardView.kt
app/src/main/java/org/wikipedia/notifications/NotificationPollBroadcastReceiver.kt
app/src/main/java/org/wikipedia/page/LinkMovementMethodExt.kt
app/src/main/java/org/wikipedia/settings/AboutActivity.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt
app/src/main/java/org/wikipedia/views/NotificationWithProgressBar.kt

Fix an issue on all current versions of Android where it is possible to activate links even when touching outside their line bounds. The issue is fixed on Android V.
**Before change**
https://github.com/wikimedia/apps-android-wikipedia/assets/31027858/2f684ec8-dabe-4983-b984-c6116364dc4a
**After change**
https://github.com/wikimedia/apps-android-wikipedia/assets/31027858/b0761582-1a82-43ea-85bd-102815b2821e

Avoid accidental link clicks

---

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageRecsFragment.kt

Couple more data wirings for image recs data. Simultaneously sending data to the legacy EditAttemptStep table as well.
Doc: https://docs.google.com/presentation/d/10Twu9rnHy4XFzBjxRKDQPMKDVPDJDd9hBQXYwN7nilU/edit#slide=id.g1e4cd7273df_0_29

IR data: EditattemptStep events

---

app/src/main/java/org/wikipedia/watchlist/WatchlistFilterActivity.kt
app/src/main/java/org/wikipedia/watchlist/WatchlistFilterTypes.kt

https://phabricator.wikimedia.org/T345869
This keeps the original logic of handling the filter value, in case we need to add something more in the future.
This PR also fixes the Reset button logic in the `WatchlistFilterActivity`.

Remove "All" option from Latest revision group and fix reset button in Watchlist filter

---

app/src/main/java/org/wikipedia/analytics/eventplatform/ImageRecommendationsEvent.kt

We had to change the stream name to keep it consistent with other streams and for it to be alphabetically listed properly.
**Phab:** https://phabricator.wikimedia.org/T346179

IR data: Change of stream name

---

app/src/main/java/org/wikipedia/readinglist/sync/ReadingListSyncAdapter.kt
app/src/main/java/org/wikipedia/readinglist/sync/SyncedReadingLists.kt

It's no longer being sent by the server anyway, and the app works perfectly fine without it.
https://phabricator.wikimedia.org/T346739

Remove hydrated Summary response from Reading List structure.

---

app/src/main/res/xml/preferences.xml

Visiting the settings page when the preference is not set explicitly is ending up setting this value to `true`. Since we want to keep them not signed for collection by default, let us turn this to `false`

Fix: Opt-in default value to `false`

---

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsRecentEditsFragment.kt

...And this updates the state of the filter icon in action mode.

Fix: empty message should only show if the filter count > 0

---

app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
app/src/main/java/org/wikipedia/diff/UndoEditDialog.kt

1. Update the snackbar messages.
2. Make the Undo dialog "Undo" button enabled by default.

Fix: update snackbar messages and make the Undo button enabled by default

---

app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsVandalismPatrolFragment.kt

Otherwise, the fragment will be added every time when you change the device's orientation.

Fix: incorrect behavior after changing device orientation in Patrol edit

---

app/src/main/res/layout-land/fragment_suggested_edits_cards.xml
app/src/main/res/layout/fragment_suggested_edits_cards.xml

In #4129, we added `MaterialToolbar` for `fragment_suggested_edits_cards`, but forgot to update the one in `land` folder.

Fix: add toolbar view to the SE cards landscape layout

---

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsRecentEditsViewModel.kt

This PR corrects the logic of the user experience filter where the "Learners" filter should be between Experienced users and newcomers.

Fix: Patroller Tasks user experience update

---

app/src/main/java/org/wikipedia/talk/template/TalkTemplatesTextInputDialog.kt
app/src/main/java/org/wikipedia/views/TextInputDialog.kt

Change from `binding.titleInput` to `binding.titleInputContainer` to avoid view jumps when losing target.

Fix: handle Patroller Tasks input field error message in the dialog correctly

---

app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt

We should collect the text by the time we hit the submit button.

Fix: get correct feedback input source for Patroller Tasks

---

app/src/main/java/org/wikipedia/navtab/MenuNavTabDialog.kt
app/src/main/res/layout/view_description_edit_success.xml

Somehow the texts on the screen show up after the first description edit were missing. Replace with a regular `TextView` since they are plain text.
Before:
After:

Fix: use TextView in the description edit success page

---

app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.kt
app/src/main/java/org/wikipedia/gallery/ImageInfo.kt
app/src/main/java/org/wikipedia/gallery/MediaDownloadReceiver.kt

Video playback is currently broken.
This is because our logic for selecting the best possible derivative for playback was not smart enough, and was blindly selecting the "last" derivative.
The list of derivatives can change, and indeed it has changed to include an unplayable derivative as the "last" one.
This improves the logic of selecting the proper derivative.
https://phabricator.wikimedia.org/T352315

Fix playback of videos in Gallery.

---

app/src/main/java/org/wikipedia/gallery/ImageInfo.kt

There are still some videos that are not playable. This is because some of the `derivative` candidates are encoded as OGG/OGV video, which is not supported by most versions of Android.
This will ensure that ogg derivatives are excluded when selecting the best derivative.

Further fix video playback!

---

app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt

I just noticed that when previewing a link in EditSectionActivity (using the wikitext keyboard button), the link preview doesn't appear at all.
It looks like this was never actually wired up (probably my fault).
This wires up the link preview dialog logic properly, _and also_ makes sure to show the exit-confirmation dialog if you tap through a link preview and exit the editing flow.

Fix showing link previews in EditSectionActivity.

---

app/build.gradle
gradle.properties

Having the `buildconfig=true` variable in `gradle.properties` is deprecated.

Fix warning from gradle build variable.

---

app/src/main/java/org/wikipedia/categories/CategoryActivity.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditActivity.kt
app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
app/src/main/java/org/wikipedia/gallery/GalleryActivity.kt
app/src/main/java/org/wikipedia/main/MainFragment.kt
app/src/main/java/org/wikipedia/page/PageActivity.kt
app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt
app/src/main/java/org/wikipedia/talk/TalkReplyActivity.kt
app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt
app/src/main/java/org/wikipedia/talk/template/AddTemplateActivity.kt

This removes a couple of callbacks that never needed to be callbacks, thereby removing over _100 lines of unnecessary code_.

Remove unnecessary callbacks from LinkPreviewDialog.

---

app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
app/src/main/res/layout/fragment_article_edit_details.xml

It is not correct to use a `RecyclerView` inside a `NestedScrollView`. This will cause the RecyclerView to unroll all of its items and display them all at once, which defeats the purpose of the RecyclerView.
If we ever need to display a "header" at the top of a RecyclerView, then we should do it in one of two ways:
* The header should be its own View, and placed inside a composite Adapter in the same RecyclerView.
* Use a AppBarLayout with CollapsingToolbarLayout (with header content inside the collapsing layout), which provides a special Behavior that lets a RecyclerView work properly.
This PR is simpler than it looks -- it just wraps the header views in an AppBarLayout instead of NestedScrollView, which improves performance significantly when there are many items in the list of diffs.

Correctly optimize display of Diff lines in RecyclerView.

---

app/src/main/java/org/wikipedia/util/DateUtil.kt

In our DateUtil class we use a static cache for caching date formatting objects, which are expensive. However, the `DateFormat.getBestDateTimePattern()` function is also expensive, and should not be called every time a date is rendered. It can be easily rolled into the same format cache.
This will provide a slight speedup of rendering date fields, particularly in long lists of items that contain dates.

Optimize date format cache.

---

app/build.gradle

Reverts wikimedia/apps-android-wikipedia#4352
This introduced some major visual regressions, giving certain components a pink hue:
When reintroducing this new version of the Material library, please also fix the corresponding styles.

Revert "Update material-components-android library version to 1.11.0"

---

app/build.gradle
app/src/main/res/values/styles.xml

https://github.com/material-components/material-components-android/releases/tag/1.11.0
https://github.com/material-components/material-components-android/commit/2114a11378fd801b32cd7431bb8a2c94de4f462c
Add `paper_color` to the related `colorSurfaceContainer` styles.

Update material-components-android to 1.11.0 and update styles

---

app/build.gradle
app/schemas/org.wikipedia.database.AppDatabase/25.json

This fixes a warning about a missing `schemaLocation` parameter, which I believe we fixed previously, but must have gotten broken when we switched from kapt to ksp.
Now that the `schemaLocation` is set correctly, it auto-generated the schema for our current database version (25), which has been missing until now.

Correctly set `schemaLocation` for the Room annotation processor.

---

build.gradle

https://github.com/JetBrains/kotlin/releases/tag/v1.9.22
You will see the following message when trying to run `./gradlew ktlint`
> ksp-1.9.22-1.0.16 is too new for kotlin-1.9.20. Please upgrade kotlin-gradle-plugin to 1.9.22.

Update Kotlin gradle plugin version to 1.9.22

---

app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
app/src/main/res/layout/fragment_article_edit_details.xml

When logged out, the bottom bar of buttons in the Diff view looks incorrect, because each of the buttons is hidden, but the bar itself is still visible, causing an empty space.

Fix behavior of Diff bottom bar when logged out.

---

app/src/main/java/org/wikipedia/richtext/CustomHtmlParser.kt
app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt

Previously we were incorrectly handling nested ordered lists (lists within lists).
We were also making incorrect assumptions about the structure of lists, i.e. assuming that list items are separated by a newline `\n`, which is not always the case.
(as seen in https://en.wikipedia.org/wiki/User_talk:QTE-Test3-WMF)
This fixes the logic to handle any kind of ordered list correctly, and with no assumptions of structure.

Correctly handle nested list tags in Html.

---

app/src/main/java/org/wikipedia/feed/news/NewsFragment.kt
app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayCardView.kt
app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayPagesViewHolder.kt
app/src/main/java/org/wikipedia/feed/topread/TopReadFragment.kt
app/src/main/java/org/wikipedia/main/MainFragment.kt
app/src/main/java/org/wikipedia/page/ExclusiveBottomSheetPresenter.kt
app/src/main/java/org/wikipedia/page/PageActivity.kt
app/src/main/java/org/wikipedia/page/PageContainerLongPressHandler.kt
app/src/main/java/org/wikipedia/page/PageFragment.kt
app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt
app/src/main/java/org/wikipedia/random/RandomFragment.kt
app/src/main/java/org/wikipedia/readinglist/MoveToReadingListDialog.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListBehaviorsUtil.kt
app/src/main/java/org/wikipedia/search/SearchFragment.kt

This PR simplified the logic of adding/moving an article to the list, which now can use either `ReadingListBehaviorsUtil.addToDefaultList` or `ReadingListBehaviorsUtil.moveToList` with an optional dialog dismiss listener.
This PR also fixed the issue that some views have incorrect invoke sources implemented.

Simplify the logic of adding/moving article to reading list

---

.github/workflows/android.yml
.github/workflows/android_branch.yml

The current Github action is failed. Update to the latest build tool fixes the issue.
https://github.com/wikimedia/apps-android-wikipedia/actions/runs/7468471414/job/20323975669
```
Error: Couldnt find the Android build tools @ /usr/local/lib/android/sdk/build-tools/29.0.3
Error: Unable to locate executable file: /usr/local/lib/android/sdk/build-tools/29.0.3/zipalign. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

Use the newer version of build tools for the Github sign-android-release action

---

app/src/main/java/org/wikipedia/search/SearchResultsFragment.kt
app/src/main/java/org/wikipedia/search/SearchResultsViewModel.kt

The previous Search fixes were correct, but there was one other issue: the `PagingDataAdapter` that was used by the RecyclerView wasn't scrolling back to the top when the search term was updated. This caused updated search results to get populated above the current scroll position, resulting in a bit of confusion.
This fixes the scroll behavior by leveraging `SearchResultsDiffCallback`, or rather un-leveraging it, since we know that all search results are unique (done at the level of the PagingSource).

Further improve/fix Search interface.

---

app/src/main/java/org/wikipedia/places/PlacesFragment.kt

We really don't need to re-query the API if the user moves the map by 1 pixel  ¯\\_(ツ)\_/¯

Re-introduce minimum movement constraint for querying map updates.

---

app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt
app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewViewModel.kt
app/src/main/java/org/wikipedia/places/PlacesFragment.kt
app/src/main/res/layout/fragment_places.xml

This PR also fixes:
1. Use `historyEntry.source == HistoryEntry.SOURCE_PLACES` instead of sending `fromPlaces` boolean.
2. Do not show the "x" icon by default on the search bar.

Places: reset the search bar text and icon after dismissing the link preview dialog

---

app/src/main/java/org/wikipedia/analytics/eventplatform/BreadCrumbLogEvent.kt

This automatically detects if a screen that's being shown contains an `InvokeSource` in its intent, and logs it as part of the event in a structured way, making breadcrumbs a bit more powerful.
This will automatically enable us to measure incoming clicks from widgets, without extra schemas.

Log invokeSource in breadcrumbs "show" events.

---

app/build.gradle
app/src/main/java/org/wikipedia/analytics/metricsplatform/ArticleEvent.kt
app/src/main/java/org/wikipedia/analytics/metricsplatform/MetricsEvent.kt
app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt

- Bump Metrics Platform library version to 2.1
- Update `MetricsEvent` submit methods to require stream name
- Update `ArticleEvent` methods to pass in required stream name
- Overload `getPageData` method to accept `PageSummary` (to populate `page_wikidata_qid`)
- Overload constructor for `ArticleLinkPreviewInteraction`
Bug: [T355360](https://phabricator.wikimedia.org/T355360)

Update Metrics Platform version, MetricsEvent, ArticleEvent

---

app/src/main/java/org/wikipedia/util/FeedbackUtil.kt
app/src/main/res/layout/view_plain_text_tooltip.xml

The Balloon library has an issue where it incorrectly inflates our custom View where the "Got it" button gets an incorrect width.
We were fixing this by giving it a `minWidth`, and optimizing the minWidth for English, but this is not a complete solution and causes weird overflow behavior like this:
This will now explicitly measure the width of the text that the button is supposed to be, and update its layoutParams explicitly.

Fix width calculation of tooltop "Got it" button.

---

app/src/main/java/org/wikipedia/analytics/eventplatform/AppInteractionEvent.kt
app/src/main/java/org/wikipedia/analytics/eventplatform/DonorExperienceEvent.kt
app/src/main/java/org/wikipedia/analytics/eventplatform/EventPlatformClient.kt
app/src/main/java/org/wikipedia/analytics/eventplatform/PatrollerExperienceEvent.kt

It's not necessary to have a static `STREAM_NAME` that needs to be set before an `AppInteractionEvent` is instantiated, and in fact this creates a race condition.
We can simply pass the stream name directly as a constructor parameter, and mark it as Transient for serialization.
The resulting serialized objects are exactly the same.

Refactor and remove race condition from AppInteractionEvent instantiation.

---

app/src/main/java/org/wikipedia/places/PlacesFragment.kt

The thumbnails will still be applied to the markers even if the `isImageDownloadedEnabled` is off.

Respect isImageDownloadedEnabled setting in Places

---

app/src/main/java/org/wikipedia/readinglist/LongPressMenu.kt

1. Go to Places
2. Save an article from the map.
3. Click on the saved article, and click on "Saved" to see the popup menu.

Fix: use null-safe for LinkPreviewDialog action menu options

---

app/src/main/java/org/wikipedia/places/PlacesFragment.kt

We should use the `lastKnownLocation` from the `locationComponent` instead of the last "map" location.

Fix: use lastKnownLocation instead of the last map location for distance

---

app/src/main/java/org/wikipedia/views/LangCodeView.kt
app/src/main/java/org/wikipedia/views/TabCountsView.kt
app/src/main/res/layout/view_lang_code.xml
app/src/main/res/layout/view_tabs_count.xml

https://phabricator.wikimedia.org/T354522#9501302

Update tab and language icon style for long text

---

app/src/main/java/org/wikipedia/widgets/WidgetProviderFeaturedPage.kt

This splits off the (minor) data instrumentation updates in the big Widgets PR, so that this change can be included in our next beta. It simply includes an `InvokeSource` when launching from the widget, so that BreadCrumbs events will pick it up automatically.
(The main Widgets PR will wait until the next release after that.)
https://phabricator.wikimedia.org/T353471

Instrumentation updates for Widgets.

---

app/src/main/java/org/wikipedia/places/PlacesFragment.kt

1. Go to Places.
2. Click on the marker and see the `LinkPreviewDialog`
3. Change the device's orientation.
4. The content in the `LinkPreviewDialog` becomes empty

Fix: dismiss the LinkPreviewDialog when changing device's orientation

---

app/src/main/res/layout/fragment_places.xml

In dark mode, when loading the Places screen, I was seeing a flash of white background before the map starts loading.
This is because we must explicitly set the foreground loading color attribute in the MapView.

Fix foreground color of MapView while loading.

---

app/src/main/java/org/wikipedia/places/PlacesFragment.kt
app/src/main/res/layout/fragment_places.xml

The insets were being applied incorrectly to the RecyclerView:
This fixes and simplifies usage of insets.

Fix/improve handling of insets in Places.

---

app/src/main/java/org/wikipedia/usercontrib/UserContribFilterActivity.kt

1. Go to More.
2. Click on Contributions.
3. Click on Filter contributions.
4. See the selected wiki language, and click on update app languages.
5. Remove the selected wiki language from the list.
6. Go back to the filter contributions page.

Reset selected language if the previous selected language was deleted

---

app/src/main/java/org/wikipedia/main/MainActivity.kt
app/src/main/java/org/wikipedia/places/PlacesFragment.kt
app/src/main/java/org/wikipedia/places/PlacesFragmentViewModel.kt
app/src/main/res/xml/developer_preferences.xml

After some preliminary findings, we want to update the logic of when the survey is shown:
Instead of showing after the user _exits_ the Places screen, we want to show the survey the _second time that the user enters_ the Places screen.
https://phabricator.wikimedia.org/T355140#9521475
Incrementing the `Prefs` counter for showing the survey is now moved into the ViewModel, so that rotating the screen doesn't count as "entering" the activity.

Update logic for Places survey.

---

app/build.gradle
app/src/main/java/org/wikipedia/analytics/metricsplatform/MetricsPlatform.kt

- Make `app_version` integer
- Bump MP lib to 2.2
Bug: [T356938](https://phabricator.wikimedia.org/T356938)

Fix AgentData property, bump Metrics Platform library version

---

app/src/main/res/layout/activity_page.xml

The hint in the Search bar must be a single line with ellipsis; otherwise it overflows and looks weird:

Ensure that search bar hint is single-line.

---

app/build.gradle
app/src/main/java/org/wikipedia/page/PageActivity.kt

We try to handle the exception that is thrown when the System WebView is being updated, but we're no longer handling it in the right place. This is probably a vestige of updating to ViewBindings.
This will now handle such exceptions correctly, by handling it in `onStart()`, which is where child fragments (`PageFragment`) are inflated.

Correctly handle WebView update exception.

---

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt

We did not show the IP-blocked message correctly for a long time, and it will show an empty screen with only the user contribution card in the "Edits".
I have a VPN enabled and it looks like the IP from the VPN has been blocked.
Demo: https://youtube.com/shorts/pdNHG2bIWIQ

Show IP blocked message in Suggested Edits correctly

---

app/build.gradle
app/src/main/java/org/wikipedia/analytics/metricsplatform/ArticleEvent.kt
app/src/main/java/org/wikipedia/analytics/metricsplatform/MetricsPlatform.kt

- Update references to updated custom schema versions
- Include `app_version_name` in `AgentData` object
- Update parameters for 2 article instruments
- Bump MP version to 2.3 to fix session_id
Bug: [T357371](https://phabricator.wikimedia.org/T357371)
Bug: [T357181](https://phabricator.wikimedia.org/T357181)
Depends-On: https://gerrit.wikimedia.org/r/c/schemas/event/secondary/+/1003810

Metrics Platform minor updates, bump version

---

app/src/main/java/org/wikipedia/places/PlacesFragment.kt

This (minor) crash occurs when a user declines the Location permission, then goes on to tap on map markers to see a link preview.

Fix possible crash when tapping on map markers with location permissions disabled.

---

app/src/main/java/org/wikipedia/random/RandomFragment.kt

I found a spot that could potentially lead to the obscure `TransactionTooLarge` exceptions that we see occasionally in the crash logs. If the user goes to the Randomizer activity, and flips through very many (hundreds) of RandomFragments, the ViewPager adapter actually keeps a reference to all those fragments, and when the activity is stopped, it tries to save the state of all those fragments.
We therefore need to _explicitly remove_ fragments that are sufficiently far into the history of the ViewPager. We actually already do this in the SuggestedEdits view pager, but not in the Randomizer.

Possibly fix TransactionTooLarge crashes.

---

app/src/main/java/org/wikipedia/analytics/eventplatform/EventPlatformClient.kt

The previous improvement to concurrency actually helped expose a slightly larger issue:
The `@Synchronized` annotations were placing a lock on the entire `EventPlatformClient` object, which is too much, and can potentially cause an ANR, since some of the synchronized functions could hold on to the lock for too long.
This updates STREAM_CONFIGS to be a built-in `ConcurrentHashMap`, and then the queueing/dequeueing of actual events is synchronized on the `QUEUE` object itself, making it correctly granular.

Further improve concurrency in EventPlatformClient.

---

app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewViewModel.kt

When we integrated Places into the LinkPreviewDialog, we introduced an API call to see if the article is currently in the user's watchlist. However, this call is being made serially, while it could easily be made in _parallel_ with other calls.

Improve performance of Link Preview when used in Places.

---

app/src/main/java/org/wikipedia/dataclient/Service.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragmentViewModel.kt

The edit counts that we get from Wikidata should be only for the Main namespace. If a user makes edits in the non-main namespace, our logic to fetch pageviews breaks, and we show an error.
https://phabricator.wikimedia.org/T358845

Fix fetching Wikidata edit counts.

---

app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
app/src/main/java/org/wikipedia/edit/preview/EditPreviewFragment.kt

This is a light refactor of the edit preview fragment which decouples it from the general editing workflow, and makes it usable from other activities where a preview will be necessary, such as TalkReplyActivity.
(No changes to existing behavior.)

Refactor EditPreviewFragment to be usable from other activities.

---

app/src/main/java/org/wikipedia/diff/ArticleEditDetailsViewModel.kt

When we started adding our "hashtag"-style comments into the edit summary, we forgot that the Rollback action _automatically generates_ a summary (if the provided summary is blank). So when we provide just the hashtag summary, it overrides and erases the default summary, leading to an edit summary that is not descriptive enough.
This updates our logic to manually fetch the standard summary message, then append our hashtag to it, and then submit the combined message as the edit summary, which will result in a much improved and informative summary when rolling back.
https://phabricator.wikimedia.org/T359006

Correctly insert edit summary when rolling back.

---

app/src/main/java/org/wikipedia/main/MainFragment.kt
app/src/main/res/layout/fragment_main.xml

In the current app version, when you go to Saved or Search, and tap "Filter" to open the search action mode, the bottom navigation bar will be invisible, but the border will still be there.
This PR fixes that and moves from `FrameLayout` to `ConstraintLayout` so the bottom space will be organized properly.

Change FrameLayout to ConstraintLayout in fragment_main

---

app/src/main/java/org/wikipedia/edit/EditHandler.kt

This is extremely minor, but there is a remote possibility for the `fragment` to become null before the menu is dismissed.

Fix extremely obscure potential crash in Edit menu.

---

app/src/main/res/layout/dialog_description_suggestion_report.xml
app/src/main/res/menu/menu_suggested_edits.xml

In the popup dialog for reporting a problem with machine-generated descriptions (a really obscure place!) we're using a `drawable` icon that is actually coming from a library (the `chrome-like-tab-switcher` library) and it's not even a vector drawable, but a PNG.
Let's use a standard "close" drawable here, and untangle this dependency.
This also fixes an incorrect `tint` attribute in the menu when looking at suggested article descriptions.

Fix incorrect Close icon in MGAD problem report dialog.

---

app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt
app/src/main/res/layout/view_description_edit.xml

Sorry, there's one other place where we were accidentally using a component from within the `chrome-like-tab-switcher` library, which is the CircularProgressDrawable component, which actually already exists in the base AndroidX library.
(This is for the purpose of fully untangling ourselves from this library, for any potential upcoming work on rebuilding our Tabs screen.)

Untangle another component from ChromeTabSwitcher library.

---

app/src/main/res/values/strings.xml

Those two messages were:
* All "wiki"
* All "type"
This was quite weird to read even in English, and hard to translate, too. The quotation marks are unnecessary, and the nouns should be plural, because it's a selection out of multiple things.

Clarify "All wikis" and "All types" notifications messages

---

app/src/main/java/org/wikipedia/analytics/metricsplatform/MetricsEvent.kt

Per discussion from the Slack channel, it is time to include it in the production.

Remove PreProdRelease condition from the MetricsEvent class

---

app/src/main/java/org/wikipedia/views/NotificationActionsOverflowView.kt

@amire80 correctly points out that the menu options in the popup menu for each Notification item should be in the language of the notification, which most of them are (because they come from the API structure itself) except the "Mark read" item, which comes from the app's local resources. We can easily match this option to be in the same language as the rest of the options.
https://phabricator.wikimedia.org/T359600

Show notification Read/Unread menu item in notification's language.

---

app/src/main/java/org/wikipedia/Constants.kt

This adds a few more subdomains of `wikipedia.org` which redirect to `wikimedia.org` and others, which the app isn't meant to handle, so we will automatically bounce these out to the default browser.
These types of redirects are becoming slightly more common in Google search results (because wikipedia.org has such good reputation), so we can expect some more false-positives to be caught by the app.

Add a few more non-language redirect domains.

---

app/build.gradle
app/src/main/res/resources.properties

Android 13 and higher now supports per-app language selection in the System settings. Apps can opt into this functionality with just a few lines of configuration, which auto-generates everything else that's necessary.
https://developer.android.com/guide/topics/resources/app-languages
https://phabricator.wikimedia.org/T359701

Enable support for per-app language selection in Android 13+.

---

app/src/main/res/values/strings.xml

The Gerrit repository has been archived five years ago. No need to advertise it anymore, especially as first of the two links.

Remove Gerrit reference from the about screen

---

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsSurvey.kt
app/src/main/res/drawable/ic_open_in_new_accent_24.xml

This is the one with `?attr/progressive_color` in the XML, and it can be replaced with a regular drawable and apply the tint programmatically.

Remove duplicated open-in-new drawable and use proper tint method

---

app/src/main/java/org/wikipedia/activity/SingleWebViewActivity.kt

The cookies **also** need to be applied after the page is finished loading, so that the base WebView can inherit any new cookies obtained during loading.

Fix account vanish cookie syncing.

---

app/src/main/java/org/wikipedia/page/LinkHandler.kt
app/src/main/java/org/wikipedia/util/StringUtil.kt
app/src/main/java/org/wikipedia/util/UriUtil.kt
app/src/test/java/org/wikipedia/util/StringUtilTest.kt

Whenever a user clicks on a "coordinates" link in an article, which is generally formatted as a GeoHack URL, we can now route it as an `Intent` with a proper Location, and open our PlacesActivity centered on that location.
https://phabricator.wikimedia.org/T136579

Parse GeoHack URLs and launch PlacesActivity with it.

---

.github/workflows/android_phab.yml

This integrates with our Phab bot which should automatically post messages on the corresponding task.
From now on, we can use the old-style GerritBot convention of mentioning the task at the bottom of the pull request description (by saying `Bug: T...` on its own line), and it will be posted automatically to the corresponding task.
(supports multiple tasks!)
(case insensitive!)
(optional whitespace between "Bug" and T number!)
Bug: T360680

Integrate with Phabricator message bot.

---

app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
app/src/main/java/org/wikipedia/edit/SyntaxHighlightViewAdapter.kt
app/src/main/java/org/wikipedia/talk/TalkReplyActivity.kt
app/src/main/java/org/wikipedia/talk/template/AddTemplateActivity.kt

This makes the template insertion logic completely self-contained inside `SyntaxHighlightViewAdapter`, so that we don't need to put the logic in every Activity that uses it.
https://phabricator.wikimedia.org/T355141

One more follow-up to template flow.

---

app/src/main/java/org/wikipedia/talk/template/TalkTemplatesFragment.kt

The app crashes when following the steps below:
1. Go to `Edit patrol`
2. Select any edits
3. Click on "Warn"
It shows `kotlin.UninitializedPropertyAccessException: lateinit property adapter has not been initialized`.

Fix: crash when tapping on the "Warn" button in the Patroller Tasks

---

app/src/main/java/org/wikipedia/edit/preview/EditPreviewFragment.kt

We've been ignoring diff links when looking at an edit preview. But now that our Talk Templates are adding diff links explicitly, let's make them clickable.

Enable clicking Diff links in edit preview.

---

app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
app/src/main/java/org/wikipedia/talk/TalkReplyActivity.kt
app/src/main/java/org/wikipedia/talk/template/TalkTemplatesFragment.kt

* When publishing a Talk message successfully based on a saved message, the user shouldn't land back on the Saved Messages activity, but rather back on the _previous_ activity from which Saved Messages was invoked.
* When previewing a Talk message and pressing Back, it should always go back to editing the message. (it was doing this only in the case of arriving from the Diff screen)
This addresses all of the following:
https://phabricator.wikimedia.org/T358898#9671612
https://phabricator.wikimedia.org/T355141#9671572
https://phabricator.wikimedia.org/T356774#9671554

Fix expected behavior upon publishing Talk message from saved messages.

---

app/src/main/java/org/wikipedia/talk/TalkReplyActivity.kt
app/src/main/res/layout/activity_talk_reply.xml

When the message to which you're replying is very long, the input field becomes obscured by the wikitext button bar.

Add padding to bottom of TalkReply input fields.

---

app/src/main/java/org/wikipedia/edit/FindInEditorActionProvider.kt

This is a very minor and rare crash, but it can happen as follows:
* In the wikitext editor window, make sure there is very little text, e.g. 4 characters total.
* Tap the "Find in article" button, and try searching for a string with more characters, e.g. 5 characters.

Fix potential crash when finding text in editor.

---

app/src/main/java/org/wikipedia/views/WikiCardView.kt
app/src/main/res/layout/activity_insert_media.xml
app/src/main/res/layout/dialog_campaign.xml
app/src/main/res/layout/fragment_places.xml
app/src/main/res/layout/view_edit_history_search_bar.xml
app/src/main/res/layout/view_notification_search_bar.xml
app/src/main/res/layout/view_search_bar.xml
app/src/main/res/layout/view_suggested_edits_recent_edits_search_bar.xml
app/src/main/res/layout/view_talk_topics_header.xml
app/src/main/res/layout/view_watchlist_search_bar.xml
app/src/main/res/values/attrs.xml

We have a `radius` attribute which is a duplicate of the standard `cardCornerRadius`.

Remove redundant attribute from custom CardView.

---

app/src/main/java/org/wikipedia/widgets/WidgetFeaturedPageWorker.kt
app/src/main/res/layout/widget_featured_page.xml

This PR fixes two things:
1. The text layout should match the width if the article does not contain an image.
2. The article title shows an incorrect language variant because the `PageSummary` from the feed endpoint is incorrect.

Update Featured article widget and show article title in the correct variant

---

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
app/src/main/java/org/wikipedia/views/EditHistoryStatsView.kt
app/src/main/java/org/wikipedia/watchlist/WatchlistFragment.kt

We have two `getShortDateString()` methods: one applies the UTC timezone, and the other one applies the default locale.
This PR changes the watchlist header item to use the one with `localDate` method for consistency.
Follow-up question: the `getShortDateString()` method with `UTC` timezone is only used by the feed card short date, should we use the local date instead of the UTC timezone?
Bug: T360873

Fix: use localizeDate for the watchlist day header

---

app/src/main/java/org/wikipedia/dataclient/RestService.kt
app/src/main/java/org/wikipedia/feed/FeedCoordinator.kt
app/src/main/java/org/wikipedia/feed/aggregated/AggregatedFeedContentClient.kt

This is for the upcoming Chinese language variants fixes.
- Remove the usage of `Observable<AggregatedFeedContent>`.
- Remove RxJava usage from `AggregatedFeedContentClient` and `FeedCoordinator`.

Use Coroutine on Feed related classes

---

app/src/main/res/values/strings.xml

While the English page redirects to the new title, translations don’t. This change will fuzzy the translations, so translators can notice and fix the broken links.
Also take the chance to make all four links point to m.mediawiki.org, instead of one pointing to m.mediawiki.org and three to www.mediawiki.org.
Bug: T348875

Update links to [[mw:Wikimedia_Apps/Android_Suggested_edits]]

---

app/src/main/java/org/wikipedia/feed/FeedCoordinatorBase.kt

Not sure if the issue came from #4583. To prevent possible crashes, we should add `progressCard` when the pending client is empty.
Or, maybe we can remove the `shouldShowProgressCard()` condition.

Fix: possible crashes when adding the progressCard on Feed

---

app/src/main/java/org/wikipedia/widgets/WidgetFeaturedPageWorker.kt
app/src/main/java/org/wikipedia/widgets/WidgetProviderFeaturedPage.kt

By tracking the logs, it looks like we still need to run `sendBroadcast` in order to run into the `onUpdate()` properly, otherwise the loop will end at the first `enqueue()` 
Bug: T362585

Fix: The Featured Article widget cannot show the content properly

---

app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.kt
app/src/main/java/org/wikipedia/gallery/MediaListItem.kt

This fixes playback of audio files in our Gallery. At some point, it looks like we started assuming that a Gallery item must be either an image or a video, with no regard for pure audio. This untangles that assumption and restores the functionality to play audio files.
https://phabricator.wikimedia.org/T362329

Fix Gallery playback of Ogg and other audio files.

---

app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewContents.kt
app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt

The way we were checking the Namespace of the PageTitle is incorrect, and in fact we should probably check other places in the code where we might do similar checks.
This changes the logic to use the `namespace` directly from the PageSummary response, which is the source of truth.
https://phabricator.wikimedia.org/T362815

Fix showing Link Preview stub edit pencil only for Main namespace.

---

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt

For a language that has variants, we should use its wiki subdomain instead of language code. 
For example: `zh-tw` -> `zh`
Bug: T350512

Fix: use subdomain for available wikis in Patroller Tasks

---

app/src/main/res/values/strings_no_translate.xml

The URL that explains "Minor" edits was moved from wikimedia.org to mediawiki.org.
https://meta.wikimedia.org/wiki/Help:Minor_edit

Update help URL for "minor" edits.

---

app/build.gradle
build.gradle

- Replace IdKey's impl with identityHashCode
- Cache enclosed descriptors by name
- Add excludedSources to the KSP extension object
- NoClassDefFoundError for LZ4Factory when trying KSP2
- Calling KSType.replace() with original arguments results
- Static fields in base class appear in derived classes
- support sealed inheritors lookup.
- support type alias for getSymbolsWithAnnotation
- support more types for reference elements
- Removed accidental usage of SettableFuture, a WorkManager internal class, which will be removed in a future release of WorkManager. After updating WorkManager to that future release, all versions of LeakCanary from 2.8 to 2.13 will crash on leak analysis. To avoid a nasty surprise in the near future, update to LeakCanary 2.14.
- Add proguard mapping support for …

Chore: update deps

---

app/build.gradle
app/src/extra/java/org/wikipedia/donate/GooglePayActivity.kt
app/src/extra/java/org/wikipedia/donate/GooglePayComponent.kt
app/src/fdroid/AndroidManifest.xml
app/src/fdroid/java/org/wikipedia/donate/GooglePayComponent.kt
app/src/main/AndroidManifest.xml
app/src/main/java/org/wikipedia/dataclient/donate/PaymentResponseContainer.kt
app/src/main/res/values-qq/strings.xml
app/src/main/res/values-zh-rTW/strings.xml

This sets up all the dependencies and underlying framework for Google Pay integration.
Can be merged now, to make it easier to switch between branches without doing full gradle resyncs.
* Properly make sure the F-Droid build will not have GPay libraries built into it.
* Set up stub Activity and Component (currently unused), to be completed in the full PR.
* Minor updates to model API response class.
* Tweak and clarify string resource.
https://phabricator.wikimedia.org/T362698

Foundations for Google Pay integration.

---

app/src/main/AndroidManifest.xml

This adds `required="false"` to our location permissions, which we should've done initially.
This is actually preventing the app from being compatible/installable on certain devices that don't have GPS hardware, such as Kindle Fire etc. (If you look at our Amazon Appstore listing, our device support list is suddenly missing numerous devices for this reason.)

Make Location permissions not required in manifest.

---

app/src/main/java/org/wikipedia/Constants.kt
app/src/main/java/org/wikipedia/dataclient/RestService.kt
app/src/main/java/org/wikipedia/dataclient/restbase/RbDefinition.kt
app/src/main/java/org/wikipedia/wiktionary/WiktionaryDialog.kt
app/src/main/java/org/wikipedia/wiktionary/WiktionaryViewModel.kt
app/src/main/res/layout/dialog_wiktionary.xml

- Use coroutine and ViewModel.
- Update the logic of showing `ProgressBar` and `ErrorView` to match the current structure.
- Update `RbDefinition` to remove `usagesByLang`.
- Add a new `ARG_TEXT` in `Constants` to send plain text.
- Use `response[pageTitle.wikiSite.languageCode]` instead of a hard-coded "en" when mapping.

Refactoring Wiktionary to use Coroutine and ViewModel

---

app/src/main/java/org/wikipedia/language/AppLanguageState.kt
app/src/main/java/org/wikipedia/language/LanguageUtil.kt
app/src/main/java/org/wikipedia/language/LanguagesListViewModel.kt

When first installing the app, we automatically pre-select the languages for the user, based on the keyboard Locales that the user has installed in the system.
However, on certain devices it is possible for the list of locales to be _all possible_ locales, not just the ones installed in the system. This could lead to inefficient behavior, and could lead to problems with data analytics, where the list of languages that we pass into our schemas contains all possible languages.
This will constrain the number of initial languages that get suggested, to prevent such a situation.

Constrain number of suggested languages on initial install.

---

app/src/main/java/org/wikipedia/dataclient/Service.kt
app/src/main/java/org/wikipedia/suggestededits/provider/EditingSuggestionsProvider.kt

Once in a while the Image Recommendations API will produce a false positive (i.e. an article that already has an image), which can lead to confusion.
We can reduce the incidence of false positives by checking whether the Page response (which we already have) contains a `thumbnail` element, implying that the API believes the article already has an image.

Reduce false positives in Image Recs by checking for existing thumbnail.

---

app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.kt
app/src/main/java/org/wikipedia/gallery/ImagePipelineBitmapGetter.kt
app/src/main/java/org/wikipedia/main/MainFragment.kt
app/src/main/java/org/wikipedia/places/PlacesFragment.kt
app/src/main/java/org/wikipedia/richtext/CustomHtmlParser.kt

The `ImagePipelineBitmapGetter` is an abstract class, but is used as a regular helper object instead of an abstract object.
This PR removes the `abstract` type from the class and adds a `Callback` to the parameter to use `lambda` when using it.

Update ImagePipelineBitmapGetter to a regular helper

---

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragmentViewModel.kt

The `refreshContents()` in `SuggestedEditsTasksFragment` will be called twice from `onResume` in `SuggestedEditsTasksFragment` and also `onActivityResult()` in `MainFragment`.
This PR adds a `Job` to cancel the previous calls and only push one result to the fragment.
Bug: T363195

Fix: Use Job to prevent adding up total contributions twice

---

app/src/main/java/org/wikipedia/search/SearchResultsViewModel.kt

In the logic block of searching tabs/history, the condition is `searchTerm.length > 2`. It makes sense for English but not non-English articles (e.g. Chinese). For example, "Captial" in Chinese is "首府", and the length is `2`.
Also, in the `getSearchResultsFromTabs`, the logic is `searchTerm.length >= 2`, which is inconsistent with the one in the `prefixSearch` if block. 
Bug: T364351

Fix: able to search tabs/history when the length of the search term >= 2

---

app/src/main/java/org/wikipedia/feed/FeedFragment.kt

Steps to reproduce it:
1. Go to `UtcDate` and `+1` for the `day`
2. Configure the feed content to show only the top read.
3. See empty card, press the device Home button
4. Go back to the feed.
Bug: T364356

Fix: the app should hide the empty card if the content is not empty

---

app/src/main/java/org/wikipedia/captcha/CaptchaHandler.kt

In #4641 we switched to using a coroutine to fetch the captcha, but the coroutine was never actually assigned to the `clientJob` variable, so it would never be cancellable.

Correctly assign Job in CaptchaHandler.

---

app/src/main/java/org/wikipedia/edit/insertmedia/InsertMediaViewModel.kt
app/src/test/java/org/wikipedia/edit/insertmedia/InsertMediaTest.kt

When inserting images into wikitext (whether through Image Recommendations or the regular editor), we should check if the wiki is RTL, and use the corresponding `left` or `right` alignment, instead of always defaulting to `right`.
In addition, if the user doesn't change the default alignment, then we can just omit it from the insertion, since the `thumb` parameter automatically uses the wiki default for alignment.

Fix RTL awareness when inserting images into wikitext.

---

app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.kt

In the previous RxJava one, we ignore the case when the device is offline. This PR adds logic to check if the device is online and a try-and-catch block to prevent crashes.

Fix: add additional try and catch block for loading lead images info in offline

---

app/src/extra/java/org/wikipedia/donate/GooglePayActivity.kt
app/src/extra/java/org/wikipedia/donate/GooglePayComponent.kt
app/src/extra/java/org/wikipedia/donate/GooglePayViewModel.kt
app/src/main/java/org/wikipedia/donate/DonateDialog.kt
app/src/main/java/org/wikipedia/page/campaign/CampaignDialog.kt

A couple of minor enhancements:
* Per feedback in the previous PR:
> Do we need to update the preference logic to make sure the user clicks one of the options in the GPay bottomsheet instead of saving the preference when tapping on the the dialog "Donate now"?
This is now fixed: the campaign will be considered "shown" only when the user clicks one of the buttons in the DonateDialog, instead of the primary button in CampaignDialog.
* The "maximum" donation amount is received from the API, but is only defined for USD. To apply the maximum amount for other currencies, we need to calculate the maximum based on the _proportion_ of the minimum USD to the minimum of the target currency.

Follow-up to Google Pay integration

---

app/src/main/java/org/wikipedia/talk/TalkReplyActivity.kt

We should use `sendPatrollerExperienceEvent` instead of using `PatrollerExperienceEvent.logAction` directly.

Fix: make sure sending data if it is from Edit Patrol

---

app/src/extra/java/org/wikipedia/donate/GooglePayComponent.kt
app/src/extra/java/org/wikipedia/donate/GooglePayViewModel.kt

The fundraising backend expects the final donation amount to be always formatted with the canonical decimal format, regardless of current locale. e.g. if the amount is 1.23, it must be sent as `1.23` instead of `1,23`.

Always send final amount in canonical decimal format.

---

app/src/extra/java/org/wikipedia/donate/GooglePayViewModel.kt

For the NumberFormat of the currency, we were unnecessarily giving it the current app language, which might be a language or variant that's unsupported by the NumberFormat system. Instead, we can simply initialize it with the default `Locale`, which picks up the current language of the device.
https://phabricator.wikimedia.org/T365278

GPay: Fix setting language for currency NumberFormat.

---

app/src/main/java/org/wikipedia/edit/insertmedia/InsertMediaViewModel.kt

For the logic that attempts to insert the image into an infobox, we are supposed to be restricting it only to English, because we only have hardcoded infobox names and parameters in English.
But it looks like we're incorrectly _falling back_ to English, and detecting infoboxes implicitly, which can lead to undesirable cases: for example French Wikipedia also uses a template called `Infobox`, but the parameter names are different (e.g. `légende` instead of `caption`), so let's add add an explicit check.
https://phabricator.wikimedia.org/T365252

Image recs: insert into infobox only for English.

---

app/src/main/java/org/wikipedia/edit/summaries/EditSummaryFragment.kt
app/src/main/java/org/wikipedia/edit/summaries/EditSummaryHandler.kt

Something to keep in mind going forward:
When doing coroutines inside "helper" classes, we should always try to inject the CoroutineScope from the parent Fragment or Activity, because the parent already has a perfectly good `lifecycleScope`, which is even better because it automatically cancels coroutines when the lifecycle ends.
In this example, if we inject the `lifecycleScope` from the parent fragment, we no longer need to check `isAttachedToWindow`.
(and it's more efficient because we don't create new instances of CoroutineScope!)

Follow-up to coroutines in EditSummary.

---

app/src/main/java/org/wikipedia/analytics/eventplatform/MachineGeneratedArticleDescriptionsAnalyticsHelper.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
app/src/main/java/org/wikipedia/talk/TalkReplyViewModel.kt
app/src/main/java/org/wikipedia/talk/TalkTopicsViewModel.kt
app/src/main/java/org/wikipedia/talk/template/TalkTemplatesViewModel.kt
app/src/main/java/org/wikipedia/usercontrib/UserInformationDialogViewModel.kt

From our early days of using coroutines, when we assumed that all `suspend` calls must be wrapped in `withContext()`.

Hygiene: remove unnecessary usages of withContext{}

---

app/src/main/java/org/wikipedia/main/MainFragment.kt
app/src/main/java/org/wikipedia/navtab/NavTab.kt
app/src/main/res/layout/fragment_main.xml
app/src/main/res/values/ids.xml

Currently, we put the "More" button on the side of `NavTabLayout`, but it does not behave like the other buttons. When running the app in a tablet landscape mode, the "More" button is not positioned properly.
This PR removes the views and moves "More" to be a NavTab enum member.
Before:
After:

Optimize NavTabLayout in MainFragment

---

app/src/main/java/org/wikipedia/analytics/eventplatform/EventPlatformClient.kt
app/src/main/java/org/wikipedia/analytics/eventplatform/EventService.kt

- Use coroutine with `CoroutineScope(Dispatchers.IO)` since we are not sending `lifecycleScope` from separate events. 
- Do not process the `sendEventsForStream()` when the device is offline.

Use coroutine on EventPlatformClient and do not send while offline

---

app/src/main/java/org/wikipedia/page/PageFragment.kt

In Dark mode, when you have the "Edit article" option configured in your toolbar (instead of the overflow menu), the tint of the icon is incorrect:
In addition, the logic of updating the toolbar icons was slightly incorrect, and could lead to the Edit icon being in the wrong state (with the "lock" icon), or being enabled even while the article is still loading.
This fixes the logic and the tinting.

Fix tint and logic of Edit pencil in page toolbar.

---

app/src/main/java/org/wikipedia/feed/FeedFragment.kt

The original PR of adding the code was: #1300
The issue should be fixed now since it has been almost 4 years.

Do not reload the feed content onResume in FeedFragment

---

app/src/main/java/org/wikipedia/util/UriUtil.kt

The recent updates to `getLanguageVariantFromUri()` introduced a slight issue where certain URLs are now being parsed incorrectly.
For example, URLs that have a path of `/w/...` (which includes things like Diff links, API urls, etc) will be incorrectly parsed as having a language variant of `w`.
This fixes the issue by explicitly excluding the `/w/` case in addition to the `/wiki/` case.
https://phabricator.wikimedia.org/T366865

Fix unintended parsing of language variant code from /w/ URLs.

---

app/src/main/java/org/wikipedia/feed/FeedFragment.kt

Unfortunately this crash is definitely still happening, as seen in the current Beta, so we still need this fix.

Revert "Do not reload the feed content onResume in FeedFragment"

---

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsRecentEditsViewModel.kt

in `filterUserExperience()`, the `anon` items are added to the end of the filtered list, and we should sort the list again to prevent incorrect order in the list.

Fix: make sure edits in Edit Patrol are sorted by date in descending order

---

app/src/main/res/layout/fragment_places.xml

If you switch to List in the Places, and click on the search bar, you will notice the ripple animation overflows the entire search bar view. Change the background to use `selectableItemBackground` will resolve the issue.

Use selectableItemBackground in SearchBarView in Places

---

app/src/main/java/org/wikipedia/dataclient/WikiSite.kt

If you select "Wikimedia COmmons" in the contributions filter and go back to the list, you will find it shows "English Wikipedia" instead of Wikimedia Commons.

Fix: add Commons to dbName() logic for Constributions list

---

app/src/main/java/org/wikipedia/usercontrib/UserContribFilterActivity.kt
app/src/main/java/org/wikipedia/usercontrib/UserContribListActivity.kt
app/src/main/java/org/wikipedia/usercontrib/UserContribListViewModel.kt

This fixes the following issues:
1. The `langCode` in the viewModel should be from `Prefs.userContribFilterLangCode` instead of the appOrSystemLanguageCode
2. If you go to "Filter contributions" and click on "Update app languages" and then go back, the selected item will be changed to the top wiki in the list.
This PR also removes the unnecessary `constructor`s

Fix: load the contribution items from saved language code

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/wikipedia/activity/BaseActivity.kt
app/src/main/java/org/wikipedia/alphaupdater/AlphaUpdateChecker.kt
app/src/main/java/org/wikipedia/notifications/NotificationPresenter.kt

This will correctly ask for permissions to show notifications on Android 13 and higher.
This may need a bit of design input in the future, but for now the logic for asking for the permission will be:
* Only if the user has passed initial onboarding
* Only if the user is logged in
* On every activity `onStart`, the permission will be checked, but only once per hour at the most.

Properly ask for permission to show notifications on API 33+.

---

app/src/main/java/org/wikipedia/search/SearchResultsFragment.kt
app/src/main/java/org/wikipedia/search/SearchResultsViewModel.kt

Along with using a PagingSource (which is good), we are also _manually_ keeping track of `totalResults` (which is bad).
The `totalResults` seems to be for checking duplicate results, but we're already checking for duplicate results in the PagingSource itself. I don't believe we need this.

Fix potential crash in Search paging, and simplify.

---

app/src/main/java/org/wikipedia/edit/richtext/SyntaxHighlighter.kt

If you edit a large article, and go to "find text" in the editing window and start typing characters, it can potentially crash with a `ConcurrentModificationException` if the syntax highlight task doesn't finish before the new query positions are updated.
This is fixed by making a _copy_ of the list of query positions when highlighting them.

Fix possible crash when searching for text in Syntax Highlighter.

---

app/src/main/java/org/wikipedia/analytics/eventplatform/EventPlatformClient.kt
app/src/main/java/org/wikipedia/dataclient/Service.kt

This uses `MainScope()` to run the API call.

Use coroutine in EventPlatformClient

---

app/src/main/java/org/wikipedia/dataclient/Service.kt

When requesting `pageimages` for getting the thumbnail of an article, we must specify `pilicense=any` to get any kind of image, including ones that might not be freely licensed, e.g. fair-use, in the case of logos etc.
https://phabricator.wikimedia.org/T368784

Fix certain markers in Places missing a thumbnail image.

---

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsFragment.kt

https://play.google.com/console/u/1/developers/6169333749249604352/app/4972092403490495074/vitals/crashes/31ea3304d3a9fdd55f70b83d8d34749f/details?days=28&versionCode=50493&isUserPerceived=true
Not sure if we are sending a default language code like (`en`) in this case.

Fix: possible NullPointerException in SuggestedEditsCardsFragment

---

app/src/main/java/org/wikipedia/alphaupdater/AlphaUpdateChecker.kt
app/src/main/java/org/wikipedia/analytics/eventplatform/EventPlatformClient.kt
app/src/main/java/org/wikipedia/recurring/RecurringTasksExecutor.kt
app/src/main/java/org/wikipedia/recurring/TalkOfflineCleanupTask.kt
app/src/main/java/org/wikipedia/settings/RemoteConfigRefreshTask.kt

According to the [best practices](https://developer.android.com/kotlin/coroutines/coroutines-best-practices#main-safe) relating to coroutines, all `suspend` functions must be "main-safe", i.e. must be callable from the main thread.
This means that each `suspend` function must be responsible for its own `withContext{}` block, instead of the calling function putting them into a context.

Follow-up to recurring tasks.

---

app/src/main/java/org/wikipedia/watchlist/WatchlistItemView.kt

The `summaryText` field was being incorrectly set, causing non-edit log messages to be shown as "empty" summaries.
https://phabricator.wikimedia.org/T369528

Fix display of non-edit log events in Watchlist items.

---

app/src/main/java/org/wikipedia/gallery/GalleryActivity.kt

Similar to https://github.com/wikimedia/apps-android-wikipedia/pull/4816 but for pictures.
Unlike the name, .commonsUrl, it works for both images uploaded on Wikimedia Commons and locally uploaded images.
To test this open an article, open an image from it, hit the rectangle button above the emulator, click on the anchor icon on the recents screen.
This is the reason it's only enabled for API level 23

Support URL sharing on recent screen for images

---

.github/dependabot.yml

My upstream PR was accepted (https://github.com/dependabot/dependabot-core/pull/10207), so the issue with `-pre` releases should now be fixed.

No longer ignore maplibre for dependabot.

---

app/build.gradle

The version-catalog refactor accidentally left behind the installreferrer dependency for the default flavor.

Remove installreferrer from refactored dependencies.

---

app/src/main/java/org/wikipedia/descriptions/DescriptionEditActivity.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt

This opens machine-generated description suggestions back up for all users, instead of being feature-flagged for pre-beta only.
It also makes sure that the correct tag is added when a description is added through a machine suggested selection.
https://phabricator.wikimedia.org/T360581

Remove feature flag for machine-suggested descriptions.

---

app/src/main/java/org/wikipedia/descriptions/DescriptionEditActivity.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt

Reverts wikimedia/apps-android-wikipedia#4830
This is now blocked on a new edit tag to be added to the MobileApp extension.

Revert "Remove feature flag for machine-suggested descriptions."

---

app/src/main/java/org/wikipedia/feed/FeedContentType.kt
app/src/main/java/org/wikipedia/feed/aggregated/AggregatedFeedContentClient.kt
app/src/main/java/org/wikipedia/feed/random/RandomClient.kt

The "edit card languages" option for Randomizer does not work properly. After digging into the issue, I have noticed the `aggregatedLanguages` will always return the app languages, which seems unnecessary. 
This PR removes the `aggregatedLanguages` from `FeedContentType` since we do not specify which type we are currently using when calling `aggregatedLanguages`, and it always return the full list of languages, it is safe to delete from the code and uses regular `WikipediaApp.instance.languageState.appLanguageCodes`.

Remove AggregatedLanguages variable in FeedContentType

---

app/src/main/java/org/wikipedia/gallery/ImagePipelineBitmapGetter.kt
app/src/main/java/org/wikipedia/places/PlacesFragment.kt

For map markers that have a thumbnail which is an SVG image with transparency, the marker must have a white background for the SVG to be properly visible.
Let's pass a `WhiteBackgroundTransformation` into the image pipeline getter, which also automatically respects the image dimming preference.

Follow-up to map markers.

---

app/src/main/java/org/wikipedia/page/PageActivity.kt

This fixes a long-standing issue where users have observed that the "Translate" menu option (provided by Google Translate) in the context menu doesn't seem to work, or doesn't appear at all.
This seems to have been because we were taking control of the context menu by clearing all the items from it, then repopulating the items including our own custom items. It looks like this method erases some necessary metadata from the original menu that was needed for the Translate option (and possibly others) to work properly.
The new method will preserve the original context menu, and merely append our custom items to it.
https://phabricator.wikimedia.org/T318041
https://phabricator.wikimedia.org/T346999

Fix proper injection and hiding of context menu over WebView.

---

app/src/main/res/layout/fragment_article_edit_details.xml

Because of how the diff views are arranged, the last item in the list is sometimes obscured by the bottom button container. For now let's just give the RecyclerView an explicit bottom padding.
https://phabricator.wikimedia.org/T371893

Fix bottom scroll position in Diff view.

---

app/src/main/java/org/wikipedia/talk/TalkTopicHolder.kt

Switched `notifications_menu_mark_as_read` with the already existing `talk_list_item_overflow_mark_as_read`. The current string is also used for notifications, which can cause localization issues when the translations for "topic" and "notification" don't have the same gender, like in Spanish.

Replace string for read topic in TalkTopicHolder

---

app/src/main/java/org/wikipedia/dataclient/Service.kt
app/src/main/java/org/wikipedia/dataclient/mwapi/MwServiceError.kt
app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
app/src/main/java/org/wikipedia/util/ThrowableUtil.kt
app/src/test/java/org/wikipedia/login/UserExtendedInfoClientTest.kt

There is an issue in the Suggested Edits screen, if the current account is blocked, the block message overlaps the other components on the screen, because the other components are not properly hidden. This is most prominent in Black mode; in other modes it looks more correct, but only by accident.
This fixes the showing/hiding of the other components in case of a block, and while fixing the issue I converted some of the block message retrieval logic to coroutines, which will simplify the work of several upcoming tasks.

Fix blocked message in Suggested Edits, and use coroutines.

---

.gitignore

Some log files exist in the `.kotlin` folder, and we should avoid pushing them to the branch.

Update .gitignore to ignore log files

---

app/src/main/java/org/wikipedia/edit/FindInEditorActionProvider.kt

Regular expressions have _awful performance_ when looking for very many matches in a very long string.
This reverts #4386 by @Isira-Seneviratne, and demonstrates yet again that "beautiful code" is often terrible in other ways, and "simplifying" things often adds huge hidden complexity.
https://phabricator.wikimedia.org/T373028

Hugely improve performance of finding text in editor window.

---

app/src/main/java/org/wikipedia/settings/Prefs.kt
app/src/main/res/values/preference_keys.xml
app/src/main/res/xml/developer_preferences.xml

Remove unused/old test group preferences

Hygiene: clean up unused preferences and test group strings

---

app/src/main/java/org/wikipedia/analytics/metricsplatform/RecommendedContentAnalyticsHelper.kt
app/src/main/java/org/wikipedia/search/RecentSearchesFragment.kt

This will make sure that Recommended Content will not be shown after a specified hard-coded date.

Enforce end-date for Recommended Content experiment.

---

app/src/main/java/org/wikipedia/feed/random/RandomClient.kt
app/src/main/java/org/wikipedia/readinglist/db/ReadingListPageDao.kt

Updating `getRandomPage()` in the `ReadingListPageDao.kt` to make sure we are getting the correct random page for a specific wiki.
If the app has multiple languages set, and once one of the `getRandomSummary()` is empty, it will fall back to search for the local pages without a specific language code, which will create content that does not align with the card language.

Fix: make sure to get a random page from a specific language code

---

app/src/main/java/org/wikipedia/page/PageFragment.kt
app/src/main/java/org/wikipedia/views/SurveyDialog.kt
app/src/main/res/values/styles.xml

Technically this still uses `adjustResize` for the window, but this doesn't seem to be deprecated, and is simpler, and applies to all dialogs automatically.

Use style instead of deprecated method for resizing dialog window.

---

app/src/main/res/layout/activity_edit_section.xml

Correctly align the scroll view in the EditSection activity, so that when the Wikitext buttons are visible, they do not obscure the last line of text in the editor.
Resolves an annoying issue where the last line in the editor is not visible because it is overlapped by the wikitext buttons.
https://phabricator.wikimedia.org/T372615

Fix scroll area of edit window when obscured by wikitext buttons.

---

app/src/main/java/org/wikipedia/analytics/eventplatform/BreadCrumbViewUtil.kt

Remove a deprecated import and check (coming from Glide?) in our breadcrumbs handler.
This might have been inserted by accident, or by incorrect autocomplete, and is no longer necessary.

Remove deprecated check from breadcrumbs handler.

---

app/src/main/java/org/wikipedia/feed/news/NewsItem.kt
app/src/main/java/org/wikipedia/feed/news/NewsLinkCard.kt
app/src/main/java/org/wikipedia/feed/onthisday/OnThisDay.kt
app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayCard.kt
app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayCardView.kt
app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayFragment.kt

Replace the `nullable` data type in a `List` with `non-nullable` to reduce unnecessary logic to check.
When requesting the API, it usually responds with an empty list or valid data, which the `List<PageSummary>` is good for the condition.

Optimizing the NewsItem and OnThisDay variables

---

app/src/main/res/values/styles.xml

The start and end padding were removed while doing the style update.
The padding is necessary for the menu items.

Fix: apply start and end padding to the OverFlowMenuItem style

---

app/src/main/java/org/wikipedia/feed/random/RandomClient.kt
app/src/main/java/org/wikipedia/util/L10nUtil.kt

Just a bit of cleanup of unnecessary list allocations.

Tiny follow-up to async improvements.

---

app/src/main/java/org/wikipedia/talk/TalkThreadHeaderView.kt
app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt

We were not stripping HTML tags from the PageTitle that is displayed as the title of the Talk activity, which can lead to unintended HTML spills.
https://phabricator.wikimedia.org/T374393

Correctly strip html styling from Talk activity titles.

---

app/src/main/java/org/wikipedia/notifications/NotificationPresenter.kt

De-duplicate action buttons in certain notifications that are shown to the user.
There was a missing `return` statement when processing a notification of a certain kind, which was causing a duplicate action to be added.
https://phabricator.wikimedia.org/T351425

Fix possible duplicate action in notifications.

---

app/src/main/java/org/wikipedia/analytics/metricsplatform/RecommendedContentAnalyticsHelper.kt

Moves `MU` country code from South Asia to sub-Saharan Africa.
To avoid confusion. No impact on the current release.

Minor: update the order of enabled countries list for Recommended Content

---

app/src/main/java/org/wikipedia/captcha/CaptchaHandler.kt
app/src/main/java/org/wikipedia/createaccount/CreateAccountActivity.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt

Removes the logic of checking whether the handler is active or not and uses the advantage of Kotlin to return either the value or `null`.
Simplify the code.

Simplify the logic of getting captchaId and captchaWord from the handler

---

app/src/main/java/org/wikipedia/WikipediaApp.kt
app/src/main/java/org/wikipedia/notifications/db/NotificationDao.kt

The notifications are kept in the database even if you log out and switch to another account, which does not make sense if the user sees the notifications that do not associate with the currently logged-in account.
Clear the notification after the user logs out to prevent showing incorrect content for the user.

Fix: clear notifications from the db after logging out

---

app/src/main/java/org/wikipedia/search/RecentSearchesFragment.kt

The (minor) crash was being caused by using the `childFragmentManager` to add the RecommendedContent child fragment _to the backstack_, which is not exactly correct. This causes the fragment manager to **recreate** the fragment automatically (outside of our control) in certain situations, which will cause a second instance of that fragment to exist, and lead to unexpected/undefined behavior.

(Truly) fix possible crash in recommended content.

---

app/src/main/java/org/wikipedia/recommendedcontent/RecommendedContentFragment.kt
app/src/main/java/org/wikipedia/recommendedcontent/RecommendedContentViewModel.kt

When you send an empty string to the `morelike` API, it returns an [unrelated result](https://en.wikipedia.org/w/api.php?format=json&formatversion=2&origin=*&action=query&prop=pageimages%7Cdescription&piprop=thumbnail&pithumbsize=160&pilimit=3&generator=search&gsrsearch=morelike:&gsrnamespace=0&gsrlimit=3&gsrqiprofile=classic_noboostlinks&uselang=content&smaxage=86400&maxage=86400).

Fix: don't send empty string for morelike API in Recommended content

---

app/src/main/java/org/wikipedia/util/L10nUtil.kt

If the `list` is empty, it will still return an empty string from the `joinToString()` method, which will cause an error when requesting the wikidata API call in `L10nUtil.getPagesForLanguageVariant()`.
If the `morelike:` API returns an empty result, it is not necessary to go through the `getPagesForLanguageVariant` process.

Fix: do not make an API call for an empty list in getPagesForLanguageVariant()

---

app/src/extra/java/org/wikipedia/donate/GooglePayViewModel.kt

The campaign ID that is sent to the fundraising API needs to be updated to match the format used by iOS, which is: `language`+`campaignID`+`_`+`platform`.  (note no underscore between language and ID, and underscore between ID and platform)
This will enhance and simplify analytics.
https://phabricator.wikimedia.org/T367360

Update campaign ID format sent with GPay transaction.

---

app/src/main/java/org/wikipedia/auth/AccountUtil.kt

This adds a few functions to `AccountUtil` that _will_ be used for temporary accounts, but should not impact any existing behavior. It will make the larger Temporary Accounts PR easier to review, and will also allow analytics PRs to make use of these functions, independently of the larger Temp Accounts PR.

A bit more ground work for temp accounts.

---

app/src/main/java/org/wikipedia/recommendedcontent/RecommendedContentFragment.kt

Replace the `popBackStack()` with a view visibility update to prevent a [possible crash](https://play.google.com/console/u/1/developers/6169333749249604352/app/4976363884102945010/vitals/crashes/40202a9f69c71b6772058d707e235375/details?days=28&versionCode=50501&isUserPerceived=true).

Fix: replace popBackStack() with a general visibility update in Recommended Content

---

app/src/main/java/org/wikipedia/dataclient/ServiceFactory.kt
app/src/test/java/org/wikipedia/test/MockRetrofitTest.kt
gradle/libs.versions.toml

This PR updates the kotlinx.serialization converter for Retrofit to [the official first-party converter](https://github.com/square/retrofit/tree/trunk/retrofit-converters/kotlinx-serialization).
The [original converter](https://github.com/JakeWharton/retrofit2-kotlinx-serialization-converter) is no longer being maintained.

Switch to official Retrofit kotlinx.serialization converter

---

app/src/main/java/org/wikipedia/commons/ImageTagsProvider.kt
app/src/main/java/org/wikipedia/dataclient/Service.kt

Clean up unused API calls and rename the `getClaims()`.

Hygiene: remove unused API calls and rename the getClaims() function

---

app/src/main/java/org/wikipedia/csrf/CsrfTokenClient.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditViewModel.kt

* Catch and rethrow `CancellationException` in try-catch blocks. Let's remember to do this wherever we have a try-catch block that catches all `Exception`s.
* Use the new function in `DescriptionEditViewModel`.

Follow-up to Csrf coroutine refactor.

---

app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageRecsFragment.kt

The hashtag comments (`#suggestededit-add-image-top` and `#suggestededit-add-image-infobox`) have been replaced by proper tags, so these can be safely removed. (We just forgot to remove them as part of the Tags task.)

Remove hashtag comment when submitting Image Recommendations.

---

app/src/extra/java/org/wikipedia/donate/GooglePayActivity.kt

In one of the most unfortunate cases of name shadowing, there were two variables called `intent`, and we were using the wrong one to get the campaign ID, resulting in a fallback to the default id.
https://phabricator.wikimedia.org/T375124

Facepalm: correctly get campaign id from Activity's intent.

---

app/src/main/assets/licenses/ChromeLikeTabSwitcher
app/src/main/res/values/credits.xml

Remove the `ChromeLikeTabSwitcher` license and credit from the app.

Remove ChromeLikeTabSwitcher license

---

app/src/main/java/org/wikipedia/richtext/CustomHtmlParser.kt

Our handling of ordered list `<ol>` tags is kind of brittle already, and can lead to issues, because we programmatically insert text into an `Editable` inside a phase where text shouldn't really be inserted. This can cause clashes with existing Spans, especially ParagraphStyle spans.
This fixes further existing issues by explicitly removing any additional `ParagraphStyle` spans that might be interfering with an `<ol>` tag. A more permanent solution will need to be devised later.
https://phabricator.wikimedia.org/T375728

Fix FromHtml rendering of ordered lists with Paragraph spans.

---

app/src/extra/java/org/wikipedia/donate/GooglePayViewModel.kt
app/src/main/java/org/wikipedia/analytics/eventplatform/DonorExperienceEvent.kt
app/src/main/java/org/wikipedia/dataclient/donate/CampaignCollection.kt

This breaks out the formatting of the campaignId into a function, and the function is now called from the Google Pay submission workflow, as well as DonorExperience events that make use of the campaignId.
https://phabricator.wikimedia.org/T375124

Correctly format Campaign ID for native payments and analytics.

---

app/src/extra/java/org/wikipedia/donate/GooglePayActivity.kt
app/src/main/java/org/wikipedia/dataclient/donate/CampaignCollection.kt
app/src/main/java/org/wikipedia/donate/DonationResult.kt
app/src/main/java/org/wikipedia/page/PageActivity.kt
app/src/main/java/org/wikipedia/settings/Prefs.kt
app/src/main/res/values/preference_keys.xml
app/src/main/res/xml/developer_preferences.xml

This creates a `DonationResult` object for successful donations, and persists a list of such objects in Prefs.
https://phabricator.wikimedia.org/T376082

Instrument donation results.

---

app/src/main/java/org/wikipedia/feed/news/NewsFragment.kt

Accessing `binding` right after setting it to `null` 😅 Somehow slipped past review.

Fix crash when leaving NewsFragment.

---

app/src/main/java/org/wikipedia/analytics/eventplatform/EditAttemptStepEvent.kt

Apparently the `EditAttemptStep` schema has an (optional) `user_is_temp` parameter that we can use, for free, without any additional work.

Send user_is_temp parameter in EditAttemptStep.

---

app/lint.xml

The IDE now warns the files that use `@Serializable` annotation, and it has the warning info below:
```
This declaration is opt-in and its usage should be marked with @kotlinx. serialization. InternalSerializationApi or @OptIn(markerClass = kotlinx. serialization. InternalSerializationApi. class) More... (Ctrl+F1) 
Inspection info: This API has been flagged as opt-in with error-level severity.  Any declaration annotated with this marker is considered part of an unstable or otherwise non-standard API surface and its call sites should accept the opt-in aspect of it by using the @OptIn annotation, using the marker annotation -- effectively causing further propagation of the opt-in aspect -- or configuring the UnsafeOptInUsageError check's options for project-wide opt-in.  To configure …
```

Ignore UnsafeOptInUsageError warning

---

app/src/main/java/org/wikipedia/dataclient/donate/Campaign.kt
app/src/main/java/org/wikipedia/page/campaign/CampaignDialog.kt
app/src/main/java/org/wikipedia/page/campaign/CampaignDialogView.kt

(This refers to the campaign URLs provided to us in the campaign configuration structures from FR-tech.)
Right now we have a dynamic parameter called `$platform;` that is automatically replaced by the `iOS` or `Android` platforms. We are adding another dynamic parameter (to be used in future campaigns by FR-tech) called `$formattedId;` which will be replaced by the decorated campaign ID that we pass to analytics.
https://phabricator.wikimedia.org/T376083

Add optional `formattedId` dynamic parameter to campaign URLs.

---

app/src/main/java/org/wikipedia/WikipediaApp.kt

Reverts wikimedia/apps-android-wikipedia#4984
This did not reduce the number of instances of this crash. In the interest of keeping unnecessary code to a minimum, and to reduce confusion for investigating the real cause of this crash, let's keep a single assignment of the `instance` variable.

Revert "Fix: a possible crash about lateinit WikipediaApp instance has not en initialized"

---

app/src/main/java/org/wikipedia/donate/DonorStatus.kt
app/src/main/java/org/wikipedia/settings/Prefs.kt
app/src/main/java/org/wikipedia/views/DonorBadgeView.kt
app/src/main/res/drawable/ic_baseline_volunteer_activism_24.xml
app/src/main/res/layout/view_donor_badge.xml
app/src/main/res/values/preference_keys.xml

Create a donor status view for both the overflow menu and the contribute tab.
To be able to share the same design and logic.

[Contributions Dashboard] Create a donor badge view

---

app/src/main/java/org/wikipedia/views/DonorBadgeView.kt
app/src/main/res/layout/view_donor_badge.xml
app/src/main/res/values/styles.xml

1. Added a default blank body for the `Callback` functions.
2. Added a small style for the chip to keep the icon's padding.
https://www.figma.com/design/qZvcD1IoEjPP13X5Ed3Fmv/Android-%E2%86%92-Contributions-Dashboard-%E2%86%92-T%3F?node-id=236-8261&node-type=frame&m=dev

Add a proper padding to the chip icon for smaller text for Donor badge

---

app/src/main/java/org/wikipedia/WikipediaApp.kt
app/src/main/java/org/wikipedia/events/LoggedOutEvent.kt

To send a `LoggedOutEvent` event after the log-out process is completed. 
To make sure the #5048 is updated properly.
https://phabricator.wikimedia.org/T377779

Send a LoggedOutEvent to the FlowEventBus for refreshing screen purpose

---

app/src/main/java/org/wikipedia/usercontrib/ContributionsDashboardHelper.kt
app/src/main/res/values/strings_no_translate.xml

- Simplified the function name, since it exists in the helper class.
- Add a survey URL picker for different language codes.
- Will add the delay and preference conditions later when integrating with the donor history PR.

Follow up: survey dialog for Contributions Dashboard

---

app/src/main/java/org/wikipedia/donate/DonorHistoryActivity.kt
app/src/main/java/org/wikipedia/donate/DonorHistoryViewModel.kt
app/src/main/java/org/wikipedia/donate/DonorStatus.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt

>Cooltey to update logic to not lock recurring based on if there is a date or not 
Based on the conversation in the Product Data meeting, we will need to enable the `recurring donor` checkbox, even if the last donated date is empty. This leads the logic of `Donor Status` some changes.

Update Donor Status logic for recurring donor option

---

app/src/main/java/org/wikipedia/dataclient/Service.kt
app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.kt
app/src/main/java/org/wikipedia/gallery/ImageInfo.kt
app/src/main/java/org/wikipedia/util/ImageUrlUtil.kt

SVG files often have text in multiple languages, encoded into the same file.
Commons automatically generates thumbnails of such SVG files with a well-formed URL that encodes the language. Let's detect the translations that exist for a given SVG, and use the appropriate language (if available) for the thumbnail URL when drawing the SVG in the Gallery.
https://phabricator.wikimedia.org/T374988

Display SVG files in correct language in Gallery.

---

app/src/main/java/org/wikipedia/gallery/ImageInfo.kt

The IDE shows a warning on the line.

Minor: remove the redundant suppression in ImageInfo

---

app/src/main/java/org/wikipedia/search/SearchFragment.kt

1. Go to the search screen and make sure you have multiple app languages.
2. Select the second or the last app language to go back to the search screen.
3. We should see the language tab is selected when going back to the Search screen.

Fix: scroll to the selected language tab when back from the language list

---

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
app/src/main/res/layout/activity_donor_history.xml
app/src/main/res/layout/fragment_suggested_edits_tasks.xml
app/src/main/res/values/styles.xml

- Add `marginHorizontal` to the divider.
- Hide the entire `suggestedEditsScrollView` when loading.
- Show the original date in the format desired for the donor history.
- Update the logged-out vs logged-in status properly in the Contribute tab only ([done in the feature branch](https://github.com/wikimedia/apps-android-wikipedia/pull/5013/commits/6620f2d55168e62e8adc0a273ecedd493159cbde)).
- Update the donation button font family to use regular font weight.
- Update error text font family to use regular font weight.
https://phabricator.wikimedia.org/T376435#10291284
https://phabricator.wikimedia.org/T376431#10291306

Fix: design signoff updates for Contribute Tab and Donor history

---

app/src/main/res/values-nl/strings.xml

Literal percent symbols must be encoded!! `%%`
After this high-priority PR, we must add a test to catch these cases in the future.

Fix incorrectly formatted percent in string, causing crash (!).

---

app/src/main/java/org/wikipedia/descriptions/DescriptionEditViewModel.kt

When submitting an article description, the comment that goes along with the edit is currently in the language of the device, not the language of the article.
The language of the comment must be the article language, regardless of the device language.
https://phabricator.wikimedia.org/T379586

Use article language for summary when adding/changing a description.

---

app/src/main/java/org/wikipedia/main/MainActivity.kt
app/src/main/java/org/wikipedia/views/DonorBadgeView.kt

Removes the clicking ability of donor badge shown on the SuggestedEditsTaskFragment
This is just for design reason.

Fix donor badge disable click state

---

app/src/androidTest/java/org/wikipedia/robots/screen/ContributionScreenScreenRobot.kt

The strings were change to different name on Contribution Dashboard. This PR fixes the missing string resource on Contribution screen Test class.

Adds missing string resource on Contribution Screen Test class 

---

app/src/main/res/layout/item_edit_history.xml

Use `flow` and set `maxWidth` for the button to prevent the layout issue where the button is cut at the end and diff text disappears.

Use Flow and set maxWidth for username and diff view in edit histroy

---

app/build.gradle
gradle/libs.versions.toml

Targeting API 35 introduces some unforeseen visual regressions (in most of our Activities) because we're no longer properly accounting for Android 15's new guidelines for edge-to-edge support:
https://developer.android.com/about/versions/15/behavior-changes-15#ux
Let's roll this back for now, and build proper edge-to-edge support (which will probably take a bit more time) before targeting API 35.
https://phabricator.wikimedia.org/T380145

Roll back targeting of SDK 35 to 34.

---

app/src/main/AndroidManifest.xml

Fixes the app icon missing from the app info screen 
https://phabricator.wikimedia.org/T380374

Fix app icon missing from the app info screen

---

app/src/main/java/org/wikipedia/diff/ArticleEditDetailsViewModel.kt
app/src/main/java/org/wikipedia/diff/DiffLineView.kt
app/src/main/java/org/wikipedia/diff/DiffUtil.kt
app/src/main/java/org/wikipedia/diff/UndoEditDialog.kt

Slightly clean up the redundant code from the classes in the `diff` package.

Hygiene: code clean up for the diff package

---

app/src/main/java/org/wikipedia/readinglist/ReadingListBehaviorsUtil.kt

This fixes a crash that can happen when:
* Go to your reading lists (Saved) tab.
* Tap the filter button in the toolbar, and type a search term, so that the filtered results include pages from your lists, not just the lists themselves.
* Long-press one of the pages.
It looks like this has been broken due to an earlier refactor (#4701), and simply not noticed until now.

Fix potential crash when filtering reading list pages.

---

app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt

This one can happen when you:
* Have no reading lists except the default Saved list.
* Add a single page to the default list.
* Go to the Saved tab and tap on the Saved list to see its contents.
* Delete your single page from that list, so that it's empty.
* Go Back to the Saved tab.
This one is very minor, but we are still seeing a few of them in the Play Store console.
It's because the logic that determines full invalidation happens in an incorrect place (before the state of the displayed lists is finished updating).

Fix another potential crash when deleting items from reading list.

---

app/src/main/java/org/wikipedia/page/ExtendedBottomSheetDialogFragment.kt
app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt

This removes the custom inset handling from the base ExtendedBottomSheetDialog class, because the system appears to be handling bottom-sheet insets for us automatically. (Look at the ThemeChooser dialog, or the ReferenceDialog)
In the case of LinkPreviewDialog, we have a "custom" situation with our overlay buttons that sit on top of the dialog. These buttons (and _only_ these buttons) should be handled with a custom inset handler.

Follow-up: More proper handling of Dialog insets.

---

app/src/main/java/org/wikipedia/analytics/eventplatform/EditAttemptStepEvent.kt

Apparently the EditAttemptStep schema has a `is_anon` field that we weren't including, so let's include it.
https://phabricator.wikimedia.org/T382178

Include `is_anon` field in EditAttemptStep events.

---

app/src/main/java/org/wikipedia/descriptions/DescriptionEditViewModel.kt

When editing image captions in a language other than English, the caption was still being saved as English.
This seems to have gotten broken because of some previous work to fix Chinese variant language selection.
https://phabricator.wikimedia.org/T382205

Fix submitting image captions in correct language.

---

app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
app/src/main/java/org/wikipedia/gallery/GalleryActivity.kt
app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.kt
app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt

When tapping the lead image of an article to go to the Gallery, the transition image has weird rounded corners that appear momentarily, then change back to regular square corners.
This is because of mismatched parameters that are being passed from the `ImageHitInfo` class. This class has a `centerCrop` parameter, which is unused, but it's being interpreted as the `cricleShape` parameter (because they're both boolean) by the `loadImage()` function.
This removes the unused `centerCrop` parameter, which fixes the rounded-corners issue. Note that the lead-image transition is still not "perfect" -- the shape and cropping of the image is still not the same between the transition and the gallery, but his is a much harder problem, to be fixed in a larger refactor. …

Fix/remove unnecessary parameter during page->gallery transition.

---

app/src/main/java/org/wikipedia/search/SearchActivity.kt
app/src/main/java/org/wikipedia/search/SearchFragment.kt

There are a couple of duplicate response codes from SearchActivity!
This can obviously lead to issues, one of which was observed by a user:
https://phabricator.wikimedia.org/T382892

Fix potential issues due to duplicate Result codes in SearchActivity.

---

app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardItemFragment.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsSnackbars.kt

This fixes issues (and a potential crash) when tapping the View action in the snackbar after completing a Suggested Edit from the Feed card.
* The fragment from which the snackbar is launched is no longer attached (replaced by a new Suggestion), so we cannot use the same context for launching an activity.
* In the case of Image Tags, the `WikiSite` for launching the View action was being constructed incorrectly.
https://phabricator.wikimedia.org/T383084

Fix issues with Snackbar action after completing SE Feed items.

---

app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardItemFragment.kt
app/src/main/java/org/wikipedia/language/LangLinksActivity.kt
app/src/main/java/org/wikipedia/notifications/NotificationFilterItemView.kt
app/src/main/java/org/wikipedia/places/PlacesFilterActivity.kt
app/src/main/java/org/wikipedia/settings/languages/WikipediaLanguagesFragment.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsRecentEditsFilterItemView.kt
app/src/main/java/org/wikipedia/views/LanguageScrollView.kt
app/src/main/java/org/wikipedia/watchlist/WatchlistFilterItemView.kt

Wherever we show a selection of languages, the names of the languages should be in the name of that language itself, instead of English.
https://phabricator.wikimedia.org/T383150

Use local language names instead of canonical names where appropriate.

---

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
app/src/main/java/org/wikipedia/views/SuggestedEditsStatsView.kt

Update the order of the Edits' tooltips to let them show from top to bottom and also set the correct target view from the `title` to the `description` view.

Update Edits sequential tooltips's target and orders

---

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt

We should not disable the Edits screen if there are too many reverts in `testwiki`. This PR helps to skip the logic of checking revert counts in the Edits screen for `testwiki`.

Do not block the Edits screen if the primary language is `test`

---

app/src/main/java/org/wikipedia/feed/places/PlacesCardView.kt
app/src/main/java/org/wikipedia/places/PlacesFragment.kt
app/src/main/java/org/wikipedia/views/ViewUtil.kt
app/src/main/res/layout/item_places_list.xml
app/src/main/res/layout/view_places_card.xml

The Material library gives us a perfectly good `ShapeableImageView` to use, so we no longer need a fully custom Glide transformation to make circular images!

Simplify: remove old way of making circular images.

---

app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
app/src/main/res/layout/fragment_suggested_edits_tasks.xml
app/src/main/res/layout/suggested_edits_tasks_container.xml
app/src/main/res/layout/suggested_edits_tasks_contribution_container.xml

Separates XML layout into different XML layouts for easier handling and maintenance
In layouts like fragment_suggested_edits_tasks we can organize the code across multiple layouts and include them as needed. This approach will simplify the process of adding new views to the UI and help maintain the design.

Separates XML layout of SuggestedEditsTasksFragment

---

app/src/main/java/org/wikipedia/WikipediaApp.kt
app/src/main/java/org/wikipedia/dataclient/okhttp/OkHttpWebViewClient.kt
app/src/main/java/org/wikipedia/language/AcceptLanguageUtil.kt
app/src/main/java/org/wikipedia/savedpages/SavedPageSyncService.kt
app/src/test/java/org/wikipedia/language/LanguageVariantTest.kt

This further simplifies and solidifies the custom handling of `zh` variants when building the `Accept-Language` header, and also adds a few explanatory comments in the logic itself.

Follow-up to zh variant fixes.

---

app/src/main/java/org/wikipedia/commons/FilePageView.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt
app/src/main/java/org/wikipedia/gallery/GalleryActivity.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsItemFragment.kt
app/src/main/java/org/wikipedia/util/StringUtil.kt
app/src/test/java/org/wikipedia/util/StringUtilTest.kt

The `strip()` function is no longer needed. (there's even a `TODO` to remove it.)

Hygiene: remove unnecessary string function.

---

app/src/main/java/org/wikipedia/dataclient/RestService.kt
app/src/main/java/org/wikipedia/descriptions/DescriptionEditViewModel.kt
app/src/main/java/org/wikipedia/edit/EditSectionViewModel.kt
app/src/main/java/org/wikipedia/page/PageFragmentLoadState.kt
app/src/main/java/org/wikipedia/savedpages/SavedPageSyncService.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageRecsFragmentViewModel.kt
app/src/main/java/org/wikipedia/suggestededits/provider/EditingSuggestionsProvider.kt
app/src/main/java/org/wikipedia/util/L10nUtil.kt
app/src/main/java/org/wikipedia/widgets/WidgetFeaturedPageWorker.kt

(note that this is based on top of #5238)
* Previously we had a `getPageSummary()` call where the optional `Referer` parameter came _first_ for some reason, which required us to pass an explicit `null` everywhere this call was made. Let's make this parameter come second, along with all other optional parameters, so that any overloaded calls can be simplified.
* In the `SavedPageSyncService` where we were making the calls to retrieve the PageSummary, MediaList, and MobileHtml, those calls were being made serially, not in parallel. Let's use `async{}` to make these calls all at once, and speed up saving articles for offline usage.

Streamline calls to PageSummary and MediaList.

---

app/src/main/java/org/wikipedia/dataclient/Service.kt

Some of our API requests have the `prop=pageimages` but do not add the `pilicense=any`. This PR adds the license parameter to align with other API calls.
For example, `morelike: 四大自由 (油畫)` in `zhwiki`, the `結婚執照 (油畫)` will not show the thumbnails if we do not specify the license.

Add `pilicense=any` for prop=pageimages API calls

---

app/src/main/java/org/wikipedia/suggestededits/provider/EditingSuggestionsProvider.kt

When using Image Recommendations with German Wikipedia, it occasionally recommends images that are "public domain" which is not always appropriate for German Wikipedia, because Germany has different definitions/durations for "public domain" than the US. Therefore let's restrict image recommendations (for dewiki) to only images that are Creative-Commons licensed.
https://phabricator.wikimedia.org/T383765

Image recs on dewiki: restrict to CC-licensed images.

---

app/src/main/java/org/wikipedia/compose/components/WikiButtons.kt

Adds a state to the ThemeColorCircularButton
https://phabricator.wikimedia.org/T381832

Compose state 

---

app/src/main/java/org/wikipedia/feed/announcement/AnnouncementCardView.kt

Rookie mistake -- doing a `.post { ... }` but forgetting to check if the activity is still active.
(this is causing a couple of crashes in production, but I do believe this crash is silent, so this is ok to wait until next release.)

Prevent possible crash due to post-ing on a View.

---

app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListViewModel.kt

This PR fixes the issue when requesting the `https://wikimedia.org/api/rest_v1/metrics` endpoint for a user talk page. It looks like an unsupported namespace, and we can check if the namespace is `Main` to avoid breaking the layout in the Edit History list.
1. Go to a user talk page.
2. Click on the Edit history
The following screenshots show the invisible icon was caused by the incompleted request in the view model.

Fix: issue of showing the User_Talk metrics in Edit History

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

Add strings for the final screen and replace the existing strings in the feature branch.

Add strings for wikigame final result screen

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

Adds strings for game feed entry card

[Wikigames] feed entry strings

---

app/src/main/java/org/wikipedia/dataclient/ServiceFactory.kt
app/src/main/java/org/wikipedia/feed/becauseyouread/BecauseYouReadClient.kt

The `page/related` endpoint has been removed some time ago, but we still have a couple of references to it in our code and comments.

Remove outdated mentions of `page/related` endpoint.

---

app/src/main/java/org/wikipedia/dataclient/ServiceFactory.kt
app/src/main/java/org/wikipedia/staticdata/ContributionsNameData.kt
app/src/main/java/org/wikipedia/staticdata/FileAliasData.kt
app/src/main/java/org/wikipedia/staticdata/MainPageNameData.kt
app/src/main/java/org/wikipedia/staticdata/SpecialAliasData.kt
app/src/main/java/org/wikipedia/staticdata/TalkAliasData.kt
app/src/main/java/org/wikipedia/staticdata/UserAliasData.kt
app/src/main/java/org/wikipedia/staticdata/UserTalkAliasData.kt
app/src/main/res/values/languages_list.xml
scripts/generate_wiki_languages.py

* This makes a slight tweak to the language update script to get the English name of each language from the `siteinfo` API call instead of the `sitematrix` call. The `siteinfo` call contains more comprehensive and more appropriate language names, specifically for the case of Norwegian Bokmål.
* This also runs the update script itself, to refresh our collection of static data.
https://phabricator.wikimedia.org/T384569

Periodic update of static language data.

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

- For menu icons.
- For the text in the share function.

Add strings for Wikigame final screen

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

Updated strings in the overflow menu, and added strings for email subject and body.
https://phabricator.wikimedia.org/T383695#10506102

Update strings for wiki game final result screen

---

app/src/main/res/layout/fragment_talk_templates.xml

A minor tweak for the empty container.

Add margins to the talk templates to avoid text reaches the edge

---

app/src/main/java/org/wikipedia/talk/TalkTopicsViewModel.kt

For some reason, my [account's talk page](https://en.wikipedia.org/w/api.php?format=json&formatversion=2&errorformat=html&errorsuselocal=1&action=discussiontoolspageinfo&prop=threaditemshtml&page=User_talk%3ACFeng_%28WMF%29) does not have the correct header content. This PR adds an additional check to remove the empty item from the list.

Remove empty item from talk page list for incorrect header

---

app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameActivity.kt

Show the wiki game pause dialog for the `onBackPressed` action.
The dialog only pops up when clicking on the close button. It will be better if we add the dialog for the back button action.

Show the pause game dialog for the onBackPressed action

---

app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameActivity.kt

The logic of scheduling wikigame notification only works for API > 32. 
The older API does not require the permission check, but we still need to run the function to schedule the notification.

Fix: make sure scheduling wikigame notification works correctly for API < 33

---

app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameActivity.kt
app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameViewModel.kt

This can happen when entering the game and very quickly pressing Back (before the ViewModel finishes loading the content from the network).
This is because we attempt to show the Pause dialog and send an analytics event that depends on the game's `currentState` which is a `lateinit var` that hasn't been loaded yet.
This fix will:
* No longer show the Pause dialog if the game is still loading.
* Prevent analytics events from depending on an uninitialized `currentState`, by explicitly handing the case of the "loading" screen.

Prevent possible crash when exiting game during loading.

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

`on_this_day_game_experiment_chip_text` and `on_this_day_game_nav_title` are unused strings.
`on_this_day_game_share_text` is a duplicated string.

Wikigames: remove unused and duplicated strings

---

app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameActivity.kt
app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameOnboardingFragment.kt
app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameViewModel.kt

This makes a few small refinements to analytics events coming from the game:
* Deduplicate code for the "X" button and the system Back button, which do the same thing, and should send the same event.
* The ViewModel doesn't differentiate very nicely between a "GameStart" state and a "first question" state, which was confusing the analytics a bit:
* This was causing events to be sent with a `slideName` of "game_start" when it should have been "game_play_1". This is now fixed by giving an explicit `slideName` in the onboarding fragment, and return "game_play_1" from the ViewModel even if the current state is GameStart.
* The `cardAnimatorSet` Animators are given a `doOnEnd {}` callback every time the cards are animated, and this actually _adds_ a `doOnEnd` call every time, which will cause …

Refine game-related analytics.

---

app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameActivity.kt
app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameViewModel.kt
app/src/main/res/layout/activity_on_this_day_game.xml

* This updates the question-card layout for the case where the question has no image thumbnail. This will no longer use a "placeholder" image, and will instead make the text flow to the full width of the card, and above the "correct/incorrect" icon.
* This also updates the logic for getting the thumbnail for the current Event. Instead of trying to get the thumbnail from the "first" article in the event, this will now get any thumbnail from _any_ article in the event.
The changes look a bit more major / intimidating than they are; this is a minor-ish tweak.

Final, ultimate, definitely for real, design tweaks to the game.

---

app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameArticleBottomSheet.kt
app/src/main/java/org/wikipedia/util/FeedbackUtil.kt
app/src/main/java/org/wikipedia/views/AllowSnackbarOverBottomSheet.kt

This introduces an `interface` to be used by BottomSheet components that want to allow Snackbars to be displayed over them.

Show snackbar over BottomSheet only if allowed.

---

app/src/main/java/org/wikipedia/views/ImageZoomHelper.kt

(not related to the game)
This is a minor-ish [crash](https://play.google.com/console/u/0/developers/6169333749249604352/app/4976363884102945010/vitals/crashes/f82733c921a2df2983a1988d3a2f627d/details?days=28&versionCode=50519&isUserPerceived=true) that seems to have started happening in production (and beta) since our last release.
Even though I can't reproduce it myself yet, this additional check should take care of it.
It would be great to merge this into our current release.

Fix potential crash when zooming images with ImageZoomHelper.

---

app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameActivity.kt

This fixes the issue when you click on the "Next question" button rapidly, the content and the behavior of the game go wrong.
https://github.com/user-attachments/assets/edfdb768-1710-43fc-a018-9321a8be5407

Wikigames: Hide next question button after clicking on it

---

app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameArticleBottomSheet.kt

A temporary solution for a crash when the "Don't keep activities" is on and the bottomsheet is opened, and a switch between the system app chooser will lead to a crash.

Dismiss the bottomsheet onPaused to avoid possible crash

---

app/src/main/java/org/wikipedia/feed/FeedFragment.kt
app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameOnboardingFragment.kt
app/src/main/java/org/wikipedia/page/PageFragment.kt

* This moves the logic of checking whether to show the Game dialog entirely into the Game class, instead of exposing it in PageFragment.
* This also adds an InvokeSource parameter into the `maybeShowOnThisDayGameDialog()` function, since it can be called from PageActivity or from the Feed, but it was hard-coding InvokeSource.PageActivity when actually launching the game.

Follow-up 2: Keep Game dialog language logic a bit more self-contained.

---

app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameViewModel.kt

In the cases where the Game state is not yet initialized, the "screen name" can still be `game_loading` instead of `unknown` because, by definition, the state being uninitialized implies that the ViewModel is in the process of loading.

Follow-up 1: loading state for Game ViewModel.

---

app/src/main/java/org/wikipedia/activity/BaseActivity.kt
app/src/main/java/org/wikipedia/activity/SingleFragmentActivity.kt
app/src/main/java/org/wikipedia/main/MainActivity.kt
app/src/main/java/org/wikipedia/notifications/NotificationPollBroadcastReceiver.kt
app/src/main/java/org/wikipedia/page/PageActivity.kt
app/src/main/java/org/wikipedia/util/DeviceUtil.kt

This might actually fix the elusive crashes we've seen relating to uninitialized `lateinit` instance variables coming from `WikipediaApp$Companion.getInstance`.
There is a platform-specific bug related to launching the app in "restricted" mode during device backup operations. I found a Google issue that provides a clue for why this may be happening:
https://issuetracker.google.com/u/0/issues/160946170
See comments in the code for more details.

Possibly (?) resolve obscure lateinit UninitializedProperty crashes.

---

app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameActivity.kt

We have a discussion on Slack about where to improve the readability of the game's question cards, this introduces a long-press action to show the full text of the card. 
https://phabricator.wikimedia.org/T387535

Wikigames: long-press to see the full text of the current card

---

app/src/main/java/org/wikipedia/compose/theme/WikipediaTheme.kt

The theme was only switching between light and dark system theme. This update resolves the issue where the compose base theme wasn't properly updating when users switched between themes.

compose base theme fix

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/org/wikipedia/yearinreview/TestScreen.kt
app/src/main/java/org/wikipedia/yearinreview/YearInReviewActivity.kt
app/src/main/java/org/wikipedia/yearinreview/testscreen.kt
gradle/libs.versions.toml

This adds the YearInReviewActivity with Jetpack Compose navigation and a simple test screen. Dependencies and manifest are updated to preview the activity.
Supports Year In Review EPIC T387034
https://phabricator.wikimedia.org/T387803
https://phabricator.wikimedia.org/T387034

T387803 - Build Jetpack Compose NavHost and first YiR screen

---

app/src/main/java/org/wikipedia/wiktionary/WiktionaryDialog.kt

https://en.wiktionary.org/api/rest_v1/page/definition/Australia
The definition of `Australia` contains some empty definitions, this PR updates the logic to filter the empty ones.

Fix: do not show empty definitions in the WiktionaryDialog

---

app/src/main/java/org/wikipedia/main/MainFragment.kt
app/src/main/java/org/wikipedia/navtab/MenuNavTabDialog.kt
app/src/main/java/org/wikipedia/yearinreview/YearInReviewActivity.kt

This adds a functioning clickable listener that links the 'Year in Review' in MenuNavTabDialog to the YearInReviewActivty
Supports EPIC T387034
https://phabricator.wikimedia.org/T387804

Create clickable navigation for the year in review entry point: T387804 

---

app/src/main/java/org/wikipedia/compose/components/HtmlText.kt

A follow up to #5397, by passing a custom `linkInteractionListener`, we can either open links on external browser or within the app.

Add linkInteractionListener to the HtmlText method

---

app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListViewModel.kt

Because of the way we were postprocessing the PagingData of the edit history, the initial revision of an article was getting a `diffSize` of zero, because the `diffSize` was simply never set.
https://phabricator.wikimedia.org/T388926

Correctly calculate size of initial revision of an article.

---

app/src/main/java/org/wikipedia/history/db/HistoryEntryWithImageDao.kt

The `entryWithImage.timeSpentSec` was added as a `prevId` in the `HistoryEntry` object incorrectly. This PR removes it from the method.

Fix: remove timeSpentSec variable in the toHistoryEntry method

---

app/src/main/java/org/wikipedia/auth/AccountUtil.kt
app/src/main/java/org/wikipedia/dataclient/SharedPreferenceCookieManager.kt
app/src/main/java/org/wikipedia/settings/LogoutPreference.kt
app/src/main/java/org/wikipedia/settings/Prefs.kt
app/src/main/res/values/preference_keys.xml
app/src/main/res/xml/developer_preferences.xml

According to updated guidance, we _cannot_ use the expiry of the CentralAuth cookie as the expiration date of the user's temp account. We must therefore hardcode a value of 90 days for the expiry, and record ourselves the date on which the temp account was created.
https://phabricator.wikimedia.org/T388849

Temp accounts: explicitly set expiry to 90 days.

---

app/src/main/java/org/wikipedia/database/AppDatabase.kt

This updates the v28 migration step to _also_ insert rows into the `PageImage` table that didn't yet exist, instead of only updating existing rows.
This catches cases where the user visited an article that doesn't have a lead image, but the user spent time reading the article, and/or the article has a description. We still want to capture this metadata in the updated `PageImage` table.
For 10000 entries, this adds another ~50ms to the migration step.

Update migration query to also insert missing PageImage rows.

---

app/src/main/java/org/wikipedia/database/AppDatabase.kt
app/src/main/java/org/wikipedia/history/db/HistoryEntryWithImageDao.kt

* There is just one more extreme edge case that the db migration logic was failing to catch (causing a tiny number of crashes in Beta): The old HistoryEntry could in fact contain entries that have the same combination of [lang, namespace, apiTitle], dating back to a time when we *didn't* upsert the "latest" entry for that combination. This kind of case would violate the primary-key constraint on the PageImage table. (This update does not increase the migration time at all.)
* When filtering the items in the History screen, they need to be unique by title *and* language, instead of just by title. Currently, if you navigate to different language versions of the same article (with the same title), it appears as a single entry in History.

Final, ultimate fixes for db migration.

---

app/src/main/res/layout/fragment_search_recent.xml

A minor update to the visibility for the recent search container is that if you do not have recent search queries, the view will still show up and disappear in a very quick way, which can be avoided.

Update the default visibility of recent search container to "gone"

---

app/src/main/java/org/wikipedia/login/LoginActivity.kt
app/src/main/java/org/wikipedia/login/LoginClient.kt
app/src/main/java/org/wikipedia/util/FeedbackUtil.kt
app/src/main/res/layout/activity_login.xml

When we receive "UI" messages from the Login API (for entering a 2FA code or captcha), these messages are received as wikitext, and might contain links or other syntax, and must therefore be passed through the parser.
This also takes care of a few other tiny tweaks:
* When displaying a snackbar with text that comes from `fromHtml()`, let's `trim()` it because certain messages, after being parsed, end up containing extraneous empty tags at the end (such as `<p>` or `<br />`) that produce unnecessary empty lines that don't look good in a snackbar.
* The 2FA field in the Login screen was missing top padding.
* When revealing the 2FA field, let's hide the soft keyboard, so that the full snackbar could be displayed, and not overlap the 2FA field.
https://phabricator.wikimedia.org/T390919

Pass login UI messages through parser.

---

app/src/main/java/org/wikipedia/compose/components/WikiCard.kt

Converts the `WikiCardView` to use Compose. No design review will be needed since this is a custom view conversion.
Some screenshots have been attached in the ticket if you desire to see the implementations.
https://phabricator.wikimedia.org/T389141

Convert WikiCardView to use Compose

---

app/src/main/java/org/wikipedia/csrf/CsrfTokenClient.kt
app/src/main/java/org/wikipedia/dataclient/Service.kt
app/src/main/java/org/wikipedia/dataclient/SharedPreferenceCookieManager.kt
app/src/main/java/org/wikipedia/dataclient/okhttp/CommonHeaderRequestInterceptor.kt
app/src/main/java/org/wikipedia/login/LoginActivity.kt
app/src/main/java/org/wikipedia/login/LoginClient.kt
app/src/main/java/org/wikipedia/login/LoginEmailAuthResult.kt
app/src/main/java/org/wikipedia/login/LoginResponse.kt
app/src/main/java/org/wikipedia/login/ResetPasswordActivity.kt
app/src/main/java/org/wikipedia/settings/Prefs.kt
app/src/main/java/org/wikipedia/views/NonEmptyValidator.kt
app/src/main/res/layout/activity_reset_password.xml
app/src/main/res/values-qq/strings.xml
app/src/main/res/values/preference_keys.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/developer_preferences.xml

This enables integration with [EmailAuth](https://www.mediawiki.org/wiki/Extension:EmailAuth), where a login attempt requires a second factor that is sent to the user via email.
This basically reuses our existing logic for 2FA ([OATHAuth](https://www.mediawiki.org/wiki/Extension:OATHAuth)), just with slightly different verbiage and logic.
There is now a new Developer preference for "forcing" email authentication, if necessary for testing.
https://phabricator.wikimedia.org/T390820

Enable EmailAuth support.

---

app/src/main/java/org/wikipedia/main/MainFragment.kt
app/src/main/java/org/wikipedia/yearinreview/YearInReviewEntryDialog.kt
app/src/main/java/org/wikipedia/yearinreview/YearInReviewEntryDialogScreen.kt
app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

A follow-up PR of #5465 that does the following optimization:
- Renames classes to `EntryDialog` instead of a plain `Dialog`.
- Renames `BottomSheetScaffold` to `YearInReviewEntryDialogScreen`, since there might be another bottomsheet that exists in the YiR package, and also for easier access.
- Renames the string resources with `entry_dialog` in them.
- Optimizes the scrolling experience.
- Optimizes the padding for title, body text, and the image - the current image is cut because of the `centerCrop`.
@voyagerfan Please help review, and we can discuss this in our 1:1 for you to have a better picture of this PR.

Follow-up: YiR entry dialog code optimization

---

app/src/main/java/org/wikipedia/talk/TalkTopicsViewModel.kt

This fixes some slightly incorrect logic that we had for checking the Watched status of a Talk page.
* There was an unused parameter in the ViewModel (`sidePanel`) that can be removed.
* The logic was depending on the above parameter (that was never set?) to check or not check the Watched status.
* The correct logic should depend on whether the current user is logged in.

Fix/improve logic for checking Watched status of Talk page.

---

app/src/main/java/org/wikipedia/search/SearchFragment.kt

* Go to Places
* Search for something in the Search interface
* Long-press on a result and select "Open"
This is because the `LongPressHandler` doesn't preserve the `location` of the search result, and therefore doesn't pass it back into its callback.
I would argue the proper fix for this behavior is just to open the result in PageActivity for reading, since intuitively if someone long-presses and chooses "Open", the intention is to "open for reading".
https://phabricator.wikimedia.org/T392660

Fix crash when long-pressing to open from Places Search.

---

app/src/androidTest/java/org/wikipedia/robots/feature/SettingsRobot.kt
app/src/main/java/org/wikipedia/settings/AboutActivity.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-az/strings.xml
app/src/main/res/values-da/strings.xml
app/src/main/res/values-fi/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-iw/strings.xml
app/src/main/res/values-mk/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-qq/strings.xml
app/src/main/res/values-sl/strings.xml
app/src/main/res/values-sv/strings.xml
app/src/main/res/values-uk/strings.xml
app/src/main/res/values-zh-rTW/strings.xml
app/src/main/res/values-zh/strings.xml
app/src/main/res/values/strings.xml

1. Renamed the string resource name from `about_screen_logo_accessibility_text` to `about_logo_content_description`
2. Moved the item under the other about screen strings.
Most of the strings are in certain groups, and it will be easier to maintain/find.

Rename string item and move it to a proper location

---

app/src/androidTest/java/org/wikipedia/base/BaseTest.kt
app/src/androidTest/java/org/wikipedia/base/ComposeTestManager.kt
app/src/androidTest/java/org/wikipedia/base/base/BaseRobot.kt
app/src/androidTest/java/org/wikipedia/base/utils/ComposeTestExtensions.kt
app/src/androidTest/java/org/wikipedia/robots/feature/PageRobot.kt
app/src/androidTest/java/org/wikipedia/robots/feature/SettingsRobot.kt
app/src/androidTest/java/org/wikipedia/robots/screen/LanguageListRobot.kt
app/src/androidTest/java/org/wikipedia/tests/search/SearchExternalIntentTest.kt
app/src/androidTest/java/org/wikipedia/tests/search/SearchIntentTest.kt
app/src/androidTest/java/org/wikipedia/tests/settings/AboutSettingsTest.kt
app/src/androidTest/java/org/wikipedia/tests/settings/ChangingLanguageTest.kt
app/src/main/java/org/wikipedia/compose/components/SearchTopAppBar.kt
app/src/main/java/org/wikipedia/language/addlanguages/AddLanguagesListScreen.kt

- adds compose test support for language links and language list
- adds support to directly use composeTestRule in both test class and robot classes
- the search intent test will be fixed in separate PR

Espresso Fix - Compose Support

---

app/src/main/java/org/wikipedia/yearinreview/YearInReviewActivity.kt
app/src/main/java/org/wikipedia/yearinreview/YearInReviewScreenData.kt
app/src/main/java/org/wikipedia/yearinreview/YearInReviewViewModel.kt

This PR utilizes the coding structure to match the project by changing:
1. Creates a `viewModel` outside the `onCreate`.
2. Keeps the `YearInReviewScreenData` clean and moves the static data to the `ViewModel` in the `companion object`.
3. Update variables `private` vs `public`.
4. Removes a redundant `async` for the edit counts calls.
@voyagerfan please review and merge this PR if it looks good to you.

Follow-up: viewModel for YearInReview

---

app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameFinalFragment.kt

Remove a weird dot from the screenshot after regenerating the image. 
**Steps to reproduce**
1. Click on share and select "Slack" to share it to your DM.
2. Switch to the Slack app and wait for upload completion.
3. Switch back to the Wikipedia app and click share again to share the image to the Slack app to your DM.
4. Switch back to the Slack app and wait for upload completion.

Fix: remove old dots after regenerating new screenshot for WikiGames

---

app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameFinalFragment.kt

I realized we could generate the shareable screenshot at the same time that the final fragment itself loads (in `onCreateView`), because why not!
* This will make the Share action _faster_, because the shareable layout will likely finish loading already.
* If the user taps Share again, we don't need to _regenerate_ the layout.
* This also solves the layout issue of dynamically adding Views, by no longer needing to remove them.

Follow-up 2 to sharing game screenshot.

---

app/src/main/res/layout/item_reading_list.xml

This PR moves the two icons to the bottom of the descriptions, and updates the icons color from `placeholder_color` to `primary_color`.
https://phabricator.wikimedia.org/T393502

Discover pre-work: change the icons location in the readinglist header item view

---

app/src/main/java/org/wikipedia/auth/AccountUtil.kt

At the moment we're detecting a temporary account by simply checking for the presence of session cookies and the absence of an account in the `AccountManager`. But this can lead to a false-positive state where the `AccountManager` credentials could go away (the user can explicitly delete the account in the device Settings, or by other means).
Let's detect the temporary account more explicitly, by checking for the magic character `~` at the start of the account name.
https://phabricator.wikimedia.org/T394013

Make temp account status detection more explicit.

---

app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt

A bug from the previous simplify PR #5531, because `getPagePositionInList()` will throw `-1` if no position has found.
```
Process: org.wikipedia.dev, PID: 5183
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 5
at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
at java.util.Objects.checkIndex(Objects.java:359)
at java.util.ArrayList.get(ArrayList.java:434)
at org.wikipedia.readinglist.ReadingListFragment$onCreateView$1$1$3$1.invokeSuspend(ReadingListFragment.kt:168)
at org.wikipedia.readinglist.ReadingListFragment$onCreateView$1$1$3$1.invoke(Unknown Source:8)
at …
```

Fix: crash when adding articles from one reading list to another

---

app/src/main/java/org/wikipedia/readinglist/database/ReadingList.kt

When you have a fresh install, the thumbnail on the list does not get updated correctly, and that's because we have always been comparing the same `numPagesOffline` by itself!

Fix: make sure to compare the correct value for updating the list in ReadingListsFragment

---

app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameFinalFragment.kt

There is a crash that can happen when launching the FinalFragment of the game, when it builds the "sharing" view. The function to start building this view is called when the fragment is created, but the `gameState` in the ViewModel might not yet be initialized.
Therefore let's call this function in a more safe (and correct) place, when the ViewModel calls back with a `GameEnded` state, which guarantees the `gameState` will be valid.

Fix minor potential crash in Final game screen.

---

app/src/main/java/org/wikipedia/settings/Prefs.kt
app/src/main/res/values/preference_keys.xml

Did not notice until now, and it is better to keep the naming style consistent in the app. (but we may re-release to beta if possible, but that's probably fine for the next release too).

Update the game sound preference key name to keep the naming consistent

---

app/src/main/java/org/wikipedia/navtab/NavTabLayout.kt
app/src/main/res/values/ids.xml

This adds a function that creates a red dot over any Navigation tab on the main screen.
This can be merged into master, since the function itself is not yet used, but can be used by the upcoming feature branch.
https://phabricator.wikimedia.org/T394113

Add optional "New" dot over navigation tabs.

---

app/src/main/res/values-mk/strings.xml
app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml
app/src/test/java/org/wikipedia/language/TranslationTests.kt

When adding a string resource with multiple parameters, the parameters _must be in the explicit sequential format_ (`%1$d`, `%2$s`, and so on) instead of the plain `%d` `%s`. This is because some languages could change the order of the parameters, which will confuse the string formatting functions, and may even cause crashes.
I'm adding a test to catch these cases in the future.

Fix sequential parameters in new strings, and add tests.

---

app/src/main/java/org/wikipedia/recurring/RecommendedReadingListTask.kt

This makes the task run on the _first_ day of the week, or the _first_ day of the month, instead of "every 7 days" or "every 31 days", which does not guarantee that it will run on the first day of the week/month.

Follow-up to recurring task.

---

app/src/main/java/org/wikipedia/compose/components/WikiCard.kt
app/src/main/java/org/wikipedia/compose/theme/WikipediaColor.kt
app/src/main/java/org/wikipedia/compose/theme/WikipediaTheme.kt

This removes the necessity to pass around an `isDarkTheme` parameter wherever a `WikiCard` composable is used.
The only purpose of this parameter is whether or not to apply an elevation to the card, and the reason it became a parameter is to make Previews work, since a Preview is not aware of `WikipediaApp.instance`.
But now, we can encode directly into the `WikipediaTheme` composable whether the current theme is Dark or not, and remove the actual dependency on `WikipediaApp.instance`.

Simplify detection of Dark theme in WikiCard composable.

---

app/src/main/java/org/wikipedia/compose/components/WikiCard.kt
app/src/main/java/org/wikipedia/compose/theme/WikipediaTheme.kt
app/src/main/java/org/wikipedia/language/LangLinksScreen.kt
app/src/main/java/org/wikipedia/language/addlanguages/AddLanguagesListScreen.kt

Are there any clickable Composables where we **don't** want a ripple effect?
If not, then let's make a `ripple()` indication be the default indication for composables.
This way, we won't need to explicitly add `indicator = ripple()` or the more bizarre `interactionSource = remember { MutableInteractionSource() }` wherever we want a ripple.

Provide a default ripple effect for all Composables.

---

app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSettingsActivity.kt
app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSettingsScreen.kt

- rename parameter 
- only shows snackbar if user has changed their source

Minor follow up RRL

---

app/src/main/java/org/wikipedia/settings/Prefs.kt

- changes the default isRecommendedReadingListNotificationEnabled to false

Default RRL notification Preference should be false

---

app/src/main/java/org/wikipedia/settings/AboutActivity.kt

The About screen (recently converted to Compose) contains a lot of text, including the app version number, but the text is no longer highlightable, so users are not able to click and copy any text from it.
This is fixed easily by using `SelectionContainer` blocks; I added one block around the version code, and another around the rest of the text in the About screen.
https://phabricator.wikimedia.org/T395992

Make text in the About screen highlightable and copyable.

---

app/src/main/java/org/wikipedia/views/imageservice/CoilImageServiceLoader.kt
app/src/main/java/org/wikipedia/views/imageservice/ImageService.kt

(This will be useful and/or necessary for the upcoming Reading Lists work)
If we expose a `getRequest()` function from our ImageService, we will be able to use it with `AsyncImage` blocks in our Composables, and get all the benefits of our ImageLoader including Face detection, white background, etc.

Follow-up to Coil: expose getRequest() for use in AsyncImage.

---

gradle/libs.versions.toml

Bumps androidx.lifecycle:lifecycle-viewmodel-compose from 2.9.0 to 2.9.1.
---
updated-dependencies:
- dependency-name: androidx.lifecycle:lifecycle-viewmodel-compose dependency-version: 2.9.1 dependency-type: direct:production update-type: version-update:semver-patch ...
https://phabricator.wikimedia.org/T...

Bump androidx.lifecycle:lifecycle-viewmodel-compose from 2.9.0 to 2.9.1

---

gradle/libs.versions.toml

Bumps androidx.appcompat:appcompat from 1.7.0 to 1.7.1.
---
updated-dependencies:
- dependency-name: androidx.appcompat:appcompat dependency-version: 1.7.1 dependency-type: direct:production update-type: version-update:semver-patch ...
https://phabricator.wikimedia.org/T...

Bump androidx.appcompat:appcompat from 1.7.0 to 1.7.1

---

app/src/main/java/org/wikipedia/talk/TalkThreadItemView.kt

The key insight is that we should not call the `MenuInflater()` constructor ourselves, and instead use `activity.menuInflater` where possible.
(`activity.menuInflater` actually becomes `SupportMenuInflater`, not the platform `MenuInflater`.)

Fix tinting of menu items in Talk topics.

---

app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSourceFragment.kt
app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListViewModel.kt

If the user entered the source selection screen from the Settings screen, we should show the confirmation dialog after it changes.
https://www.figma.com/design/Z2n0gZOOAbgsIdHgUS5ocQ/Android-%E2%86%92-Rabbit-Holes-%E2%86%92-T378612?node-id=1210-18522&t=5EYUyKoJosPad3bC-4

Show a confirm dialog when adjust source from settings

---

app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
app/src/main/java/org/wikipedia/readinglist/ReadingListFragmentViewModel.kt
app/src/main/java/org/wikipedia/readinglist/db/RecommendedPageDao.kt
app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListHelper.kt
app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSettingsActivity.kt
app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSettingsViewModel.kt
app/src/main/java/org/wikipedia/recurring/RecommendedReadingListTask.kt
app/src/main/java/org/wikipedia/settings/Prefs.kt
app/src/main/res/values/preference_keys.xml

Currently, we do not reset the recommended reading list after making changes in the Discover Settings. The way of making the app to expire old pages and regenerating new pages is to save a reset preference for the `ReadingListFragment` to be able to update the list, and not losing the entry point in the `ReadingListFragments`. 
Pending discussion: do we need a "Reset" button in the Discover settings so people can reset recommendations and back to the default?

Optimize the way of re-generating new list from Settings

---

app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListHelper.kt

- When the user selects 'Saved articles' as the source, the `prefixedText` includes 'Main' at the beginning of the title, which prevents the generation of a recommended reading list. Replacing it with `text` ensures the title is correct for generating the list.

Use text instead of prefixedText for generating RRL

---

app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListInterestsFragment.kt

The introduction of `BackHandler { }` is conflicting with the explicit call to `onBackPressedDispatcher.onBackPressed()`, and causes a stack overflow.

Fix StackOverflow when pressing Back from Interests selection.

---

app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt
app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsFragment.kt
app/src/main/res/values/strings_no_translate.xml

This updates the URL that the user is taken to, when tapping Info links about short descriptions.
In the case of English Wikipedia, the URL will now go directly to [WP:SHORTDESC](https://en.wikipedia.org/wiki/Wikipedia:Short_description), instead of our general Suggested Edits page on MediaWiki.org.
https://phabricator.wikimedia.org/T390105

Use correct help URL for Short Descriptions in enwiki.

---

app/src/main/res/layout/fragment_reading_lists.xml

When you visit the Saved tab for the first time after you open the app, the layout animation shifts the recyclerview below the onboarding/Discover card. Since the view does not have a background color, the text on the list overlaps a bit.

Add background color to the reading lists recyclerview

---

app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListAbTest.kt

Based on the request from the PM signoff, this PR changes the logic of enabling test groups for `DevRelease` instead of `PreBetaRelease`.

Adjust the A/B test logic from PreBetaRelease to DevRelease for Recommended Reading List

---

app/src/main/java/org/wikipedia/compose/components/LicenseLinkText.kt
app/src/main/java/org/wikipedia/compose/components/WikiButtons.kt
app/src/main/java/org/wikipedia/compose/components/WikiCard.kt
app/src/main/java/org/wikipedia/compose/components/WikiSnackbar.kt
app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListInterestsFragment.kt
app/src/main/java/org/wikipedia/settings/AboutActivity.kt

Another goal in adopting pure Material typography is to use as few explicit `fontSize`, `lineHeight`, etc. overrides as possible.
This PR focuses mostly on the AboutActivity, where there were quite a few unnecessary `.sp` overrides.
This also updates some of our custom Composables which are currently unused (WikiButtons and WikiCard), which don't need to override any text styles.

Follow-up to Material typography.

---

app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSettingsActivity.kt

A fix for showing the "translated" frequency text in the event, regarding the analyst's feedback.

Fix: should use hard-coded text for the event in RRL

---

app/src/androidTest/java/org/wikipedia/base/actions/ListActions.kt
app/src/androidTest/java/org/wikipedia/robots/screen/SuggestedEditsScreenRobot.kt
app/src/androidTest/java/org/wikipedia/tests/SuggestedEditScreenTest.kt

- fixes suggested edit screen test following the update to hide article descriptions for edits under 50 characters.

Suggested task edits espresso test fix

---

app/src/main/java/org/wikipedia/database/AppDatabase.kt

- Rename the parameter `database` to `db` to match the library default naming and avoid IDE warnings.
- Rename `e` to `_` because they are used.
- Remove `.allowMainThreadQueries()` because we have completed the migration for a while.
- Update `fallbackToDestructiveMigration` instead of using the deprecated one.

Update AppDatabase class to clean up IDE warnings and todo stuff

---

app/src/main/res/values/strings_no_translate.xml

The current URL is a redirect to an updated one.
https://phabricator.wikimedia.org/T398141

Update mediawiki URL for help with edit summaries.

---

app/src/main/java/org/wikipedia/dataclient/RestService.kt
app/src/main/java/org/wikipedia/feed/aggregated/AggregatedFeedContentClient.kt
app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameViewModel.kt
app/src/main/java/org/wikipedia/widgets/WidgetFeaturedPageWorker.kt

1. Remove part of the language variants code from the project, but we still need to keep the one in the `BecauseYouReadClient` because it was for the article description.
2. Add a `lang=` parameter to the `feed/featured` endpoint to avoid the cache issue when switching between different language variants.
**Related tickets
https://phabricator.wikimedia.org/T355192
https://phabricator.wikimedia.org/T397743

Remove extra language variants code and add an extra parameter to featured endpoint

---

app/src/main/res/layout/view_wiki_games_card.xml

The width of  `viewWikiGamesCardTitle` view was set to `wrap_content`, which was incorrect in a `ConstraintLayout` if you have other views connected to it, which led to an incorrect display if the title text is short.
Before vs. After

Fix: set the width correctly for the WikiGames feed card view

---

app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt
app/src/main/res/layout/dialog_link_preview.xml

Recent updates in PCS have affected the display of link previews in Dark mode.
Rather than reverting the PCS changes, let's no longer use a WebView in link previews, and figure out a more sensible balance of showing html content in link previews going forward.

No longer use WebView in LinkPreviewDialog.

---

app/src/main/java/org/wikipedia/page/PageFragment.kt

Our WebView maintains its own internal cache of resources, such as CSS and JS files.
But since we are intercepting all WebView requests and piping them through OkHttp (which has its own cache!), it may be possible for the WebView cache to become out-of-sync with the OkHttp cache.
When the user swipes down to refresh the article, let's explicitly clear the WebView cache (which is the user's intention anyway), to make sure the WebView definitely pulls the next requests from OkHttp.

Clear WebView cache when explicitly refreshing page.

---

app/src/main/java/org/wikipedia/language/AppLanguageLookUpTable.kt
app/src/main/java/org/wikipedia/language/LangLinksViewModel.kt

There are a few languages, namely `mni`, `tg`, `tly`, and `zgh`, where the language code _is itself_ one of the variants, instead of other languages like `zh`, where the variants are `zh-*`, and the base code `zh` is _not_ a variant. And so, the languages where the base code is its own variant need to be treated slightly differently.
https://phabricator.wikimedia.org/T399562

Fix listing of language variants where the first variant is the code.

---

.github/workflows/android_phab.yml

The Phabricator API is being rate-limited. The best practice is to include a proper User-Agent when making requests to the API, which should help avoid rate limiting errors.
https://phabricator.wikimedia.org/T360680

Include user-agent when posting with GitHubPRBot.

---

app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

The two strings for the input fields' error messages in the Donation Reminder Settings screen are missing.

Add strings for Donation Reminder error messages

---

app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt

The main issue was that the `lateinit` variable is still `null`, which causes a problem when executing the if conditions. We should probably avoid using `lateinit` and use `null-safe` (`?`) for variables.
https://phabricator.wikimedia.org/T401176

Fix: null from lateinit causes crash in DescriptionEditView

---

app/src/main/java/org/wikipedia/gallery/GalleryActivity.kt

We have a sneaky usage of a `View.tag` where we assume it's nonnull, when in fact it could be null.
https://phabricator.wikimedia.org/T401540

Fix potential NPE when tapping on Licence icon in Gallery.

---

app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameArticleBottomSheet.kt

If you click on articles that have no `extract` and no image available, the view in the article bottomsheet in the WikiGames results screen will remain blank. This is quick solution for this situation by adding the description to it.
Before vs. After

Fill description to the summary view in the article bottomsheet for WikiGames

---

app/src/main/java/org/wikipedia/activitytab/ActivityTabFragment.kt
app/src/main/java/org/wikipedia/activitytab/ActivityTabViewModel.kt

- In the current implementation, the **UiState** in the **ViewModel** can cause the entire UI to fail if an exception occurs during loading. This means that even modules unaffected by the exception may not be displayed.
- The proposed approach is to remove this shared **UiState** and instead create separate composable views for each module, which allows them to handle their own errors and UI events independently.

Activity tab to remove UI state proposal 

---

app/src/main/java/org/wikipedia/dataclient/RestService.kt
app/src/main/java/org/wikipedia/dataclient/restbase/PreviewRequest.kt
app/src/main/java/org/wikipedia/edit/preview/EditPreviewFragment.kt

The API request to get the preview of an edit is a POST request that takes the wikitext as a body parameter. The thing is, we were allowing the WebView to make this request on its own; and the problem is that the WebView only knows how to do a POST request with `x-www-form-urlencoded` data, whereas our API call performs better when the data is encoded as plain Json.
Therefore, let's just manage the POST request ourselves, and pass the resulting HTML directly to the WebView, like nature intended.
https://phabricator.wikimedia.org/T403137

Improve and streamline edit preview API call.

---

app/src/main/java/org/wikipedia/compose/components/WikiCard.kt
app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListInterestsFragment.kt

For the current `WikiCard` Compose component, the ripple animation does not respect the round corners of the card. This PR adds a `Box` and separates the clickable event out as a new `onClick` parameter.

Adds an onClick parameter for WikiCard to avoid ripple animation issue

---

app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListInterestsViewModel.kt

Somehow, the interests screen in the Recommended Reading list shows duplicated articles.
This PR adds a `.distinctBy { it.prefixedText }` to fix the issue.

Fix: use distinctBy to avoid showing duplicated articles in the interests screen 

---

app/src/main/java/org/wikipedia/activitytab/ActivityTabCustomizationActivity.kt
app/src/main/java/org/wikipedia/activitytab/ActivityTabModules.kt

The `ActivityTabModules` and `ModuleType` classes are in the customization activity. This PR separates them out into an individual class so we can easily find them later.

Consolidate ActivityTabModules and ModuleType classes

---

app/src/main/java/org/wikipedia/activitytab/EditingInsightsModule.kt
app/src/main/res/values/strings.xml

Change the suggested edits card back to a view component and update the logic for the current month edits only.
https://phabricator.wikimedia.org/T403129

Update Contributions this month logic for design updates

---

app/src/fdroid/java/org/wikipedia/donate/GooglePayComponent.kt

The F-Droid build is currently failing because it looks like some of the Donation Reminder logic changed the interfacing of the `GooglePayComponent` object.

Fix fdroid build (from Donation Reminder work).

---

app/src/main/java/org/wikipedia/activitytab/ActivityTabFragment.kt
app/src/main/java/org/wikipedia/activitytab/ActivityTabViewModel.kt
app/src/main/java/org/wikipedia/activitytab/timeline/TimelineRepository.kt

We have regular `langCode` and `wikiSite` variables in the activity tab `viewModel`, but they are actually used by the timeline module. 
Since the `wikiSite` is based on the `Prefs.userContribFilterLangCode` preference, it is good to have a proper name that indicates only for the timeline module.
This PR also does a rename for  `MAX_BATCH_SIZE` since the IDE gives a warning about the syntax.

Rename wikiSite to wikiSiteForTimeline for the specific usage

---

app/src/main/java/org/wikipedia/navtab/NavTabLayout.kt

It looks like the recent material library change affects the parent layout of `NavTabLayout` from `FrameLayout` to `LinearLayout`. This PR updates it to prevent a crash when starting up the app.

When injecting red overlay dot, use grandparent view instead of parent.

---

app/src/main/java/org/wikipedia/activitytab/timeline/TimelineRepository.kt

- fixes crash when user scrolls the activity tab all the way to the bottom. 
- reason for crash was due to duplicate pagination keys, was returning wrong Cursor class from ReadingListPagingSource

Activity Tab crash fix

---

app/src/main/java/org/wikipedia/page/PageActivity.kt

When we rewrite `http` links to `https` (correctly), we're only doing it for the Prod flavor, not Beta. But since Beta is basically a production app where links should be similarly rewritten, we should do it for both Prod and Beta.

Hygiene: rewrite http->https scheme in both Beta and Prod.

---

app/src/main/java/org/wikipedia/activitytab/timeline/TimelineRepository.kt

- fixes timeline items not updating history entry table 
- Root cause: the timestamp was being set to the previous timestamp
https://phabricator.wikimedia.org/T405014

Fix for Timeline items not updating the history entry table on click

---

app/src/main/java/org/wikipedia/yearinreview/YearInReviewSlides.kt
app/src/main/java/org/wikipedia/yearinreview/YearInReviewViewModel.kt
app/src/main/res/values-qq/strings.xml
app/src/main/res/values/strings.xml

https://phabricator.wikimedia.org/T405425

YiR: Create Your Top Articles slide
