- app/src/main/res/values-ro/strings.xml
Prevent showing an error on the IDE when opening the BottomContentView.java
> Add missing parameter to a string resource in ro/strings.xml

- app/src/main/java/org/wikipedia/views/PageItemView.java
- app/src/main/res/layout/item_page_list_entry.xml
This improves the elevation and scroll behavior of the chips.
> Follow-up to Chips.

- app/src/main/res/drawable/ic_image_gray_24dp.xml
- app/src/main/res/layout/fragment_feed.xml
- app/src/main/res/layout/fragment_search_recent.xml
- app/src/main/res/layout/item_on_this_day_pages.xml
- app/src/main/res/layout/item_tab_contents.xml
- app/src/main/res/layout/view_wikipedia_language_footer.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/values/styles_black.xml
- app/src/main/res/values/styles_dark.xml
- app/src/main/res/values/styles_light.xml
- app/src/main/res/values/styles_sepia.xml
Tweak: update sepia theme color sets
https://phabricator.wikimedia.org/T194327
----
Optimize “Add Wikipedia languages“ button background-color in black theme
https://phabricator.wikimedia.org/T215885
----
> Tweak: update theme color set

- app/src/main/java/org/wikipedia/descriptions/DescriptionEditTutorialActivity.java
- app/src/main/java/org/wikipedia/editactionfeed/EditTasksFragment.java
- app/src/main/java/org/wikipedia/onboarding/InitialOnboardingActivity.java
- app/src/main/java/org/wikipedia/onboarding/OnboardingPageView.java
- app/src/main/res/drawable/ic_editor_onboarding.xml
- app/src/main/res/layout-land/view_onboarding_page.xml
- app/src/main/res/layout/fragment_edit_tasks.xml
- app/src/main/res/layout/fragment_onboarding_pager.xml
- app/src/main/res/layout/view_onboarding_page.xml
- app/src/main/res/menu/menu_edit_tasks.xml
- app/src/main/res/values-qq/strings.xml
- app/src/main/res/values/strings.xml
Changes to the screen itself:
https://phabricator.wikimedia.org/T217167
Changes to onboarding:
https://phabricator.wikimedia.org/T217166
> Visual changes to editor tasks screen.

- app/src/main/res/color/color_state_nav_tab_light.xml
- app/src/main/res/drawable/ic_image_gray_dark_24dp.xml
- app/src/main/res/drawable/ic_image_gray_light_24dp.xml
- app/src/main/res/drawable/ic_image_gray_transparent_24dp.xml
- app/src/main/res/drawable/ic_text_placeholder.xml
- app/src/main/res/layout/activity_page.xml
- app/src/main/res/layout/dialog_link_preview.xml
- app/src/main/res/layout/group_captcha.xml
- app/src/main/res/layout/item_on_this_day_pages.xml
- app/src/main/res/layout/item_page_list_entry.xml
- app/src/main/res/layout/item_search_result.xml
- app/src/main/res/layout/item_tab_contents.xml
- app/src/main/res/layout/view_description_edit.xml
- app/src/main/res/layout/view_floating_queue.xml
- app/src/main/res/layout/view_list_card_item.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/values/styles_black.xml
- app/src/main/res/values/styles_dark.xml
- app/src/main/res/values/styles_light.xml
- app/src/main/res/values/styles_sepia.xml
- Update styles in SimpleDraweeViewPlaceholder since some of them do not work properly.
- Add a new tab_placeholder_text_color attribute since the app:tint or android:tint does not work properly on an ImageView item.
https://phabricator.wikimedia.org/T194327
> Tweak of Add sepia theme ticket

- app/src/main/res/color/color_state_nav_tab_dark.xml
Regarding Robin's comment:
https://phabricator.wikimedia.org/T194327#5005938
> Change inactive nav tab color to white50 for the dark/black mode

- app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.java
- app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.java
- app/src/main/java/org/wikipedia/views/PageItemView.java
**Updated review comments**
- Translated colors to the other themes according to the Android Theme guidelines.
- Adjusted thumbnail width to 56x56px
- Clipped scrolling to the start of title & description.
- Blue shadow on the left of scrollview removed
- Search within a list (e.g. Saved) works exactly the same as the global “My lists“ search. Shows Chips.
Phab : https://phabricator.wikimedia.org/T214504
> Design review  - T214504

- app/src/main/java/org/wikipedia/views/PageItemView.java
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/values/styles_black.xml
- app/src/main/res/values/styles_dark.xml
- app/src/main/res/values/styles_light.xml
- app/src/main/res/values/styles_sepia.xml
**Chips Design tweaks**
- Updated chip colors to :
Element			| Light	| Sepia    | Dark		|Black
------------------ | --------- | -------| -------------- | -----
Chip Background | base80 | amate |base20 | base14
Chip text color | base20 | masi | base80 | base70
Phab: https://phabricator.wikimedia.org/T214504
> T214504 - Chips Design tweaks

- app/src/main/java/org/wikipedia/views/PageItemView.java
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/styles.xml
Remove unnecessary API restriction, and simplify a bit.
> Follow-up to chip styles.

- app/src/main/java/org/wikipedia/readinglist/ReadingListItemView.java
- app/src/main/java/org/wikipedia/search/SearchFragment.java
- app/src/main/java/org/wikipedia/views/CabSearchView.java
- app/src/main/java/org/wikipedia/views/SearchActionProvider.java
- app/src/main/res/layout/fragment_search.xml
- app/src/main/res/values/styles.xml
Update the thumbnail color
https://phabricator.wikimedia.org/T214505#5010784
Enable the `X` button
https://phabricator.wikimedia.org/T214505#5010855
Adjust arrow icon position and hintText color in SearchFragment 
https://phabricator.wikimedia.org/T214505#5011757
> Design tweak of enhancing reading lists search function

- app/src/main/java/org/wikipedia/page/PageFragment.java
- app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java
Just a bit of cleanup. (We don't actually need to set the margin upon configuration change now)
> Follow-up to fixing tablet margins

- app/src/main/java/org/wikipedia/bridge/CommunicationBridge.java
- app/src/main/java/org/wikipedia/crash/hockeyapp/HockeyAppExceptionHandler.java
- app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.java
- app/src/main/java/org/wikipedia/page/LinkHandler.java
- app/src/main/java/org/wikipedia/page/PageFragment.java
- app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java
- app/src/main/java/org/wikipedia/page/PageProperties.java
- app/src/main/java/org/wikipedia/recurring/RecurringTask.java
- app/src/main/java/org/wikipedia/widgets/WidgetProviderSearch.java
- Replace all remaining usages of Log.d() with our L.d() wrapper.
- Very minor roll-ups and optimizations.
> Some general minor cleanup.

- app/src/main/res/layout/dialog_link_preview.xml
- app/src/main/res/layout/group_captcha.xml
- app/src/main/res/layout/item_on_this_day_pages.xml
- app/src/main/res/layout/item_page_list_entry.xml
- app/src/main/res/layout/item_search_result.xml
- app/src/main/res/layout/view_description_edit.xml
- app/src/main/res/layout/view_floating_queue.xml
- app/src/main/res/layout/view_list_card_item.xml
- app/src/main/res/values/styles.xml
The base style `SimpleDraweeViewPlaceholder` should contain themed drawables, too. 
```
2019-03-14 11:32:44.659 19030-19030/org.wikipedia.dev W/Resources: Drawable org.wikipedia.dev:drawable/ic_image_gray_24dp has unresolved theme attributes! Consider using Resources.getDrawable(int, Theme) or Context.getDrawable(int).
java.lang.RuntimeException
at android.content.res.Resources.getDrawable(Resources.java:804)
at com.facebook.drawee.generic.GenericDraweeHierarchyInflater.getDrawable(GenericDraweeHierarchyInflater.java:268)
at com.facebook.drawee.generic.GenericDraweeHierarchyInflater.updateBuilder(GenericDraweeHierarchyInflater.java:130)
at com.facebook.drawee.generic.GenericDraweeHierarchyInflater.inflateBuilder(GenericDraweeHierarchyInflater.java:83)
at …
```
> Use themed drawable for the base style of DraweeViewPlaceholder

- app/build.gradle
- app/src/main/java/org/wikipedia/dataclient/okhttp/OfflineCacheInterceptor.java
Doesn't fix any issues, but good to keep on top of it.
> Update to OkHttp 3.14.0.

- app/build.gradle
- app/src/main/java/org/wikipedia/dataclient/okhttp/OfflineCacheInterceptor.java
Reverts wikimedia/apps-android-wikipedia#99
> Revert "Update to OkHttp 3.14.0."

- app/src/main/java/org/wikipedia/analytics/SessionData.java
- app/src/main/java/org/wikipedia/analytics/SessionFunnel.java
- app/src/main/java/org/wikipedia/descriptions/DescriptionEditActivity.java
- app/src/main/java/org/wikipedia/history/HistoryEntry.java
This adds the `session_token` parameter, as well as the new `fromSuggestedEdits` field.
https://phabricator.wikimedia.org/T218594
> Update SessionFunnel to latest spec.

- app/src/main/java/org/wikipedia/descriptions/DescriptionEditActivity.java
- app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.java
- app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.java
- app/src/main/java/org/wikipedia/editactionfeed/AddTitleDescriptionsFragment.kt
- app/src/main/java/org/wikipedia/page/PageFragment.java
The current master branch will have a failure when building APK due to the naming. Not sure why Github pass the check before merged.
This PR also update some naming on methods and extra sources.
> Fix: master branch build failed

- app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.java
- app/src/main/java/org/wikipedia/nearby/NearbyFragment.java
- app/src/main/java/org/wikipedia/page/PageActivity.java
This fixes a few very minor crashes observed in the latest Beta releases in HockeyApp:
https://rink.hockeyapp.net/manage/apps/226650/app_versions/337/crash_reasons/267351195
https://rink.hockeyapp.net/manage/apps/226650/app_versions/337/crash_reasons/267328006
https://rink.hockeyapp.net/manage/apps/226650/app_versions/337/crash_reasons/267318347
> Fix a couple of minor crashes.

- app/src/main/java/org/wikipedia/readinglist/database/ReadingList.java
> Fix sorting reading lists by name.

- .travis.yml
- app/build.gradle
- scripts/apps-android-wikipedia-publish-travis
Fix Travis to require environment variables only for publishing.
> Travis improvements

- app/src/main/java/org/wikipedia/feed/becauseyouread/BecauseYouReadCardView.java
- app/src/main/java/org/wikipedia/feed/mostread/MostReadFragment.java
- app/src/main/java/org/wikipedia/feed/news/NewsFragment.java
- app/src/main/java/org/wikipedia/page/ReferenceDialog.java
- app/src/main/java/org/wikipedia/page/tabs/TabActivity.java
- app/src/main/java/org/wikipedia/search/SearchFragment.java
- app/src/main/java/org/wikipedia/search/SearchResultsFragment.java
Some views do not respect the RTL language. It can be simple to fix by adding the `setConditionalLayoutDirection`  method.
> Add RTL support for views

- app/src/main/java/org/wikipedia/dataclient/Service.java
Editor task api call change @Field to @Query. @Field is only for POST calls.
> Minor follow-up to API call

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/wikipedia/descriptions/DescriptionEditLicenseView.kt
- app/src/main/java/org/wikipedia/descriptions/DescriptionEditReadArticleBarView.kt
- app/src/main/java/org/wikipedia/descriptions/DescriptionEditReviewView.kt
- app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.java
- app/src/main/java/org/wikipedia/editactionfeed/AddTitleDescriptionsActivity.kt
- app/src/main/java/org/wikipedia/editactionfeed/AddTitleDescriptionsFragment.kt
- app/src/main/java/org/wikipedia/editactionfeed/AddTitleDescriptionsItemFragment.kt
- app/src/main/java/org/wikipedia/util/AnimationUtil.java
- app/src/main/res/layout-land/fragment_add_title_descriptions.xml
- app/src/main/res/layout-land/fragment_add_title_descriptions_item.xml
- app/src/main/res/layout/fragment_add_title_descriptions.xml
- app/src/main/res/layout/fragment_add_title_descriptions_item.xml
- app/src/main/res/layout/view_description_edit.xml
- app/src/main/res/layout/view_description_edit_read_article_bar.xml
- app/src/main/res/layout/view_description_edit_review.xml
- app/src/main/res/values-qq/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
https://phabricator.wikimedia.org/T217169#5053622
https://phabricator.wikimedia.org/T217173#5052973
> Tweak of visual changes to add description

- app/src/main/java/org/wikipedia/main/MainActivity.java
- app/src/main/java/org/wikipedia/main/MainDrawerView.java
This removes the remainder of the PreBeta flags that were being used to hide this feature in Beta and Prod builds.
> Remove PreBeta flag from suggested edits feature.

- app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.java
- app/src/main/java/org/wikipedia/editactionfeed/AddTitleDescriptionsItemFragment.kt
- app/src/main/res/layout-land/fragment_add_title_descriptions_item.xml
- app/src/main/res/layout/fragment_add_title_descriptions_item.xml
- app/src/main/res/layout/view_description_edit.xml
- app/src/main/res/layout/view_description_edit_read_article_bar.xml
- app/src/main/res/layout/view_description_edit_review.xml
https://phabricator.wikimedia.org/T217169#5082447
> Tweak of visual changes to add descriptions

- app/src/main/java/org/wikipedia/notifications/NotificationEditorTasksHandler.java
- app/src/main/res/layout/view_dialog_title_with_image.xml
https://phabricator.wikimedia.org/T217369#5083157
Fixes bugs and update UI based on the comments, and will do the final update in other PR if needed.
> Update notification string and line height of dialog title for SuggestedEdits

- app/src/main/res/layout-land/fragment_random.xml
- app/src/main/res/layout/fragment_random.xml
Got the idea from #144, and also make the buttons in the center-horizontal in landscape mode
> Design tweaks: elevation clipping on Randomizer

- app/src/main/java/org/wikipedia/editactionfeed/MyContributionsFragment.kt
Also make sure to clear any Disposables when the fragment is destroyed. (don't forget this!)
> Show local language names in My Contributions.

- app/build.gradle
- app/src/main/java/org/wikipedia/dataclient/okhttp/OfflineCacheInterceptor.java
For real, now.
(Note that OkHttp now requires API 21+)
> Update OkHttp to 3.14.0.

- app/src/main/java/org/wikipedia/WikipediaApp.java
- app/src/main/java/org/wikipedia/alphaupdater/AlphaUpdateChecker.java
- app/src/main/java/org/wikipedia/analytics/EventLoggingService.java
- app/src/main/java/org/wikipedia/dataclient/ServiceFactory.java
- app/src/main/java/org/wikipedia/dataclient/okhttp/OkHttpConnectionFactory.kt
- app/src/main/java/org/wikipedia/dataclient/okhttp/OkHttpWebViewClient.java
- app/src/main/java/org/wikipedia/savedpages/SavedPageSyncService.java
- app/src/main/java/org/wikipedia/settings/RemoteConfigRefreshTask.java
- app/src/test/java/org/wikipedia/test/MockWebServerTest.java
A follow-up PR of using `@JvmField` and `@JvmStatic` and added `const` to some parameters.
> Follow up: network interceptors to Kotlin 

- app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayCardView.java
- app/src/main/java/org/wikipedia/feed/view/HorizontalScrollingListCardView.java
- app/src/main/res/layout/view_card_on_this_day.xml
- app/src/main/res/layout/view_events_layout.xml
The layout of the OnThisDay card was unnecessarily heavy, with multiple nested usages of `RelativeLayout` and incorrect usages of `match_parent`, which was slowing down the layout/rendering pipeline.
(No visual changes are intended.)
> Optimization: improve xml layout of OnThisDay card.

- app/src/main/java/org/wikipedia/dataclient/RestService.java
- app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayFragment.java
...it was still using the old Retrofit `Call` style.
> Convert OnThisDay to Rx.

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsAddDescriptionsFragment.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsContributionsFragment.kt
> Follow up of importing Android X libraries

- app/src/main/java/org/wikipedia/language/AppLanguageState.java
It is time to remove the logic.
> Remove old app language code logic

- app/src/main/java/org/wikipedia/feed/FeedFragment.java
- app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardView.kt
- app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsFeedClient.kt
Set the description on `PageTitle` correctly and update some variables.
> Follow up of SuggestedEdits feed card

- app/src/main/java/org/wikipedia/WikipediaApp.java
Added the 'locale' property to crash report.
**Phab:** https://phabricator.wikimedia.org/T117380
> Device locale added to crash report description 

- app/src/main/java/org/wikipedia/Constants.java
- app/src/main/java/org/wikipedia/feed/FeedContentType.java
- app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCard.kt
- app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardView.kt
- app/src/main/res/values-qq/strings.xml
- app/src/main/res/values/strings.xml
1. Update string item name
2. Minor code changes
3. Reorganize the orders of `InvokeSource`
> Follow up #2 of SuggestedEdits feed card 

- app/src/main/java/org/wikipedia/feed/FeedContentType.java
- app/src/main/java/org/wikipedia/feed/configure/ConfigureFragment.java
Remove preBeta cards from Customize settings
> Remove preBeta cards from Customize settings

- app/src/main/java/org/wikipedia/page/ToCHandler.java
I'm not sure why we needed that specific condition. It doesn't seem to be necessary.
> Follow-up to ToC tweaks.

- app/src/main/java/org/wikipedia/LongPressHandler.java
- app/src/main/java/org/wikipedia/page/PageContainerLongPressHandler.java
- app/src/main/java/org/wikipedia/page/PageFragment.java
- app/src/main/java/org/wikipedia/page/bottomcontent/BottomContentView.java
- app/src/main/java/org/wikipedia/search/SearchResultsFragment.java
Simplify a couple of things, and also correctly get the Referrer from the PageFragment.
> Follow-up to long-press actions.

- app/src/main/res/layout/fragment_page.xml
- app/src/main/res/values/styles.xml
- Fix snackbars that appear on top of the bottom bar.
- Fix tint color of bottom bar buttons.
> Follow-up and design tweak of bottom button bar.

- app/src/main/java/org/wikipedia/page/shareafact/ShareHandler.java
https://phabricator.wikimedia.org/T221464
> Fix possible race condition when getting highlighted text.

- www/preview.html
...otherwise, we will get the old version of preview HTML when running the `grunt`
> Update preview HTML in /www folder.

- app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardView.kt
- app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsFeedClient.kt
Remove the unnecessary `companion object` and also use the `isTranslation` boolean on the `getArticleWithMissingDescription()` method.
> Follow up to Suggested edits feed tweaks

- app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayPagesViewHolder.java
- app/src/main/java/org/wikipedia/main/MainActivity.java
- app/src/main/java/org/wikipedia/main/MainFragment.java
- app/src/main/java/org/wikipedia/page/PageActivity.java
- app/src/main/java/org/wikipedia/page/PageFragment.java
- app/src/main/java/org/wikipedia/page/tabs/Tab.java
...Forgot to handle the case of zero tabs, which was showing a "0" in the tabs button!.
> Improve behavior with zero tabs, and improve Back behavior.

- app/src/main/java/org/wikipedia/analytics/ToCInteractionFunnel.java
- app/src/main/java/org/wikipedia/page/ToCHandler.java
The PR will make the scroller hide completely and will show only with the ToC list.
https://phabricator.wikimedia.org/T213133
> ToC tweaks: remove peek behavior of the scroller

- app/src/main/java/org/wikipedia/analytics/ToCInteractionFunnel.java
- app/src/main/java/org/wikipedia/page/ToCHandler.java
Remove some unnecessary logic.
> Follow-up to removing ToC peeking.

- app/src/main/java/org/wikipedia/page/bottomcontent/MainPageReadMoreTopicTask.java
- app/src/main/res/drawable/ic_favorite_white_24dp.xml
- app/src/main/res/layout/item_page_list_entry.xml
Use the correct bookmark icon, deleted the `ic_favorite_white_24dp`, and also did a minor code clean up on `MainPageReadMoreTopicTask.java`
> Hygiene: use correct default bookmark icon and clean up ReadMore task

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsAddDescriptionsFragment.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsAddDescriptionsItemFragment.kt
- app/src/main/res/layout-land/fragment_suggested_edits_add_descriptions_item.xml
- app/src/main/res/layout/fragment_suggested_edits_add_descriptions.xml
- app/src/main/res/layout/fragment_suggested_edits_add_descriptions_item.xml
Simplify codes, remove some unused layouts and update UI settings such as `paddings` and `font-family`.
> Follow up to the design recommendation for “Add/translate descriptions“

- scripts/make-release.py
Alright! This updates our build script to do all of the following:
- It will generate a universal `.APK`, like before.
- It will also generate a Bundle, for uploading to the Play Store, which is an `.AAB` file. When creating a new release in the Play Store (for both Beta and Production apps), we shall now use these bundles instead of the APK.
These files are placed in the `/releases` directory, as before.
> Update build script to generate Bundles in addition to APKs.

- app/src/main/java/org/wikipedia/page/ReferenceDialog.java
I... don't even know.
https://phabricator.wikimedia.org/T223530
> Fix crash when clicking reference(s).

- app/src/main/java/org/wikipedia/richtext/RichTextUtil.java
https://rink.hockeyapp.net/manage/apps/226649/app_versions/669/crash_reasons/272926971?type=overview
> Fix possible crash when rendering News text.

- app/src/main/java/org/wikipedia/page/ToCHandler.java
https://rink.hockeyapp.net/manage/apps/226649/app_versions/670/crash_reasons/271933247
> Fix possible crash when animating ToC with destroyed activity.

- app/src/main/java/org/wikipedia/search/SearchResultsFragment.java
The changes made in #230 left open the possibility for a crash when clicking on a search result.
https://rink.hockeyapp.net/manage/apps/226649/app_versions/669/crash_reasons/271908036
> Fix possible crash when clicking search result.

- app/src/main/res/layout/fragment_gallery_item.xml
Not sure why it formatted like this, but let's update the XML layout to match our current layout standard.
> Update the Gallery item XML layout format

- app/src/main/java/org/wikipedia/page/tabs/TabActivity.java
- app/src/main/res/layout/activity_tabs.xml
- app/src/main/res/layout/item_tab_contents.xml
Done with some UI changes partially due to the limitation of the 3rd party library.
https://phabricator.wikimedia.org/T222434
> Design update: Tab screen

- app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsFeedClient.kt
Make the `if` logic more clear and follow the style guide from Android Developer: https://developer.android.com/kotlin/style-guide#expressions
> Change the variable access level and follow the style guide

- app/src/main/java/org/wikipedia/readinglist/ReadingListBehaviorsUtil.kt
1. Removed the way of sending unnecessary callbacks to methods.
2. Use `forEach` for the performance. Reference. [Kotlin: For-loop vs ForEach](https://medium.com/@elye.project/kotlin-for-loop-vs-foreach-7eb594960333)
3. Reformatting the codes to be less mess
4. Reduce creating variables for the `if` logic and use express `if` statement
5. Use string templates for the string values
> Kotlin: improve performance in ReadingListBehaviorsUtil.kt 

- app/src/main/java/org/wikipedia/gallery/GalleryActivity.java
- app/src/main/java/org/wikipedia/wikidata/Entities.java
- app/src/main/res/layout/activity_gallery.xml
This makes an extra API call when looking at images in the Gallery, and shows a structured caption for the current image if it's available in the user's current language.
https://phabricator.wikimedia.org/T224492
> Show structured captions in Gallery, if available!

- app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.java
- app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.java
- app/src/main/res/drawable/ic_spacer_24dp.xml
- app/src/main/res/layout/view_description_edit.xml
https://phabricator.wikimedia.org/T224501
> Allow voice input for description/caption editing.

- app/src/main/res/layout/activity_tabs.xml
Tweak: https://phabricator.wikimedia.org/T222434#5221551
> Tweak: update tabBackgroundColor in TabActivity

- app/src/main/res/layout/view_description_edit.xml
https://phabricator.wikimedia.org/T224501
> Don't auto-capitalize sentences in the Description Edit box.

- app/src/main/AndroidManifest.xml
https://phabricator.wikimedia.org/T224788
> Fix the deep link does not work properly on /zh/ pattern

- app/src/main/java/org/wikipedia/views/ViewUtil.java
Removed unused code in utility class
> Hygiene: removed unused code in ViewUtil

- app/src/main/java/org/wikipedia/history/HistoryFragment.java
- app/src/main/java/org/wikipedia/page/bottomcontent/BottomContentView.java
- app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.java
- app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.java
- app/src/main/java/org/wikipedia/views/PageItemView.java
- app/src/main/res/layout/item_page_list_entry.xml
* Rearrange some of the `item_page_list_entry` view for better logic and consistency.
* Remove a bunch of unnecessary code.
> Follow-up to no placeholder images

- www/package-lock.json
- www/package.json
Bumping to the latest Grunt version fixes the affected vulnerable packages.
> Fix npm vulnerabilities.

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.java
We can merge this PR after all tests from QA and Design are done.
> Remove the testing codes for Suggested edits

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsFragment.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsItemFragment.kt
- The new data class `SuggestedEditsSummary` contains `PageTitle`, so there's no need to add the logic of creating `PageTitle`.
- Use `forEach` for the existing for loops in the Kotlin classes
> Simplified code logic and use forEach loop in Suggested edits

- app/src/main/java/org/wikipedia/language/LangLinksActivity.java
https://phabricator.wikimedia.org/T225385
> Fix placement of Norwegian language link.

- app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.java
- app/src/main/java/org/wikipedia/descriptions/DescriptionEditReviewView.kt
- app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.java
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsFragment.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsItemFragment.kt
- app/src/main/res/drawable/ic_icon_caption_images.xml
- app/src/main/res/values-qq/strings.xml
- app/src/main/res/values/strings.xml
https://phabricator.wikimedia.org/T224051
> Add image caption in Suggested edits

- app/src/main/java/org/wikipedia/dataclient/WikiSite.java
https://phabricator.wikimedia.org/T225381
> Allow external URLs without proper subdomain.

- app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.java
https://phabricator.wikimedia.org/T225472
This PR also adjusts the logic to prevent setting the colors if it is not necessary.
> Fix: use ResourceUtil.getThemedColor() to get correct tint colors

- app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.java
- app/src/main/java/org/wikipedia/gallery/GalleryActivity.java
- app/src/main/java/org/wikipedia/gallery/GalleryItem.java
https://phabricator.wikimedia.org/T223128
https://phabricator.wikimedia.org/T223129
> Hook up Gallery with adding/translating captions.

- app/src/main/res/layout/activity_gallery.xml
Add a click ripple animation to the translate button
> Add a click ripple animation to the translate button

- app/src/main/java/org/wikipedia/suggestededits/provider/MissingDescriptionProvider.kt
This substantially improves the efficiency of serving up suggested edits by caching both suggested Descriptions and Captions (across multiple threads).
> Improve caching layer for suggested edits.

- app/src/main/java/org/wikipedia/descriptions/DescriptionEditReviewView.kt
Feedback `#2` and `#3` in https://phabricator.wikimedia.org/T225635
> Use thumbnail URL for image caption review screen

- app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.java
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsItemFragment.kt
- app/src/main/java/org/wikipedia/views/ImagePreviewDialog.kt
`#13` in https://phabricator.wikimedia.org/T225635
> Remove HTML tag for SuggestedEdits views

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsFragment.kt
- app/src/main/java/org/wikipedia/util/AnimationUtil.java
`#18` in https://phabricator.wikimedia.org/T225635#5278148
> Use default ViewPager animation in Suggested edits cards screen

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.java
`#19` in https://phabricator.wikimedia.org/T225635
> Move the multilingual task in Suggested edits feed to the bottom of the feed

- app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCard.kt
- app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsFeedClient.kt
Update Date string  to correctly indicate date according to age for Suggested edits feed cards.
> Fix: Update Date string for Suggested edits feed cards

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.java
- app/src/main/res/values/strings.xml
https://phabricator.wikimedia.org/T226116
> Update/tweak suggested edit task unlocking logic and text.

- app/src/main/res/layout/view_image_detail_horizontal.xml
https://phabricator.wikimedia.org/T224500
> Tweak: adjust the lineSpacing to align to the left column text

- app/src/main/java/org/wikipedia/dataclient/WikiSite.java
- app/src/main/java/org/wikipedia/language/LanguageUtil.java
- app/src/test/java/org/wikipedia/dataclient/WikiSiteTest.java
URLs for testing
https://zh.wikipedia.org/wiki/核武器
https://zh.wikipedia.org/zh/核武器
> Fix: prevent showing mixed Chinese variants articles when opening /zh/ or /wiki/ URLs

- app/src/main/assets/bundle.js
- app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java
- www/js/sections.js
- www/js/transforms/hideImages.js
This simplifies things and gets rid of unnecessary hard-coded colors in javascript.
> Follow-up to placeholder images.

- app/src/main/java/org/wikipedia/suggestededits/provider/MissingDescriptionProvider.kt
The `retry` was in the wrong place.
> Fix improper retry mechanism in suggested edits provider.

- app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardView.kt
- app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsFeedClient.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsItemFragment.kt
- app/src/main/res/values/strings_no_translate.xml
Bug report from https://phabricator.wikimedia.org/T227037
> Fix: keep the original namespace of the "File:" to avoid a non-exist file page.

- app/src/main/res/layout-land/fragment_suggested_edits_cards_item.xml
`#34` in https://phabricator.wikimedia.org/T225635#5288605
> Tweak: use proper ratio on the card image for the landscape mode

- app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsFeedClient.kt
...to prevent empty description field on the edit screen.
> Fix: add "no description" string for the suggested edits explore feed card

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksActivity.java
`#6` in https://phabricator.wikimedia.org/T225635#5299612
> Fix: make sure the button on the Suggested edit dialogs lead to the correct screens

- app/src/main/java/org/wikipedia/page/PageActivity.java
https://phabricator.wikimedia.org/T224789#5306112
> Tweak: keep "deep link" users in the app when pressing the back button

- app/build.gradle
https://github.com/ReactiveX/RxJava/releases/tag/v2.2.10
https://github.com/ReactiveX/RxAndroid/releases/tag/2.1.1
https://github.com/square/retrofit/releases/tag/parent-2.6.0
> Update Rx and Retrofit versions.

- app/src/main/res/layout/item_reading_list.xml
> Fix: incorrect empty image position for default list in the reading list page

- app/src/main/res/layout/view_image_detail.xml
...so that the user can copy/paste text.
> Make text selectable in image preview dialog.

- app/src/main/java/org/wikipedia/page/PageActivity.java
- app/src/main/java/org/wikipedia/page/PageFragment.java
- app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.java
Just a couple of naming clarifications and logic hardening.
> Follow-up to Call To Action.

- app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.java
- app/src/main/java/org/wikipedia/gallery/GalleryActivity.java
- app/src/main/res/layout/view_description_edit.xml
https://phabricator.wikimedia.org/T228103
> Fix: showing correct summary field label in Suggested edits screen

- app/src/main/java/org/wikipedia/login/LoginActivity.java
- app/src/main/res/layout/activity_login.xml
https://phabricator.wikimedia.org/T228464
> Replace ProgressDialog with ProgressBar: LoginActivity

- app/src/main/java/org/wikipedia/page/PageActivity.java
- app/src/main/java/org/wikipedia/page/PageFragment.java
- app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.java
- app/src/main/res/layout/view_page_header.xml
- app/src/main/res/values-qq/strings.xml
- app/src/main/res/values/strings.xml
Design review comments incorporated
**Phab**: https://phabricator.wikimedia.org/T224728
> Article CTA -View tweaks

- app/src/main/java/org/wikipedia/util/FeedbackUtil.java
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/styles_dark.xml
- app/src/main/res/values/styles_light.xml
Change button color in feedback util message to R.attr.color_group_52
> Change button color in feedback util 

- app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.java
- app/src/main/res/values-qq/strings.xml
- app/src/main/res/values/strings.xml
https://phabricator.wikimedia.org/T226446#5360462
> Show helper text when editing article description

- app/src/main/java/org/wikipedia/util/DeviceUtil.java
`05` in https://phabricator.wikimedia.org/T226401
> Add a method of checking accessibility tools' status

- app/src/main/java/org/wikipedia/bridge/CommunicationBridge.java
- app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
- app/src/main/java/org/wikipedia/page/PageFragment.java
- app/src/main/res/values/strings_no_translate.xml
Updated breaking changes for existing bridge scripts
Changed from PageMods to Page
Changed from setMulti to setUp
removed 'document' parameter
> Breaking changes update

- app/src/main/java/org/wikipedia/feed/FeedContentType.java
Remove pre-beta flag and un-hide the suggested edits cards
> Remove pre-beta flag for suggested edits cards

- app/src/main/java/org/wikipedia/feed/FeedFragment.java
Fixed correct feedback message on caption/description published through feed cards
> Fix: Feedback message after edit from Suggested Edits cards

- app/src/main/java/org/wikipedia/edit/EditHandler.java
- app/src/main/java/org/wikipedia/views/ObservableWebView.java
https://phabricator.wikimedia.org/T219995
TODO: add "edit here" for article description
> Add "edit description" support

- app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
- app/src/main/java/org/wikipedia/page/shareafact/ShareHandler.java
Phab: https://phabricator.wikimedia.org/T219995
> Mobile html: Text selection

- app/src/main/java/org/wikipedia/settings/Prefs.java
- app/src/main/res/values/preference_keys.xml
- app/src/main/res/xml/developer_preferences.xml
https://phabricator.wikimedia.org/T230111
> Fix developer settings to unlock suggested edit features.

- app/src/main/java/org/wikipedia/page/PageFragment.java
- app/src/main/res/values-qq/strings.xml
- app/src/main/res/values/strings.xml
Based on the latest comment from Charlotte:
https://phabricator.wikimedia.org/T226290#5403040
> Show snackbar when tapping on the in-article images while offline.

- app/src/main/res/values/styles.xml
Switch to using the more proper MaterialComponents parent style.
> Follow-up to Button vs TextView components.

- app/src/main/res/layout/view_link_preview_overlay.xml
- app/src/main/res/values/styles.xml
https://phabricator.wikimedia.org/T229707#5409011
> Tweak: update bottom sheet button height and use correct parent style on Transparent buttons

- app/src/main/java/org/wikipedia/page/tabs/TabActivity.java
https://appcenter.ms/orgs/ci-apps-hockeyapp-f5mf/apps/Wikipedia/crashes/errors/2258638947u/overview
> Fix possible crash on TabActivity

- app/src/main/java/org/wikipedia/page/PageFragment.java
Reverts wikimedia/apps-android-wikipedia#473
https://phabricator.wikimedia.org/T230635
> Revert "Use setTextZoom() to change the WebView font size"

- app/src/main/java/org/wikipedia/gallery/GalleryActivity.java
- app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.java
https://appcenter.ms/orgs/ci-apps-hockeyapp-f5mf/apps/Wikipedia/crashes/errors/4256860024u/reports
> Prevent possible crash on videoView in GalleryItemFragment

- app/src/main/java/org/wikipedia/gallery/GalleryActivity.java
https://phabricator.wikimedia.org/T230603
> Fix proper display/sequencing of image caption in Gallery.

- app/src/main/java/com/facebook/samples/zoomable/DefaultZoomableController.java
The current zooming of images in the Gallery isn't actually very deep. You can only zoom the image by 2x. This patch increases the maximum zoom to 4x.
> Make gallery images zoomable twice as deeply.

- app/src/main/java/org/wikipedia/views/LanguageScrollView.java
Due to the build failure:
https://travis-ci.com/wikimedia/apps-android-wikipedia/builds/124144361
> Hygiene: fix import error, remove unused resource and update naming

- app/src/main/java/org/wikipedia/page/tabs/TabActivity.java
https://appcenter.ms/orgs/ci-apps-hockeyapp-f5mf/apps/Wikipedia/crashes/errors/4185295725u/overview
> Fix: possible crash when showing undo snackbar in TabActivity

- app/src/main/res/layout/activity_gallery.xml
- app/src/main/res/layout/view_page_header.xml
https://phabricator.wikimedia.org/T230605
> Adapt same button style for gallery and lead image view

- app/src/main/java/org/wikipedia/gallery/GalleryActivity.java
- app/src/main/java/org/wikipedia/page/PageFragment.java
- app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.java
https://phabricator.wikimedia.org/T229928
> Restore ability to view single SVG images in Gallery.

- app/src/androidTest/java/org/wikipedia/espresso/history/HistoryTabTest.java
- app/src/main/java/org/wikipedia/activity/BaseActivity.java
- app/src/main/java/org/wikipedia/history/UpdateHistoryTask.java
- app/src/main/java/org/wikipedia/page/PageActivity.java
- app/src/main/java/org/wikipedia/page/PageFragment.java
- app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.java
- app/src/main/java/org/wikipedia/settings/SettingsFragment.java
- app/src/main/java/org/wikipedia/theme/ThemeChooserDialog.java
- app/src/main/java/org/wikipedia/theme/ThemeFittingRoomFragment.java
> Minor clean-up

- app/src/main/java/org/wikipedia/gallery/GalleryActivity.java
https://phabricator.wikimedia.org/T231064
> Make sure the Gallery CTA button shows the consistent language

- app/src/main/res/values/strings.xml
> Very minor string tweak

- app/build.gradle
- app/src/main/java/org/wikipedia/edit/EditSectionActivity.java
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsContributionsFragment.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
https://developer.android.com/jetpack/androidx/releases/core#1.1.0
> Update Androidx core/fragment/preference to 1.1.0.

- app/src/main/java/org/wikipedia/WikipediaApp.java
- app/src/main/res/values-sw600dp/dimens.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/styles.xml
Changes end date for survey
Changes snackbar action button inline style
> Minor design changes

- app/src/main/java/org/wikipedia/bridge/CommunicationBridge.java
- app/src/main/java/org/wikipedia/edit/preview/EditPreviewFragment.java
- app/src/main/java/org/wikipedia/page/PageFragment.java
- app/src/main/java/org/wikipedia/views/ObservableWebView.java
https://rink.hockeyapp.net/manage/apps/226649/app_versions/692/crash_reasons/288953025
> Fix internal crash in WebView on Lollipop.

- app/src/main/java/org/wikipedia/page/PageFragment.java
https://phabricator.wikimedia.org/T232275
> Properly fix creating blank new tab when there are no tabs remaining.

- app/src/main/java/org/wikipedia/WikipediaApp.java
- app/src/main/java/org/wikipedia/createaccount/CreateAccountActivity.java
- app/src/main/java/org/wikipedia/dataclient/Service.java
- app/src/main/java/org/wikipedia/dataclient/mwapi/ListUserResponse.java
- app/src/main/java/org/wikipedia/dataclient/mwapi/UserInfo.java
- app/src/main/java/org/wikipedia/login/LoginClient.java
- app/src/test/java/org/wikipedia/login/UserExtendedInfoClientTest.java
This also cleans up a few things in our logic to retrieve the current user's group assignments, as well as the logic to detect whether a certain username already exists.
> Add API groundwork for detecting whether user is blocked.

- app/src/main/java/org/wikipedia/page/PageActivity.java
> Use NavTab type explicitly in PageActivity

- app/src/main/java/org/wikipedia/notifications/NotificationPollBroadcastReceiver.java
A very minor change on the `retrieveNotifications()`.
> Clear the correct map variable in NotificationPollBroadcastReceiver.java 

- app/src/main/res/xml/developer_preferences.xml
- app/src/test/java/org/wikipedia/dataclient/okhttp/util/HttpUrlUtilTest.java
The product infrastructure team is switching the labs instance host to mobileapps from appservice.
> Change labs URL

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsSurvey.java
- app/src/main/java/org/wikipedia/util/DateUtil.java
**Phab**: https://phabricator.wikimedia.org/T234949
> Extends survey indefinitely

- app/src/main/java/org/wikipedia/main/MainActivity.java
- app/src/main/java/org/wikipedia/views/TabCountsView.java
- app/src/main/res/layout/activity_page.xml
The current one shows "show tabs", which is incorrect.
This PR also simplified the `activity_page.xml` XML format.
> Show correct long press toast message on tab count view in TabActivity

- app/src/main/java/org/wikipedia/main/MainFragment.java
Very minor PR of removing unused method in MainFragment
> Remove unused method in MainFragment

- app/src/main/java/org/wikipedia/navtab/NavTabLayout.kt
Workaround Until the library stabilizes.
> Showing long text without truncating on BottomNavigationView

- app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayFragment.java
- app/src/main/java/org/wikipedia/views/CustomDatePicker.java
- app/src/main/res/layout/date_picker_dialog.xml
- app/src/main/res/layout/fragment_on_this_day.xml
- app/src/main/res/layout/view_custom_calendar_day.xml
- app/src/main/res/values-qq/strings.xml
- app/src/main/res/values/strings.xml
https://phabricator.wikimedia.org/T236418
> Fix date picker view width issue and optimizing the code

- app/src/main/res/layout/activity_login.xml
This one may have actually been my fault!
> Whoops: fix 2FA visibility.

- app/src/main/java/org/wikipedia/feed/announcement/Announcement.java
- app/src/main/java/org/wikipedia/feed/announcement/AnnouncementClient.java
https://phabricator.wikimedia.org/T235537
Will start working on the fundraising bottom sheet in `PageActivity` after finalizing the design in https://phabricator.wikimedia.org/T235538
> Support the placement parameter of the fundraising endpoint.

- app/build.gradle
https://github.com/robolectric/robolectric/releases/tag/robolectric-4.3.1
> Update robolectric version to 4.3.1

- .travis.yml
- app/build.gradle
- app/src/main/java/org/wikipedia/model/EnumCodeMap.kt
> Bump SDK version to 29.

- app/src/main/java/org/wikipedia/feed/FeedCoordinatorBase.java
https://phabricator.wikimedia.org/T235652#5630326
> Show date above the fundraising card on Explore feed

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsActivity.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
- app/src/main/java/org/wikipedia/util/ResourceUtil.java
https://phabricator.wikimedia.org/T238239
> Fix: properly set tint on menu icons.

- app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.java
Prevent to show the `Failed to fetch gallery collection.` in Logcat.
> Prevent to show error log when having no images in LinkPreviewDialog

- app/src/main/java/org/wikipedia/page/bottomcontent/BottomContentView.java
https://en.wikipedia.org/api/rest_v1/page/related/IPhone
> Show displayTitle on "Read more" section in PageActivity

- app/src/main/java/org/wikipedia/main/MainFragment.java
https://phabricator.wikimedia.org/T238840
> Increase onboarding snackbar time to 7 seconds.

- app/src/main/java/org/wikipedia/page/AnnouncementDialog.kt
- app/src/main/res/layout/view_card_announcement.xml
* Make the content scrollable (for small displays and landscape)
* Improve appearance of buttons when elevated.
> Follow-up to Announcement dialog.

- app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
This PR is just making the footer can display properly. 
The actions such as references or read more will be handled on other PRs.
> Setting footer properly on mobile-html 

- app/src/main/java/org/wikipedia/gallery/GalleryActivity.java
- app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.java
It would reduce the IDE yellow warning labels on both classes.
> Hygiene: replace old codes and add null checks to Gallery classes

- app/src/main/res/layout/view_page_header.xml
This will make the "Add image caption" message (as well as the gradient background) fade in nicely, instead of just appearing suddenly.
> Animate layout changes in Lead Image container.

- app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
Use Kotlin `${variable}` string template on most of the variables instead of using `String.format()` to combine the string.
> Reformat the JS string in setUp() and use Kotlin string template

- app/src/main/java/org/wikipedia/bridge/CommunicationBridge.java
- app/src/main/java/org/wikipedia/edit/EditHandler.java
- app/src/main/java/org/wikipedia/page/LinkHandler.java
- app/src/main/java/org/wikipedia/page/PageFragment.java
Gson is more efficient and less cumbersome than `JSONObject`.
> Use Gson for deserializing bridge messages.

- app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
Removes unused methods:
setHandler() and setScrollTop(..)
> Hygiene: Remove set handler

- app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
- app/src/main/java/org/wikipedia/page/PageFragment.java
Based on https://gerrit.wikimedia.org/r/c/mediawiki/services/mobileapps/+/556191 
Works on Dog article
> Add Pre-setting parameters for Lead image and user groups

- app/build.gradle
rxjava :-  2.2.10 => 2.2.14
butterknife :- 10.1.0 => 10.2.0
> Update miscellaneous library versions.

- app/src/main/java/org/wikipedia/views/WikiTextKeyboardView.java
https://phabricator.wikimedia.org/T240769
> Improve link parsing in wikitext editing previews.

- app/src/main/java/org/wikipedia/bridge/CommunicationBridge.java
- app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java
**Steps to reproduce**
1. Search "Obama" and you will see the redirected result
2. The page will break after it reaching the `resetHTML()`.
> Sending proper title object to the resetHTML()

- app/src/main/java/org/wikipedia/util/ShareUtil.java
https://phabricator.wikimedia.org/T241792
> Fix showing of proper chooser intent when sharing link to article.

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsFragment.kt
Not sure why it still exists there, and it should be removed.
> Remove RandomizerFunnel from SuggestedEdits

- app/src/main/res/layout/view_onboarding.xml
https://phabricator.wikimedia.org/T242210
> Design tweak: reading list onboarding button style.

- app/src/main/java/org/wikipedia/Constants.java
- app/src/main/java/org/wikipedia/page/PageActivity.java
- app/src/main/java/org/wikipedia/page/PageFragment.java
- app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java
- app/src/main/java/org/wikipedia/page/tabs/TabActivity.java
- app/src/main/res/layout/fragment_page.xml
- app/src/main/res/values-qq/strings.xml
- app/src/main/res/values/strings.xml
The new tab will now be empty. (and I mean _really_ empty.)
> No longer load Main Page in empty tabs.

- app/src/main/java/org/wikipedia/descriptions/DescriptionEditReviewView.kt
- app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.java
- app/src/main/java/org/wikipedia/feed/becauseyouread/BecauseYouReadItemCard.java
- app/src/main/java/org/wikipedia/feed/featured/FeaturedArticleCard.java
- app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayPagesViewHolder.java
- app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardView.kt
- app/src/main/java/org/wikipedia/feed/view/ListCardItemView.java
- app/src/main/java/org/wikipedia/page/shareafact/ShareHandler.java
- app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.java
- app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.java
- app/src/main/java/org/wikipedia/search/SearchResultsFragment.java
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsItemFragment.kt
https://phabricator.wikimedia.org/T241545
> No longer capitalize descriptions and captions throughout.

- app/src/main/java/org/wikipedia/page/references/ReferenceListDialog.kt
- app/src/main/java/org/wikipedia/util/StringUtil.java
- app/src/test/java/org/wikipedia/util/StringUtilTest.java
https://phabricator.wikimedia.org/T230047
> Design touch-up for references list.

- app/src/main/java/org/wikipedia/page/references/ReferenceDialog.java
- app/src/main/res/drawable/ic_oojs_reference.xml
- app/src/main/res/layout/fragment_references_pager.xml
- app/src/main/res/layout/view_reference_pager_item.xml
https://phabricator.wikimedia.org/T242323
> Update design of single reference dialog.

- app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
- app/src/main/java/org/wikipedia/dataclient/page/PageLead.java
- app/src/main/java/org/wikipedia/dataclient/page/PageLeadProperties.java
- app/src/main/java/org/wikipedia/page/PageProperties.java
We already have the Languages button in the bottom bar!
> No longer show Number of Languages in page footer.

- app/src/main/java/org/wikipedia/dataclient/WikiSite.java
- app/src/main/java/org/wikipedia/feed/FeedFragment.java
- app/src/main/java/org/wikipedia/language/LangLinksActivity.java
- app/src/main/java/org/wikipedia/suggestededits/provider/MissingDescriptionProvider.kt
https://phabricator.wikimedia.org/T243612
> Correctly handle legacy language codes in Suggested Edits.

- app/src/main/java/org/wikipedia/history/HistoryFragment.java
- app/src/main/java/org/wikipedia/language/LangLinksActivity.java
- app/src/main/java/org/wikipedia/language/LanguagesListActivity.java
- app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.java
- app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.java
https://phabricator.wikimedia.org/T242142
> Don't dismiss ActionModes unnecessarily on touch events.

- app/src/main/res/layout/view_horizontal_scroll_list_item_card.xml
https://phabricator.wikimedia.org/T244754
> Fix text height of News items without image.

- app/src/main/java/org/wikipedia/page/PageFragment.java
https://phabricator.wikimedia.org/T230047
> Fix clicking of reference backlinks.

- app/src/main/java/org/wikipedia/util/StringUtil.java
- app/src/test/java/org/wikipedia/util/StringUtilTest.java
The md5 function isn't actually used anywhere in our code yet, so now is a good time to make it actually work correctly!
> Fix md5 string function.

- app/src/main/res/layout/dialog_reference_list.xml
- app/src/main/res/layout/item_reference.xml
https://phabricator.wikimedia.org/T230047
> Design tweak: increase tap area of reference backlink button.

- app/build.gradle
https://github.com/material-components/material-components-android/releases/tag/1.1.0
^^ some interesting things in there.
Also update the `fragment` library to 1.2.0.
> Update material library to 1.1.0.

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsActivity.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsItemFragment.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt
- app/src/main/res/layout-land/fragment_suggested_edits_cards.xml
- app/src/main/res/layout-land/fragment_suggested_edits_cards_item.xml
- app/src/main/res/layout/fragment_suggested_edits_cards.xml
- app/src/main/res/layout/fragment_suggested_edits_cards_item.xml
- app/src/main/res/layout/item_language_spinner.xml
- app/src/main/res/values-qq/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
https://phabricator.wikimedia.org/T240197
> Design tweaks of existing suggested edit screens.

- app/src/main/java/org/wikipedia/Constants.java
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsOnboardingActivity.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
https://phabricator.wikimedia.org/T241843
> Improve flow of showing onboarding for image tags.

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsActivity.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsFragment.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt
- app/src/main/java/org/wikipedia/util/FeedbackUtil.java
- app/src/main/res/layout-land/fragment_suggested_edits_cards.xml
- app/src/main/res/values-qq/strings.xml
- app/src/main/res/values/strings.xml
> Further design tweaks for image tagging.

- app/src/main/java/org/wikipedia/navtab/NavTabOverlayLayout.kt
- app/src/main/res/layout/fragment_main.xml
- app/src/main/res/layout/view_nav_tab_overlay.xml
- app/src/main/res/layout/view_nav_tab_overlay_fill.xml
https://phabricator.wikimedia.org/T241844
> Simplify/improve pulsating overlay on navigation tabs.

- app/src/main/res/values/styles.xml
The latest Material library has updated the appearance of `TextInputLayout`, which now require some additional styling to account for their new features and flexibility. Overall an improvement, I think.
> Update styling of TextInput fields.

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt
> Vibrate upon successful publishing of image tags.

- app/build.gradle
https://developer.android.com/jetpack/androidx/releases/core#1.2.0
Also a minor update to the fragment library.
> Update androidx core library to 1.2.0.

- app/src/main/java/org/wikipedia/views/ReadingListsOverflowView.java
https://appcenter.ms/orgs/ci-apps-hockeyapp-f5mf/apps/Wikipedia/crashes/errors/3358520905u/overview
> Prevent minor crash when displaying reading list overflow menu.

- app/src/main/java/org/wikipedia/edit/richtext/SyntaxHighlighter.java
- app/src/main/java/org/wikipedia/views/PlainPasteEditText.java
https://appcenter.ms/orgs/ci-apps-hockeyapp-f5mf/apps/Wikipedia/crashes/errors/2492373835u/overview
> Prevent potential crash when pasting rich text containing Uri data.

- app/src/main/java/org/wikipedia/analytics/EditFunnel.java
https://phabricator.wikimedia.org/T240469
> Fix passing of correctly-formatted namespace to EditFunnel.

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt
- app/src/main/res/drawable/button_shape_border_light.xml
- app/src/main/res/drawable/ic_chip_add_24px.xml
- app/src/main/res/drawable/ic_chip_check_24px.xml
- app/src/main/res/layout/fragment_suggested_edits_image_tags_item.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/styles_dark.xml
- app/src/main/res/values/styles_light.xml
- app/src/main/res/values/styles_sepia.xml
> Additional design tweaks for image tags.

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt
> Tiny design tweaks in image tags.

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsFragment.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt
- app/src/main/res/drawable/circular_progress.xml
- app/src/main/res/layout/fragment_suggested_edits_image_tags_item.xml
> Final design tweaks for suggested image tags.

- app/src/main/java/org/wikipedia/settings/Prefs.java
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsItemFragment.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt
- app/src/main/res/values-qq/strings.xml
- app/src/main/res/values/preference_keys.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/developer_preferences.xml
https://phabricator.wikimedia.org/T245972
> Design tweak: introduce tooltip when initially tapping on zoomable image.

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt
https://phabricator.wikimedia.org/T245972
> Design tweak: Change snackbar to tooltip.

- app/src/main/res/layout-sw600dp/view_suggested_edits_task_item.xml
- app/src/main/res/layout/view_suggested_edits_task_item.xml
https://phabricator.wikimedia.org/T246129
> Fix: use correct attributes for src and tint.

- app/src/main/java/org/wikipedia/analytics/SessionData.java
- app/src/main/java/org/wikipedia/analytics/SessionFunnel.java
- app/src/main/java/org/wikipedia/page/PageFragment.java
https://phabricator.wikimedia.org/T246333
> Update session funnel to work with mobile-html latency.

- app/src/androidTest/java/org/wikipedia/espresso/main/overflow/CustomizeFeedTest.java
- app/src/main/java/com/facebook/samples/gestures/MultiPointerGestureDetector.java
- app/src/main/java/com/facebook/samples/gestures/TransformGestureDetector.java
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsFragment.kt
- app/src/test/java/org/wikipedia/descriptions/DescriptionEditClientTest.java
- app/src/test/java/org/wikipedia/language/TranslationTestsOld.java
- app/src/test/java/org/wikipedia/savedpages/PageImageUrlParserTest.java
Just a run of Analyse-> Code CleanUp
> Hygiene: Code clean-up

- app/src/main/java/org/wikipedia/util/ShareUtil.java
- app/src/main/java/org/wikipedia/util/UriUtil.java
- app/src/main/java/org/wikipedia/views/ImagePreviewDialog.kt
https://phabricator.wikimedia.org/T246514
This should fix the "share" issues that users have been reporting, at a slight cost: the "Wikipedia" app will be available as one of the choices for sharing, even though we want to share a URL with an external app.
> Fix issue(s) with sharing URLs to external apps.

- app/src/main/res/values/credits.xml
A couple of unpardonable omissions.
> Update list of credits.

- app/src/main/java/org/wikipedia/dataclient/Service.java
- app/src/main/java/org/wikipedia/dataclient/mwapi/MwResponse.java
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsUserStats.kt
https://phabricator.wikimedia.org/T247989
> Improve checking of blocked status in suggested edits.

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt
- app/src/main/res/layout/fragment_suggested_edits_image_tags_item.xml
https://phabricator.wikimedia.org/T247022
> Further design tweaks of image tags.

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
and also remove the pre-beta feature flag.
> Update order of suggested tasks.

- app/build.gradle
https://developer.android.com/jetpack/androidx/releases/fragment#1.2.3
> Update androidx.fragment to 1.2.3.

- app/src/main/java/org/wikipedia/settings/AboutActivity.java
- app/src/main/res/layout/activity_about.xml
- app/src/main/res/values-qq/strings.xml
- app/src/main/res/values/credits.xml
- app/src/main/res/values/strings.xml
https://phabricator.wikimedia.org/T247542
> Replace team credits with a link to the team page

- app/src/main/java/org/wikipedia/readinglist/AddToReadingListDialog.java
- app/src/main/res/values-qq/strings.xml
- app/src/main/res/values/strings.xml
**Phab: ** https://phabricator.wikimedia.org/T224339#6001343
> Adding different copy for saving articles from tabs

- app/src/main/java/org/wikipedia/page/PageFragment.java
> Fix playback of article pronunciation.

- app/src/main/java/org/wikipedia/descriptions/DescriptionEditLicenseView.kt
- app/src/main/java/org/wikipedia/feed/announcement/AnnouncementCardView.java
This will also enable links in the body of Announcement cards in the feed.
> Correctly use LinkMovementMethod in TextViews with links.

- app/src/main/java/org/wikipedia/createaccount/CreateAccountActivity.java
- app/src/main/java/org/wikipedia/login/LoginActivity.java
https://appcenter.ms/orgs/ci-apps-hockeyapp-f5mf/apps/Wikipedia-Beta/crashes/errors/74454899u/overview
> Fix potential crash in Login/CreateAccount logic.

- app/src/main/java/org/wikipedia/activity/BaseActivity.java
This crash has eluded me so far:
https://appcenter.ms/orgs/ci-apps-hockeyapp-f5mf/apps/Wikipedia-Beta/crashes/errors/2836099990u/overview
This PR will shimmy some additional information that should tell us at least which activity the crash is happening in.
> Add probe to research mysterious crash.

- app/src/main/res/layout/view_suggested_edit_card.xml
**Phab:** https://phabricator.wikimedia.org/T244866
> Minor Design review change for SE feed card

- app/src/main/java/org/wikipedia/page/PageFragment.java
This is a safer sequencing of the calls we make to the PCS layer, since it actually gives us events called `setup` and `final_setup` which tell us when it is safe to make certain calls. (We weren't making use of these events yet.)
> More properly sequence loading of PCS calls.

- app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
- app/src/main/res/layout/fragment_references_pager.xml
- app/src/main/res/layout/group_find_references_in_page.xml
**Phab:** https://phabricator.wikimedia.org/T247248
> Design tweaks : T247248

- app/src/main/java/org/wikipedia/settings/AboutActivity.java
https://phabricator.wikimedia.org/T248880
> Update feedback email address.

- app/src/main/java/org/wikipedia/analytics/SuggestedEditsFunnel.java
- app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryPage.java
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt
This is for the benefit of analytics, so that machine-suggested image tag edits could be distinguished from manually-selected tags.
> Provide better edit comments on image tag edits.

- app/src/main/java/org/wikipedia/bridge/CommunicationBridge.java
- app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
- app/src/main/java/org/wikipedia/onboarding/OnboardingPageView.java
- app/src/main/java/org/wikipedia/page/PageFragment.java
- app/src/main/java/org/wikipedia/page/PageToolbarHideHandler.java
- app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.java
- app/src/main/java/org/wikipedia/page/leadimages/PageHeaderView.java
- app/src/main/java/org/wikipedia/random/RandomItemFragment.java
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsFeedCardImageTagActivity.kt
- app/src/main/java/org/wikipedia/util/DimenUtil.java
- app/src/main/res/layout/fragment_page.xml
https://phabricator.wikimedia.org/T249214
> Fix inconsistent lead image margins upon screen rotation.

- app/src/main/java/org/wikipedia/page/Section.java
- app/src/test/java/org/wikipedia/page/SectionTest.java
Looks like it is safe to be deleted.
> Hygiene: remove the methods that only for tests

- app/src/main/java/org/wikipedia/edit/preview/EditPreviewFragment.java
- app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.java
- app/src/main/java/org/wikipedia/notifications/NotificationItemActionsDialog.java
- app/src/main/java/org/wikipedia/page/LinkHandler.java
- app/src/main/java/org/wikipedia/page/PageFragment.java
https://phabricator.wikimedia.org/T249288
> Consolidate handling of File: links from pages.

- app/src/main/java/org/wikipedia/page/LinkHandler.java
- app/src/main/java/org/wikipedia/util/UriUtil.java
We don't use ZIM file anymore.
> Remove unused ZIM offline file check logic

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsOnboardingActivity.kt
- app/src/main/res/drawable/ic_illustration_reading_list_offline_white.xml
- app/src/main/res/layout-land/view_onboarding_page.xml
- app/src/main/res/layout/activity_suggested_edits_tags_onboarding.xml
- app/src/main/res/layout/view_onboarding_page.xml
The views were looking too lopsided towards the bottom. This centers everything in the middle of the screen.
> Follow up: further refine onboarding layouts.

- app/build.gradle
https://developer.android.com/jetpack/androidx/releases/fragment#1.2.4
> Update androidx.fragment to 1.2.4

- app/build.gradle
https://github.com/microsoft/appcenter-sdk-android/releases/tag/3.1.0
> Update AppCenter sdk to 3.1.0.

- app/src/main/java/org/wikipedia/settings/Prefs.java
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
Only for pre-production, for now.
> Reinstate feature flag for Image Tags.

- app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryPage.java
- app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsFeedClient.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsItemFragment.kt
This also updates a few API calls to use the Commons domain explicitly, since that's what they should do anyway.
> Add API response parameter to check if an image is from Commons.

- app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.java
> Follow up: use the proper constructor

- app/src/main/res/values/colors.xml
https://phabricator.wikimedia.org/T251150
> Design tweak: update base10 color.

- app/build.gradle
https://developer.android.com/jetpack/androidx/releases/preference#version_111_3
> Update androidx.preference to 1.1.1

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsFragment.kt
- app/src/main/java/org/wikipedia/views/PositionAwareFragmentStateAdapter.kt
https://phabricator.wikimedia.org/T242449
> Manually remove fragments after the old fragment get destroyed in FragmentStateAdapter

- app/src/main/java/org/wikipedia/bridge/CommunicationBridge.java
- app/src/main/java/org/wikipedia/page/PageFragment.java
- app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java
Fixing issues by reducing code.
> Fix sequencing of metadata loading with PCS setup events.

- app/src/main/java/org/wikipedia/feed/FeedFragment.java
- app/src/main/res/layout/fragment_feed.xml
- app/src/main/res/values/styles_black.xml
- Remove unnecessary/redundant overrides in Black style.
- Remove view in Feed that is no longer necessary,
> Follow-up to consolidating colors.

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsUserStats.kt
This PR benefits #1191 which can share the `getPageViews()` method.
> Move getPageViews() to SuggestedEditsUserStats

- app/src/main/java/org/wikipedia/notifications/NotificationPollBroadcastReceiver.java
- app/src/main/java/org/wikipedia/notifications/NotificationPresenter.java
https://phabricator.wikimedia.org/T249629#6112039
> Add an option to not draw icon cirlce in NotificationPresenter

- app/src/main/java/org/wikipedia/search/SearchFragment.java
**Phab:** https://phabricator.wikimedia.org/T229213
> Remove "enter to go to first item" on search

- app/src/main/java/org/wikipedia/gallery/MediaDownloadReceiver.java
https://appcenter.ms/orgs/ci-apps-hockeyapp-f5mf/apps/Wikipedia-Beta/crashes/errors/105195133u/overview
> Fix potential crash when downloading non-image media to gallery.

- app/src/main/java/org/wikipedia/activity/BaseActivity.java
- app/src/main/java/org/wikipedia/descriptions/DescriptionEditActivity.java
- app/src/main/java/org/wikipedia/main/MainActivity.java
- app/src/main/java/org/wikipedia/page/PageToolbarHideHandler.java
- app/src/main/java/org/wikipedia/random/RandomActivity.java
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsActivity.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsFeedCardImageTagActivity.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsOnboardingActivity.kt
- app/src/main/res/layout/view_search_bar.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/styles_black.xml
- app/src/main/res/values/styles_dark.xml
- app/src/main/res/values/styles_light.xml
- app/src/main/res/values/styles_sepia.xml
https://phabricator.wikimedia.org/T252867
Since the colors are app-wide consistency, we'll just need to call the method on `BaseActivity`.
> Change status bar color to paper_color

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt
https://phabricator.wikimedia.org/T253317
> Minor visual improvements for SE v4

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagDialog.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt
The display of tags in the "published" state was still not quite perfect, especially when the display is rotated.
> Additional minor visual improvement for image tags.

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt
**Phab:**https://phabricator.wikimedia.org/T253475
> Remove unselected tags

- app/src/main/res/drawable/ic_icon_move_to_another_reading_list.xml
https://phabricator.wikimedia.org/T237152#6162227
> Update the icon resource of moving an article to another list

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsFragment.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsFeedCardImageTagActivity.kt
- app/src/main/res/layout/activity_suggested_edits_feed_card_image_tags.xml
**Phab:** https://phabricator.wikimedia.org/T253523
> Update publish button

- app/src/main/java/org/wikipedia/descriptions/DescriptionEditActivity.java
- app/src/main/java/org/wikipedia/page/ExtendedBottomSheetDialogFragment.java
- app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.java
- app/src/main/java/org/wikipedia/views/ImagePreviewDialog.kt
- app/src/main/res/values/dimens.xml
https://phabricator.wikimedia.org/T250726#6167516
> Use standard bottomsheet width globally

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/wikipedia/commons/FilePageView.kt
- app/src/main/res/layout/view_image_detail.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
https://phabricator.wikimedia.org/T250192#6168930
> Design tweak: Commons file page

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
This is required by the Android Studio 4.0
https://developer.android.com/studio/releases#4-0-0
> Update android gradle plugin to 4.0.0 and gradle version to 6.1.1

- app/src/main/java/org/wikipedia/feed/FeedFragment.java
- app/src/main/java/org/wikipedia/feed/featured/FeaturedArticleCardView.java
- app/src/main/java/org/wikipedia/feed/mostread/MostReadFragment.java
- app/src/main/java/org/wikipedia/feed/news/NewsFragment.java
- app/src/main/java/org/wikipedia/feed/view/ListCardItemView.java
- app/src/main/java/org/wikipedia/main/MainFragment.java
- app/src/main/java/org/wikipedia/page/ExclusiveBottomSheetPresenter.java
- app/src/main/java/org/wikipedia/page/PageActivity.java
- app/src/main/java/org/wikipedia/page/PageFragment.java
- app/src/main/java/org/wikipedia/random/RandomFragment.java
- app/src/main/java/org/wikipedia/readinglist/ReadingListBookmarkMenu.java
- app/src/main/res/menu/menu_feed_card_item.xml
- app/src/main/res/menu/menu_reading_list_page_toggle.xml
- app/src/main/res/values-qq/strings.xml
- app/src/main/res/values/strings.xml
https://phabricator.wikimedia.org/T237152#6177262
> Add an option to move article in ReadingListBookmarkMenu 

- app/src/main/res/values/styles.xml
https://phabricator.wikimedia.org/T246897
> Set correct background color to input fields

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagDialog.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt
https://phabricator.wikimedia.org/T255041
> Preserve search text when dismissing Image Tag search dialog.

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsContributionsFragment.kt
**Phab:**https://phabricator.wikimedia.org/T250190
> Update the image tag contribution title to the correct tag

- app/src/main/java/org/wikipedia/page/tabs/TabActivity.java
[Bug: T255853](https://phabricator.wikimedia.org/T255853)
> Don't ask if all tabs should be closed if there are none

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsContributionDetailsFragment.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsContributionsItemView.kt
- app/src/main/res/values-qq/strings.xml
- app/src/main/res/values/strings.xml
- Updated %numberOfCharacters quantity to be absolute
-Updated "You have added/removed %numberOfCharacters" strings to plurals
> Minor updates to plurals

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
- app/src/main/java/org/wikipedia/views/ImageTitleDescriptionView.kt
- app/src/main/java/org/wikipedia/views/WikiCardView.kt
- app/src/main/res/layout/view_suggested_edits_task_item.xml
https://phabricator.wikimedia.org/T250202
> Design tweaks for card enhancements.

- app/src/main/res/layout/fragment_suggested_edits_rewards_item.xml
https://phabricator.wikimedia.org/T241847#6251584
> Update reward interstitial text color to primary_text_color

- app/src/main/java/org/wikipedia/suggestededits/Contribution.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsContributionDetailsFragment.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsContributionsFragment.kt
- app/src/main/res/layout/fragment_contribution_diff_detail.xml
Removes revision number in the details screen when it is not the current version
> Design updates for Contribution Details

- app/src/main/java/org/wikipedia/main/MainFragment.java
- app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.java
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
This will also benefit the code review comment in #1297
> Refresh fragment contents after logged in/out

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
- app/src/main/java/org/wikipedia/views/SuggestedEditsDisabledStatesView.kt
- app/src/main/res/layout/fragment_suggested_edits_tasks.xml
- app/src/main/res/layout/view_suggested_edits_disabled_states.xml
https://phabricator.wikimedia.org/T250202
> A few more design tweaks for card layouts.

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsContributionDetailsFragment.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsContributionsFragment.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsContributionsItemView.kt
- app/src/main/res/layout/item_suggested_edits_contributions.xml
-Changed pageviews label to accent color
-Image loading done differently to reduce flicker
-Removed 'File:' from the image titles. used 'replaceFirst' just in case of edge case of having files named that way
-Could not reproduce or see in code how text could be cut-off as mentioned in design review. Open to suggestions.
**Phab:*https://phabricator.wikimedia.org/T250190
> Design tweaks [Final?] for contributions

- app/src/main/java/org/wikipedia/navtab/MenuNavTabDialog.java
- app/src/main/res/layout/view_main_drawer.xml
**Phab:**https://phabricator.wikimedia.org/T253238
> Minor design adjustment to login/logout button

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsContributionDetailsFragment.kt
- app/src/main/res/layout/fragment_contribution_diff_detail.xml
- app/src/main/res/layout/view_suggested_edits_contribution_diff_detail.xml
1. Rename `contributionDetailText` to `contributionDiffDetailText` to avoid confusion.
1. Should show `contribution.description`  in `contributionDiffDetailText.text`.
2. Set up `marginStart` in `ImageView`
3. Remove unnecessary `layout_weight` in layout
> Follow up: diff detail screen optimization and bug fix

- app/src/main/java/org/wikipedia/analytics/UserContributionFunnel.java
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsContributionDetailsFragment.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsContributionsFragment.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
https://meta.wikimedia.org/wiki/Schema:MobileWikiAppUserContribution
> Add analytics for user contributions screen.

- app/src/main/java/org/wikipedia/navtab/MenuNavTabDialog.java
- app/src/main/res/drawable/ic_baseline_person_24.xml
**Phab:** https://phabricator.wikimedia.org/T253238
> Navigation icon tint change

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsContributionDetailsFragment.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsContributionsItemView.kt
- app/src/main/res/drawable/ic_baseline_person_24.xml
**Phab:** https://phabricator.wikimedia.org/T250190#6259420
> Design update to pageviews label

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTaskView.kt
- app/src/main/res/layout-sw600dp/view_suggested_edits_task_item.xml
- app/src/main/res/layout/fragment_suggested_edits_tasks.xml
- app/src/main/res/layout/view_suggested_edits_disabled_states.xml
- app/src/main/res/layout/view_suggested_edits_task_item.xml
- app/src/main/res/values/styles.xml
https://github.com/wikimedia/apps-android-wikipedia/pull/1297#pullrequestreview-438355114
> Replace custom icon+text button with MaterialButton

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsContributionDetailsFragment.kt
- app/src/main/java/org/wikipedia/util/GradientUtil.java
- app/src/main/res/layout/fragment_contribution_diff_detail.xml
This makes the gradient color match the designs, without needing a new color group.
> Correctly use gradient with transparency in Contribution detail view.

- app/src/main/java/org/wikipedia/main/MainFragment.java
- app/src/main/java/org/wikipedia/navtab/MenuNavTabDialog.java
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsFragment.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
- app/src/main/java/org/wikipedia/views/PositionAwareFragmentStateAdapter.kt
This fixes a few possible leaks by explicitly nulling some critical variables.
https://issuetracker.google.com/issues/151212195
https://issuetracker.google.com/issues/154751401
> Fix potential memory leak(s) in MainFragment.

- app/src/main/java/org/wikipedia/feed/FeedContentType.java
- app/src/main/java/org/wikipedia/feed/configure/ConfigureFragment.java
https://phabricator.wikimedia.org/T256773
> Don't show SE cards in feed customisation when logged out

- app/src/main/res/values/styles_dark.xml
- app/src/main/res/values/styles_light.xml
https://phabricator.wikimedia.org/T257083
> Fix overflow menu style on Lollipop.

- app/src/main/java/org/wikipedia/util/ShareUtil.java
https://phabricator.wikimedia.org/T257084
> Strip html when sharing page title.

- app/src/main/res/values-es/strings.xml
https://phabricator.wikimedia.org/T257519
> Fix: remove redundant line break symbol from specific string items in es/strings.xml

- app/src/main/java/org/wikipedia/views/FaceAndColorDetectImageView.java
That is, _don't_ do face detection for animated images, because it causes face detection to run for _every_ frame of the animation, all the time.
> Optimize face detection for animated images.

- app/src/main/java/org/wikipedia/dataclient/okhttp/CommonHeaderRequestInterceptor.kt
- app/src/main/java/org/wikipedia/dataclient/okhttp/OkHttpWebViewClient.java
https://phabricator.wikimedia.org/T257859
> Send X-Analytics pageview header only when viewing in WebView.

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
**Bug**: https://youtu.be/VBeKXi10DOI
> Fix: Update UI on main thread

- app/src/main/java/org/wikipedia/random/RandomItemFragment.java
If the app language is an RTL language, then we should make the Randomizer supports it.
> Add RTL support in Randomizer

- app/src/main/res/layout-land/view_onboarding_page.xml
- app/src/main/res/layout/fragment_history.xml
- app/src/main/res/layout/fragment_reading_lists.xml
- app/src/main/res/layout/view_onboarding_page.xml
- app/src/main/res/values/styles.xml
**Phab:** https://phabricator.wikimedia.org/T257841
-Removes faux bolding
> Design tweaks: Harmonize onboarding and empty screens

- app/src/main/java/org/wikipedia/analytics/ABTestSuggestedEditsOnboardingIconFunnel.java
- app/src/main/java/org/wikipedia/analytics/FeedConfigureFunnel.java
- app/src/main/java/org/wikipedia/main/MainFragment.java
- app/src/main/java/org/wikipedia/settings/Prefs.java
- app/src/main/res/values/preference_keys.xml
https://phabricator.wikimedia.org/T258200
> Update analytics for simplified onboarding.

- app/build.gradle
Change-Id: I302956395018cfa3ce7d2a5f99a4b0331b3a9b07
> Bump versionCode

- app/src/main/res/values/styles.xml
https://phabricator.wikimedia.org/T258702
> Enlarge touch target size to 48dp in reading lists chips

- app/build.gradle
https://developer.android.com/jetpack/androidx/releases/core#1.3.1
> Update androidx.core:core to 1.3.1

- app/src/main/java/org/wikipedia/commons/ImageTagsProvider.kt
- app/src/main/java/org/wikipedia/dataclient/wikidata/Claims.java
Certain Wikibase claims have different `value` structures, which was breaking our Json parsing when it encountered unexpected claims.
> Expand and correct class structure of Wikibase claims.

- app/src/main/java/org/wikipedia/page/PageActivity.java
https://phabricator.wikimedia.org/T259312
> Reject external URLs from the donate.wp domain.

- app/src/main/res/layout/view_language_scroll.xml
https://phabricator.wikimedia.org/T259395
> Fix: incorrect search bar background color in dark mode

- app/src/main/java/org/wikipedia/analytics/CreateAccountFunnel.java
- app/src/main/java/org/wikipedia/analytics/LoginFunnel.java
https://phabricator.wikimedia.org/T253982#6358116
https://meta.wikimedia.org/wiki/Schema:MobileWikiAppCreateAccount
https://meta.wikimedia.org/wiki/Schema:MobileWikiAppLogin
> Update schema revision for account creation and account login

- app/src/main/res/values/styles_sepia.xml
https://phabricator.wikimedia.org/T259396
> Fix Sepia background color.

- app/src/main/java/org/wikipedia/history/HistoryFragment.java
- app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.java
- app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.java
- app/src/main/res/drawable/ic_baseline_filter_list_24.xml
- app/src/main/res/layout/group_search.xml
- app/src/main/res/menu/menu_history.xml
- app/src/main/res/menu/menu_reading_list.xml
- app/src/main/res/menu/menu_reading_lists.xml
- app/src/main/res/values-qq/strings.xml
- app/src/main/res/values/strings.xml
**Phab:* https://phabricator.wikimedia.org/T259133
> Change search icon in “My lists” and “History” to filter_list

- app/src/main/res/layout/view_main_drawer.xml
https://phabricator.wikimedia.org/T259650
> Fix multiline login button text appearance.

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
https://github.com/wikimedia/apps-android-wikipedia/pull/1508#pullrequestreview-461977791
> Follow up: update setUserStatsTooltips() to a proper method name

- app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsFeedClient.kt
- app/src/main/java/org/wikipedia/settings/DeveloperSettingsPreferenceLoader.java
- app/src/main/java/org/wikipedia/suggestededits/provider/EditingSuggestionsProvider.kt
If the app language is Traditional Chinese, the infinite loading of SE providers will stop users from scrolling down for more content.
> Setup max retry limit for EditSuggestionsProvider to prevent infinite loading on Explore feed

- app/src/main/res/layout/fragment_onboarding_pager.xml
- app/src/main/res/layout/fragment_references_pager.xml
https://github.com/wikimedia/apps-android-wikipedia/pull/1514#pullrequestreview-465082401
> Change the Tablayout background to transparent

- app/src/main/java/org/wikipedia/analytics/ABTestDescriptionEditChecksFunnel.java
- app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.java
https://phabricator.wikimedia.org/T256816#6375552
> Show submission warnings only for descriptions, not captions.

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
- app/src/main/res/layout/fragment_suggested_edits_tasks.xml
**Phab:** https://phabricator.wikimedia.org/T256772
> Make the whole area of profile stats card clickable.

- app/src/main/java/org/wikipedia/page/PageActivity.java
- app/src/main/java/org/wikipedia/views/PageActionOverflowView.java
- app/src/main/res/layout/view_page_action_overflow.xml
This PR does the following change in the ticket.
> Overflow menu
https://phabricator.wikimedia.org/T259795
> Change overflow menu items in PageActivity

- app/src/main/java/org/wikipedia/analytics/ABTestExploreVsHomeFunnel.java
- app/src/main/java/org/wikipedia/views/PageActionOverflowView.java
- app/src/main/res/drawable/ic_baseline_home_24.xml
- app/src/main/res/values-qq/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/developer_preferences.xml
https://phabricator.wikimedia.org/T260332
> Set up A/B test for showing Home vs. Explore menu item.

- app/src/main/res/values-qq/strings.xml
as requested by:
https://phabricator.wikimedia.org/T260496
https://phabricator.wikimedia.org/T260499
> Tweak qq documentation for a couple of strings.

- app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.java
https://phabricator.wikimedia.org/T256816
> Tweak behavior and delay of description warnings.

- app/src/main/java/org/wikipedia/WikipediaApp.java
- app/src/main/java/org/wikipedia/settings/SettingsPreferenceLoader.java
https://phabricator.wikimedia.org/T260756
> Correctly disable all of AppCenter when crash reporting is disabled.

- app/src/main/java/org/wikipedia/history/HistoryFragment.java
- app/src/main/res/values-qq/strings.xml
- app/src/main/res/values/strings.xml
**Phab:** https://phabricator.wikimedia.org/T259133
> Design tweak: Change filter history hint text

- app/build.gradle
https://github.com/Kotlin/kotlinx.coroutines/releases
> Update kotlinx-coroutine plugins version to 1.3.9

- build.gradle
https://plugins.gradle.org/plugin/org.jetbrains.kotlin.android
> Update kotlin-gradle-plugin to 1.4.0

- app/build.gradle
https://androidstudio.googleblog.com/2020/08/constraintlayout-200.html
> Update androidx.constraintlayout library to 2.0.1

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsSnackbars.kt
https://phabricator.wikimedia.org/T257941#6423284
> Fix: crash when the activity is destroyed on sequential snackbars

- app/build.gradle
https://developer.android.com/jetpack/androidx/releases/test#1.3.0
> Update androidx.test libraries to 1.3.0

- app/src/main/java/org/wikipedia/LongPressHandler.java
- app/src/main/java/org/wikipedia/page/PageContainerLongPressHandler.java
- app/src/main/java/org/wikipedia/search/SearchResultsFragment.java
- app/src/main/res/layout/fragment_search_results.xml
This PR also removes the logic for showing `PopupMenu` in `ListView` item.
> Replace ListView with RecyclerView in SearchResultsFragment

- app/src/main/AndroidManifest.xml
**Phab:** https://phabricator.wikimedia.org/T261322
> Launch PageActivity in default mode to maintain back-stack as expected

- app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
- app/src/main/java/org/wikipedia/page/PageFragment.java
> 02) Make sure titles on main pages (new tab) are not cut off by the app bar (e.g. by applying more margin)
https://phabricator.wikimedia.org/T260871
> Add extra CSS to the header in mobile-web for Main page

- app/src/main/java/org/wikipedia/search/SearchFragment.java
**Phab:** https://phabricator.wikimedia.org/T261322
> Load page in current stack when searched from PageActivity

- app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayFragment.java
https://phabricator.wikimedia.org/T262049
> Correctly show/hide progress bar in OnThisDay screen.

- app/src/main/java/org/wikipedia/staticdata/FileAliasData.java
- app/src/main/java/org/wikipedia/staticdata/MainPageNameData.java
- app/src/main/java/org/wikipedia/staticdata/SpecialAliasData.java
- app/src/main/res/values/languages_list.xml
https://phabricator.wikimedia.org/T262190
> Update languages and static data.

- app/src/main/java/org/wikipedia/feed/FeedContentType.java
- app/src/main/java/org/wikipedia/feed/FeedCoordinatorBase.java
- app/src/main/java/org/wikipedia/feed/featured/FeaturedArticleCard.java
- app/src/main/java/org/wikipedia/feed/featured/FeaturedArticleCardView.java
- app/src/main/java/org/wikipedia/feed/mainpage/MainPageCard.java
- app/src/main/java/org/wikipedia/feed/mainpage/MainPageCardView.java
- app/src/main/java/org/wikipedia/feed/mainpage/MainPageClient.java
- app/src/main/java/org/wikipedia/feed/model/CardType.java
- app/src/main/java/org/wikipedia/main/MainFragment.java
- app/src/main/java/org/wikipedia/page/PageActivity.java
- app/src/main/res/layout/view_card_featured_article.xml
- app/src/main/res/layout/view_card_footer.xml
- app/src/main/res/values-qq/strings.xml
- app/src/main/res/values/strings.xml
Reverts wikimedia/apps-android-wikipedia#1591
> Revert "Redesign featured article card & update footer layout"

- app/build.gradle
https://github.com/material-components/material-components-android/releases/tag/1.2.1
https://developer.android.com/jetpack/androidx/releases/drawerlayout#1.1.1
> Update material library to 1.2.1 and drawerlayout library to 1.1.1

- app/src/main/res/layout/view_card_header.xml
The `view_card_header_subtitle` was removed.
> Fix: set up constraint attritube to the card_header_title correctly

- app/src/main/java/org/wikipedia/feed/image/FeaturedImageCardView.java
> Follow-up to Featured Image card.

- app/src/main/java/org/wikipedia/feed/featured/FeaturedArticleCard.java
https://phabricator.wikimedia.org/T261668#6465543
> Tweak: show plain extract text for the featured article and random article cards

- app/src/main/java/org/wikipedia/feed/view/CardLargeHeaderView.java
- app/src/main/java/org/wikipedia/views/FaceAndColorDetectImageView.java
- app/src/main/java/org/wikipedia/views/ViewUtil.java
- Consolidate a few static items.
- Perform a bit more magic with color gradient extraction to make the colors more interesting.
> Follow-up to Because You Read card.

- app/src/main/java/org/wikipedia/feed/featured/FeaturedArticleCard.java
- app/src/main/java/org/wikipedia/feed/image/FeaturedImageCard.java
- app/src/main/java/org/wikipedia/feed/model/WikiSiteCard.java
- app/src/main/java/org/wikipedia/feed/mostread/MostReadListCard.java
- app/src/main/java/org/wikipedia/feed/news/NewsListCard.java
- app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayCard.java
- app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCard.kt
This PR also use the `wikiSite()` method instead of creating an extra `wiki` variable since we already have extended `WikiSiteCard`
> Fix: crash when clicking on the "More like this" button in the trending card

- app/src/main/res/layout/fragment_suggested_edits_cards_item.xml
- app/src/main/res/layout/fragment_suggested_edits_image_tags_item.xml
https://phabricator.wikimedia.org/T263571
> Fix crash when zooming image in Image Tags interface.

- app/src/main/java/org/wikipedia/search/SearchResultsFragment.java
**Phab: https://phabricator.wikimedia.org/T259717**
> Design Tweak: Kick-off search on app sources only after 2 characters

- app/src/main/java/org/wikipedia/search/SearchResultsFragment.java
**Phab:** https://phabricator.wikimedia.org/T259717
> Re-order personalized search results

- app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayFragment.java
- app/src/main/res/anim/pulse.xml
- app/src/main/res/layout/view_on_this_day_event.xml
**Phab: https://phabricator.wikimedia.org/T261673#6489844**
> Pulse animation

- app/src/main/res/values/styles.xml
Robin asked for this change as it had come up in a design review long time back. Lmk if we need a ticket for this..
> Tint the page action layout icons to accent color

- app/src/main/java/org/wikipedia/page/PageActivity.java
> Unused code

- app/src/main/java/org/wikipedia/feed/view/ListCardView.java
https://phabricator.wikimedia.org/T261671#6503316
> Tweak: remove unwanted dividers in ListCardView

- app/src/main/java/org/wikipedia/feed/dayheader/DayHeaderMarginItemDecoration.java
- app/src/main/java/org/wikipedia/feed/view/CardHeaderView.java
- app/src/main/java/org/wikipedia/feed/view/FeedView.java
- app/src/main/res/layout/view_card_day_header.xml
- app/src/main/res/layout/view_card_featured_article.xml
- app/src/main/res/layout/view_card_featured_image.xml
- app/src/main/res/layout/view_card_header.xml
- app/src/main/res/layout/view_card_news.xml
- app/src/main/res/layout/view_card_on_this_day.xml
- app/src/main/res/values-land/dimens.xml
- app/src/main/res/values/dimens.xml
https://phabricator.wikimedia.org/T263007
This PR also removes unnecessary the resource of feed card header height.
> Tweak: adjust feed card and feed header spacing

- app/src/main/res/layout/activity_page.xml
- app/src/main/res/layout/fragment_page.xml
- app/src/main/res/values/dimens.xml
per Robin : https://youtu.be/Gvz41sgHyY8
> Adjust the labels on the bottom of pageFragment

- app/src/main/java/org/wikipedia/feed/view/GradientCircleNumberView.kt
- app/src/main/java/org/wikipedia/views/GraphView.kt
- app/src/main/res/layout/view_gradient_circle_number.xml
https://phabricator.wikimedia.org/T261669#6506939
> Tweak: design changes in the Top read feed card

- app/src/main/java/org/wikipedia/feed/news/NewsCardView.java
**Phab:** https://phabricator.wikimedia.org/T261672
> News card back button behavior

- app/src/main/res/values-bn/strings.xml
- app/src/main/res/values-fa/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-iw/strings.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-tr/strings.xml
> Localisation updates from https://translatewiki.net.

- app/src/main/java/org/wikipedia/page/PageFragment.java
https://appcenter.ms/orgs/ci-apps-hockeyapp-f5mf/apps/Wikipedia/crashes/errors/724032326u/overview
> Fix possible crash when transitioning from WebView to Gallery.

- app/src/main/res/layout/view_list_card_item.xml
This is a minor design tweak from Robin's feedback during our discussion in Slack.
> Design tweak: adjust list item text line height and margin

- app/src/main/java/org/wikipedia/login/LoginActivity.java
https://phabricator.wikimedia.org/T266026
> Fix: unable to reach login screen

- app/src/main/res/layout/item_on_this_day_pages.xml
- app/src/main/res/layout/view_on_this_day_footer.xml
**Phab:** https://phabricator.wikimedia.org/T261673
> Design tweaks: On this day

- app/src/main/java/org/wikipedia/richtext/URLSpanBoldNoUnderline.java
Do the same thing as `Typeface.create(Typeface.DEFAULT, Typeface.BOLD)`
> Simplify set bold text in setTypeFace()

- app/src/main/java/org/wikipedia/theme/ThemeChooserDialog.java
- app/src/main/res/layout/dialog_theme_chooser.xml
- app/src/main/res/values/styles.xml
https://phabricator.wikimedia.org/T264445#6579226
> Tweak: theme dialog design changes

- app/build.gradle
> Update constraint layout version

- app/src/main/java/org/wikipedia/WikipediaApp.java
- app/src/main/java/org/wikipedia/activity/BaseActivity.java
- app/src/main/java/org/wikipedia/settings/Prefs.java
- app/src/main/res/values/preference_keys.xml
https://phabricator.wikimedia.org/T266034
> Add more info for tracking unknown crashes

- app/src/main/res/layout/fragment_suggested_edits_card_item.xml
**Phab:** https://phabricator.wikimedia.org/T261676
> Minor: Color group update

- app/src/main/AndroidManifest.xml
https://phabricator.wikimedia.org/T267238
> Fix lint error during F-Droid build.

- app/src/main/java/org/wikipedia/history/HistoryFragment.java
- app/src/main/res/layout/view_history_header_with_search.xml
- app/src/main/res/layout/view_search_bar.xml
> Search ui fix - Redesign

- app/src/main/java/org/wikipedia/feed/featured/FeaturedArticleCardView.java
- app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardItemFragment.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTaskView.kt
- app/src/main/java/org/wikipedia/views/WikiCardView.kt
- app/src/main/res/drawable/ripple_background.xml
- app/src/main/res/drawable/ripple_background_borderless.xml
- app/src/main/res/layout-sw600dp/view_suggested_edits_task_item.xml
- app/src/main/res/layout/fragment_suggested_edits_card_item.xml
- app/src/main/res/layout/item_on_this_day_pages.xml
- app/src/main/res/layout/view_card_featured_article.xml
- app/src/main/res/layout/view_card_featured_image.xml
- app/src/main/res/layout/view_horizontal_scroll_list_item_card.xml
- app/src/main/res/layout/view_list_card.xml
- app/src/main/res/layout/view_suggested_edits_task_item.xml
- app/src/main/res/values/styles.xml
https://phabricator.wikimedia.org/T267012
This PR also optimizes the clickable area in `FeaturedArticleCardView`, which makes the ripple effect more senses.
> Tweak: optimize ripple effect in black theme

- app/src/main/java/org/wikipedia/feed/FeedContentType.java
**Phab:** https://phabricator.wikimedia.org/T267122
> Feed reDesign: Rearrange cards

- app/src/extra/java/org/wikipedia/push/WikipediaFirebaseMessagingService.kt
https://phabricator.wikimedia.org/T267367
> Fix: don't call Push Unsubscribe API with empty token.

- app/src/main/java/org/wikipedia/feed/view/ListCardItemView.java
- app/src/main/res/values-qq/strings.xml
- app/src/main/res/values/strings.xml
We should handle pageviews that over one million with a suffix `M`.
> Use proper suffix for pageviews in the top read list items

- app/src/main/java/org/wikipedia/page/ExtendedBottomSheetDialogFragment.java
- app/src/main/java/org/wikipedia/page/PageFragment.java
- app/src/main/java/org/wikipedia/theme/ThemeChooserDialog.java
- app/src/main/java/org/wikipedia/theme/ThemeFittingRoomActivity.java
https://phabricator.wikimedia.org/T267243
> Smoothly scroll page up a bit when changing themes.

- app/src/main/res/layout/view_card_announcement.xml
> Customize margin adjustment

- app/src/main/res/layout/view_horizontal_scroll_list_item_card.xml
> Minor adjustment to news margin

- app/src/main/java/org/wikipedia/readinglist/AddToReadingListDialog.java
https://phabricator.wikimedia.org/T267422
This PR also handles the IDE warnings.
> Fix: should not enable long-press menu in the reading list bottomsheet.

- app/build.gradle
https://androidstudio.googleblog.com/2020/10/constraintlayout-204.html
> Update androidx.constraintlayout library to 2.0.4

- app/build.gradle
https://firebase.google.com/support/release-notes/android#messaging_v21-0-0
> Update firebase-messaging library version to 21.0.0

- app/build.gradle
https://developer.android.com/kotlin/ktx
This would be helpful when we creating/updating Kotlin classes.
> Enable Kotlin extension in androidx libraries

- app/src/main/java/org/wikipedia/views/FaceAndColorDetectImageView.java
https://phabricator.wikimedia.org/T267244
> Align image to top if face detection fails

- app/src/main/java/org/wikipedia/history/HistoryFragment.java
- app/src/main/java/org/wikipedia/views/WikiCardView.kt
- app/src/main/res/layout/view_search_bar.xml
- app/src/main/res/values/attrs.xml
The previous PR #1795 breaks the bottom margin of the search bar in History
https://phabricator.wikimedia.org/T266233#6626804
> Tweak: search bar design changes

- app/src/main/java/org/wikipedia/random/RandomFragment.java
- app/src/main/java/org/wikipedia/readinglist/ReadingListBehaviorsUtil.kt
In Randomizer, if we click on the bookmark icon, the page will be saved in the reading list successfully, but the bookmark is not filled.
> Fix: update bookmark icon status correctly in Randomizer

- app/src/main/java/org/wikipedia/feed/FeedCoordinatorBase.java
- app/src/main/java/org/wikipedia/feed/announcement/AnnouncementCardView.java
- app/src/main/res/layout/view_card_announcement.xml
https://phabricator.wikimedia.org/T266289#6632111
> Tweak: AnnouncementCardView design changes for dialog

- app/src/main/java/org/wikipedia/login/LoginActivity.java
https://appcenter.ms/orgs/ci-apps-hockeyapp-f5mf/apps/Wikipedia-Beta/crashes/errors/646390600u/overview
> Fix possible crash in LoginActivity.

- app/src/main/java/org/wikipedia/csrf/CsrfTokenClient.java
- app/src/main/java/org/wikipedia/login/LoginClient.java
I believe this will fix the issue that some users have reported where they get "logged out for no reason".
> Fix mystery of being logged out automatically.

- app/src/main/java/org/wikipedia/readinglist/ReadingListItemView.java
https://appcenter.ms/orgs/ci-apps-hockeyapp-f5mf/apps/Wikipedia-Beta/crashes/errors/428265582u/overview
> Fix: prevent possible crash when clicking/long-pressing on reading list items

- app/src/main/res/layout/view_horizontal_scroll_list_item_card.xml
https://phabricator.wikimedia.org/T268334
> Fix: prevent in the news card item text being cut off.

- app/src/main/java/org/wikipedia/feed/news/NewsFragment.java
Sort of a follow-up PR of #1811
> Follow-up: apply correct transntion animation in NewsFragment

- app/src/main/java/org/wikipedia/views/TabCountsView.kt
https://phabricator.wikimedia.org/T268172
> Fix: use PX on TabCountsView text size

- app/src/main/java/org/wikipedia/feed/news/NewsCardView.java
- app/src/main/java/org/wikipedia/feed/news/RecyclerViewIndicatorDotDecor.java
For RTL news cards, the indicator dots were in the wrong direction.
> Correctly show News indicator dots for RTL.

- app/src/main/java/org/wikipedia/feed/mostread/MostReadFragment.java
>  Follow-up #2: apply correct transition animation on MostReadFragment

- app/src/main/res/layout/view_main_drawer.xml
**Phab:**https://phabricator.wikimedia.org/T268286
> More menu username style change

- app/src/main/res/layout/view_card_news.xml
https://phabricator.wikimedia.org/T268334
> Fix variable height of News cards.

- app/src/main/res/layout/view_card_featured_image.xml
https://phabricator.wikimedia.org/T268956
> Remove maxLines setting from the description view in POTD

- app/src/main/java/org/wikipedia/page/PageActivity.java
- app/src/main/java/org/wikipedia/views/TabCountsView.kt
- app/src/main/res/drawable/page_tab_counts_shape_border_light.xml
- app/src/main/res/drawable/tab_counts_shape_border.xml
- app/src/main/res/layout/view_tabs_count.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/styles_dark.xml
- app/src/main/res/values/styles_light.xml
https://phabricator.wikimedia.org/T268172#6641006
> Tweak: TabCountsView design changes and simplify code

- app/src/main/java/org/wikipedia/feed/mostread/MostReadFragment.java
- app/src/main/java/org/wikipedia/feed/news/NewsFragment.java
- app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayPagesViewHolder.java
- app/src/main/java/org/wikipedia/main/MainFragment.java
- app/src/main/java/org/wikipedia/random/RandomFragment.java
https://phabricator.wikimedia.org/T269149
> Always open a new tab for the item in the Explore feed

- app/src/main/java/org/wikipedia/feed/featured/FeaturedArticleCardView.java
- app/src/main/java/org/wikipedia/views/ImageZoomHelper.java
https://phabricator.wikimedia.org/T269240
> Don't show long-press menu when zooming image.

- app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.java
https://phabricator.wikimedia.org/T269005
> Don't add #SuggestedEditAdd comment when editing outside of Suggested Edits.

- app/src/main/java/org/wikipedia/feed/view/ListCardItemView.java
https://phabricator.wikimedia.org/T269243
> Fix: issues with trending sparkline in top read

- app/src/main/java/org/wikipedia/WikipediaApp.java
- app/src/main/java/org/wikipedia/analytics/eventplatform/EventPlatformClient.java
- app/src/main/java/org/wikipedia/connectivity/NetworkConnectivityReceiver.java
- app/src/main/java/org/wikipedia/settings/DeveloperSettingsPreferenceLoader.java
- app/src/test/java/org/wikipedia/analytics/eventplatform/EventPlatformClientTest.java
- app/src/test/java/org/wikipedia/connectivity/NetworkConnectivityReceiverTest.java
per CR on https://github.com/wikimedia/apps-android-wikipedia/pull/1774#discussion_r536122104
> EventPlatformClient class structure changes

- app/src/main/java/org/wikipedia/analytics/eventplatform/DestinationEventService.java
- app/src/main/java/org/wikipedia/analytics/eventplatform/EventPlatformClient.java
- app/src/main/java/org/wikipedia/analytics/eventplatform/EventPlatformClientIntegration.java
- app/src/main/java/org/wikipedia/analytics/eventplatform/EventService.java
- app/src/main/java/org/wikipedia/dataclient/ServiceFactory.java
- app/src/test/java/org/wikipedia/analytics/eventplatform/EventPlatformClientIntegrationTest.java
To keep things consistent with current practices
> Create analytics service through ServiceFactory.

- app/src/main/res/layout/view_suggested_edits_task_item.xml
This is a very powerful feature of ConstraintLayout that we can use in many other places that have this issue.
https://phabricator.wikimedia.org/T269783
> Fix suggested edits button overflow by using ConstraintLayout Flow.

- app/src/main/res/layout/activity_create_account.xml
- app/src/main/res/layout/activity_login.xml
https://phabricator.wikimedia.org/T269189
> Add autofill hints to form fields.

- app/src/main/java/org/wikipedia/dataclient/watch/Watch.kt
- app/src/main/java/org/wikipedia/page/PageFragment.java
The Kotlin `data class` makes things much more concise, and reduce the need for getter methods.
> Follow-up to watchlist add/remove.

- app/src/main/res/values/attrs.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/values/styles_dark.xml
- app/src/main/res/values/styles_light.xml
https://phabricator.wikimedia.org/T270906
> Update page bottom toolbar icon and text color

- app/build.gradle
https://firebase.google.com/support/release-notes/android#messaging_v21-0-1
> Update firebase-messaging version to 21.0.1

- app/build.gradle
- app/src/main/java/org/wikipedia/main/MainFragment.java
- app/src/main/java/org/wikipedia/page/PageActivity.java
- app/src/main/java/org/wikipedia/settings/Prefs.java
- app/src/main/java/org/wikipedia/util/FeedbackUtil.java
- app/src/main/res/drawable/ic_baseline_star_outline_24.xml
- app/src/main/res/layout/view_watchlist_main_tooltip.xml
- app/src/main/res/layout/view_watchlist_page_tooltip.xml
- app/src/main/res/values-qq/strings.xml
- app/src/main/res/values/preference_keys.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/developer_preferences.xml
https://phabricator.wikimedia.org/T269448
This PR updated the `Balloon` library version to `1.2.7` to solve the issue when pointing to the overflow menu icon in `PageActivity`.
> Build onboarding tooltips for Watchlist

- app/src/main/java/org/wikipedia/history/HistoryFragment.java
- app/src/main/java/org/wikipedia/main/MainFragment.java
https://phabricator.wikimedia.org/T271160
> Avoid race condition when clearing History.

- app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.java
https://phabricator.wikimedia.org/T271524
> Fix explicit display of images in gallery when images are disabled.

- app/src/main/java/org/wikipedia/main/MainFragment.java
- app/src/main/java/org/wikipedia/page/PageActivity.java
https://phabricator.wikimedia.org/T269448#6731997
> Tweak: Watchlist tooltips design tweak

- app/src/main/java/org/wikipedia/dataclient/RestService.java
- app/src/main/java/org/wikipedia/dataclient/Service.java
unused Cache-Control header removed
> Remove unnecessary header on POST requests

- app/src/main/java/org/wikipedia/main/MainActivity.java
- app/src/main/java/org/wikipedia/main/MainFragment.java
- app/src/main/java/org/wikipedia/page/PageActivity.java
- app/src/main/java/org/wikipedia/page/tabs/TabActivity.java
- app/src/main/java/org/wikipedia/views/TabCountsView.kt
In the PageActivity, the `TabCountsView` shows an animation when opening a new tab in the background, and maybe we need this in the MainActivity, too.
> Show animation on TabCountsView when opening a tab in backgrond on Explore feed

- app/src/main/java/org/wikipedia/settings/DeveloperSettingsPreferenceLoader.java
- app/src/main/res/values/dev_settings_strings.xml
Don't know when in the world these got introduced, but they are not necessary.
> Remove unnecessary dev strings.

- app/src/main/java/org/wikipedia/watchlist/WatchlistItemView.kt
- app/src/main/res/layout/item_watchlist.xml
https://phabricator.wikimedia.org/T269445
> Final design tweaks for Watchlist main screen.

- app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
- app/src/main/java/org/wikipedia/util/FeedbackUtil.java
- app/src/main/res/values-ca/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-fy/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-iw/strings.xml
- app/src/main/res/values-ko/strings.xml
- app/src/main/res/values-lb/strings.xml
- app/src/main/res/values-mk/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-zh-rTW/strings.xml
- app/src/main/res/values-zh/strings.xml
- app/src/main/res/values/strings_no_translate.xml
* Remove unnecessary/incorrect resources.
* Optimize the conversion between UTF-8 and byte lengths.
> Another follow-up to Diff view.

- app/src/main/java/org/wikipedia/dataclient/page/PageSummary.java
- app/src/main/java/org/wikipedia/page/PageFragment.java
- app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java
- app/src/main/java/org/wikipedia/page/PageTitle.java
- app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.java
https://phabricator.wikimedia.org/T269981
> Correctly handle URL fragments in redirects.

- app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.java
https://phabricator.wikimedia.org/T272189
> State the editing language when editing image caption

- app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
- app/src/main/res/drawable/ic_baseline_person_themed.xml
- app/src/main/res/drawable/ic_heart_24.xml
- app/src/main/res/layout/fragment_article_edit_details.xml
- app/src/main/res/menu/menu_edit_details.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/styles_dark.xml
- app/src/main/res/values/styles_light.xml
**Phab:** https://phabricator.wikimedia.org/T269447
Pending : 02, 06, 07 a), and 09 for discussion
> Design tweaks: Watchlist diff view 

- app/src/main/java/org/wikipedia/edit/EditHandler.java
https://appcenter.ms/orgs/ci-apps-hockeyapp-f5mf/apps/Wikipedia-Beta/crashes/errors/3485211621/overview
> Fix: possible NullPointerException in EditHandler

- app/src/main/java/org/wikipedia/watchlist/WatchlistItemView.kt
- app/src/main/res/drawable/ic_baseline_lock_24.xml
- app/src/main/res/layout/item_watchlist.xml
- app/src/main/res/values-qq/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/strings_no_translate.xml
**Phab:** https://phabricator.wikimedia.org/T269447#6783313
> Fix for different log types

- app/src/main/java/org/wikipedia/Constants.java
- app/src/main/java/org/wikipedia/analytics/TalkFunnel.kt
- app/src/main/java/org/wikipedia/analytics/TimedFunnel.java
- app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
- app/src/main/java/org/wikipedia/main/MainFragment.java
- app/src/main/java/org/wikipedia/notifications/NotificationPresenter.java
- app/src/main/java/org/wikipedia/page/PageActivity.java
- app/src/main/java/org/wikipedia/page/PageFragment.java
- app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt
- app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt
- app/src/main/java/org/wikipedia/watchlist/WatchlistFragment.kt
* Enrich the Talk activities with InvokeSources.
* Hook the editing into the `EditFunnel`.
* Wire it up to the new `MobileWikiAppTalk` schema.
> Whoops: wire up analytics for Talk pages.

- app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
**Phab:** https://phabricator.wikimedia.org/T269447#6784202
> Dynamically update character count

- app/src/main/java/org/wikipedia/watchlist/WatchlistItemView.kt
**Phab:** https://phabricator.wikimedia.org/T269447#6793233
> Clear icon when there is a diff count

- app/src/main/java/org/wikipedia/watchlist/WatchlistItemView.kt
**Phab:** https://phabricator.wikimedia.org/T269447#6793233
> Design tweak: Dim the diff view if not clickable

- app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryPage.java
- app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
- app/src/main/java/org/wikipedia/watchlist/WatchlistItemView.kt
**Phab:** https://phabricator.wikimedia.org/T269447
> Do not show profile menu item for anonymous user

- app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
**Phab:** https://phabricator.wikimedia.org/T269447
Few minor things:
- When any call fails, the progressbar needs to be hidden
- Few ui fields do not carry meaningful info when calls fail, hence need to be hidden
> Fix: UI fixes to diff view

- app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
A tiny bit of reshuffling to make things more consistent.
> Follow-up: minor cleanup of Diff view logic.

- app/src/main/java/org/wikipedia/util/DateUtil.kt
**Phab:** https://phabricator.wikimedia.org/T269447
> Design tweak: Minor change in date format

- build.gradle
https://developers.google.com/android/guides/releases#january_28_2021
> Update gms services version to 4.3.5

- app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.java
https://appcenter.ms/orgs/ci-apps-hockeyapp-f5mf/apps/Wikipedia/crashes/errors/3496665651u/overview
https://appcenter.ms/orgs/ci-apps-hockeyapp-f5mf/apps/Wikipedia-Beta/crashes/errors/2274612711u/overview
> Fix possible crash during language detection.

- app/src/main/java/org/wikipedia/util/StringUtil.kt
https://appcenter.ms/orgs/ci-apps-hockeyapp-f5mf/apps/Wikipedia-Beta/crashes/errors/4070835036u/overview
> Fix possible crash when editing descriptions.

- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
> Follow up: reduce lines of code

- app/src/main/java/org/wikipedia/page/PageFragment.java
https://appcenter.ms/orgs/ci-apps-hockeyapp-f5mf/apps/Wikipedia-Beta/crashes/errors/2587365457/overview
> Fix: possible crash on setupMessageHandlers in PageFragment

- app/src/main/java/org/wikipedia/database/Database.java
- app/src/main/java/org/wikipedia/search/RecentSearchDatabaseTable.kt
**Phab:** https://phabricator.wikimedia.org/T276484
> Fix: Oversight of db version conversion fixed

- app/build.gradle
https://developer.android.com/jetpack/androidx/releases/fragment#1.3.1
> Update fragment-ktx library to 1.3.1.

- app/src/main/java/org/wikipedia/database/column/CodeEnumColumn.java
- app/src/main/java/org/wikipedia/database/column/Column.java
- app/src/main/java/org/wikipedia/database/column/DateColumn.java
- app/src/main/java/org/wikipedia/database/column/IntColumn.java
- app/src/main/java/org/wikipedia/database/column/LongColumn.java
- app/src/main/java/org/wikipedia/database/column/StrColumn.java
- app/src/main/java/org/wikipedia/edit/summaries/EditSummaryDatabaseTable.java
- app/src/main/java/org/wikipedia/feed/becauseyouread/MainPageReadMoreTopicTask.java
- app/src/main/java/org/wikipedia/history/HistoryEntryDatabaseTable.java
- app/src/main/java/org/wikipedia/history/HistoryFragment.java
- app/src/main/java/org/wikipedia/history/UpdateHistoryTask.java
- app/src/main/java/org/wikipedia/offline/OfflineObjectTable.java
- app/src/main/java/org/wikipedia/pageimages/PageImageDatabaseTable.kt
- app/src/main/java/org/wikipedia/readinglist/database/ReadingListPageTable.java
- app/src/main/java/org/wikipedia/readinglist/database/ReadingListTable.java
- app/src/main/java/org/wikipedia/search/RecentSearchDatabaseTable.kt
- app/src/main/java/org/wikipedia/talk/TalkPageSeenDatabaseTable.kt
val() to value() as per this CR comment:
https://github.com/wikimedia/apps-android-wikipedia/pull/2199#discussion-diff-594738781
> Rename function in Column to avoid using reserved word in Kotlin

- app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
This fixes a bug introduced in #2181
> Fix operating on multiple selected Reading List items.

- app/src/main/java/org/wikipedia/descriptions/DescriptionEditActivity.kt
Rearrange the order of public/private methods and some minor changes.
> Follow up: DescriptionEditActivity Kotlin conversion

- app/build.gradle
- app/src/main/java/org/wikipedia/navtab/NavTabLayout.kt
- app/src/main/java/org/wikipedia/page/PageActionTabLayout.kt
- app/src/main/java/org/wikipedia/settings/AboutActivity.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt
- app/src/main/java/org/wikipedia/views/ConfigurableTabLayout.kt
- app/src/main/java/org/wikipedia/views/ImageZoomHelper.kt
Use extensions for `ViewGroup` defined in the Core KTX library.
> Use ViewGroup extensions.

- app/src/main/java/org/wikipedia/notifications/NotificationPresenter.kt
- app/src/main/java/org/wikipedia/page/tabs/TabActivity.kt
- app/src/main/java/org/wikipedia/util/CenterCropWithFaceTransformation.kt
- app/src/main/java/org/wikipedia/util/ResourceUtil.kt
- app/src/main/java/org/wikipedia/util/WhiteBackgroundTransformation.kt
- app/src/main/java/org/wikipedia/views/AppTextViewWithImages.kt
- app/src/main/java/org/wikipedia/views/DiscreteSeekBar.kt
Use Core KTX extensions for `Bitmap`, `Canvas` and `Drawable`.
> Use graphics extensions.

- app/src/main/java/org/wikipedia/edit/EditHandler.java
https://appcenter.ms/orgs/ci-apps-hockeyapp-f5mf/apps/Wikipedia-Beta/crashes/errors/1149566818/overview
> Fix: possible crash when showing context menu of editing description

- app/src/main/java/org/wikipedia/suggestededits/ImageRecsFragment.kt
- app/src/main/res/layout/fragment_suggested_edits_image_recommendation_item.xml
https://phabricator.wikimedia.org/T278528
> ImageRecs: update progress bar background for different themes.

- app/src/main/res/values-ca/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-in/strings.xml
- app/src/main/res/values-iw/strings.xml
- app/src/main/res/values-ko/strings.xml
- app/src/main/res/values-mk/strings.xml
- app/src/main/res/values-ms/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-sk/strings.xml
- app/src/main/res/values-sv/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values-uz/strings.xml
- app/src/main/res/values-zh-rTW/strings.xml
- app/src/main/res/values/strings.xml
https://phabricator.wikimedia.org/T278530
> ImgRecs: change italics to bold on the "suggestion reason"

- app/src/main/res/layout/view_image_recs_tooltip.xml
https://phabricator.wikimedia.org/T278490
This basically copies the same format from other tooltip XML layouts.
> ImgRecs: update tooltip XML layout to prevent content cutoff

- app/src/main/res/layout/fragment_suggested_edits_image_recommendation_item.xml
https://phabricator.wikimedia.org/T278493
> ImageRecs: show instruction text properly in small screen

- app/src/main/res/values/strings.xml
Related to #2288 and I've already updated the translated string on TWN.
> Update suggestion reason string

- app/build.gradle
https://developer.android.com/jetpack/androidx/releases/fragment#1.3.2
> Update android fragment-ktx version to 1.3.2

- app/src/main/java/org/wikipedia/suggestededits/ImageRecsFragment.kt
- app/src/main/java/org/wikipedia/util/FeedbackUtil.kt
- app/src/main/res/layout/view_plain_text_tooltip.xml
https://phabricator.wikimedia.org/T278490#6984218
> ImgRecs: tooltip textview lineHeight design tweak

- app/src/main/java/org/wikipedia/analytics/eventplatform/ImageRecommendationsEvent.kt
- app/src/main/java/org/wikipedia/suggestededits/ImageRecsFragment.kt
**Phab:** https://phabricator.wikimedia.org/T273057
Tested this on beta and production and it worked!
> Image Recs: Instrumentation on MEP

- app/src/main/java/org/wikipedia/page/PageViewModel.java
https://phabricator.wikimedia.org/T279850
> Fix loading of Main Page via mobile-web call.

- app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.kt
For some reason this had stopped working recently (possibly after kotlin conversion)?
https://phabricator.wikimedia.org/T279851
> Fix adding image caption from lead image.

- app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt
- app/src/main/res/layout/item_talk_topic.xml
https://phabricator.wikimedia.org/T274835
> Update design of read/unread talk topics.

- app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt
- app/src/main/res/layout/activity_talk_topic.xml
https://phabricator.wikimedia.org/T280092
> Show CC license information when submitting Talk replies.

- app/src/main/java/org/wikipedia/suggestededits/ImageRecsDialog.kt
- app/src/main/res/layout/fragment_suggested_edits_image_recommendation_dialog.xml
- app/src/main/res/values-qq/strings.xml
- app/src/main/res/values/strings.xml
**Phab:** https://phabricator.wikimedia.org/T278532
>  Optimize the 'No' and 'Not sure' dialog title copy

- app/src/main/res/layout/view_onboarding_page.xml
**Phab:** https://phabricator.wikimedia.org/T278526
> Design tweak: Image recs onboarding

- app/src/main/res/layout/fragment_suggested_edits_image_recommendation_dialog.xml
The "CANCEL" or "CONTINUE" buttons are covered and not reachable on the Nexus S emulator.
> ImgRecs: make the dialog content scrollable for small screen devices

- app/src/main/java/org/wikipedia/suggestededits/ImageRecsFragment.kt
- app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
- app/src/main/java/org/wikipedia/util/FeedbackUtil.kt
- app/src/main/res/layout/view_plain_text_tooltip.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/styles.xml
https://phabricator.wikimedia.org/T278550
> ImgRecs: add "Got it" button on sequential tooltips

- app/build.gradle
https://firebase.google.com/support/release-notes/android#messaging_v21-1-0
> Update firebaseMessaging version to 21.1.0
